/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.GroupCohomology.TateHexagon
import SICs.RepresentationTheory.Basic
import Mathlib.RepresentationTheory.Homological.FiniteCyclic
import Mathlib.LinearAlgebra.Quotient.Card
import Mathlib.Data.ZMod.QuotientRing
import Mathlib.GroupTheory.QuotientGroup.Finite

/-!
# The Herbrand quotient

The Herbrand quotient $h(V) = |\widehat H^0(G, V)| / |\widehat H^{-1}(G, V)|$ of a representation
of a finite cyclic group, its multiplicativity in short exact sequences, its value `1` on finite
modules, its invariance under maps with finite kernel and cokernel, and its value $|G|$ on
the trivial module $\mathbb Z$.

This module follows Milne, *Class Field Theory*, version 4.03 (2020), Chapter II, §3, Lemma 3.3(b),
Proposition 3.6, Lemma 3.7, Proposition 3.8, and Corollary 3.9. Milne writes
$h(M) = |\widehat H^0(G, M)| / |H^1(G, M)|$; for a cyclic group generated by `σ` both
$H^1(G, M)$ and $\widehat H^{-1}(G, M)$ are $\ker N_G / (\sigma - 1) M$ (Milne, Chapter II, (1.20)
and §3), and the explicit groups `TateZero` and `TateNegOne` of
`SICs.GroupCohomology.TateLowDegree` are used here.

## The argument

Fix a generator `σ` of `G`. Then $V^G = \ker(\sigma - 1)$ and $I_G V = (\sigma - 1) V$, so
$\widehat H^0 = \ker(\sigma - 1)/\operatorname{im} N_G$ and
$\widehat H^{-1} = \ker N_G / \operatorname{im}(\sigma - 1)$ are the homology groups of the
$2$-periodic complex $\cdots \to V \xrightarrow{\sigma - 1} V \xrightarrow{N_G} V
\xrightarrow{\sigma - 1} \cdots$. A short exact sequence $0 \to V' \to V \to V'' \to 0$ of
representations is a short exact sequence of such complexes, and its long exact homology
sequence is periodic: the hexagon
$$\widehat H^0(V') \to \widehat H^0(V) \to \widehat H^0(V'') \to \widehat H^{-1}(V') \to
\widehat H^{-1}(V) \to \widehat H^{-1}(V'') \to \widehat H^0(V')$$
is exact, with connecting maps obtained by lifting to `V`, applying $\sigma - 1$ or $N_G$, and
pulling back to `V'`. Cutting it at one place gives an exact sequence of the kind in Lemma 3.7,
where the alternating product of orders of an exact sequence of finite groups is `1`; so if two
of the three Herbrand quotients are defined, so is the third, and $h(V) = h(V')h(V'')$.

For finite `V`, the exact sequences $0 \to V^G \to V \xrightarrow{\sigma - 1} V \to V_G \to 0$ and
$0 \to \widehat H^{-1} \to V_G \xrightarrow{N_G} V^G \to \widehat H^0 \to 0$ give
$|V^G| = |V_G|$ and then $|\widehat H^{-1}| = |\widehat H^0|$. A map with finite kernel and
cokernel then has equal Herbrand quotients at its source, image, and target, by
multiplicativity. For $\mathbb Z$ with trivial action, $N_G$ is multiplication by $|G|$, so
$\widehat H^0 = \mathbb Z / |G| \mathbb Z$ and $\widehat H^{-1} = 0$.
-/

noncomputable section

namespace SIC

namespace Representation

variable {k G V W U : Type*} [CommRing k] [Group G] [Fintype G]
  [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W] [AddCommGroup U] [Module k U]
  (ρ : _root_.Representation k G V) (σ : _root_.Representation k G W)
  (τ : _root_.Representation k G U)

/-! ### The Herbrand quotient -/

/-- The Herbrand quotient $h(V) = |\widehat H^0(G, V)| / |\widehat H^{-1}(G, V)|$, a rational
number; it is meaningful when `HasHerbrandQuotient ρ` holds (an infinite group has `Nat.card`
zero). Milne, *Class Field Theory*, Chapter II, §3. -/
def herbrandQuotient : ℚ :=
  (Nat.card (TateZero ρ) : ℚ) / Nat.card (TateNegOne ρ)

/-- The Herbrand quotient of `ρ` is defined: both Tate groups $\widehat H^0(G, V)$ and
$\widehat H^{-1}(G, V)$ are finite. Milne, *Class Field Theory*, Chapter II, §3. -/
structure HasHerbrandQuotient : Prop where
  /-- The group $\widehat H^0(G, V)$ is finite. -/
  finite_tateZero : Finite (TateZero ρ)
  /-- The group $\widehat H^{-1}(G, V)$ is finite. -/
  finite_tateNegOne : Finite (TateNegOne ρ)

/-- The Herbrand quotient is defined exactly when its rational value is nonzero: the two Tate
groups are nonempty, and an infinite group's natural cardinal is zero. -/
theorem hasHerbrandQuotient_iff_ne_zero :
    HasHerbrandQuotient ρ ↔ herbrandQuotient ρ ≠ 0 := by
  simp only [herbrandQuotient, div_ne_zero_iff, Nat.cast_ne_zero, Nat.card_ne_zero]
  constructor
  · intro h
    exact ⟨⟨⟨0⟩, h.finite_tateZero⟩, ⟨⟨0⟩, h.finite_tateNegOne⟩⟩
  · rintro ⟨⟨_, h₀⟩, ⟨_, h₁⟩⟩
    exact ⟨h₀, h₁⟩

/-- Equality of Herbrand quotients implies simultaneous definedness. -/
theorem hasHerbrandQuotient_iff_of_eq' {ρ : _root_.Representation k G V}
    {σ : _root_.Representation k G W} (h : herbrandQuotient ρ = herbrandQuotient σ) :
    HasHerbrandQuotient ρ ↔ HasHerbrandQuotient σ := by
  rw [hasHerbrandQuotient_iff_ne_zero, hasHerbrandQuotient_iff_ne_zero, h]

/-- Simultaneous definedness and equality whenever defined imply unconditional equality of
Herbrand quotients. -/
theorem herbrandQuotient_eq_of_iff' {ρ : _root_.Representation k G V}
    {σ : _root_.Representation k G W}
    (hiff : HasHerbrandQuotient ρ ↔ HasHerbrandQuotient σ)
    (heq : HasHerbrandQuotient σ → herbrandQuotient ρ = herbrandQuotient σ) :
    herbrandQuotient ρ = herbrandQuotient σ := by
  by_cases hσ : HasHerbrandQuotient σ
  · exact heq hσ
  · have hρ : ¬HasHerbrandQuotient ρ := fun h => hσ (hiff.mp h)
    have hzρ : herbrandQuotient ρ = 0 := by
      by_contra hz
      exact hρ ((hasHerbrandQuotient_iff_ne_zero ρ).2 hz)
    have hzσ : herbrandQuotient σ = 0 := by
      by_contra hz
      exact hσ ((hasHerbrandQuotient_iff_ne_zero σ).2 hz)
    exact hzρ.trans hzσ.symm

/-- A representation with $\widehat H^0(G, V) = \widehat H^{-1}(G, V) = 0$ has a Herbrand
quotient. -/
theorem hasHerbrandQuotient_of_subsingleton (h₀ : Subsingleton (TateZero ρ))
    (h₁ : Subsingleton (TateNegOne ρ)) : HasHerbrandQuotient ρ := by
  exact ⟨@Finite.of_subsingleton _ h₀, @Finite.of_subsingleton _ h₁⟩

/-- If $\widehat H^{-1}(G, V) = 0$, the Herbrand quotient is the order of
$\widehat H^0(G, V)$: $h(V) = |\widehat H^0(G, V)|$. -/
theorem herbrandQuotient_eq_card_tateZero (h₁ : Subsingleton (TateNegOne ρ)) :
    herbrandQuotient ρ = Nat.card (TateZero ρ) := by
  have hc₁ : Nat.card (TateNegOne ρ) = 1 := @Nat.card_unique _ ⟨0⟩ h₁
  rw [herbrandQuotient, hc₁]
  norm_num

/-- A representation with $\widehat H^0(G, V) = \widehat H^{-1}(G, V) = 0$ has Herbrand
quotient `1`. -/
theorem herbrandQuotient_eq_one_of_subsingleton (h₀ : Subsingleton (TateZero ρ))
    (h₁ : Subsingleton (TateNegOne ρ)) : herbrandQuotient ρ = 1 := by
  rw [herbrandQuotient_eq_card_tateZero ρ h₁, @Nat.card_unique _ ⟨0⟩ h₀]
  norm_num

/-- If $\widehat H^{-1}(G, V) = 0$ and $h(V) = 1$ is defined, then $\widehat H^0(G, V) = 0$. -/
theorem subsingleton_tateZero_of_herbrandQuotient_eq_one (h : HasHerbrandQuotient ρ)
    (h₁ : Subsingleton (TateNegOne ρ)) (hone : herbrandQuotient ρ = 1) :
    Subsingleton (TateZero ρ) := by
  have hc : Nat.card (TateZero ρ) = 1 := by
    exact_mod_cast (herbrandQuotient_eq_card_tateZero ρ h₁).symm.trans hone
  exact (@Finite.card_le_one_iff_subsingleton _ h.finite_tateZero).mp hc.le

/-! ### Finite modules and the trivial module -/

/-- A finite representation has a Herbrand quotient. -/
theorem hasHerbrandQuotient_of_finite [Finite V] : HasHerbrandQuotient ρ := by
  have h₀ : Finite ρ.invariants := Finite.of_injective _ Subtype.val_injective
  have h₁ : Finite (LinearMap.ker ρ.norm) :=
    Finite.of_injective _ Subtype.val_injective
  exact ⟨@Quotient.finite _ h₀ _, @Quotient.finite _ h₁ _⟩

/-- Counting the norm submodule gives the order of `Ĥ⁰` times the number of norms. -/
private theorem card_invariants_eq_norm_mul_tateZero :
    Nat.card ρ.invariants = Nat.card ρ.norm.range * Nat.card (TateZero ρ) := by
  calc
    _ = Nat.card (normSubmodule ρ) * Nat.card (TateZero ρ) :=
      Submodule.card_eq_card_quotient_mul_card _
    _ = _ := congrArg (· * Nat.card (TateZero ρ))
      (Nat.card_congr
        (Submodule.comapSubtypeEquivOfLe (range_norm_le_invariants ρ)).toEquiv)

/-- Counting the augmentation submodule gives the order of `Ĥ⁻¹` times its order. -/
private theorem card_kerNorm_eq_aug_mul_tateNegOne :
    Nat.card ρ.norm.ker =
      Nat.card (_root_.Representation.Coinvariants.ker ρ) * Nat.card (TateNegOne ρ) := by
  calc
    _ = Nat.card (augmentationSubmodule ρ) * Nat.card (TateNegOne ρ) :=
      Submodule.card_eq_card_quotient_mul_card _
    _ = _ := congrArg (· * Nat.card (TateNegOne ρ))
      (Nat.card_congr
        (Submodule.comapSubtypeEquivOfLe (coinvariantsKer_le_ker_norm ρ)).toEquiv)

/-- Rank-nullity for the cardinalities of the kernel and range of a linear endomorphism,
used in `herbrandQuotient_eq_one_of_finite`. -/
private theorem card_eq_ker_mul_range {A B : Type*}
    [AddCommGroup A] [Module k A] [AddCommGroup B] [Module k B] (a : A →ₗ[k] B) :
    Nat.card A = Nat.card a.ker * Nat.card a.range := by
  rw [Submodule.card_eq_card_quotient_mul_card a.ker,
    Nat.card_congr (a.quotKerEquivRange).toEquiv]

/-- The Herbrand quotient of a finite representation of a cyclic group is `1`. Milne,
*Class Field Theory*, Chapter II, Proposition 3.8. -/
theorem herbrandQuotient_eq_one_of_finite [IsCyclic G] [Finite V] :
    herbrandQuotient ρ = 1 := by
  obtain ⟨g, hg⟩ := IsCyclic.exists_generator (α := G)
  let D : V →ₗ[k] V := ρ g - LinearMap.id
  have hInv : ρ.invariants = D.ker := by
    ext x
    simp only [Representation.mem_invariants_iff_of_forall_mem_zpowers ρ g hg x,
      LinearMap.mem_ker, D, LinearMap.sub_apply, LinearMap.id_apply, sub_eq_zero]
  have hAug : _root_.Representation.Coinvariants.ker ρ = D.range := by
    exact _root_.Representation.FiniteCyclicGroup.coinvariantsKer_eq_range ρ g hg
  have hD := card_eq_ker_mul_range D
  have hN := card_eq_ker_mul_range ρ.norm
  have hNormPos : 0 < Nat.card ρ.norm.range :=
    @Nat.card_pos _ ⟨0⟩ (Finite.of_injective _ Subtype.val_injective)
  have hDPos : 0 < Nat.card D.range :=
    @Nat.card_pos _ ⟨0⟩ (Finite.of_injective _ Subtype.val_injective)
  have hZero' : Nat.card D.ker =
      Nat.card ρ.norm.range * Nat.card (TateZero ρ) := by
    rw [← hInv]
    exact card_invariants_eq_norm_mul_tateZero ρ
  have hNeg' : Nat.card ρ.norm.ker =
      Nat.card D.range * Nat.card (TateNegOne ρ) := by
    rw [← hAug]
    exact card_kerNorm_eq_aug_mul_tateNegOne ρ
  have hCard : Nat.card (TateZero ρ) = Nat.card (TateNegOne ρ) := by
    have h : Nat.card ρ.norm.range * Nat.card (TateZero ρ) * Nat.card D.range =
        Nat.card D.range * Nat.card (TateNegOne ρ) * Nat.card ρ.norm.range := by
      calc
        _ = Nat.card D.ker * Nat.card D.range := by rw [← hZero']
        _ = Nat.card V := hD.symm
        _ = Nat.card ρ.norm.ker * Nat.card ρ.norm.range := hN
        _ = _ := by rw [hNeg']
    apply Nat.mul_left_cancel hNormPos
    apply Nat.mul_right_cancel hDPos
    simpa only [mul_assoc, mul_comm, mul_left_comm] using h
  have hNegPos : (Nat.card (TateNegOne ρ) : ℚ) ≠ 0 := by
    exact_mod_cast (@Nat.card_pos _ ⟨0⟩
      (hasHerbrandQuotient_of_finite ρ).finite_tateNegOne).ne'
  simp [herbrandQuotient, hCard, hNegPos]

omit [Fintype G] in
/-- The trivial integral representation in the computation of `herbrandQuotient_trivial`. -/
private abbrev trivialInt : _root_.Representation ℤ G ℤ :=
  _root_.Representation.trivial ℤ G ℤ

/-- The norm of the trivial integral representation is multiplication by `|G|`. -/
private theorem trivialInt_norm (x : ℤ) :
    (trivialInt (G := G)).norm x = Fintype.card G * x := by
  simp [trivialInt, _root_.Representation.norm]

omit [Fintype G] in
/-- Every integer is invariant under the trivial integral representation. -/
private theorem trivialInt_invariants : (trivialInt (G := G)).invariants = ⊤ :=
  _root_.Representation.invariants_eq_top (_root_.Representation.trivial ℤ G ℤ)

/-- The norms of the trivial integral representation form the ideal `|G|ℤ`. -/
private theorem trivialInt_norm_range : LinearMap.range (trivialInt (G := G)).norm =
    (Ideal.span {(Fintype.card G : ℤ)} : Submodule ℤ ℤ) := by
  ext x
  simp only [LinearMap.mem_range, Ideal.mem_span_singleton]
  constructor
  · rintro ⟨y, rfl⟩
    exact ⟨y, by rw [trivialInt_norm]⟩
  · rintro ⟨y, rfl⟩
    exact ⟨y, by rw [trivialInt_norm]⟩

/-- For the trivial integral representation, `Ĥ⁰` is `ℤ/|G|ℤ`. -/
private def trivialInt_tateZeroEquiv :
    TateZero (trivialInt (G := G)) ≃ ZMod (Fintype.card G) := by
  let e : (trivialInt (G := G)).invariants ≃ₗ[ℤ] ℤ :=
    (LinearEquiv.ofEq _ _ trivialInt_invariants).trans Submodule.topEquiv
  have he (x : (trivialInt (G := G)).invariants) : e x = (x : ℤ) := rfl
  have hmap : Submodule.map (e : _ →ₗ[ℤ] ℤ) (normSubmodule (trivialInt (G := G))) =
      (Ideal.span {(Fintype.card G : ℤ)} : Submodule ℤ ℤ) := by
    ext x
    constructor
    · rintro ⟨y, hy, rfl⟩
      change (y : ℤ) ∈ LinearMap.range (trivialInt (G := G)).norm at hy
      simpa only [LinearEquiv.coe_coe, he, ← trivialInt_norm_range] using hy
    · intro hx
      have hxinv : x ∈ (trivialInt (G := G)).invariants := by
        rw [trivialInt_invariants]
        trivial
      refine ⟨⟨x, hxinv⟩, ?_, ?_⟩
      · change x ∈ LinearMap.range (trivialInt (G := G)).norm
        rwa [trivialInt_norm_range]
      · rfl
  exact ((Submodule.Quotient.equiv _ _ e hmap).toEquiv).trans
    (Int.quotientSpanNatEquivZMod (Fintype.card G)).toEquiv

/-- For the trivial integral representation, `Ĥ⁻¹` is the trivial group. -/
private theorem trivialInt_tateNegOne_subsingleton :
    Subsingleton (TateNegOne (trivialInt (G := G))) := by
  have hn : (Fintype.card G : ℤ) ≠ 0 := by exact_mod_cast Fintype.card_ne_zero
  have hinj : Function.Injective (trivialInt (G := G)).norm := by
    intro x y h
    rw [trivialInt_norm, trivialInt_norm] at h
    exact (mul_left_cancel₀ hn) h
  have htop : augmentationSubmodule (trivialInt (G := G)) = ⊤ := by
    apply eq_top_iff.mpr
    intro x _
    have hx : (x : ℤ) = 0 := hinj (by simpa only [LinearMap.mem_ker, map_zero] using x.property)
    have hx' : x = 0 := Subtype.ext hx
    simp [hx']
  change Subsingleton (LinearMap.ker (trivialInt (G := G)).norm ⧸
    augmentationSubmodule (trivialInt (G := G)))
  rw [htop]
  infer_instance

/-- The trivial representation on $\mathbb Z$ has a Herbrand quotient. -/
theorem hasHerbrandQuotient_trivial :
    HasHerbrandQuotient (_root_.Representation.trivial ℤ G ℤ) := by
  exact ⟨Finite.of_equiv _ (trivialInt_tateZeroEquiv (G := G)).symm,
    @Finite.of_subsingleton _ (trivialInt_tateNegOne_subsingleton (G := G))⟩

/-- The Herbrand quotient of the trivial representation on $\mathbb Z$ is the order of the group:
$h(\mathbb Z) = |G|$. Milne, *Class Field Theory*, Chapter II, Lemma 3.3(b). -/
theorem herbrandQuotient_trivial :
    herbrandQuotient (_root_.Representation.trivial ℤ G ℤ) = Fintype.card G := by
  change herbrandQuotient (trivialInt (G := G)) = Fintype.card G
  have hzero : Nat.card (TateZero (trivialInt (G := G))) = Fintype.card G := by
    rw [Nat.card_congr (trivialInt_tateZeroEquiv (G := G)), Nat.card_zmod]
  have hneg : Nat.card (TateNegOne (trivialInt (G := G))) = 1 :=
    @Nat.card_unique _ ⟨0⟩ (trivialInt_tateNegOne_subsingleton (G := G))
  simp [herbrandQuotient, hzero, hneg]

/-! ### Counting the Tate hexagon

The exact hexagon gives an alternating product of cardinalities and transfers finiteness across
its vertices. -/

variable {ρ σ τ}

/-- Around an exact six-cycle of abelian groups, the alternating products of orders agree.
This is the periodic form of Milne, *Class Field Theory*, Chapter II, Lemma 3.7. -/
private theorem card_exact_hexagon {A B C D E F : Type*}
    [AddCommGroup A] [Module k A] [AddCommGroup B] [Module k B]
    [AddCommGroup C] [Module k C] [AddCommGroup D] [Module k D]
    [AddCommGroup E] [Module k E] [AddCommGroup F] [Module k F]
    (a : A →ₗ[k] B) (b : B →ₗ[k] C) (c : C →ₗ[k] D)
    (d : D →ₗ[k] E) (e : E →ₗ[k] F) (f : F →ₗ[k] A)
    (hab : Function.Exact a b) (hbc : Function.Exact b c)
    (hcd : Function.Exact c d) (hde : Function.Exact d e)
    (hef : Function.Exact e f) (hfa : Function.Exact f a) :
    Nat.card A * Nat.card C * Nat.card E =
      Nat.card B * Nat.card D * Nat.card F := by
  have hA : Nat.card A = Nat.card f.range * Nat.card a.range := by
    rw [card_eq_ker_mul_range a]
    congr 1
    exact Nat.card_congr (LinearEquiv.ofEq _ _ (by ext x; exact hfa x)).toEquiv
  have hB : Nat.card B = Nat.card a.range * Nat.card b.range := by
    rw [card_eq_ker_mul_range b]
    congr 1
    exact Nat.card_congr (LinearEquiv.ofEq _ _ (by ext x; exact hab x)).toEquiv
  have hC : Nat.card C = Nat.card b.range * Nat.card c.range := by
    rw [card_eq_ker_mul_range c]
    congr 1
    exact Nat.card_congr (LinearEquiv.ofEq _ _ (by ext x; exact hbc x)).toEquiv
  have hD : Nat.card D = Nat.card c.range * Nat.card d.range := by
    rw [card_eq_ker_mul_range d]
    congr 1
    exact Nat.card_congr (LinearEquiv.ofEq _ _ (by ext x; exact hcd x)).toEquiv
  have hE : Nat.card E = Nat.card d.range * Nat.card e.range := by
    rw [card_eq_ker_mul_range e]
    congr 1
    exact Nat.card_congr (LinearEquiv.ofEq _ _ (by ext x; exact hde x)).toEquiv
  have hF : Nat.card F = Nat.card e.range * Nat.card f.range := by
    rw [card_eq_ker_mul_range f]
    congr 1
    exact Nat.card_congr (LinearEquiv.ofEq _ _ (by ext x; exact hef x)).toEquiv
  rw [hA, hB, hC, hD, hE, hF]
  ring

/-- A module between two finite modules in an exact pair is finite. This is used at the two
middle vertices of the Tate hexagon. -/
private theorem finite_of_exact_middle {A B C : Type*}
    [AddCommGroup A] [Module k A] [AddCommGroup B] [Module k B]
    [AddCommGroup C] [Module k C] (hA : Finite A) (hC : Finite C)
    (f : A →ₗ[k] B) (g : B →ₗ[k] C) (hfg : Function.Exact f g) : Finite B := by
  have heq : f.range = g.ker := by
    ext b
    exact (hfg b).symm
  have hk : Finite g.ker := by
    rw [← heq]
    exact @Finite.of_surjective _ _ hA f.rangeRestrict f.surjective_rangeRestrict
  have hr : Finite g.range := @Finite.of_injective _ _ hC _ Subtype.val_injective
  have hq : Finite (B ⧸ g.ker) :=
    @Finite.of_equiv _ g.range hr (g.quotKerEquivRange).symm.toEquiv
  have hq' : Finite (B ⧸ g.ker.toAddSubgroup) := by
    change Finite (B ⧸ g.ker)
    exact hq
  exact @Finite.of_addSubgroup_quotient _ _ g.ker.toAddSubgroup hk hq'


/-! ### Definedness and multiplicativity

Finiteness at any two representations transfers to the third through the exact hexagon; the
alternating product of orders gives the quotient formula. -/

/-- If $0 \to V' \to V \to V'' \to 0$ is exact and $V'$, $V''$ have Herbrand quotients, so does
`V`. Milne, *Class Field Theory*, Chapter II, Proposition 3.6. -/
theorem HasHerbrandQuotient.of_left_of_right [IsCyclic G] {f : ρ.IntertwiningMap σ}
    {g : σ.IntertwiningMap τ} (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) (h₁ : HasHerbrandQuotient ρ) (h₃ : HasHerbrandQuotient τ) :
    HasHerbrandQuotient σ := by
  have hzero : Finite (TateZero σ) :=
    finite_of_exact_middle h₁.finite_tateZero h₃.finite_tateZero
      (TateZero.map f) (TateZero.map g)
      (TateZero.exact_middle hf hg hfg)
  have hneg : Finite (TateNegOne σ) :=
    finite_of_exact_middle h₁.finite_tateNegOne h₃.finite_tateNegOne
      (TateNegOne.map f) (TateNegOne.map g)
      (TateNegOne.exact_middle hf hg hfg)
  exact ⟨hzero, hneg⟩

/-- If $0 \to V' \to V \to V'' \to 0$ is exact and `V`, $V''$ have Herbrand quotients, so does
$V'$. Milne, *Class Field Theory*, Chapter II, Proposition 3.6. -/
theorem HasHerbrandQuotient.of_middle_of_right [IsCyclic G] {f : ρ.IntertwiningMap σ}
    {g : σ.IntertwiningMap τ} (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) (h₂ : HasHerbrandQuotient σ) (h₃ : HasHerbrandQuotient τ) :
    HasHerbrandQuotient ρ := by
  obtain ⟨s, hs⟩ := IsCyclic.exists_generator (α := G)
  have hzero : Finite (TateZero ρ) :=
    finite_of_exact_middle h₃.finite_tateNegOne h₂.finite_tateZero
      (TateNegOne.δ hf hg hfg s hs).val (TateZero.map f)
      (exact_zero_left hf hg hfg s hs)
  have hneg : Finite (TateNegOne ρ) :=
    finite_of_exact_middle h₃.finite_tateZero h₂.finite_tateNegOne
      (TateZero.δ hf hg hfg s hs).val (TateNegOne.map f)
      (exact_neg_left hf hg hfg s hs)
  exact ⟨hzero, hneg⟩

/-- If $0 \to V' \to V \to V'' \to 0$ is exact and $V'$, `V` have Herbrand quotients, so does
$V''$. Milne, *Class Field Theory*, Chapter II, Proposition 3.6. -/
theorem HasHerbrandQuotient.of_left_of_middle [IsCyclic G] {f : ρ.IntertwiningMap σ}
    {g : σ.IntertwiningMap τ} (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) (h₁ : HasHerbrandQuotient ρ) (h₂ : HasHerbrandQuotient σ) :
    HasHerbrandQuotient τ := by
  obtain ⟨s, hs⟩ := IsCyclic.exists_generator (α := G)
  have hzero : Finite (TateZero τ) :=
    finite_of_exact_middle h₂.finite_tateZero h₁.finite_tateNegOne
      (TateZero.map g) (TateZero.δ hf hg hfg s hs).val
      (exact_zero_right hf hg hfg s hs)
  have hneg : Finite (TateNegOne τ) :=
    finite_of_exact_middle h₂.finite_tateNegOne h₁.finite_tateZero
      (TateNegOne.map g) (TateNegOne.δ hf hg hfg s hs).val
      (exact_neg_right hf hg hfg s hs)
  exact ⟨hzero, hneg⟩

/-- The Herbrand quotient is multiplicative in short exact sequences: $h(V) = h(V')h(V'')$ when
$h(V')$ and $h(V'')$ are defined. Milne, *Class Field Theory*, Chapter II, Proposition 3.6. -/
theorem herbrandQuotient_eq_mul [IsCyclic G] {f : ρ.IntertwiningMap σ}
    {g : σ.IntertwiningMap τ} (hf : Function.Injective f) (hg : Function.Surjective g)
    (hfg : Function.Exact f g) (h₁ : HasHerbrandQuotient ρ) (h₃ : HasHerbrandQuotient τ) :
    herbrandQuotient σ = herbrandQuotient ρ * herbrandQuotient τ := by
  obtain ⟨s, hs⟩ := IsCyclic.exists_generator (α := G)
  have h₂ := HasHerbrandQuotient.of_left_of_right hf hg hfg h₁ h₃
  have hcard := card_exact_hexagon
    (TateZero.map f) (TateZero.map g) (TateZero.δ hf hg hfg s hs).val
    (TateNegOne.map f) (TateNegOne.map g) (TateNegOne.δ hf hg hfg s hs).val
    (TateZero.exact_middle hf hg hfg) (exact_zero_right hf hg hfg s hs)
    (exact_neg_left hf hg hfg s hs) (TateNegOne.exact_middle hf hg hfg)
    (exact_neg_right hf hg hfg s hs) (exact_zero_left hf hg hfg s hs)
  have h₁pos : (Nat.card (TateNegOne ρ) : ℚ) ≠ 0 := by
    exact_mod_cast (@Nat.card_pos _ ⟨0⟩ h₁.finite_tateNegOne).ne'
  have h₂pos : (Nat.card (TateNegOne σ) : ℚ) ≠ 0 := by
    exact_mod_cast (@Nat.card_pos _ ⟨0⟩ h₂.finite_tateNegOne).ne'
  have h₃pos : (Nat.card (TateNegOne τ) : ℚ) ≠ 0 := by
    exact_mod_cast (@Nat.card_pos _ ⟨0⟩ h₃.finite_tateNegOne).ne'
  dsimp [herbrandQuotient]
  field_simp [h₁pos, h₂pos, h₃pos]
  have hcard' : (Nat.card (TateZero σ) : ℚ) * Nat.card (TateNegOne ρ) *
      Nat.card (TateNegOne τ) =
      (Nat.card (TateZero ρ) : ℚ) * Nat.card (TateZero τ) *
        Nat.card (TateNegOne σ) := by
    exact_mod_cast hcard.symm
  calc
    _ = (Nat.card (TateZero ρ) : ℚ) * Nat.card (TateZero τ) *
        Nat.card (TateNegOne σ) := hcard'
    _ = _ := by ring

/-! ### Maps with finite kernel and cokernel

The equivariant range restriction from `SICs.RepresentationTheory.Basic` factors a map through
its image. Finite kernels and cokernels then reduce comparison to finite representations. -/

section Factorization

variable (f : ρ.IntertwiningMap σ)

/-- The kernel representation in the finite-kernel-and-cokernel factorization. -/
private abbrev kerRep := f.ker.toRepresentation
/-- The image representation in the finite-kernel-and-cokernel factorization. -/
private abbrev rangeRep := f.range.toRepresentation
/-- The quotient representation on the cokernel of an intertwining map. -/
private abbrev cokerRep := σ.quotient f.range.toSubmodule f.range.apply_mem_toSubmodule

/-- The quotient map onto the cokernel as an intertwining map. -/
private def cokerProj : σ.IntertwiningMap (cokerRep f) where
  toLinearMap := f.range.toSubmodule.mkQ
  isIntertwining' := by intro γ; ext x; rfl
omit [Fintype G] in
/-- Exactness at the source of the image factorization. -/
private theorem ker_range_exact :
    Function.Exact (Subrepresentation.subtype f.ker) (IntertwiningMap.rangeRestrict f) := by
  intro x
  constructor
  · intro hx
    have hfx : f x = 0 := congrArg Subtype.val hx
    exact ⟨⟨x, hfx⟩, rfl⟩
  · rintro ⟨a, ha⟩
    rw [← ha]
    apply Subtype.ext
    exact a.property
omit [Fintype G] in
/-- Exactness at the target of the image factorization. -/
private theorem range_coker_exact :
    Function.Exact (Subrepresentation.subtype f.range) (cokerProj f) := by
  intro x
  constructor
  · intro hx
    have hx' : x ∈ f.range.toSubmodule :=
      (Submodule.Quotient.mk_eq_zero f.range.toSubmodule).mp hx
    exact ⟨⟨x, hx'⟩, rfl⟩
  · rintro ⟨a, ha⟩
    rw [← ha]
    exact (Submodule.Quotient.mk_eq_zero f.range.toSubmodule).mpr a.property
omit [Fintype G] in
/-- The cokernel projection is surjective. -/
private theorem cokerProj_surjective : Function.Surjective (cokerProj f) :=
  f.range.toSubmodule.mkQ_surjective

end Factorization

/-- A map with finite kernel and cokernel preserves the existence of Herbrand quotients. Milne,
*Class Field Theory*, Chapter II, Corollary 3.9. -/
theorem hasHerbrandQuotient_iff_of_finite_ker_coker [IsCyclic G] (f : ρ.IntertwiningMap σ)
    (hker : Finite (LinearMap.ker f.toLinearMap))
    (hcoker : Finite (W ⧸ LinearMap.range f.toLinearMap)) :
    HasHerbrandQuotient ρ ↔ HasHerbrandQuotient σ := by
  have : Finite f.ker.toSubmodule := hker
  have hK : HasHerbrandQuotient (kerRep f) := hasHerbrandQuotient_of_finite _
  have : Finite (W ⧸ f.range.toSubmodule) := hcoker
  have hC : HasHerbrandQuotient (cokerRep f) := hasHerbrandQuotient_of_finite _
  constructor
  · intro hV
    have hR : HasHerbrandQuotient (rangeRep f) :=
      HasHerbrandQuotient.of_left_of_middle (Subrepresentation.subtype_injective f.ker)
        (IntertwiningMap.rangeRestrict_surjective f) (ker_range_exact f) hK hV
    exact HasHerbrandQuotient.of_left_of_right (Subrepresentation.subtype_injective f.range)
      (cokerProj_surjective f) (range_coker_exact f) hR hC
  · intro hW
    have hR : HasHerbrandQuotient (rangeRep f) :=
      HasHerbrandQuotient.of_middle_of_right (Subrepresentation.subtype_injective f.range)
        (cokerProj_surjective f) (range_coker_exact f) hW hC
    exact HasHerbrandQuotient.of_left_of_right (Subrepresentation.subtype_injective f.ker)
      (IntertwiningMap.rangeRestrict_surjective f) (ker_range_exact f) hK hR

/-- A map with finite kernel and cokernel preserves Herbrand quotients: $h(V) = h(W)$. Milne,
*Class Field Theory*, Chapter II, Corollary 3.9. -/
theorem herbrandQuotient_eq_of_finite_ker_coker [IsCyclic G] (f : ρ.IntertwiningMap σ)
    (hker : Finite (LinearMap.ker f.toLinearMap))
    (hcoker : Finite (W ⧸ LinearMap.range f.toLinearMap)) :
    herbrandQuotient ρ = herbrandQuotient σ := by
  apply herbrandQuotient_eq_of_iff'
    (hasHerbrandQuotient_iff_of_finite_ker_coker f hker hcoker)
  intro h
  have : Finite f.ker.toSubmodule := hker
  have hK : HasHerbrandQuotient (kerRep f) := hasHerbrandQuotient_of_finite _
  have : Finite (W ⧸ f.range.toSubmodule) := hcoker
  have hC : HasHerbrandQuotient (cokerRep f) := hasHerbrandQuotient_of_finite _
  have hR : HasHerbrandQuotient (rangeRep f) :=
    HasHerbrandQuotient.of_middle_of_right (Subrepresentation.subtype_injective f.range)
      (cokerProj_surjective f) (range_coker_exact f) h hC
  have hVR := herbrandQuotient_eq_mul (Subrepresentation.subtype_injective f.ker)
    (IntertwiningMap.rangeRestrict_surjective f) (ker_range_exact f) hK hR
  have hRW := herbrandQuotient_eq_mul (Subrepresentation.subtype_injective f.range)
    (cokerProj_surjective f) (range_coker_exact f) hR hC
  have hKone : herbrandQuotient (kerRep f) = 1 :=
    herbrandQuotient_eq_one_of_finite _
  have hCone : herbrandQuotient (cokerRep f) = 1 :=
    herbrandQuotient_eq_one_of_finite _
  rw [hKone, one_mul] at hVR
  rw [hCone, mul_one] at hRW
  exact hVR.trans hRW.symm

/-- An injective intertwining map with finite cokernel preserves the Herbrand quotient. -/
theorem herbrandQuotient_eq_of_injective_of_finite_coker [IsCyclic G]
    (f : ρ.IntertwiningMap σ) (hinj : Function.Injective f)
    (hcoker : Finite (W ⧸ LinearMap.range f.toLinearMap)) :
    herbrandQuotient ρ = herbrandQuotient σ := by
  have hker : Finite (LinearMap.ker f.toLinearMap) := by
    rw [LinearMap.ker_eq_bot.mpr hinj]
    infer_instance
  exact herbrandQuotient_eq_of_finite_ker_coker f hker hcoker

/-! ### Exact pairs with finite cokernel

For an exact sequence $0 \to V' \to V \to V''$ with finite cokernel, first restrict the
last map to its image. The inclusion of this image into $V''$ has trivial kernel and finite
cokernel, so it preserves the Herbrand quotient. Thus the short exact sequence formulas
apply without requiring the last map to be surjective. -/

/-- If $0 \to V' \to V \to V''$ is exact with finite cokernel and $h(V')$, $h(V)$ are
defined, then $h(V'')$ is defined. This follows from short exact sequence multiplicativity
and finite-module invariance in Milne, *Class Field Theory*, Chapter II, Proposition 3.6
and Corollary 3.9. -/
theorem HasHerbrandQuotient.of_exact_of_finite_coker [IsCyclic G]
    {f : ρ.IntertwiningMap σ} {g : σ.IntertwiningMap τ}
    (hf : Function.Injective f) (hfg : Function.Exact f g)
    (hcoker : Finite (U ⧸ LinearMap.range g.toLinearMap))
    (h₁ : HasHerbrandQuotient ρ) (h₂ : HasHerbrandQuotient σ) :
    HasHerbrandQuotient τ := by
  have hR := HasHerbrandQuotient.of_left_of_middle hf
    (IntertwiningMap.rangeRestrict_surjective g)
    ((IntertwiningMap.exact_rangeRestrict_iff f g).mpr hfg) h₁ h₂
  have : Finite (U ⧸ g.range.toSubmodule) := hcoker
  have hC : HasHerbrandQuotient (cokerRep g) := hasHerbrandQuotient_of_finite _
  exact HasHerbrandQuotient.of_left_of_right (Subrepresentation.subtype_injective g.range)
    (cokerProj_surjective g) (range_coker_exact g) hR hC

/-- For an exact sequence $0 \to V' \to V \to V''$ with finite cokernel,
$h(V) = h(V')h(V'')$ when $h(V')$, $h(V'')$ are defined. This follows from short exact
sequence multiplicativity and finite-module invariance in Milne, *Class Field Theory*,
Chapter II, Proposition 3.6 and Corollary 3.9. -/
theorem herbrandQuotient_eq_mul_of_finite_coker [IsCyclic G]
    {f : ρ.IntertwiningMap σ} {g : σ.IntertwiningMap τ}
    (hf : Function.Injective f) (hfg : Function.Exact f g)
    (hcoker : Finite (U ⧸ LinearMap.range g.toLinearMap))
    (h₁ : HasHerbrandQuotient ρ) (h₃ : HasHerbrandQuotient τ) :
    herbrandQuotient σ = herbrandQuotient ρ * herbrandQuotient τ := by
  have : Finite (U ⧸ g.range.toSubmodule) := hcoker
  have hC : HasHerbrandQuotient (cokerRep g) := hasHerbrandQuotient_of_finite _
  have hR := HasHerbrandQuotient.of_middle_of_right
    (Subrepresentation.subtype_injective g.range) (cokerProj_surjective g)
    (range_coker_exact g) h₃ hC
  have hRC := herbrandQuotient_eq_mul (Subrepresentation.subtype_injective g.range)
    (cokerProj_surjective g) (range_coker_exact g) hR hC
  have hCone : herbrandQuotient (cokerRep g) = 1 :=
    herbrandQuotient_eq_one_of_finite _
  rw [hCone, mul_one] at hRC
  rw [hRC]
  exact herbrandQuotient_eq_mul hf (IntertwiningMap.rangeRestrict_surjective g)
    ((IntertwiningMap.exact_rangeRestrict_iff f g).mpr hfg) h₁ hR

/-! ### Equivalences

Equivalences of the two Tate groups preserve the Herbrand quotient. -/

section Transport

variable {H : Type*} [Group H] [Fintype H]

/-! The equivalences identify the two cardinalities in the rational quotient. No cyclicity of the
acting group is needed. -/

/-- Equivalences of both Tate groups preserve the Herbrand quotient, even when the acting
finite groups differ. Used by `herbrandQuotient_equiv`. -/
theorem herbrandQuotient_eq_of_equivs
    (ρ : _root_.Representation k G V) (τ : _root_.Representation k H W)
    (eZero : TateZero ρ ≃ TateZero τ) (eNegOne : TateNegOne ρ ≃ TateNegOne τ) :
    herbrandQuotient ρ = herbrandQuotient τ := by
  unfold herbrandQuotient
  rw [Nat.card_congr eZero, Nat.card_congr eNegOne]

/-- Equivalence preserves the Herbrand quotient. -/
theorem herbrandQuotient_equiv (e : ρ.Equiv σ) :
    herbrandQuotient ρ = herbrandQuotient σ := by
  exact herbrandQuotient_eq_of_equivs ρ σ
    (tateZeroEquiv e).toEquiv (tateNegOneEquiv e).toEquiv

end Transport

end Representation

end SIC
