/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.GroupCohomology.Multiplicative
import SICs.FieldTheory.GaloisDescent
import Mathlib.RepresentationTheory.Homological.GroupCohomology.Hilbert90
import Mathlib.GroupTheory.SemidirectProduct

/-!
# Tate cohomology of the multiplicative group of a Galois extension

For a finite Galois extension `L/K` with group `G`, the groups $\widehat H^0(G, L^\times) \cong
K^\times / N_{L/K} L^\times$ and, for cyclic `G`, $\widehat H^{-1}(G, L^\times) = 0$ (Hilbert's
Theorem 90) and $h(L^\times) = [K^\times : N_{L/K} L^\times]$.

This module follows Milne, *Class Field Theory*, version 4.03 (2020), Chapter II,
Corollary 1.23, Example 1.20, Exercise 3.14, and Chapter III, Lemma 2.5.

## The argument

The fixed units of $L$ are the units of $K$, and the product of all automorphisms is the field
norm, which identifies degree-zero Tate cohomology with the norm-residue quotient. For a cyclic
automorphism group generated by $\sigma$, a unit of norm one determines a crossed homomorphism
by extending the pair $(x,\sigma)$ to a splitting of the semidirect projection. Noether's form
of Hilbert 90 makes that crossed homomorphism principal, expressing $x$ as a quotient of a unit
by its $\sigma$-translate. Thus degree-minus-one Tate cohomology vanishes, and the Herbrand
quotient is the norm index.
-/

noncomputable section

namespace SIC
namespace Representation

/-! ### A cocycle from a cyclic norm-one element

A norm-one element at a generator defines a multiplicative cocycle by lifting that generator
through a semidirect product. -/

/-- The first coordinate of a semidirect power is the product of successive conjugates.
Used in `cyclic_semidirect_pow_card_eq_one`. -/
private theorem semidirect_pow_left {G M : Type*} [Group G] [CommGroup M]
    [MulDistribMulAction G M] (σ : G) (x : M) (n : ℕ) :
    ((⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^ n).left =
      ∏ i ∈ Finset.range n, σ ^ i • x := by
  induction n with
  | zero => simp
  | succ n ih =>
    have hr : ((⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^ n).right =
        σ ^ n := by
      change SemidirectProduct.rightHom
        ((⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^ n) = σ ^ n
      rw [map_pow]
      rfl
    rw [pow_succ, SemidirectProduct.mul_left, ih, Finset.prod_range_succ, hr]
    rfl

/-- A generator enumerates the finite group in the multiplicative norm.
Used in `cyclic_semidirect_pow_card_eq_one`. -/
private theorem cyclic_prod_range_eq_norm {G M : Type*} [Group G] [Fintype G]
    [CommGroup M] [MulDistribMulAction G M] (σ : G)
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) (x : M) :
    (∏ i ∈ Finset.range (Fintype.card G), σ ^ i • x) = ∏ g : G, g • x := by
  classical
  have ho : orderOf σ = Fintype.card G := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hσ, Nat.card_eq_fintype_card]
  have himg : Finset.image (fun i : ℕ => σ ^ i) (Finset.range (Fintype.card G)) =
      Finset.univ := by
    simpa only [Nat.card_eq_fintype_card] using IsCyclic.image_range_card hσ
  calc
    _ = ∏ g ∈ Finset.image (fun i : ℕ => σ ^ i) (Finset.range (Fintype.card G)),
        g • x := by
      symm
      apply Finset.prod_image
      intro a ha b hb hab
      exact pow_injOn_Iio_orderOf (by simpa [ho] using Finset.mem_range.mp ha)
        (by simpa [ho] using Finset.mem_range.mp hb) hab
    _ = _ := by rw [himg]

/-- A norm-one element makes the semidirect product element `(x, σ)` have order dividing
`|G|`. Used in `cyclic_cocycle_of_norm_one`. -/
private theorem cyclic_semidirect_pow_card_eq_one {G M : Type*} [Group G] [Fintype G]
    [CommGroup M] [MulDistribMulAction G M] (σ : G)
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) (x : M)
    (hx : (∏ g : G, g • x) = 1) :
    (⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^ Fintype.card G = 1 := by
  have ho : orderOf σ = Fintype.card G := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hσ, Nat.card_eq_fintype_card]
  apply SemidirectProduct.ext
  · change ((⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^
      Fintype.card G).left = 1
    rw [semidirect_pow_left, cyclic_prod_range_eq_norm σ hσ x, hx]
  · change SemidirectProduct.rightHom
      ((⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^ Fintype.card G) = 1
    rw [map_pow]
    change σ ^ Fintype.card G = 1
    rw [← ho, pow_orderOf_eq_one]

/-- A cyclic generator whose semidirect power is trivial extends to a splitting of the
projection. Used in `cyclic_cocycle_of_norm_one`. -/
private theorem cyclic_semidirect_lift {G M : Type*} [Group G] [Fintype G]
    [CommGroup M] [MulDistribMulAction G M] (σ : G)
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) (x : M)
    (ht : (⟨x, σ⟩ : M ⋊[MulDistribMulAction.toMulAut G M] G) ^ Fintype.card G = 1) :
    ∃ F : G →* M ⋊[MulDistribMulAction.toMulAut G M] G,
      F σ = ⟨x, σ⟩ ∧ SemidirectProduct.rightHom.comp F = MonoidHom.id G := by
  let t : M ⋊[MulDistribMulAction.toMulAut G M] G := ⟨x, σ⟩
  have ho : orderOf σ = Fintype.card G := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hσ, Nat.card_eq_fintype_card]
  have hd : orderOf t ∣ orderOf σ := by
    rw [ho]
    exact orderOf_dvd_of_pow_eq_one ht
  let F : G →* M ⋊[MulDistribMulAction.toMulAut G M] G :=
    monoidHomOfForallMemZpowers hσ hd
  have hF : F σ = t := monoidHomOfForallMemZpowers_apply_gen hσ hd
  refine ⟨F, hF, ?_⟩
  apply (MonoidHom.eq_iff_eq_on_generator hσ _ _).2
  change (F σ).right = σ
  rw [hF]

/-- A norm-one element extends from a cyclic generator to a multiplicative cocycle.
Milne, *Class Field Theory*, Chapter II, Example 1.20. -/
private theorem cyclic_cocycle_of_norm_one {G M : Type*} [Group G] [Fintype G]
    [CommGroup M] [MulDistribMulAction G M] (σ : G)
    (hσ : ∀ g : G, g ∈ Subgroup.zpowers σ) (x : M)
    (hx : (∏ g : G, g • x) = 1) :
    ∃ f : G → M, groupCohomology.IsMulCocycle₁ f ∧ f σ = x := by
  obtain ⟨F, hFσ, hright⟩ := cyclic_semidirect_lift σ hσ x
    (cyclic_semidirect_pow_card_eq_one σ hσ x hx)
  let f : G → M := fun g => (F g).left
  refine ⟨f, ?_, ?_⟩
  · intro g h
    change (F (g * h)).left = g • (F h).left * (F g).left
    rw [map_mul, SemidirectProduct.mul_left]
    have hrg : (F g).right = g :=
      congrArg (fun q : G →* G => q g) hright
    rw [hrg]
    change (F g).left * g • (F h).left = g • (F h).left * (F g).left
    exact mul_comm _ _
  · simpa [f] using congrArg SemidirectProduct.left hFσ

/-! ### Units of a finite Galois extension

The fixed units are $K^\times$; the norm and Hilbert's theorem 90 identify the two Tate
groups and the Herbrand quotient. -/

section Units

variable {K L : Type*} [Field K] [Field L] [Algebra K L] [FiniteDimensional K L]

/-- The multiplicative norm of $L^\times$ is the field norm: $\prod_{\sigma} \sigma x =
N_{L/K}(x)$. -/
theorem unitsMap_algebraMap_norm [IsGalois K L] (x : Lˣ) :
    Units.map (algebraMap K L : K →* L) (Units.map (Algebra.norm K : L →* K) x) =
      mulNorm (L ≃ₐ[K] L) Lˣ x := by
  apply Units.ext
  simp only [Units.coe_map, mulNorm_apply, Units.coe_prod, AlgEquiv.smul_units_def]
  exact Algebra.norm_eq_prod_automorphisms (K := K) (x : L)

/-- $\widehat H^0(\operatorname{Gal}(L/K), L^\times) \cong K^\times / N_{L/K} L^\times$. Milne,
*Class Field Theory*, Chapter II, §3, with Chapter III, §1. -/
def tateZeroUnitsEquiv [IsGalois K L] :
    TateZero (_root_.Representation.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) ≃+
      Additive (Kˣ ⧸ (Units.map (Algebra.norm K : L →* K)).range) :=
  tateZeroEquivOfFixed (Units.map (algebraMap K L : K →* L))
    (Units.map_injective (algebraMap K L).injective) range_unitsMap_algebraMap
    (Units.map (Algebra.norm K : L →* K)) unitsMap_algebraMap_norm

/-- Hilbert's Theorem 90 in Tate form: when the $K$-automorphism group of a finite extension
is cyclic, $\widehat H^{-1}(G,L^\times)=\ker N_G/I_G L^\times=0$. Milne, *Class Field Theory*,
Chapter II, Corollary 1.23, states the Galois case. -/
theorem subsingleton_tateNegOne_units [IsCyclic (L ≃ₐ[K] L)] :
    Subsingleton
      (TateNegOne (_root_.Representation.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ)) := by
  let ρ := _root_.Representation.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ
  have hzero (z : TateNegOne ρ) : z = 0 := by
    refine Submodule.Quotient.induction_on (augmentationSubmodule ρ) z ?_
    intro x
    apply (TateNegOne.mk_eq_zero_iff ρ x).2
    rw [mem_coinvariantsKer_ofMulDistribMulAction]
    obtain ⟨σ, hσ⟩ := IsCyclic.exists_generator (α := L ≃ₐ[K] L)
    have hx : mulNorm (L ≃ₐ[K] L) Lˣ x.val.toMul = 1 := by
      have h := x.property
      change ρ.norm x.val = 0 at h
      rw [norm_ofMulDistribMulAction] at h
      exact congrArg Additive.toMul h
    obtain ⟨f, hf, hfσ⟩ := cyclic_cocycle_of_norm_one σ hσ x.val.toMul
      (by simpa only [mulNorm_apply] using hx)
    obtain ⟨c, hc⟩ :=
      groupCohomology.isMulCoboundary₁_of_isMulCocycle₁_of_aut_to_units f hf
    apply Subgroup.subset_closure
    exact ⟨σ, c, (hc σ).trans hfσ⟩
  exact ⟨fun a b => (hzero a).trans (hzero b).symm⟩

/-- For a cyclic Galois extension the Herbrand quotient of $L^\times$ is the norm index:
$h(L^\times) = [K^\times : N_{L/K} L^\times]$, both sides being `0` when the index is infinite.
Milne, *Class Field Theory*, Chapter II, Corollary 1.23 and Exercise 3.14, used in the
proof of Chapter III, Lemma 2.5. -/
theorem herbrandQuotient_units [IsGalois K L] [IsCyclic (L ≃ₐ[K] L)] :
    herbrandQuotient (_root_.Representation.ofMulDistribMulAction (L ≃ₐ[K] L) Lˣ) =
      Nat.card (Kˣ ⧸ (Units.map (Algebra.norm K : L →* K)).range) := by
  rw [herbrandQuotient_eq_card_tateZero _ subsingleton_tateNegOne_units]
  exact_mod_cast Nat.card_congr (tateZeroUnitsEquiv (K := K) (L := L)).toEquiv

end Units

end Representation
end SIC
