/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.GroupCohomology.Herbrand

/-!
# Tate groups of multiplicative modules

The norm, invariants, and augmentation submodule of a commutative multiplicative group with a
group action, its stable subgroups, their Tate groups and finite-index Herbrand comparison, and
the description of $\widehat H^0(G,M)$ through a norm-residue quotient.

This module follows Milne, *Class Field Theory*, version 4.03 (2020), Chapter II, §1,
Proposition 1.22 and Corollary 1.23, and §3, for the multiplicative modules $L^\times$, $I_L$, and
$C_L$ of class field theory.

## The argument

On `Additive M` the action is additive, the norm $\sum_g g$ is the product $\prod_g g x$, the
invariants are the fixed points, and the augmentation submodule (the span of the $gx - x$) is the
subgroup generated by the quotients $g x / x$: a $\mathbb Z$-span is an additive subgroup closure.
If `i : B → M` is injective onto the fixed points and $i \circ \nu$ is the norm, then `i` identifies
$M^G / N_G M$ with $B / \nu(M)$.

A `G`-stable subgroup `H` of `M` is a subrepresentation; the norm of an element of `H` is its norm
in `M`, so $\widehat H^0(G, H) = 0$ says that the fixed elements of `H` are norms from `H`, and the
augmentation submodule of `H` is the set of products $\prod_g g y_g / y_g$ with $y_g \in H$.
-/

noncomputable section

namespace SIC

namespace Representation

/-! ### Norm, invariants, and augmentation of a multiplicative module -/

section Multiplicative

variable {G M N : Type*} [Group G] [CommGroup M] [MulDistribMulAction G M] [CommGroup N]
  [MulDistribMulAction G N]

variable (G M) in
/-- The norm $N_G(x) = \prod_{g \in G} g x$ of a multiplicative module, as a homomorphism.
Milne, *Class Field Theory*, Chapter II, §3. -/
def mulNorm [Fintype G] : M →* M where
  toFun x := ∏ g : G, g • x
  map_one' := by simp
  map_mul' x y := by simp [Finset.prod_mul_distrib, smul_mul']

/-- The value of the multiplicative norm. -/
theorem mulNorm_apply [Fintype G] (x : M) : mulNorm G M x = ∏ g : G, g • x :=
  rfl

/-- The norm of the additive representation is the multiplicative norm:
$N_G(x) = \prod_{g \in G} g x$. -/
@[simp]
theorem norm_ofMulDistribMulAction [Fintype G] (x : Additive M) :
    (_root_.Representation.ofMulDistribMulAction G M).norm x =
      Additive.ofMul (mulNorm G M x.toMul) := by
  simp [mulNorm, _root_.Representation.norm]

/-- The invariants of the additive representation are the fixed points. -/
theorem mem_invariants_ofMulDistribMulAction (x : Additive M) :
    x ∈ (_root_.Representation.ofMulDistribMulAction G M).invariants ↔
      x.toMul ∈ FixedPoints.subgroup G M := by
  simp only [_root_.Representation.mem_invariants, FixedPoints.mem_subgroup,
    _root_.Representation.ofMulDistribMulAction_apply_apply]
  constructor
  · intro h g
    exact congrArg Additive.toMul (h g)
  · intro h g
    exact congrArg Additive.ofMul (h g)

/-- The norm is fixed by the group: $g N_G(x) = N_G(x)$. -/
theorem smul_mulNorm [Fintype G] (g : G) (x : M) : g • mulNorm G M x = mulNorm G M x := by
  simpa only [mulNorm_apply] using Finset.smul_prod_perm x g

/-- Conjugate elements have the same norm: $N_G(g x) = N_G(x)$. -/
theorem mulNorm_smul [Fintype G] (g : G) (x : M) : mulNorm G M (g • x) = mulNorm G M x := by
  simp only [mulNorm_apply, smul_smul]
  exact Finset.prod_bijective (· * g) (Group.mulRight_bijective g) (by simp)
    (fun _ _ => rfl)

/-- A product of quotients $g y_g / y_g$ has norm one. -/
theorem mulNorm_prod_smul_div [Fintype G] (y : G → M) :
    mulNorm G M (∏ g, g • y g / y g) = 1 := by
  rw [map_prod]
  simp [map_div, mulNorm_smul]

variable (G M) in
/-- The augmentation subgroup $I_G M$, generated by the quotients $g x / x$. Milne, *Class Field
Theory*, Chapter II, §3. -/
def augmentationSubgroup : Subgroup M :=
  Subgroup.closure {y | ∃ (g : G) (x : M), g • x / x = y}

/-- The augmentation submodule of the additive representation is the augmentation subgroup. -/
theorem mem_coinvariantsKer_ofMulDistribMulAction (x : Additive M) :
    x ∈ _root_.Representation.Coinvariants.ker
        (_root_.Representation.ofMulDistribMulAction G M) ↔
      x.toMul ∈ augmentationSubgroup G M := by
  change x ∈ Submodule.span ℤ
      (Set.range fun gv : G × Additive M =>
        (_root_.Representation.ofMulDistribMulAction G M) gv.1 gv.2 - gv.2) ↔
      x ∈ (augmentationSubgroup G M).toAddSubgroup
  rw [← Submodule.mem_toAddSubgroup, Submodule.span_int_eq_addSubgroupClosure]
  rw [augmentationSubgroup, Subgroup.toAddSubgroup_closure]
  have hsets :
      (Set.range fun gv : G × Additive M =>
        (_root_.Representation.ofMulDistribMulAction G M) gv.1 gv.2 - gv.2) =
      (Additive.toMul ⁻¹' {y : M | ∃ (g : G) (z : M), g • z / z = y}) := by
    ext y
    simp only [Set.mem_range, Set.mem_preimage, Set.mem_ofPred_eq]
    constructor
    · rintro ⟨⟨g, z⟩, rfl⟩
      exact ⟨g, z.toMul, rfl⟩
    · rintro ⟨g, z, rfl⟩
      exact ⟨(g, Additive.ofMul z), rfl⟩
  rw [hsets]

/-- The augmentation subgroup consists of the products $\prod_g g y_g / y_g$, with one quotient for
each `g ∈ G`. Milne, *Class Field Theory*, Chapter II, §3. -/
theorem mem_augmentationSubgroup_iff [Fintype G] (x : M) :
    x ∈ augmentationSubgroup G M ↔ ∃ y : G → M, x = ∏ g, g • y g / y g := by
  change (Additive.ofMul x).toMul ∈ augmentationSubgroup G M ↔ _
  rw [← mem_coinvariantsKer_ofMulDistribMulAction (G := G) (M := M)
    (Additive.ofMul x), mem_coinvariantsKer_iff_exists_sum]
  constructor
  · rintro ⟨y, hy⟩
    exact ⟨fun g => (y g).toMul, (congrArg Additive.toMul hy).symm⟩
  · rintro ⟨y, hy⟩
    exact ⟨fun g => Additive.ofMul (y g), congrArg Additive.ofMul hy.symm⟩

/-- The intertwining map of an equivariant homomorphism of multiplicative modules. -/
def ofMulDistribMulActionHom (f : M →*[G] N) :
    (_root_.Representation.ofMulDistribMulAction G M).IntertwiningMap
      (_root_.Representation.ofMulDistribMulAction G N) where
  toFun x := Additive.ofMul (f x.toMul)
  map_add' x y := by
    simp [map_mul]
  map_smul' n x := by
    simp [map_zpow]
  isIntertwining' g := by
    ext x
    exact congrArg Additive.ofMul (map_smul f g x.toMul)

end Multiplicative

/-! ### Stable subgroups

A subgroup `H` of a multiplicative module stable under `G` is a subrepresentation of
`Additive M`. Its Tate group in degree $0$ vanishes exactly when every `G`-fixed element of `H` is
a norm $\prod_g g y$ with `y ∈ H`, and in degree $-1$ exactly when every element of `H` of norm
one is a product $\prod_g g y_g / y_g$ with all $y_g \in H$: the augmentation submodule of `H`
consists of these products, since $\prod_g g y_g / y_g \cdot \prod_g g y'_g / y'_g =
\prod_g g (y_g y'_g) / (y_g y'_g)$. -/

section Stable

variable {G M : Type*} [Group G] [CommGroup M] [MulDistribMulAction G M]

/-- A `G`-stable subgroup `H` of a multiplicative module `M`, as a subrepresentation of the
representation of `G` on `Additive M`. -/
def subgroupSubrep (H : Subgroup M) (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H) :
    _root_.Subrepresentation (_root_.Representation.ofMulDistribMulAction G M) where
  toSubmodule := AddSubgroup.toIntSubmodule (Subgroup.toAddSubgroup H)
  apply_mem_toSubmodule g x hx := hH g x.toMul hx

/-- Membership in the subrepresentation of a stable subgroup is membership in the subgroup. -/
@[simp]
theorem mem_subgroupSubrep {H : Subgroup M} {hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H}
    (x : Additive M) : x ∈ subgroupSubrep H hH ↔ x.toMul ∈ H := Iff.rfl

/-- The subrepresentation of a stable subgroup is monotone in the subgroup. -/
theorem subgroupSubrep_mono {H H' : Subgroup M} {hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H}
    {hH' : ∀ g : G, ∀ x ∈ H', g • x ∈ H'} (h : H ≤ H') :
    subgroupSubrep H hH ≤ subgroupSubrep H' hH' := by
  intro x hx
  exact (mem_subgroupSubrep x).2 (h ((mem_subgroupSubrep x).1 hx))

variable [Fintype G]

/-- The norm on a stable subgroup agrees with the ambient multiplicative norm; used in the
two vanishing criteria for `subgroupSubrep`. -/
private theorem subgroupSubrep_norm (H : Subgroup M)
    (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H)
    (y : (subgroupSubrep H hH).toSubmodule) :
    (((subgroupSubrep H hH).toRepresentation.norm y : Additive M).toMul) =
      mulNorm G M (y.val.toMul) := by
  let W := subgroupSubrep H hH
  have hn := IntertwiningMap.map_norm (Subrepresentation.subtype W) y
  simp only [Subrepresentation.subtype_apply, norm_ofMulDistribMulAction] at hn
  exact congrArg Additive.toMul hn

/-- A sum of augmentation differences in a stable subgroup becomes the product of their
multiplicative quotients; used in `subgroupSubrep_mem_coinvariantsKer_iff`. -/
private theorem subgroupSubrep_sum_toMul (H : Subgroup M)
    (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H)
    (y : G → (subgroupSubrep H hH).toSubmodule) :
    ((∑ g : G, ((subgroupSubrep H hH).toRepresentation g (y g) - y g) :
      (subgroupSubrep H hH).toSubmodule) : Additive M).toMul =
      ∏ g : G, (g • (y g).val.toMul) / (y g).val.toMul := by
  simp only [Submodule.coe_sum, Submodule.coe_sub]
  rfl

/-- Membership in the augmentation submodule of a stable subgroup is a product of quotients
$g y_g/y_g$ with $y_g \in H$; used in `subsingleton_tateNegOne_subgroupSubrep_iff`. -/
private theorem subgroupSubrep_mem_coinvariantsKer_iff (H : Subgroup M)
    (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H)
    (x : (subgroupSubrep H hH).toSubmodule) :
    x ∈ _root_.Representation.Coinvariants.ker
        (subgroupSubrep H hH).toRepresentation ↔
      ∃ y : G → M, (∀ g, y g ∈ H) ∧
        x.val.toMul = ∏ g : G, g • y g / y g := by
  let W := subgroupSubrep H hH
  rw [mem_coinvariantsKer_iff_exists_sum W.toRepresentation x]
  constructor
  · rintro ⟨y, hy⟩
    refine ⟨fun g => (y g).val.toMul, ?_, ?_⟩
    · intro g
      exact (mem_subgroupSubrep (y g).val).1 (y g).property
    · have hy' := congrArg (fun z : W.toSubmodule => z.val.toMul) hy
      rw [subgroupSubrep_sum_toMul H hH] at hy'
      exact hy'.symm
  · rintro ⟨y, hy, hx⟩
    let v : G → W.toSubmodule := fun g =>
      ⟨Additive.ofMul (y g), (mem_subgroupSubrep _).2 (hy g)⟩
    refine ⟨v, ?_⟩
    apply Subtype.ext
    apply Additive.toMul.injective
    change ((∑ g : G, (W.toRepresentation g (v g) - v g) : W.toSubmodule) :
      Additive M).toMul = x.val.toMul
    rw [subgroupSubrep_sum_toMul H hH]
    exact hx.symm

/-- $\widehat H^0(G, H) = 0$ exactly when every `G`-fixed element of `H` is a norm
$N_G(y) = \prod_g g y$ with `y ∈ H`. Milne, *Class Field Theory*, Chapter II, §3. -/
theorem subsingleton_tateZero_subgroupSubrep_iff (H : Subgroup M)
    (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H) :
    Subsingleton (TateZero (subgroupSubrep H hH).toRepresentation) ↔
      ∀ x ∈ H, (∀ g : G, g • x = x) → ∃ y ∈ H, mulNorm G M y = x := by
  let W := subgroupSubrep H hH
  constructor
  · intro hs x hx hfix
    let v : W.toSubmodule := ⟨Additive.ofMul x, (mem_subgroupSubrep _).2 hx⟩
    have hv : v ∈ W.toRepresentation.invariants := by
      apply (W.toRepresentation.mem_invariants v).2
      intro g
      apply Subtype.ext
      exact congrArg Additive.ofMul (hfix g)
    let z : W.toRepresentation.invariants := ⟨v, hv⟩
    have hz : (Submodule.Quotient.mk z : TateZero W.toRepresentation) = 0 :=
      Subsingleton.elim _ _
    obtain ⟨y, hy⟩ := (TateZero.mk_eq_zero_iff W.toRepresentation z).1 hz
    refine ⟨y.val.toMul, (mem_subgroupSubrep y.val).1 y.property, ?_⟩
    have hn := subgroupSubrep_norm H hH y
    rw [hy] at hn
    exact hn.symm
  · intro h
    have hzero (z : TateZero W.toRepresentation) : z = 0 := by
      refine Submodule.Quotient.induction_on (normSubmodule W.toRepresentation) z ?_
      intro v
      let x : M := v.val.val.toMul
      have hx : x ∈ H := (mem_subgroupSubrep v.val.val).1 v.val.property
      have hfix (g : G) : g • x = x := by
        have hg := (W.toRepresentation.mem_invariants v.val).1 v.property g
        exact congrArg (fun w : W.toSubmodule => w.val.toMul) hg
      obtain ⟨y, hyH, hy⟩ := h x hx hfix
      apply (TateZero.mk_eq_zero_iff W.toRepresentation v).2
      let yy : W.toSubmodule :=
        ⟨Additive.ofMul y, (mem_subgroupSubrep _).2 hyH⟩
      refine ⟨yy, ?_⟩
      apply Subtype.ext
      apply Additive.toMul.injective
      exact (subgroupSubrep_norm H hH yy).trans hy
    exact ⟨fun a b => (hzero a).trans (hzero b).symm⟩

/-- $\widehat H^{-1}(G, H) = 0$ exactly when every element of `H` of norm one is a product
$\prod_g g y_g / y_g$ with all $y_g \in H$. Milne, *Class Field Theory*, Chapter II, §3. -/
theorem subsingleton_tateNegOne_subgroupSubrep_iff (H : Subgroup M)
    (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H) :
    Subsingleton (TateNegOne (subgroupSubrep H hH).toRepresentation) ↔
      ∀ x ∈ H, mulNorm G M x = 1 → ∃ y : G → M, (∀ g, y g ∈ H) ∧ x = ∏ g, g • y g / y g := by
  let W := subgroupSubrep H hH
  constructor
  · intro hs x hx hnorm
    let v : W.toSubmodule := ⟨Additive.ofMul x, (mem_subgroupSubrep _).2 hx⟩
    have hv : v ∈ LinearMap.ker W.toRepresentation.norm := by
      change W.toRepresentation.norm v = 0
      apply Subtype.ext
      apply Additive.toMul.injective
      exact (subgroupSubrep_norm H hH v).trans hnorm
    let z : LinearMap.ker W.toRepresentation.norm := ⟨v, hv⟩
    have hz : (Submodule.Quotient.mk z : TateNegOne W.toRepresentation) = 0 :=
      Subsingleton.elim _ _
    have ha := (TateNegOne.mk_eq_zero_iff W.toRepresentation z).1 hz
    obtain ⟨y, hy, hxy⟩ := (subgroupSubrep_mem_coinvariantsKer_iff H hH v).1 ha
    exact ⟨y, hy, hxy⟩
  · intro h
    have hzero (z : TateNegOne W.toRepresentation) : z = 0 := by
      refine Submodule.Quotient.induction_on (augmentationSubmodule W.toRepresentation) z ?_
      intro v
      let x : M := v.val.val.toMul
      have hx : x ∈ H := (mem_subgroupSubrep v.val.val).1 v.val.property
      have hnorm : mulNorm G M x = 1 := by
        have hn := subgroupSubrep_norm H hH v.val
        rw [LinearMap.mem_ker.mp v.property] at hn
        exact hn.symm
      obtain ⟨y, hy, hxy⟩ := h x hx hnorm
      apply (TateNegOne.mk_eq_zero_iff W.toRepresentation v).2
      exact (subgroupSubrep_mem_coinvariantsKer_iff H hH v.val).2 ⟨y, hy, hxy⟩
    exact ⟨fun a b => (hzero a).trans (hzero b).symm⟩

omit [Fintype G] in
/-- The inclusion of stable subgroups $V \le H$ has finite cokernel when $H/V$ is finite;
used in the two Herbrand quotient comparisons below. -/
private theorem finiteCoker_subgroupSubrepInclusion {V H : Subgroup M}
    (hV : ∀ g : G, ∀ x ∈ V, g • x ∈ V) (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H)
    (hle : V ≤ H) (hfin : (V.subgroupOf H).FiniteIndex) :
    Finite ((subgroupSubrep H hH).toSubmodule ⧸
      LinearMap.range (Subrepresentation.inclusion
        (subgroupSubrep_mono (hH := hV) (hH' := hH) hle)).toLinearMap) := by
  let W := subgroupSubrep V hV
  let U := subgroupSubrep H hH
  let inc : W.toRepresentation.IntertwiningMap U.toRepresentation :=
    Subrepresentation.inclusion (subgroupSubrep_mono (hH := hV) (hH' := hH) hle)
  let C := U.toSubmodule ⧸ LinearMap.range inc.toLinearMap
  let φ : H →* Multiplicative C := {
    toFun u := Multiplicative.ofAdd (Submodule.Quotient.mk
      (⟨Additive.ofMul (u : M), by
        change (u : M) ∈ H
        exact u.property⟩ : U.toSubmodule))
    map_one' := by rfl
    map_mul' := by intros; rfl }
  have hsurj : Function.Surjective φ := by
    intro c
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective (LinearMap.range inc.toLinearMap) c
    let u : H := ⟨x.val.toMul, x.property⟩
    exact ⟨u, rfl⟩
  have hker : V.subgroupOf H ≤ φ.ker := by
    intro x hx
    change φ x = 1
    change (Submodule.Quotient.mk (⟨Additive.ofMul (x : M), _⟩ : U.toSubmodule) : C) = 0
    rw [Submodule.Quotient.mk_eq_zero]
    let y : W.toSubmodule := ⟨Additive.ofMul (x : M), hx⟩
    exact ⟨y, rfl⟩
  have hq : Finite (H ⧸ φ.ker) :=
    Subgroup.finiteIndex_iff_finite_quotient.mp
      (@Subgroup.finiteIndex_of_le _ _ _ _ hfin hker)
  have hfinite : Finite (Multiplicative C) :=
    (QuotientGroup.quotientKerEquivOfSurjective φ hsurj).finite_iff.mp hq
  exact hfinite

/-- For `G`-stable subgroups $V \le H$ with `V` of finite index in `H`, $h(V) = h(H)$.
Milne, *Class Field Theory*, Chapter II, Corollary 3.9. -/
theorem herbrandQuotient_subgroupSubrep_eq [IsCyclic G] {V H : Subgroup M}
    (hV : ∀ g : G, ∀ x ∈ V, g • x ∈ V) (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H) (hle : V ≤ H)
    (hfin : (V.subgroupOf H).FiniteIndex) :
    herbrandQuotient (subgroupSubrep V hV).toRepresentation =
      herbrandQuotient (subgroupSubrep H hH).toRepresentation := by
  let hle' := subgroupSubrep_mono (hH := hV) (hH' := hH) hle
  exact herbrandQuotient_eq_of_injective_of_finite_coker
    (Subrepresentation.inclusion hle') (Subrepresentation.inclusion_injective hle')
    (finiteCoker_subgroupSubrepInclusion hV hH hle hfin)

/-- For `G`-stable subgroups $V \le H$ with `V` of finite index in `H`, the Herbrand quotient of
`V` is defined exactly when that of `H` is. Milne, *Class Field Theory*, Chapter II,
Corollary 3.9. -/
theorem hasHerbrandQuotient_subgroupSubrep_iff [IsCyclic G] {V H : Subgroup M}
    (hV : ∀ g : G, ∀ x ∈ V, g • x ∈ V) (hH : ∀ g : G, ∀ x ∈ H, g • x ∈ H) (hle : V ≤ H)
    (hfin : (V.subgroupOf H).FiniteIndex) :
    HasHerbrandQuotient (subgroupSubrep V hV).toRepresentation ↔
      HasHerbrandQuotient (subgroupSubrep H hH).toRepresentation :=
  hasHerbrandQuotient_iff_of_eq' (herbrandQuotient_subgroupSubrep_eq hV hH hle hfin)

end Stable

/-! ### Norm residues of a multiplicative module

When the fixed points are a copy of a group `B` and the norm factors through `B`, the Tate group
in degree $0$ is the quotient of `B` by the norms. -/

section NormResidues

variable {G M B : Type*} [Group G] [Fintype G] [CommGroup M] [MulDistribMulAction G M]
  [CommGroup B]

/-- The identification of `B` with the invariant vectors used in `tateZeroEquivOfFixed`. -/
private def fixedAddEquiv (i : B →* M) (hi : Function.Injective i)
    (hrange : i.range = FixedPoints.subgroup G M) :
    Additive B ≃+ (_root_.Representation.ofMulDistribMulAction G M).invariants := by
  let j : Additive B →+ (_root_.Representation.ofMulDistribMulAction G M).invariants := {
    toFun := fun b => ⟨Additive.ofMul (i b.toMul), by
      rw [mem_invariants_ofMulDistribMulAction]
      rw [← hrange]
      exact ⟨b.toMul, rfl⟩⟩
    map_zero' := by
      apply Subtype.ext
      simp
    map_add' := by
      intro b c
      apply Subtype.ext
      simp [map_mul]
  }
  apply AddEquiv.ofBijective j
  constructor
  · intro b c h
    apply Additive.toMul.injective
    apply hi
    exact congrArg Additive.toMul (congrArg Subtype.val h)
  · intro z
    have hz : z.val.toMul ∈ FixedPoints.subgroup G M :=
      (mem_invariants_ofMulDistribMulAction z.val).1 z.property
    rw [← hrange] at hz
    obtain ⟨b, hb⟩ := hz
    refine ⟨Additive.ofMul b, ?_⟩
    apply Subtype.ext
    exact congrArg Additive.ofMul hb

omit [Fintype G] in
/-- The fixed-point equivalence sends `b` to the invariant vector represented by `i(b)`. -/
private theorem fixedAddEquiv_apply (i : B →* M) (hi : Function.Injective i)
    (hrange : i.range = FixedPoints.subgroup G M) (b : B) :
    ((fixedAddEquiv i hi hrange (Additive.ofMul b) :
      (_root_.Representation.ofMulDistribMulAction G M).invariants) : Additive M) =
      Additive.ofMul (i b) := rfl

/-- The fixed-point equivalence carries `ν(M)` to the norm submodule. -/
private theorem fixedAddEquiv_map_range (i : B →* M) (hi : Function.Injective i)
    (hrange : i.range = FixedPoints.subgroup G M) (ν : M →* B)
    (hν : ∀ x, i (ν x) = mulNorm G M x) :
    AddSubgroup.map (fixedAddEquiv i hi hrange : Additive B →+
      (_root_.Representation.ofMulDistribMulAction G M).invariants)
      ν.range.toAddSubgroup =
      (normSubmodule (_root_.Representation.ofMulDistribMulAction G M)).toAddSubgroup := by
  let ρ := _root_.Representation.ofMulDistribMulAction G M
  have hnorm (z : ρ.invariants) :
      z ∈ normSubmodule ρ ↔
        ∃ x : M, fixedAddEquiv i hi hrange (Additive.ofMul (ν x)) = z := by
    change (z : Additive M) ∈ LinearMap.range ρ.norm ↔ _
    constructor
    · rintro ⟨v, hv⟩
      refine ⟨v.toMul, ?_⟩
      apply Subtype.ext
      rw [fixedAddEquiv_apply, hν, ← norm_ofMulDistribMulAction]
      exact hv
    · rintro ⟨x, hx⟩
      refine ⟨Additive.ofMul x, ?_⟩
      have h := congrArg Subtype.val hx
      rw [fixedAddEquiv_apply, hν] at h
      rw [norm_ofMulDistribMulAction]
      exact h
  ext z
  rw [AddSubgroup.mem_map]
  constructor
  · rintro ⟨b, hb, rfl⟩
    change b.toMul ∈ ν.range at hb
    obtain ⟨x, hx⟩ := hb
    have hb' : b = Additive.ofMul (ν x) :=
      (congrArg Additive.ofMul hx).symm
    subst b
    exact (hnorm _).2 ⟨x, rfl⟩
  · intro hz
    obtain ⟨x, hx⟩ := (hnorm z).1 hz
    exact ⟨Additive.ofMul (ν x), ⟨x, rfl⟩, hx⟩

/-- The equivalence on norm quotients induced by `fixedAddEquiv`. -/
private def fixedQuotientEquiv (i : B →* M) (hi : Function.Injective i)
    (hrange : i.range = FixedPoints.subgroup G M) (ν : M →* B)
    (hν : ∀ x, i (ν x) = mulNorm G M x) :
    (Additive B ⧸ ν.range.toAddSubgroup) ≃+
      TateZero (_root_.Representation.ofMulDistribMulAction G M) :=
  QuotientAddGroup.congr ν.range.toAddSubgroup
    (normSubmodule (_root_.Representation.ofMulDistribMulAction G M)).toAddSubgroup
    (fixedAddEquiv i hi hrange) (fixedAddEquiv_map_range i hi hrange ν hν)

/-- The additive quotient of `B` by `ν(M)` is the additive group of `B / ν(M)`.
Used in `tateZeroEquivOfFixed`. -/
private def additiveQuotientEquiv (ν : M →* B) :
    (Additive B ⧸ ν.range.toAddSubgroup) ≃+ Additive (B ⧸ ν.range) := by
  let φ : Additive B →+ Additive (B ⧸ ν.range) :=
    (QuotientGroup.mk' ν.range).toAdditive
  have hker : φ.ker = ν.range.toAddSubgroup := by
    ext b
    simp [φ]
  have hsurj : Function.Surjective φ := by
    intro b
    obtain ⟨x, hx⟩ := QuotientGroup.mk'_surjective ν.range b.toMul
    exact ⟨Additive.ofMul x, congrArg Additive.ofMul hx⟩
  exact (QuotientAddGroup.quotientAddEquivOfEq hker.symm).trans
    (QuotientAddGroup.quotientKerEquivOfSurjective φ hsurj)

/-- If `i : B → M` is injective onto the fixed points $M^G$ and `i ∘ ν = N_G`, then
$\widehat H^0(G, M) = M^G / N_G M \cong B / ν(M)$. Milne, *Class Field Theory*, Chapter II,
§3. -/
def tateZeroEquivOfFixed (i : B →* M) (hi : Function.Injective i)
    (hrange : i.range = FixedPoints.subgroup G M) (ν : M →* B)
    (hν : ∀ x, i (ν x) = mulNorm G M x) :
    TateZero (_root_.Representation.ofMulDistribMulAction G M) ≃+ Additive (B ⧸ ν.range) :=
  (fixedQuotientEquiv i hi hrange ν hν).symm.trans (additiveQuotientEquiv ν)

end NormResidues

end Representation

end SIC
