/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.Quadratic.TowerValues
import Mathlib.Algebra.Polynomial.Degree.IsMonicOfDegree
import Mathlib.LinearAlgebra.FreeModule.Finite.CardQuotient

/-!
# Orders Generated by Real-Quadratic Unit Powers

The suborder `ℤ[ε^j]`, its lattice, and the divisibility `j ∣ k` forced by `ε^k ∈ ℤ[ε^j]`.

At a positive tower index `j`, the suborder `ℤ[ε^j]` of the maximal order has underlying lattice
`ℤ · 1 + ℤ · ε^j`, and it contains a power `ε^k` only when `j ∣ k`. This is the order-membership
form of one direction of [AFK25, Theorem 4.14(4), `thm:UnitsConductorsIndicesProperties`].

## Main results

- `RealQuadraticUnitData.powerOrder`: the suborder `ℤ[ε^j]` of the ring of integers.
- `RealQuadraticUnitData.powerOrder_toSubmodule`: its underlying rank-two lattice.
- `RealQuadraticUnitData.dvd_of_epsilon_pow_mem_powerOrder`: membership `ε^k ∈ ℤ[ε^j]` forces
  the exponent divisibility `j ∣ k`.

## References

- [AFK25, Definition 1.23, equation (1.37), `dfn:sequenceofconductors`]
- [AFK25, Definition 1.47, `dfn:orderConductorf`]
- [AFK25, Theorem 4.14, `thm:UnitsConductorsIndicesProperties`]
-/

noncomputable section

namespace SIC

namespace RealQuadraticUnitData

open Module NumberField Polynomial

variable {K : Type*} [Field K] [NumberField K] [NumberField.IsTotallyReal K]

/-! ### The order generated by a unit power

The order is defined as an algebraic adjoin inside the maximal order. The quadratic
trace-and-norm equation later shows that every higher power reduces to a linear combination of
`1` and `ε^j`.
-/

/-- The quadratic order `ℤ[ε^j]`, represented as a `ℤ`-subalgebra of the maximal order `𝒪_K`.

The inclusion into `𝒪_K` is the subtype map of this subalgebra. For positive `j` it is the order
`𝒪_{f_j}` of [AFK25, Definition 1.47, `dfn:orderConductorf`]. At the extra API value `j = 0`,
this is only the degenerate subalgebra `ℤ · 1`, not a full-rank quadratic order;
[AFK25, Definition 1.23, `dfn:sequenceofconductors`] only uses positive indices. -/
def powerOrder (T : RealQuadraticUnitData K) (j : ℕ) :
    Subalgebra ℤ (NumberField.RingOfIntegers K) :=
  Algebra.adjoin ℤ {((T.epsilon ^ j : (NumberField.RingOfIntegers K)ˣ) :
    NumberField.RingOfIntegers K)}

/-- The integral unit power satisfies its quadratic trace-and-norm equation, with norm one.

This specializes `quadratic_sq_eq_trace_mul_sub_norm` for the reduction of powers in
`powerOrder_toSubmodule`. -/
private lemma epsilonPowInt_sq (T : RealQuadraticUnitData K) (j : ℕ) :
    let x : NumberField.RingOfIntegers K :=
      ((T.epsilon ^ j : (NumberField.RingOfIntegers K)ˣ) :
        NumberField.RingOfIntegers K)
    x ^ 2 = algebraMap ℤ (NumberField.RingOfIntegers K)
        (Algebra.trace ℤ (NumberField.RingOfIntegers K) x) * x - 1 := by
  intro x
  rw [T.finrank_eq_two |> quadratic_sq_eq_trace_mul_sub_norm]
  have hnormQ : ((Algebra.norm ℤ x : ℤ) : ℚ) = 1 := by
    rw [Algebra.coe_norm_int]
    simpa [x, NumberField.Units.coe_pow] using T.epsilon_pow_norm_eq_one j
  have hnorm : Algebra.norm ℤ x = 1 := by exact_mod_cast hnormQ
  rw [hnorm, map_one]

/-! ### Underlying lattice

The monic quadratic for `ε^j` identifies the generated order with the lattice on `(1, ε^j)`.
-/

/-- The underlying `ℤ`-module of `ℤ[ε^j]` is exactly the span of `(1, ε^j)`.

The quadratic trace-and-norm equation gives a monic degree-two polynomial annihilating `ε^j`;
Mathlib's monic-polynomial adjoin theorem then reduces every element of `ℤ[ε^j]` to the first
two powers. -/
lemma powerOrder_toSubmodule (T : RealQuadraticUnitData K) (j : ℕ+) :
    (T.powerOrder (j : ℕ)).toSubmodule =
      Submodule.span ℤ (Set.range (T.powerPair (j : ℕ))) := by
  let x : NumberField.RingOfIntegers K :=
    ((T.epsilon ^ (j : ℕ) : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K)
  let f : ℤ[X] := X ^ 2 - C (Algebra.trace ℤ (NumberField.RingOfIntegers K) x) * X + C 1
  have hf : f.IsMonicOfDegree 2 := isMonicOfDegree_sub_add_two _ _
  have hfx : aeval x f = 0 := by
    dsimp only [f]
    simp only [map_add, map_sub, map_pow, map_mul, aeval_X, aeval_C, map_one]
    rw [T.epsilonPowInt_sq (j : ℕ)]
    ring
  change (Algebra.adjoin ℤ {x}).toSubmodule = _
  rw [← Submodule.span_range_natDegree_eq_adjoin hf.monic hfx, hf.natDegree_eq]
  simp only [show Finset.range 2 = {0, 1} by decide, Finset.image_insert,
    Finset.image_singleton, pow_zero, pow_one]
  congr 1
  ext y
  simp [powerPair, x, or_comm]

/-! ### Exponents detected by the generated order

The order `ℤ[ε^j]` contains `ε^{-j}` by the quadratic trace relation.  Reducing an exponent modulo
`j` therefore reduces membership to a power `ε^s` with `0 ≤ s < j`.  Its expression in the
lattice basis `(1, ε^j)`, evaluated at the selected real embedding and compared with traces,
forces an impossible integral coefficient strictly between zero and one unless `s = 0`.
-/

/-- The inverse power `ε^{-j}` belongs to the order generated by `ε^j`. -/
private lemma epsilonPowInv_mem_powerOrder (T : RealQuadraticUnitData K) (j : ℕ+) :
    (((T.epsilon ^ (j : ℕ))⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) ∈ T.powerOrder (j : ℕ) := by
  let x : NumberField.RingOfIntegers K :=
    ((T.epsilon ^ (j : ℕ) : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K)
  have hx : x ∈ T.powerOrder (j : ℕ) := by
    apply Algebra.subset_adjoin
    exact Set.mem_singleton x
  have hsq := T.epsilonPowInt_sq (j : ℕ)
  dsimp only at hsq
  have hinv : (((T.epsilon ^ (j : ℕ))⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) =
      algebraMap ℤ (NumberField.RingOfIntegers K)
        (Algebra.trace ℤ (NumberField.RingOfIntegers K) x) - x := by
    have hxne : x ≠ 0 := (T.epsilon ^ (j : ℕ)).isUnit.ne_zero
    apply mul_right_cancel₀ hxne
    change (((T.epsilon ^ (j : ℕ))⁻¹ : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) *
        ((T.epsilon ^ (j : ℕ) : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) = _
    rw [Units.inv_mul]
    rw [sub_mul]
    rw [← pow_two]
    rw [hsq]
    ring
  rw [hinv]
  exact (T.powerOrder (j : ℕ)).sub_mem ((T.powerOrder (j : ℕ)).algebraMap_mem _) hx

/-- Membership in `ℤ[ε^j]` gives integral coordinates in the basis `(1, ε^j)`. -/
private lemma exists_int_add_mul_epsilonPow_of_mem_powerOrder
    (T : RealQuadraticUnitData K) (j : ℕ+) {z : NumberField.RingOfIntegers K}
    (hz : z ∈ T.powerOrder (j : ℕ)) :
    ∃ b c : ℤ, z = algebraMap ℤ (NumberField.RingOfIntegers K) b +
      algebraMap ℤ (NumberField.RingOfIntegers K) c *
        ((T.epsilon ^ (j : ℕ) : (NumberField.RingOfIntegers K)ˣ) :
          NumberField.RingOfIntegers K) := by
  change z ∈ (T.powerOrder (j : ℕ)).toSubmodule at hz
  rw [T.powerOrder_toSubmodule j] at hz
  obtain ⟨a, ha⟩ := (Submodule.mem_span_range_iff_exists_fun ℤ).mp hz
  refine ⟨a 0, a 1, ?_⟩
  rw [← ha]
  simp [powerPair]

/-- If a norm-one element is `b + c ε^j`, its conjugate real value is
`b + c ρ₁(ε^j)⁻¹`. This is the conjugate-value step used by
`not_epsilonPow_mem_powerOrder_of_lt`. -/
private lemma realEmbedding_inv_eq_int_add_mul_epsilonPow_inv
    (T : RealQuadraticUnitData K) (j : ℕ+) (y : K) (b c : ℤ)
    (hnorm : Algebra.norm ℚ y = 1)
    (hy : y = (b : K) + (c : K) * (T.epsilon : K) ^ (j : ℕ)) :
    (realEmbeddingAt K T.place y)⁻¹ =
      (b : ℝ) + (c : ℝ) * (T.epsilonReal ^ (j : ℕ))⁻¹ := by
  have htracey := T.trace_eq_embedding_add_inv y hnorm
  have htracej := T.trace_eq_embedding_add_inv ((T.epsilon : K) ^ (j : ℕ))
    (T.epsilon_pow_norm_eq_one (j : ℕ))
  have htraceField := congrArg (Algebra.trace ℚ K) hy
  have htraceReal := congrArg (fun q : ℚ ↦ (q : ℝ)) htraceField
  have hbtrace : Algebra.trace ℚ K (b : K) = 2 * (b : ℚ) := by
    rw [show (b : K) = algebraMap ℚ K (b : ℚ) by norm_num]
    rw [Algebra.trace_algebraMap, T.finrank_eq_two]
    norm_num
  have hctrace : Algebra.trace ℚ K ((c : K) * (T.epsilon : K) ^ (j : ℕ)) =
      (c : ℚ) * Algebra.trace ℚ K ((T.epsilon : K) ^ (j : ℕ)) := by
    rw [show (c : K) = algebraMap ℚ K (c : ℚ) by norm_num]
    rw [← Algebra.smul_def, map_smul]
    rfl
  rw [map_add, hbtrace, hctrace] at htraceReal
  push_cast at htraceReal
  rw [htracey, htracej] at htraceReal
  simp only [map_pow] at htraceReal
  change realEmbeddingAt K T.place y + (realEmbeddingAt K T.place y)⁻¹ =
    2 * (b : ℝ) + (c : ℝ) *
      (T.epsilonReal ^ (j : ℕ) + (T.epsilonReal ^ (j : ℕ))⁻¹) at htraceReal
  have hyval := congrArg (realEmbeddingAt K T.place) hy
  simp only [map_add, map_mul, map_intCast, map_pow] at hyval
  change realEmbeddingAt K T.place y =
    (b : ℝ) + (c : ℝ) * T.epsilonReal ^ (j : ℕ) at hyval
  nlinarith

/-- An integral coefficient cannot scale `x - x⁻¹` to `y - y⁻¹` when
`1 < y < x`. This is the inequality step used by `not_epsilonPow_mem_powerOrder_of_lt`. -/
private lemma not_int_mul_sub_inv_eq_of_between {x y : ℝ} (c : ℤ)
    (hx : 1 < x) (hy : 1 < y) (hyx : y < x)
    (hsub : y - y⁻¹ = (c : ℝ) * (x - x⁻¹)) : False := by
  have hypos : 0 < y := lt_trans Real.zero_lt_one hy
  have hxpos : 0 < x := lt_trans Real.zero_lt_one hx
  have hinv : x⁻¹ < y⁻¹ := (inv_lt_inv₀ hxpos hypos).2 hyx
  have hydiff : 0 < y - y⁻¹ := by
    have : y⁻¹ < 1 := inv_lt_one_of_one_lt₀ hy
    linarith
  have hdiff : y - y⁻¹ < x - x⁻¹ := by linarith
  have hxinv : x⁻¹ < 1 := inv_lt_one_of_one_lt₀ hx
  have hxdiff : 0 < x - x⁻¹ := by linarith
  have hcpos : (0 : ℝ) < c := by nlinarith [hsub]
  have hclt : (c : ℝ) < 1 := by nlinarith [hsub]
  have hcposInt : (0 : ℤ) < c := by exact_mod_cast hcpos
  have hcltInt : c < (1 : ℤ) := by exact_mod_cast hclt
  omega

/-- No strictly intermediate positive power `ε^s`, with `s < j`, belongs to `ℤ[ε^j]`. -/
private lemma not_epsilonPow_mem_powerOrder_of_lt (T : RealQuadraticUnitData K) (j : ℕ+)
    {s : ℕ} (hspos : 0 < s) (hsj : s < (j : ℕ)) :
    ¬ ((T.epsilon ^ s : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) ∈ T.powerOrder (j : ℕ) := by
  intro hs
  obtain ⟨b, c, hbc⟩ := T.exists_int_add_mul_epsilonPow_of_mem_powerOrder j hs
  have hfield : (T.epsilon : K) ^ s = (b : K) + (c : K) * (T.epsilon : K) ^ (j : ℕ) := by
    have hcoe := congrArg (fun z : NumberField.RingOfIntegers K ↦ (z : K)) hbc
    simpa [NumberField.Units.coe_pow] using hcoe
  let x : ℝ := T.epsilonReal ^ (j : ℕ)
  let y : ℝ := T.epsilonReal ^ s
  have hxy : y = (b : ℝ) + (c : ℝ) * x := by
    have h := congrArg (realEmbeddingAt K T.place) hfield
    simpa [x, y, epsilonReal, map_pow] using h
  have hyinv : y⁻¹ = (b : ℝ) + (c : ℝ) * x⁻¹ := by
    simpa [x, y, epsilonReal, map_pow] using
      T.realEmbedding_inv_eq_int_add_mul_epsilonPow_inv j ((T.epsilon : K) ^ s) b c
        (T.epsilon_pow_norm_eq_one s) hfield
  apply not_int_mul_sub_inv_eq_of_between c (T.one_lt_epsilonReal_pow j)
    (one_lt_pow₀ T.one_lt_epsilonReal hspos.ne')
    (pow_lt_pow_right₀ T.one_lt_epsilonReal hsj)
  nlinarith [hxy, hyinv]

/-- If `ε^k ∈ ℤ[ε^j]` for `j ≥ 1`, then `j ∣ k`.

This is the direction `f_j ∣ f_k → j ∣ k` of [AFK25, Theorem 4.14(4),
`thm:UnitsConductorsIndicesProperties`] in the order-membership form used in the proof of
Theorem 4.20(B). The source passes through the classification of quadratic orders; this proof
instead reduces `k` modulo `j` inside `ℤ[ε^j]` and uses the selected real embedding directly. -/
theorem dvd_of_epsilon_pow_mem_powerOrder (T : RealQuadraticUnitData K) (j : ℕ+) (k : ℕ)
    (h : ((T.epsilon ^ k : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) ∈ T.powerOrder (j : ℕ)) : (j : ℕ) ∣ k := by
  let s := k % (j : ℕ)
  let q := k / (j : ℕ)
  have hslt : s < (j : ℕ) := Nat.mod_lt _ j.property
  have hunit : T.epsilon ^ s = T.epsilon ^ k * ((T.epsilon ^ (j : ℕ))⁻¹) ^ q := by
    have hk : k = s + (j : ℕ) * q := by
      dsimp [s, q]
      exact (Nat.mod_add_div k (j : ℕ)).symm
    rw [hk, pow_add, inv_pow, ← pow_mul]
    simp
  have hs : ((T.epsilon ^ s : (NumberField.RingOfIntegers K)ˣ) :
      NumberField.RingOfIntegers K) ∈ T.powerOrder (j : ℕ) := by
    rw [hunit]
    exact (T.powerOrder (j : ℕ)).mul_mem h (pow_mem (T.epsilonPowInv_mem_powerOrder j) q)
  have hszero : s = 0 := by
    by_contra hsne
    exact T.not_epsilonPow_mem_powerOrder_of_lt j (Nat.pos_of_ne_zero hsne) hslt hs
  exact Nat.dvd_of_mod_eq_zero hszero

end RealQuadraticUnitData

end SIC

end
