/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import Mathlib.FieldTheory.KummerExtension
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure
import Mathlib.FieldTheory.Galois.Abelian
import Mathlib.FieldTheory.SeparableClosure
import Mathlib.GroupTheory.Finiteness

/-!
# Kummer extensions generated by a subgroup

The extension obtained by adjoining roots of a finitely generated multiplicative subgroup.

This follows Milne, *Class Field Theory*, version 4.03 (2020), Chapter VII, Appendix A.3,
and *Fields and Galois Theory*, version 5.10 (2022), Theorem 5.30.

## The argument

Adjoin all nth roots of elements of the subgroup in an algebraic closure. Finitely many
subgroup generators suffice, since products and inverses of roots remain in the resulting
field, and roots of unity account for the choice of root. When the base contains a primitive
nth root of unity, every generator polynomial splits. Automorphisms multiply each root by a
base-field root of unity; their action is therefore commutative and killed by n.
-/

noncomputable section

namespace SIC

variable (K : Type*) [Field K]

/-- The field $K[B^{1/n}]$ generated by all nth roots of elements of $B$.
Milne, *Class Field Theory*, Chapter VII, Appendix A.3. -/
def kummerExtension (n : ℕ) (B : Subgroup Kˣ) : IntermediateField K (AlgebraicClosure K) :=
  IntermediateField.adjoin K {x | ∃ b : B, x ^ n = algebraMap K _ (b.val : K)}

variable {K} {n : ℕ} {B : Subgroup Kˣ}

/-- Every specified nth root of an element of $B$ lies in $K[B^{1/n}]$. -/
theorem root_mem_kummerExtension (b : B) {x : AlgebraicClosure K}
    (hx : x ^ n = algebraMap K _ (b.val : K)) : x ∈ kummerExtension K n B :=
  IntermediateField.subset_adjoin K _ ⟨b, hx⟩

/-- The universal property of $K[B^{1/n}]$: it is the smallest intermediate field
containing all nth roots of elements of $B$. -/
theorem kummerExtension_le_iff (E : IntermediateField K (AlgebraicClosure K)) :
    kummerExtension K n B ≤ E ↔
      ∀ b : B, ∀ x : AlgebraicClosure K, x ^ n = algebraMap K _ (b.val : K) → x ∈ E := by
  rw [kummerExtension, IntermediateField.adjoin_le_iff]
  exact ⟨fun h b x hx ↦ h ⟨b, hx⟩, fun h x ⟨b, hx⟩ ↦ h b x hx⟩

/-- Algebra homomorphisms out of $K[B^{1/n}]$ agree if they agree on every radical
of an element of $B$. -/
theorem kummerExtension_algHom_ext {F : Type*} [Semiring F] [Algebra K F]
    {f g : kummerExtension K n B →ₐ[K] F}
    (h : ∀ b : B, ∀ x : kummerExtension K n B,
      x ^ n = algebraMap K _ (b.val : K) → f x = g x) : f = g := by
  apply IntermediateField.adjoin_algHom_ext K
  rintro x ⟨b, hx⟩
  exact h b ⟨x, root_mem_kummerExtension b hx⟩ (Subtype.ext hx)

/-- The constructed radical extension is generated by its radical elements over $K$.
This is the internal form of the defining adjunction in `kummerExtension`. -/
theorem kummerExtension_adjoin_radicals_eq_top (n : ℕ) (B : Subgroup Kˣ) :
    IntermediateField.adjoin K {x : kummerExtension K n B | ∃ b : B,
      x ^ n = algebraMap K _ (b.val : K)} = ⊤ := by
  let E := IntermediateField.adjoin K {x : kummerExtension K n B | ∃ b : B,
    x ^ n = algebraMap K _ (b.val : K)}
  have hle : kummerExtension K n B ≤ IntermediateField.lift E := by
    apply (kummerExtension_le_iff _).mpr
    intro b x hx
    refine ⟨⟨x, root_mem_kummerExtension b hx⟩, ?_, rfl⟩
    exact IntermediateField.subset_adjoin K _ ⟨b, Subtype.ext hx⟩
  apply top_unique
  intro x _
  exact (IntermediateField.mem_lift x).mp (hle x.property)

/-- Every $b\in B$ has an nth root in $K[B^{1/n}]$ when $n>0$. -/
theorem exists_root_kummerExtension (hn : 0 < n) (b : B) :
    ∃ x : kummerExtension K n B, x ^ n = algebraMap K _ (b.val : K) := by
  obtain ⟨x, hx⟩ := IsAlgClosed.exists_pow_nat_eq
    (algebraMap K (AlgebraicClosure K) (b.val : K)) hn
  exact ⟨⟨x, root_mem_kummerExtension b hx⟩, Subtype.ext hx⟩

/-! ### Radicands and finite generators

The base elements admitting an nth root in an extension form a subgroup. Thus roots of
subgroup generators supply roots of every element. A primitive root of unity in the base
then accounts for every choice of nth root. -/

variable (K) (n : ℕ) (L : Type*) [Field L] [Algebra K L]

/-- The subgroup $B(L)=K^\times\cap L^{\times n}$ of units that acquire an nth root in $L$.
Milne, *Fields and Galois Theory*, version 5.10 (2022), proof of Theorem 5.30. -/
def kummerRadicands : Subgroup Kˣ where
  carrier := {b | ∃ x : L, x ^ n = algebraMap K L (b : K)}
  one_mem' := ⟨1, by simp⟩
  mul_mem' := by
    rintro a b ⟨x, hx⟩ ⟨y, hy⟩
    exact ⟨x * y, by simp [mul_pow, hx, hy]⟩
  inv_mem' := by
    rintro a ⟨x, hx⟩
    exact ⟨x⁻¹, by simp [inv_pow, hx]⟩

variable {K n L}

/-- Roots of equal powers differ by a base-field root of unity; used by
`automorphism_root_image`. -/
theorem exists_base_mul_of_pow_eq {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (hn : 0 < n) {x y : L} (hxy : x ^ n = y ^ n) :
    ∃ i : ℕ, i < n ∧ x = algebraMap K L (ζ ^ i) * y := by
  have hx := (Polynomial.mem_nthRoots hn).2 hxy
  rw [(hζ.map_of_injective (algebraMap K L).injective).nthRoots_eq rfl] at hx
  obtain ⟨i, hi, heq⟩ := Multiset.mem_map.mp hx
  exact ⟨i, Multiset.mem_range.mp hi, by simpa using heq.symm⟩

/-- A field containing $\mu_n$ and one nth root contains every choice of that root;
used by the finite-generation arguments below. -/
private theorem root_mem_of_root (hn : 0 < n)
    (E : IntermediateField K (AlgebraicClosure K))
    (hμ : ∀ z : AlgebraicClosure K, z ^ n = 1 → z ∈ E) {b : Kˣ}
    (hb : b ∈ kummerRadicands K n E) {x : AlgebraicClosure K}
    (hx : x ^ n = algebraMap K _ (b : K)) : x ∈ E := by
  obtain ⟨y, hy⟩ := hb
  have hy' : (y.val : AlgebraicClosure K) ^ n = algebraMap K _ (b : K) :=
    congrArg Subtype.val hy
  have hb0 : algebraMap K (AlgebraicClosure K) (b : K) ≠ 0 :=
    (map_ne_zero (algebraMap K (AlgebraicClosure K))).2 b.ne_zero
  have hμxy : (x / y.val) ^ n = 1 := by rw [div_pow, hx, hy', div_self hb0]
  have hy0 : (y.val : AlgebraicClosure K) ≠ 0 := by
    intro hy0
    rw [hy0, zero_pow hn.ne'] at hy'
    exact hb0 hy'.symm
  simpa only [div_mul_cancel₀ x hy0] using E.mul_mem (hμ _ hμxy) y.property

/-- A finitely generated group of radicands gives a finite extension, without a
roots-of-unity assumption. The finite binomial splitting fields give the finiteness
step of Milne, *Fields and Galois Theory*, version 5.10 (2022), Theorem 5.30. -/
theorem kummerExtension_finiteDimensional (hn : 0 < n) (hB : B.FG) :
    FiniteDimensional K (kummerExtension K n B) := by
  classical
  obtain ⟨s, hs⟩ := hB
  let S : Set (AlgebraicClosure K) :=
    (Polynomial.X ^ n - Polynomial.C (1 : K)).rootSet (AlgebraicClosure K) ∪
      ⋃ b : (s : Set Kˣ),
        (Polynomial.X ^ n - Polynomial.C (b.val : K)).rootSet (AlgebraicClosure K)
  have hS : S.Finite := (Polynomial.rootSet_finite _ _).union
    (Set.finite_iUnion fun b : (s : Set Kˣ) ↦ Polynomial.rootSet_finite _ _)
  let E := IntermediateField.adjoin K S
  have : Finite S := hS.to_subtype
  have : FiniteDimensional K E := IntermediateField.finiteDimensional_adjoin
    fun x _ ↦ Algebra.IsIntegral.isIntegral x
  have hμ : ∀ z : AlgebraicClosure K, z ^ n = 1 → z ∈ E := by
    intro z hz
    apply IntermediateField.subset_adjoin K S
    left
    rw [Polynomial.mem_rootSet_of_ne (Polynomial.X_pow_sub_C_ne_zero hn 1)]
    simp [hz]
  have hB : B ≤ kummerRadicands K n E := by
    rw [← hs, Subgroup.closure_le]
    intro b hb
    obtain ⟨x, hx⟩ := IsAlgClosed.exists_pow_nat_eq
      (algebraMap K (AlgebraicClosure K) (b : K)) hn
    have hxE : x ∈ E := by
      apply IntermediateField.subset_adjoin K S
      right
      apply Set.mem_iUnion.mpr ⟨⟨b, hb⟩, ?_⟩
      rw [Polynomial.mem_rootSet_of_ne (Polynomial.X_pow_sub_C_ne_zero hn _)]
      simp [hx]
    exact ⟨⟨x, hxE⟩, Subtype.ext hx⟩
  have hLE : kummerExtension K n B ≤ E :=
    (kummerExtension_le_iff E).2 fun b _ hx ↦ root_mem_of_root hn E hμ (hB b.property) hx
  exact FiniteDimensional.of_injective (IntermediateField.inclusion hLE).toLinearMap
    (IntermediateField.inclusion hLE).injective

/-! ### Normality

If `F/K` is normal and the radicands are stable under $\operatorname{Gal}(F/K)$, every
`K`-embedding of the radical field into the algebraic closure restricts to an automorphism of `F`
and sends an nth root of `d` to an nth root of $\sigma d$. This works for every `n`; over `K`
itself, each radicand is fixed by the Galois action. -/

/-- Radicals of Galois-stable radicands over a normal extension `F/K` generate a normal
extension of `K`: if $\sigma D = D$ for every $\sigma\in\operatorname{Gal}(F/K)$, then
$F[D^{1/n}]/K$ is normal. Used by `exists_intermediateField_range_norm_eq` to make the Kummer
field over $K(\zeta_n)$ Galois over `K`. -/
theorem kummerExtension_normal_of_smul_mem {F : Type*} [Field F] [Algebra K F] [Normal K F]
    {D : Subgroup Fˣ} (hD : ∀ σ : F ≃ₐ[K] F, ∀ d ∈ D, σ • d ∈ D) :
    Normal K (kummerExtension F n D) := by
  change Normal K ((kummerExtension F n D).restrictScalars K)
  apply (IntermediateField.normal_iff_forall_map_le).2
  intro φ
  rw [IntermediateField.map_le_iff_le_comap]
  intro x hx
  change φ x ∈ (kummerExtension F n D).restrictScalars K
  rw [IntermediateField.mem_restrictScalars]
  rw [IntermediateField.mem_restrictScalars] at hx
  change x ∈ IntermediateField.adjoin F _ at hx
  induction hx using IntermediateField.adjoin_induction with
  | mem x hx =>
      obtain ⟨d, hd⟩ := hx
      let σ := φ.restrictNormal' F
      have hσd : ((σ • d.val : Fˣ) : F) = σ (d.val : F) := by rfl
      have hroot : (φ x) ^ n = algebraMap F (AlgebraicClosure F) ((σ • d.val : Fˣ) : F) := by
        rw [← map_pow, hd, hσd]
        exact (φ.restrictNormal_commutes F (d.val : F)).symm
      exact root_mem_kummerExtension ⟨σ • d.val, hD σ d.val d.property⟩ hroot
  | algebraMap x =>
      have h := φ.restrictNormal_commutes F x
      rw [← h]
      exact IntermediateField.algebraMap_mem _ _
  | add x y hx hy ihx ihy =>
      simpa only [map_add] using IntermediateField.add_mem _ ihx ihy
  | inv x hx ihx =>
      simpa only [map_inv₀] using IntermediateField.inv_mem _ ihx
  | mul x y hx hy ihx ihy =>
      simpa only [map_mul] using IntermediateField.mul_mem _ ihx ihy

/-- The extension generated by all nth roots of $B$ is normal for every `n`.
This is `kummerExtension_normal_of_smul_mem` with `F = K`. -/
theorem kummerExtension_normal : Normal K (kummerExtension K n B) := by
  apply kummerExtension_normal_of_smul_mem (K := K) (F := K)
  intro σ d hd
  have hs : σ • d = d := Units.ext (σ.commutes (d : K))
  simpa only [hs] using hd

/-! ### Galois action

A primitive nth root of unity makes the binomials separable. Each automorphism scales
each radical by a base-field root of unity, which proves commutativity and exponent dividing n. -/

/-- The radical extension is Galois if $K$ contains a primitive nth root of unity.
Milne, *Fields and Galois Theory*, version 5.10 (2022), compositum step of Theorem 5.30. -/
theorem kummerExtension_isGalois {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 0 < n) :
    IsGalois K (kummerExtension K n B) := by
  have : NeZero n := ⟨hn.ne'⟩
  have := hζ.neZero'
  have : Algebra.IsSeparable K (kummerExtension K n B) := by
    apply (IntermediateField.isSeparable_adjoin_iff_isSeparable K _).2
    rintro x ⟨b, hx⟩
    apply (Polynomial.separable_X_pow_sub_C (b.val : K) (NeZero.ne (n : K))
      b.val.ne_zero).of_dvd
    exact minpoly.dvd K x (by simp [hx])
  have := kummerExtension_normal (n := n) (B := B)
  exact ⟨⟩

/-- An automorphism scales a radical by a base-field nth root of unity; used in the
abelian and exponent assertions for `kummerExtension`. -/
private theorem automorphism_root_image {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (hn : 0 < n) {b : K} {x : L} (hx : x ^ n = algebraMap K L b) (σ : Gal(L/K)) :
    ∃ i : ℕ, i < n ∧ σ x = algebraMap K L (ζ ^ i) * x := by
  apply exists_base_mul_of_pow_eq hζ hn
  rw [← map_pow, hx, σ.commutes]

/-- The automorphisms of $K[B^{1/n}]$ commute when $\mu_n\subset K$.
Milne, *Fields and Galois Theory*, version 5.10 (2022), compositum step of Theorem 5.30. -/
theorem kummerExtension_aut_comm {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 0 < n)
    (σ τ : Gal((kummerExtension K n B)/K)) : σ * τ = τ * σ := by
  apply AlgEquiv.coe_toAlgHom_injective
  apply kummerExtension_algHom_ext
  intro b y hy
  obtain ⟨i, _, hi⟩ := automorphism_root_image hζ hn hy σ
  obtain ⟨j, _, hj⟩ := automorphism_root_image hζ hn hy τ
  change σ (τ y) = τ (σ y)
  simp only [hi, hj, map_mul, AlgEquiv.commutes]
  ring

/-- The extension $K[B^{1/n}]/K$ is abelian Galois when $\mu_n\subset K$.
Milne, *Fields and Galois Theory*, version 5.10 (2022), compositum step of Theorem 5.30. -/
theorem kummerExtension_isAbelianGalois {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 0 < n) :
    IsAbelianGalois K (kummerExtension K n B) := by
  have := kummerExtension_isGalois (B := B) hζ hn
  have : IsMulCommutative Gal((kummerExtension K n B)/K) :=
    .of_comm (kummerExtension_aut_comm hζ hn)
  exact ⟨⟩

/-- Every automorphism of $K[B^{1/n}]/K$ satisfies $\sigma^n=1$.
Milne, *Fields and Galois Theory*, version 5.10 (2022), exponent step of Theorem 5.30. -/
theorem kummerExtension_aut_pow {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : 0 < n)
    (σ : Gal((kummerExtension K n B)/K)) : σ ^ n = 1 := by
  apply AlgEquiv.coe_toAlgHom_injective
  apply kummerExtension_algHom_ext
  intro b y hy
  obtain ⟨i, _, hi⟩ := automorphism_root_image hζ hn hy σ
  have hpow (m : ℕ) : (σ ^ m) y = algebraMap K _ ((ζ ^ i) ^ m) * y := by
    induction m with
    | zero => simp
    | succ m hm =>
      simp only [pow_succ, AlgEquiv.mul_apply, hi, map_mul, AlgEquiv.commutes, hm]
      ring
  change (σ ^ n) y = y
  rw [hpow, ← pow_mul, Nat.mul_comm, pow_mul, hζ.pow_eq_one]
  simp

end SIC
