/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.IndependentResidues
import SICs.ClassField.Reciprocity.Cyclotomic

/-!
# Artin's auxiliary fields

Inside an abelian extension $\Omega$ containing `L` and $\zeta_M$, whose restriction and
cyclotomic character map surjectively to
$\operatorname{Gal}(L/K)\times(\mathbb Z/M\mathbb Z)^\times$, auxiliary fields $E_{\mathfrak p}$
for a finite set of primes. Every prime of $E_{\mathfrak p}$ above $\mathfrak p$ has residue
degree one, $L\subseteq E_{\mathfrak p}(\zeta_M)$, and one automorphism fixes all these fields
while restricting to a prescribed element of $\operatorname{Gal}(L/K)$.

This module follows Childress, *Class Field Theory* (2009), Chapter V, Lemma 2.8 (Artin's
lemma) and its simultaneous use in the proof of Proposition 2.2, pp. 118–122. Its consumer is
`SICs.ClassField.Reciprocity.Cyclic`, which proves Childress's Proposition 2.2 from it.

Childress applies Lemma 2.8 to each prime $\mathfrak p_i$ with its own modulus $m_i$, chooses
the $m_i$ pairwise coprime, and then works in $K(\zeta_{m_1},\dots,\zeta_{m_r})$. Here a single
modulus `M` with a single residue `t` serves every prime at once
(`exists_isIndependentResidue_of_finset`), and the fields are cut out directly in
$\Omega = L(\zeta_M)$. The four clauses of Lemma 2.8 appear in the forms their consumer uses:
(i) and the simultaneous intersection $L\cap E_1\cdots E_r = K$ become the existence of one
automorphism `g` fixing every $E_{\mathfrak p}$ and restricting to a prescribed `σ`, from which
the consumer obtains a common norm with Artin symbol `σ`; (ii) becomes
$L\subseteq E_{\mathfrak p}(\zeta_M)$; (iv) becomes residue degree one at every prime of
$E_{\mathfrak p}$ above $\mathfrak p$. Clause (iii), $L\cap K(\zeta_m)=K$, is represented by the
surjectivity hypothesis on $\operatorname{Gal}(\Omega/K)$. This formalizes exactly the residue
degree clause used by the consumer. When $\mathfrak p$ is unramified in $\Omega$, residue degree
one also gives complete splitting, as in Childress's application. The printed Lemma 2.8 omits
unramifiedness, although its argument that Frobenius generates the decomposition group uses it;
the application supplies it.

## The argument

Let $G = \operatorname{Gal}(L/K)$, $n = [L:K]$, and $\chi$ the cyclotomic character
(`IsPrimitiveRoot.autToPow`). By hypothesis some $g\in\operatorname{Gal}(\Omega/K)$ has
$g|_L = \sigma$ and $\chi(g) = t$. For $\mathfrak p\in T$ prime to `M`, let
$\varphi_{\mathfrak p}$ be the chosen Frobenius lift of $\Omega/K$. It has
$\chi(\varphi_{\mathfrak p}) = N\mathfrak p$ (`autToPow_frobeniusAt`), and
$\varphi_{\mathfrak p}|_L$ is an automorphism of `L/K` whose `n`th power is one.
Let $E_{\mathfrak p}$ be the fixed field of the subgroup $H_{\mathfrak p}$ generated by `g` and
$\varphi_{\mathfrak p}$. Under restriction and the cyclotomic character, these generators map to
$(\sigma,t)$ and $(\varphi_{\mathfrak p}|_L,N\mathfrak p)$, matching Childress's generators in
his unramified application.

*The common automorphism.* `g` lies in every $H_{\mathfrak p}$, so it fixes every
$E_{\mathfrak p}$.

*Splitting.* $\varphi_{\mathfrak p}$ fixes $E_{\mathfrak p}$, so every prime of
$E_{\mathfrak p}$ above $\mathfrak p$ has residue degree one
(`IsFrobeniusAt.inertiaDeg_eq_one_of_mem_fixingSubgroup`); Childress argues through the
decomposition field.

*$L\subseteq E_{\mathfrak p}(\zeta_M)$.* By Galois theory it suffices that every
$h\in H_{\mathfrak p}$ fixing $\zeta_M$ fixes `L`. As $\operatorname{Gal}(\Omega/K)$ is abelian,
$h = g^i\varphi_{\mathfrak p}^j$, and $\chi(h) = 1$ gives $t^i(N\mathfrak p)^j = 1$, so `n ∣ i`
and `n ∣ j` by the independence hypothesis. Since `n` kills `G`,
$h|_L = \sigma^i(\varphi_{\mathfrak p}|_L)^j = 1$.
-/

noncomputable section

open IsDedekindDomain NumberField
open scoped IsMulCommutative

namespace SIC

/-- Fixing the primitive root makes the cyclotomic character trivial; used by
`exists_auxiliaryFields`. -/
private theorem autToPow_eq_one_of_fix {K Ω : Type*} [Field K] [Field Ω] [Algebra K Ω]
    {M : ℕ} [NeZero M] {ζ : Ω}
    (hζ : IsPrimitiveRoot ζ M) (h : Ω ≃ₐ[K] Ω) (hfix : h ζ = ζ) :
    hζ.autToPow K h = 1 := by
  apply Units.ext
  apply ZMod.val_injective M
  apply hζ.pow_inj (ZMod.val_lt _) (ZMod.val_lt _)
  calc
    ζ ^ (hζ.autToPow K h : ZMod M).val = h ζ := hζ.autToPow_spec K h
    _ = ζ := hfix
    _ = ζ ^ ((1 : (ZMod M)ˣ) : ZMod M).val := by
      simpa only [map_one, AlgEquiv.one_apply] using
        (hζ.autToPow_spec K (1 : Ω ≃ₐ[K] Ω)).symm

variable {K L Ω : Type*} [Field K] [NumberField K] [Field L] [NumberField L] [Algebra K L]
  [Field Ω] [NumberField Ω] [Algebra K Ω] [Algebra L Ω] [IsScalarTower K L Ω]

/-- A multiple of the degree kills an automorphism of a finite Galois extension; used by
`exists_auxiliaryFields`. -/
private theorem aut_zpow_eq_one_of_finrank_dvd [IsGalois K L]
    (a : L ≃ₐ[K] L) (i : ℤ) (hi : (Module.finrank K L : ℤ) ∣ i) : a ^ i = 1 := by
  rcases hi with ⟨m, rfl⟩
  rw [zpow_mul, zpow_natCast]
  have hcard : a ^ Module.finrank K L = 1 := by
    rw [← IsGalois.card_aut_eq_finrank K L]
    exact pow_card_eq_one'
  simp [hcard]

/-- In the two-generator subgroup defining an auxiliary field, an automorphism fixing `ζ`
restricts trivially to `L`; used by `exists_auxiliaryFields`. -/
private theorem auxiliary_group_fixes_L [IsGalois K L] [IsAbelianGalois K Ω]
    {M : ℕ} [NeZero M] {ζ : Ω} (hζ : IsPrimitiveRoot ζ M)
    (g : Ω ≃ₐ[K] Ω) (t : (ZMod M)ˣ) (hgχ : hζ.autToPow K g = t)
    (p : HeightOneSpectrum (𝓞 K))
    (hM : (M : 𝓞 K) ∉ p.asIdeal)
    (hind : IsIndependentResidue (Module.finrank K L) (Ideal.absNorm p.asIdeal) t)
    (h : Ω ≃ₐ[K] Ω) (hH : h ∈ Subgroup.closure {g, frobeniusAt Ω p})
    (hζfix : h ζ = ζ) : h.restrictNormal L = 1 := by
  have hχ : hζ.autToPow K h = 1 := autToPow_eq_one_of_fix hζ h hζfix
  obtain ⟨i, j, hij⟩ := (Subgroup.mem_closure_pair.mp hH)
  let φ := frobeniusAt Ω p
  have hχφ : ((hζ.autToPow K φ : (ZMod M)ˣ) : ZMod M) =
      Ideal.absNorm p.asIdeal := autToPow_frobeniusAt hζ p hM
  have hprod : t ^ i * (hζ.autToPow K φ) ^ j = 1 := by
    have hmap := congrArg (hζ.autToPow K) hij
    simpa only [map_mul, map_zpow, hgχ, hχ] using hmap
  have hind' : (Module.finrank K L : ℤ) ∣ j ∧
      (Module.finrank K L : ℤ) ∣ i :=
    hind (hζ.autToPow K φ) hχφ j i (by simpa only [mul_comm] using hprod)
  change (AlgEquiv.restrictNormalHom L) h = 1
  rw [← hij, map_mul, map_zpow, map_zpow]
  change (g.restrictNormal L) ^ i * (φ.restrictNormal L) ^ j = 1
  rw [aut_zpow_eq_one_of_finrank_dvd _ _ hind'.2,
    aut_zpow_eq_one_of_finrank_dvd _ _ hind'.1, one_mul]

/-- The fixed field of the two-generator subgroup becomes an overfield of `L` after adjoining
`ζ`; used by `exists_auxiliaryFields`. -/
private theorem auxiliary_fixedField_contains_L [IsGalois K L] [IsAbelianGalois K Ω]
    {M : ℕ} [NeZero M] {ζ : Ω} (hζ : IsPrimitiveRoot ζ M)
    (g : Ω ≃ₐ[K] Ω) (t : (ZMod M)ˣ) (hgχ : hζ.autToPow K g = t)
    (p : HeightOneSpectrum (𝓞 K))
    (hM : (M : 𝓞 K) ∉ p.asIdeal)
    (hind : IsIndependentResidue (Module.finrank K L) (Ideal.absNorm p.asIdeal) t) :
    (IsScalarTower.toAlgHom K L Ω).fieldRange ≤
      IntermediateField.fixedField (Subgroup.closure {g, frobeniusAt Ω p}) ⊔
        IntermediateField.adjoin K {ζ} := by
  let H := Subgroup.closure {g, frobeniusAt Ω p}
  let E := IntermediateField.fixedField H
  let F := (IsScalarTower.toAlgHom K L Ω).fieldRange
  have hsub : (E ⊔ IntermediateField.adjoin K {ζ}).fixingSubgroup ≤
      F.fixingSubgroup := by
    rw [IntermediateField.fixingSubgroup_sup]
    intro h hh
    have hH : h ∈ H := by
      have hhE : h ∈ (IntermediateField.fixedField H).fixingSubgroup := hh.1
      rw [IntermediateField.fixingSubgroup_fixedField] at hhE
      exact hhE
    have hζfix : h ζ = ζ :=
      (IntermediateField.mem_fixingSubgroup_iff _ h).mp hh.2 ζ
        (IntermediateField.subset_adjoin K {ζ} (by simp))
    have hres := auxiliary_group_fixes_L hζ g t hgχ p hM hind h hH hζfix
    rw [← AlgEquiv.ker_restrictNormalHom L]
    exact (MonoidHom.mem_ker).mpr hres
  have hle := (IntermediateField.le_iff_le
    (E ⊔ IntermediateField.adjoin K {ζ}).fixingSubgroup F).mpr hsub
  simpa only [IsGalois.fixedField_fixingSubgroup] using hle

/-- **Artin's auxiliary fields**: let $\Omega\supseteq L\supseteq K$ with `L/K` Galois of
degree `n`, $\Omega/K$ abelian, and $\zeta\in\Omega$ a primitive `M`th root of unity such that
every pair in $\operatorname{Gal}(L/K)\times(\mathbb Z/M\mathbb Z)^\times$ is
$(g|_L,\chi(g))$ for some $g\in\operatorname{Gal}(\Omega/K)$. Let `T` be a finite set of primes of
`K` prime to `M`, and `t` a unit modulo `M` such that
$(N\mathfrak p)^it^j = 1$ forces $n\mid i$ and $n\mid j$ for every $\mathfrak p\in T$. Then for
every $\sigma\in\operatorname{Gal}(L/K)$ there are intermediate fields $E_{\mathfrak p}$ and
$g\in\operatorname{Gal}(\Omega/K)$ with $g|_L = \sigma$, `g` fixing every $E_{\mathfrak p}$,
$L\subseteq E_{\mathfrak p}(\zeta)$, and residue degree one at every prime of
$E_{\mathfrak p}$ above $\mathfrak p$. When $\mathfrak p$ is unramified in $\Omega$ this also
gives complete splitting, as in the source application.
Childress, *Class Field Theory*, Chapter V, Lemma 2.8, with the simultaneous intersection of the
proof of Proposition 2.2, in the form described in the module docstring. -/
theorem exists_auxiliaryFields [IsGalois K L] [IsAbelianGalois K Ω] {M : ℕ} [NeZero M]
    {ζ : Ω} (hζ : IsPrimitiveRoot ζ M)
    (hsurj : Function.Surjective fun g : Ω ≃ₐ[K] Ω ↦ (g.restrictNormal L, hζ.autToPow K g))
    (T : Finset (HeightOneSpectrum (𝓞 K)))
    (hM : ∀ p ∈ T, (M : 𝓞 K) ∉ p.asIdeal) (t : (ZMod M)ˣ)
    (hind : ∀ p ∈ T, IsIndependentResidue (Module.finrank K L) (Ideal.absNorm p.asIdeal) t)
    (σ : L ≃ₐ[K] L) :
    ∃ (E : HeightOneSpectrum (𝓞 K) → IntermediateField K Ω) (g : Ω ≃ₐ[K] Ω),
      g.restrictNormal L = σ ∧ (∀ p ∈ T, g ∈ (E p).fixingSubgroup) ∧
      (∀ p ∈ T, (IsScalarTower.toAlgHom K L Ω).fieldRange ≤
        E p ⊔ IntermediateField.adjoin K {ζ}) ∧
      ∀ p ∈ T, ∀ P : HeightOneSpectrum (𝓞 (E p)), P.asIdeal.LiesOver p.asIdeal →
        P.asIdeal.inertiaDeg (𝓞 K) = 1 := by
  obtain ⟨g, hg⟩ := hsurj (σ, t)
  have hgL : g.restrictNormal L = σ := congrArg Prod.fst hg
  have hgχ : hζ.autToPow K g = t := congrArg Prod.snd hg
  let H (p : HeightOneSpectrum (𝓞 K)) : Subgroup (Ω ≃ₐ[K] Ω) :=
    Subgroup.closure {g, frobeniusAt Ω p}
  let E (p : HeightOneSpectrum (𝓞 K)) : IntermediateField K Ω :=
    IntermediateField.fixedField (H p)
  refine ⟨E, g, hgL, ?_, ?_, ?_⟩
  · intro p hp
    change g ∈ (IntermediateField.fixedField (H p)).fixingSubgroup
    rw [IntermediateField.fixingSubgroup_fixedField]
    exact Subgroup.subset_closure (by simp)
  · intro p hp
    exact auxiliary_fixedField_contains_L hζ g t hgχ p (hM p hp) (hind p hp)
  · intro p hp P hP
    let φ := frobeniusAt Ω p
    have hφE : φ ∈ (E p).fixingSubgroup := by
      change φ ∈ (IntermediateField.fixedField (H p)).fixingSubgroup
      rw [IntermediateField.fixingSubgroup_fixedField]
      exact Subgroup.subset_closure (by simp [φ])
    let Q := FinitePlace.PrimeAbove.place (L := Ω) P (Classical.arbitrary _)
    have : P.asIdeal.LiesOver p.asIdeal := hP
    have : Q.asIdeal.LiesOver p.asIdeal :=
      Ideal.LiesOver.trans Q.asIdeal P.asIdeal p.asIdeal
    have hsplit := (isFrobeniusAt_frobeniusAt p Q.asIdeal).inertiaDeg_eq_one_of_mem_fixingSubgroup
      (E p) hφE
    simpa only [← Ideal.LiesOver.over (P := Q.asIdeal) (p := P.asIdeal)] using hsplit

end SIC
