/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.ClassField.Ideles.IdealMap
import SICs.ClassField.Ideles.Norm
import Mathlib.RingTheory.Ideal.Norm.RelNorm
import Mathlib.NumberTheory.NumberField.ClassNumber

/-!
# Relative norms of fractional ideals

The relative norm of nonzero fractional ideals, computed through the idèle norm, with its
idèle compatibility and its principal, tower, integral-ideal, and prime formulas, and its
preservation of ideals prime to a finite set.

For a finite extension of number fields `L/K`, the relative norm
$N_{L/K} : I_L \to I_K$ is the homomorphism of groups of nonzero fractional ideals with
$N_{L/K}(\mathfrak P) = \mathfrak p^{f(\mathfrak P/\mathfrak p)}$ for every prime
$\mathfrak P$ of `L` above $\mathfrak p$, and $N_{L/K}((\alpha)) = (N_{L/K}\alpha)$; this is
the norm map on ideals in Milne, *Class Field Theory*, version 4.03 (2020), Chapter V, §3,
before Proposition 3.3. It is the norm of the consistency property of the Artin map in
Childress, *Class Field Theory* (2009), Chapter V, Proposition 1.1.

## The argument

Define $N_{L/K}J$ as the fractional ideal of the idèle norm of the uniformizer idèle of `J`.
Local norms carry integral units to integral units, so the idèle norm preserves the kernel of
the fractional-ideal map. Hence the fractional ideal of $N_{L/K}x$ depends only on the
fractional ideal of the idèle `x`; this is the compatibility with idèle norms. Applied to a
principal idèle it gives $N_{L/K}((\alpha)) = (N_{L/K}\alpha)$, and transitivity of idèle
norms gives the tower law.

For a nonzero integral ideal `I`, the class number `h` makes $I^h = (a)$ principal with `a`
integral. Then $N_{L/K}(I)^h = (N_{L/K}a)$ is Mathlib's relative norm of $I^h$, which is the
`h`th power of Mathlib's relative norm of `I`. The group of fractional ideals is torsion-free,
so $N_{L/K}(I)$ is Mathlib's `Ideal.relNorm` of `I`, and Mathlib's prime formula
`Ideal.relNorm_eq_pow_of_isMaximal` gives $N_{L/K}(\mathfrak P) = \mathfrak p^f$.
Hence the norm of an ideal prime to the primes above `S` is prime to `S`: such an ideal is
generated by primes outside them, whose norms are powers of primes outside `S`. Applied to the
idèle supported at one prime `w`, whose norm is supported at the prime `v` below it, the prime
formula is the valuation formula $\operatorname{ord}_v(N_{L_w/K_v}x)=f\operatorname{ord}_w(x)$.
-/

noncomputable section

open IsDedekindDomain NumberField
open scoped nonZeroDivisors

namespace SIC

variable {K L : Type*} [Field K] [Field L] [NumberField K] [NumberField L] [Algebra K L]

/-! ### The norm through idèles -/

namespace FractionalIdeal

variable (K) in
/-- The relative norm $N_{L/K}$ of nonzero fractional ideals: the fractional ideal of the idèle
norm of the uniformizer idèle. Milne, *Class Field Theory*, Chapter V, §3, before
Proposition 3.3. -/
def relNorm : (FractionalIdeal (𝓞 L)⁰ L)ˣ →* (FractionalIdeal (𝓞 K)⁰ K)ˣ :=
  IdeleGroup.toFractionalIdeal.comp
    ((IdeleGroup.norm (K := K) (L := L)).comp IdeleGroup.ofFractionalIdeal)

end FractionalIdeal

/-- The idèle norm preserves the kernel of the fractional-ideal map; used by
`IdeleGroup.toFractionalIdeal_norm`. -/
private theorem IdeleGroup.toFractionalIdeal_norm_eq_one
    (u : NumberField.IdeleGroup (𝓞 L) L)
    (hu : IdeleGroup.toFractionalIdeal u = 1) :
    IdeleGroup.toFractionalIdeal (IdeleGroup.norm (K := K) (L := L) u) = 1 := by
  apply (IdeleGroup.toFractionalIdeal_eq_one_iff _).2
  intro v
  apply (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers.mem_units_iff_valued_eq_one).mp
  rw [IdeleGroup.finiteComponent_norm_apply]
  apply Subgroup.prod_mem
  intro w _
  apply SIC.FinitePlace.localNorm_mem_integral_units
  exact (IsDedekindDomain.HeightOneSpectrum.adicCompletionIntegers.mem_units_iff_valued_eq_one).mpr
    ((IdeleGroup.toFractionalIdeal_eq_one_iff u).mp hu _)

/-- The fractional ideal of the idèle norm is the relative norm of the fractional ideal:
$(N_{L/K}x) = N_{L/K}((x))$. Milne, *Class Field Theory*, Chapter V, §4, "Norms of idèles",
the square relating the idèle norm to the ideal norm. -/
theorem IdeleGroup.toFractionalIdeal_norm (x : NumberField.IdeleGroup (𝓞 L) L) :
    IdeleGroup.toFractionalIdeal (IdeleGroup.norm (K := K) (L := L) x) =
      FractionalIdeal.relNorm K (IdeleGroup.toFractionalIdeal x) := by
  let J := IdeleGroup.toFractionalIdeal x
  let u := (IdeleGroup.ofFractionalIdeal J)⁻¹ * x
  have hu : IdeleGroup.toFractionalIdeal u = 1 := by
    simp [u, J]
  have hx : IdeleGroup.ofFractionalIdeal J * u = x := by simp [u]
  change IdeleGroup.toFractionalIdeal (IdeleGroup.norm (K := K) (L := L) x) =
    FractionalIdeal.relNorm K J
  rw [← hx, map_mul, map_mul, IdeleGroup.toFractionalIdeal_norm_eq_one u hu, mul_one]
  rfl

namespace FractionalIdeal

/-- The relative norm of a principal fractional ideal is generated by the norm of its
generator: $N_{L/K}((\alpha)) = (N_{L/K}\alpha)$. Milne, *Class Field Theory*, Chapter V, §3,
before Proposition 3.3. -/
theorem relNorm_toPrincipalIdeal (a : Lˣ) :
    relNorm K (toPrincipalIdeal (𝓞 L) L a) =
      toPrincipalIdeal (𝓞 K) K (Units.map (Algebra.norm K : L →* K) a) := by
  calc
    _ = relNorm K (IdeleGroup.toFractionalIdeal
        (NumberField.IdeleGroup.unitEmbedding (𝓞 L) L a)) := by
          rw [IdeleGroup.toFractionalIdeal_unitEmbedding]
    _ = IdeleGroup.toFractionalIdeal (IdeleGroup.norm (K := K) (L := L)
        (NumberField.IdeleGroup.unitEmbedding (𝓞 L) L a)) :=
          (IdeleGroup.toFractionalIdeal_norm _).symm
    _ = IdeleGroup.toFractionalIdeal
        (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K
          (Units.map (Algebra.norm K : L →* K) a)) := by
            rw [IdeleGroup.norm_unitEmbedding]
    _ = _ := IdeleGroup.toFractionalIdeal_unitEmbedding _

/-! ### Towers -/

variable {M : Type*} [Field M] [NumberField M] [Algebra L M] [Algebra K M]
  [IsScalarTower K L M]

/-- The relative norm is transitive in towers: $N_{L/K} \circ N_{M/L} = N_{M/K}$. -/
theorem relNorm_relNorm (J : (FractionalIdeal (𝓞 M)⁰ M)ˣ) :
    relNorm K (relNorm L J) = relNorm K J := by
  let x := IdeleGroup.ofFractionalIdeal J
  change relNorm K (IdeleGroup.toFractionalIdeal
    (IdeleGroup.norm (K := L) (L := M) x)) = relNorm K J
  rw [← IdeleGroup.toFractionalIdeal_norm,
    IdeleGroup.norm_norm (K := K) (L := L) (M := M) x]
  rfl

/-! ### Integral ideals and primes -/

/-- The class-number powers of the idèlic ideal norm and Mathlib's ideal norm agree;
used by `coe_relNorm_coeIdeal`. -/
private theorem relNorm_coeIdeal_pow_eq (I : Ideal (𝓞 L)) (hI : I ≠ ⊥)
    (a : 𝓞 L) (ha0 : a ≠ 0)
    (ha : I ^ NumberField.classNumber L = Ideal.span {a}) :
    ((relNorm K (Units.mk0 (I : FractionalIdeal (𝓞 L)⁰ L)
        (FractionalIdeal.coeIdeal_ne_zero.mpr hI)) : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
      FractionalIdeal (𝓞 K)⁰ K) ^ NumberField.classNumber L =
      (Ideal.relNorm (𝓞 K) I : FractionalIdeal (𝓞 K)⁰ K) ^ NumberField.classNumber L := by
  let h := NumberField.classNumber L
  let J : (FractionalIdeal (𝓞 L)⁰ L)ˣ :=
    Units.mk0 (I : FractionalIdeal (𝓞 L)⁰ L) (FractionalIdeal.coeIdeal_ne_zero.mpr hI)
  have haL : (a : L) ≠ 0 := NumberField.RingOfIntegers.coe_eq_zero_iff.not.mpr ha0
  let ua : Lˣ := Units.mk0 (a : L) haL
  have hprincipal : J ^ h = toPrincipalIdeal (𝓞 L) L ua := by
    apply Units.ext
    rw [Units.val_pow_eq_pow_val, coe_toPrincipalIdeal]
    change (I : FractionalIdeal (𝓞 L)⁰ L) ^ h =
      FractionalIdeal.spanSingleton (𝓞 L)⁰ (a : L)
    rw [← FractionalIdeal.coeIdeal_pow, ha, FractionalIdeal.coeIdeal_span_singleton]
  calc
    _ = ((relNorm K (J ^ h) : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
        FractionalIdeal (𝓞 K)⁰ K) := by rw [map_pow, Units.val_pow_eq_pow_val]
    _ = (toPrincipalIdeal (𝓞 K) K (Units.map (Algebra.norm K : L →* K) ua) :
        FractionalIdeal (𝓞 K)⁰ K) := by rw [hprincipal, relNorm_toPrincipalIdeal]
    _ = (Ideal.relNorm (𝓞 K) (I ^ h) : FractionalIdeal (𝓞 K)⁰ K) := by
      rw [ha]
      simp only [coe_toPrincipalIdeal, Units.coe_map, Ideal.relNorm_singleton,
        FractionalIdeal.coeIdeal_span_singleton]
      change FractionalIdeal.spanSingleton (𝓞 K)⁰ (Algebra.norm K (a : L)) =
        FractionalIdeal.spanSingleton (𝓞 K)⁰
          (algebraMap (𝓞 K) K (Algebra.intNorm (𝓞 K) (𝓞 L) a))
      rw [Algebra.algebraMap_intNorm (A := 𝓞 K) (K := K) (L := L) (B := 𝓞 L)]
    _ = (Ideal.relNorm (𝓞 K) I : FractionalIdeal (𝓞 K)⁰ K) ^ h := by
      rw [map_pow, FractionalIdeal.coeIdeal_pow]

/-- On a nonzero integral ideal the relative norm is Mathlib's `Ideal.relNorm`. -/
theorem coe_relNorm_coeIdeal (I : Ideal (𝓞 L)) (hI : I ≠ ⊥) :
    ((relNorm K (Units.mk0 (I : FractionalIdeal (𝓞 L)⁰ L)
        (FractionalIdeal.coeIdeal_ne_zero.mpr hI)) : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
      FractionalIdeal (𝓞 K)⁰ K) = (Ideal.relNorm (𝓞 K) I : FractionalIdeal (𝓞 K)⁰ K) := by
  let h := NumberField.classNumber L
  have hh : h ≠ 0 := NumberField.classNumber_ne_zero L
  obtain ⟨a, ha0, ha⟩ : ∃ a : 𝓞 L, a ≠ 0 ∧
      I ^ NumberField.classNumber L = Ideal.span {a} := by
    simpa only [NumberField.classNumber, Nat.card_eq_fintype_card] using
      (Ideal.exists_classGroupCard_power_generator L I hI)
  have hpow := relNorm_coeIdeal_pow_eq (K := K) I hI a ha0 ha
  have hnorm_ne : (Ideal.relNorm (𝓞 K) I : FractionalIdeal (𝓞 K)⁰ K) ≠ 0 :=
    FractionalIdeal.coeIdeal_ne_zero.mpr
      ((Ideal.relNorm_eq_bot_iff).not.mpr hI)
  exact FractionalIdeal.pow_injective_of_ne_zero h hh
    (relNorm K (Units.mk0 (I : FractionalIdeal (𝓞 L)⁰ L)
      (FractionalIdeal.coeIdeal_ne_zero.mpr hI))).ne_zero hnorm_ne hpow

/-- The relative norm of a prime is
$N_{L/K}(\mathfrak P) = \mathfrak p^{f(\mathfrak P/\mathfrak p)}$. Milne, *Class Field
Theory*, Chapter V, §3, before Proposition 3.3. -/
theorem relNorm_primeFractionalIdeal (v : HeightOneSpectrum (𝓞 K))
    (w : HeightOneSpectrum (𝓞 L)) [w.asIdeal.LiesOver v.asIdeal] :
    relNorm K (primeFractionalIdeal L w) =
      primeFractionalIdeal K v ^ w.asIdeal.inertiaDeg (𝓞 K) := by
  have h := coe_relNorm_coeIdeal (K := K) w.asIdeal w.ne_bot
  rw [Ideal.relNorm_eq_pow_of_isMaximal w.asIdeal v.asIdeal] at h
  apply Units.ext
  simpa only [primeFractionalIdeal, Units.val_pow_eq_pow_val, Units.val_mk0,
    FractionalIdeal.coeIdeal_pow] using h

/-- The relative norm of an ideal prime to the primes above `S` is prime to `S`:
$N_{L/K}(I_L^{S_L}) \subseteq I_K^S$. Milne, *Class Field Theory*, Chapter V, §3, before
Proposition 3.3. -/
theorem relNorm_mem_primeTo (S : Finset (HeightOneSpectrum (𝓞 K)))
    {J : (FractionalIdeal (𝓞 L)⁰ L)ˣ}
    (hJ : J ∈ primeTo L (FinitePlace.placesAbove (K := K) (L := L) S)) :
    relNorm K J ∈ primeTo K S := by
  obtain ⟨T, hT, hclosure⟩ := exists_finset_mem_closure J
  have hTaway : ∀ w ∈ T, w ∉ FinitePlace.placesAbove (K := K) (L := L) S := by
    intro w hwT hwS
    exact hT w hwT ((mem_primeTo_iff.mp hJ) w hwS)
  have hsub : (primeFractionalIdeal L '' (T : Set (HeightOneSpectrum (𝓞 L)))) ⊆
      ↑((primeTo K S).comap (relNorm (L := L) K)) := by
    rintro x ⟨w, hwT, rfl⟩
    apply (Subgroup.mem_comap).2
    have hw : FinitePlace.below (K := K) w ∉ S := by
      intro hw
      exact hTaway w hwT ((FinitePlace.mem_placesAbove S w).2 hw)
    rw [relNorm_primeFractionalIdeal (FinitePlace.below (K := K) w) w]
    exact (primeTo K S).pow_mem (primeFractionalIdeal_mem_primeTo (K := K) hw) _
  have hle : Subgroup.closure (primeFractionalIdeal L ''
      (T : Set (HeightOneSpectrum (𝓞 L)))) ≤
      (primeTo K S).comap (relNorm (L := L) K) :=
    (Subgroup.closure_le _).2 hsub
  exact hle hclosure

end FractionalIdeal

/-! ### Valuations of local norms

The prime formula, read at an idèle supported at one place, is the valuation formula
$\operatorname{ord}_v(N_{L_w/K_v}x)=f(w/v)\operatorname{ord}_w(x)$ for local norms. -/

/-- The count of the norm of a one-place idèle, used by `FinitePlace.valued_localNorm`. -/
private theorem FinitePlace.neg_log_valued_localNorm (v : HeightOneSpectrum (𝓞 K))
    (w : HeightOneSpectrum (𝓞 L)) [w.asIdeal.LiesOver v.asIdeal] (x : (w.adicCompletion L)ˣ) :
    -WithZero.log (Valued.v
      ((FinitePlace.localNorm v w x : (v.adicCompletion K)ˣ) : v.adicCompletion K)) =
      -WithZero.log (Valued.v (x : w.adicCompletion L)) *
        (w.asIdeal.inertiaDeg (𝓞 K) : ℤ) := by
  let n := -WithZero.log (Valued.v (x : w.adicCompletion L))
  have hfrac : IdeleGroup.toFractionalIdeal
      (NumberField.IdeleGroup.ofAdicCompletion (𝓞 L) L w x) =
      primeFractionalIdeal L w ^ n := by
    apply Units.ext
    simpa only [n, Units.val_zpow_eq_zpow_val, coe_primeFractionalIdeal] using
      IdeleGroup.coe_toFractionalIdeal_ofAdicCompletion w x
  calc
    _ = FractionalIdeal.count K v
        ((IdeleGroup.toFractionalIdeal
          (IdeleGroup.norm (K := K) (L := L)
            (NumberField.IdeleGroup.ofAdicCompletion (𝓞 L) L w x)) :
              (FractionalIdeal (𝓞 K)⁰ K)ˣ) : FractionalIdeal (𝓞 K)⁰ K) := by
          rw [IdeleGroup.norm_ofAdicCompletion v w x,
            IdeleGroup.count_toFractionalIdeal,
            IdeleGroup.finiteComponent_ofAdicCompletion_self]
    _ = FractionalIdeal.count K v
        (((primeFractionalIdeal K v ^ w.asIdeal.inertiaDeg (𝓞 K)) ^ n :
          (FractionalIdeal (𝓞 K)⁰ K)ˣ) : FractionalIdeal (𝓞 K)⁰ K) := by
          rw [IdeleGroup.toFractionalIdeal_norm, hfrac, map_zpow,
            FractionalIdeal.relNorm_primeFractionalIdeal v w]
    _ = _ := by
          rw [Units.val_zpow_eq_zpow_val, Units.val_pow_eq_pow_val,
            coe_primeFractionalIdeal, FractionalIdeal.count_zpow,
            FractionalIdeal.count_pow_self]

/-- **The valuation of a local norm**: $v(N_{L_w/K_v}x)=w(x)^{f(w/v)}$ for the normalized
valuations, i.e. $\operatorname{ord}_v(N_{L_w/K_v}x)=f(w/v)\operatorname{ord}_w(x)$. Milne,
*Class Field Theory*, Chapter V, §3, before Proposition 3.3, read through the idèle norm. -/
theorem FinitePlace.valued_localNorm (v : HeightOneSpectrum (𝓞 K))
    (w : HeightOneSpectrum (𝓞 L)) [w.asIdeal.LiesOver v.asIdeal] (x : (w.adicCompletion L)ˣ) :
    Valued.v ((FinitePlace.localNorm v w x : (v.adicCompletion K)ˣ) : v.adicCompletion K) =
      Valued.v (x : w.adicCompletion L) ^ w.asIdeal.inertiaDeg (𝓞 K) := by
  have hlog : WithZero.log (Valued.v
      ((FinitePlace.localNorm v w x : (v.adicCompletion K)ˣ) : v.adicCompletion K)) =
      (w.asIdeal.inertiaDeg (𝓞 K) : ℤ) *
        WithZero.log (Valued.v (x : w.adicCompletion L)) := by
    linear_combination -(FinitePlace.neg_log_valued_localNorm v w x)
  have hv : Valued.v
      ((FinitePlace.localNorm v w x : (v.adicCompletion K)ˣ) : v.adicCompletion K) ≠ 0 :=
    (Valuation.ne_zero_iff (Valued.v : Valuation (v.adicCompletion K) _)).2
      (FinitePlace.localNorm v w x).ne_zero
  have hw : Valued.v (x : w.adicCompletion L) ≠ 0 :=
    (Valuation.ne_zero_iff (Valued.v : Valuation (w.adicCompletion L) _)).2 x.ne_zero
  calc
    _ = WithZero.exp (WithZero.log (Valued.v
        ((FinitePlace.localNorm v w x : (v.adicCompletion K)ˣ) : v.adicCompletion K))) :=
          (WithZero.exp_log hv).symm
    _ = WithZero.exp (w.asIdeal.inertiaDeg (𝓞 K) •
        WithZero.log (Valued.v (x : w.adicCompletion L))) := by
          rw [hlog, nsmul_eq_mul]
    _ = _ := by rw [WithZero.exp_nsmul, WithZero.exp_log hw]

end SIC
