/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.ClassField.RayClassField.SignClasses
import SICs.Dilogarithm.Reciprocity.RayField

/-!
# The totally negative sign class acts on the squared values by `x ↦ -x`

In the narrow ray class field `H` of modulus `M𝒪_K`, the Artin symbol of the sign class negative
at both real places sends the squared normalized value at `x` to the squared normalized value at
`-x`.

This module follows [RW26b, Radchenko, Wheeler (2026b), Section 8, proof of Proposition 4] for
the class `s₁s₂` of the two real sign classes, in squared form. A prime in this class has a
totally negative generator `α ≡ 1 (mod M)`, whose two inverse translates by the positive
generators `-α` and `-α'` both have the values of `I` at `-x`. Thus the two split-prime
congruences agree, and no sign argument is needed for this class. It supplies
`SICs.Dilogarithm.Reciprocity.UnitaryConjugates`
with the action of `s₁s₂`, which together with the real-place Artin law
(`globalArtin_signIdeleClass_eq_one_or_isConj`) decides the action of complex conjugation.

## The argument

Let `σ` be the Artin symbol of the sign idèle `(-1, -1)` and `c = σa - b` for the integral
elements `a`, `b` of `H` with `ψ(a) = (E(x)/E(0))²`, `ψ(b) = (E(-x)/E(0))²`
(`pseudolatticeDilog_sq_isIntegral`). Suppose `c ≠ 0`. By
`exists_degreeOne_hasSignedRayGenerator` there is a prime `𝔭` of `K` of prime absolute norm
`p`, outside the finitely many primes dividing `2M disc K` (`exists_rayPrime_exclusion`) and those
below a prime of `H` containing `c`, generated by a totally negative `α ≡ 1 (mod M)`. At a prime
`𝔓` of `H` above `𝔭`, `σ` is the Frobenius element (`isFrobeniusAt_globalArtin_signIdeleClass_iff`),
so `σa ≡ a^p (mod 𝔓)`. At a valuation `v` of `ℂ` above `𝔓` through `ψ`
(`exists_valuation_complex_lt_one_iff`), the split Frobenius congruence for the signed generator
(`pseudolatticeDilog_frobenius_signed` with sign `-1`) gives `u_x^p ≡ u_{-x}`, so
`ψ(a)^p ≡ ψ(b)` (`valuation_pow_sub_pow_lt_one`). Hence `c ∈ 𝔓`, contradicting the choice of `𝔭`.
-/

noncomputable section

open IsDedekindDomain NumberField
open scoped NNReal

namespace SIC

variable {K : Type*} [Field K] [NumberField K] [NumberField.IsTotallyReal K]
variable {F : RealQuadraticFieldData K} {B : PseudolatticeBasis F} {ε : K}

/-! ### Exceptional primes and integral congruences -/

/-- Equality of the integral squared values under the totally negative Artin symbol; the
integral core of `pseudolatticeDilog_artin_signClass`. -/
private theorem pseudolatticeDilog_artin_signClass_integral (h : B.IsPeriod ε)
    {M : ℕ} (hM0 : 0 < M)
    (hM : ∀ a : 𝓞 K, ∀ x : K, (ε - 1) * x ∈ B.submodule →
      (M : K) * (a : K) * x ∈ B.submodule)
    {H : Type*} [Field H] [NumberField H] [Algebra K H] [IsAbelianGalois K H]
    (hU : (IdeleClassGroup.norm (K := K) (L := H)).range =
      IdeleClassGroup.raySubgroup Set.univ (Ideal.span {(M : 𝓞 K)}))
    (ψ : H →+* ℂ) {x : K} (hx : (ε - 1) * x ∈ B.submodule)
    (aO bO : 𝓞 H)
    (ha : ψ (aO : H) = (pseudolatticeDilog h x / pseudolatticeDilog h 0) ^ 2)
    (hb : ψ (bO : H) = (pseudolatticeDilog h (-x) / pseudolatticeDilog h 0) ^ 2) :
    globalArtin H (signIdeleClass (K := K) fun _ => -1) (aO : H) = (bO : H) := by
  classical
  let σ := globalArtin H (signIdeleClass (K := K) fun _ => -1)
  by_contra hne
  let c : 𝓞 H := RingOfIntegers.mapRingEquiv σ.toRingEquiv aO - bO
  have hc : c ≠ 0 := by
    intro hc0
    apply hne
    have heq := congrArg (fun z : 𝓞 H => (z : H)) hc0
    apply sub_eq_zero.mp
    simpa only [c, map_sub, map_zero, RingOfIntegers.mapRingEquiv_apply,
      AlgEquiv.coe_ringEquiv] using heq
  let T := (FinitePlace.finite_below_primes_containing (K := K) hc).toFinset
  obtain ⟨S₀, hS₀⟩ := exists_rayPrime_exclusion (K := K) (H := K) hM0
  have hm : Ideal.span {(M : 𝓞 K)} ≠ ⊥ := by
    rw [ne_eq, Ideal.span_singleton_eq_bot]
    exact_mod_cast hM0.ne'
  obtain ⟨v, hvS, hp, hgen⟩ :=
    exists_degreeOne_hasSignedRayGenerator F hm (fun _ => -1) (S₀ ∪ T)
  have hvS₀ : v ∉ S₀ := fun hv => hvS (Finset.mem_union_left _ hv)
  have hvT : v ∉ T := fun hv => hvS (Finset.mem_union_right _ hv)
  obtain ⟨hp2, hdisc, hcop⟩ := hS₀ v hvS₀ hp
  let p := Ideal.absNorm v.asIdeal
  let _ : Fact p.Prime := ⟨hp⟩
  let P₀ : FinitePlace.PrimeAbove (L := H) v := Classical.choice inferInstance
  let P := FinitePlace.PrimeAbove.place v P₀
  let _ : P.asIdeal.LiesOver v.asIdeal := FinitePlace.PrimeAbove.place_liesOver v P₀
  have hFrob : IsFrobeniusAt K H σ v.asIdeal P.asIdeal :=
    (isFrobeniusAt_globalArtin_signIdeleClass_iff hU (fun _ => -1)
      (by simpa only [FinitePlace.below_self] using hcop) P).mpr hgen
  have hpP : (p : 𝓞 H) ∈ P.asIdeal := by
    simpa only [map_natCast] using
      (Ideal.mem_of_liesOver P.asIdeal v.asIdeal (p : 𝓞 K)).mp
        (by change (Ideal.absNorm v.asIdeal : 𝓞 K) ∈ v.asIdeal
            exact Ideal.absNorm_mem v.asIdeal)
  have hpow : aO ^ p - bO ∈ P.asIdeal :=
    pseudolatticeDilog_sq_signed_mem h hM ψ hx aO bO
      (s := -1) ha (by simpa using hb) hp2 hdisc rfl P hpP hgen
  have hcP : c ∈ P.asIdeal := by
    have hc_eq : c =
        (RingOfIntegers.mapRingEquiv σ.toRingEquiv aO - aO ^ p) + (aO ^ p - bO) := by
      dsimp [c]
      ring
    rw [hc_eq]
    exact P.asIdeal.add_mem (hFrob.sub_mem aO) hpow
  apply hvT
  rw [← FinitePlace.below_eq_of_liesOver v P]
  simp only [T, Set.Finite.mem_toFinset, Set.mem_image, Set.mem_ofPred_eq]
  exact ⟨P, hcP, rfl⟩

/-- **The totally negative sign class sends the squared value at `x` to that at `-x`**: let `M`
be a modulus for `G_{I,ε}` (`IsPeriod.exists_modulus_mul_mem`) and `H/K` abelian with norm group
the narrow ray subgroup of modulus `M𝒪_K`. For an embedding `ψ : H → ℂ` and `a, b ∈ H` with
`ψ(a) = (E_{I,ε}(x)/E_{I,ε}(0))²` and `ψ(b) = (E_{I,ε}(-x)/E_{I,ε}(0))²`, the Artin symbol of the
sign idèle negative at both real places sends `a` to `b`. The case `s₁s₂` of
[RW26b, Radchenko, Wheeler (2026b), Section 8, proof of Proposition 4] in squared form, where
the two split-prime translates agree by [RW26b, Radchenko, Wheeler (2026b), Proposition 8]. -/
theorem pseudolatticeDilog_artin_signClass (h : B.IsPeriod ε) {M : ℕ} (hM0 : 0 < M)
    (hM : ∀ a : 𝓞 K, ∀ x : K, (ε - 1) * x ∈ B.submodule →
      (M : K) * (a : K) * x ∈ B.submodule)
    {H : Type*} [Field H] [NumberField H] [Algebra K H] [IsAbelianGalois K H]
    (hU : (IdeleClassGroup.norm (K := K) (L := H)).range =
      IdeleClassGroup.raySubgroup Set.univ (Ideal.span {(M : 𝓞 K)}))
    (ψ : H →+* ℂ) {x : K} (hx : (ε - 1) * x ∈ B.submodule) {a b : H}
    (ha : ψ a = (pseudolatticeDilog h x / pseudolatticeDilog h 0) ^ 2)
    (hb : ψ b = (pseudolatticeDilog h (-x) / pseudolatticeDilog h 0) ^ 2) :
    globalArtin H (signIdeleClass (K := K) fun _ => -1) a = b := by
  have hxneg : (ε - 1) * (-x) ∈ B.submodule := by
    simpa only [mul_neg] using B.submodule.neg_mem hx
  have ha_int : IsIntegral ℤ a := pseudolatticeDilog_sq_isIntegral h hx ψ ha
  have hb_int : IsIntegral ℤ b := pseudolatticeDilog_sq_isIntegral h hxneg ψ hb
  obtain ⟨aO, haO⟩ :=
    (IsIntegralClosure.isIntegral_iff (A := 𝓞 H) (R := ℤ) (B := H)).mp ha_int
  obtain ⟨bO, hbO⟩ :=
    (IsIntegralClosure.isIntegral_iff (A := 𝓞 H) (R := ℤ) (B := H)).mp hb_int
  have heq := pseudolatticeDilog_artin_signClass_integral h hM0 hM hU ψ hx aO bO
    (by change ψ ((algebraMap (𝓞 H) H) aO) = _; rw [haO]; exact ha)
    (by change ψ ((algebraMap (𝓞 H) H) bO) = _; rw [hbO]; exact hb)
  change globalArtin H (signIdeleClass (K := K) fun _ => -1)
    ((algebraMap (𝓞 H) H) aO) = (algebraMap (𝓞 H) H) bO at heq
  rw [haO, hbO] at heq
  exact heq

end SIC

end
