/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import Mathlib.Algebra.Algebra.Hom.Rat
import Mathlib.Algebra.QuadraticAlgebra.Basic
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.FieldTheory.IsAlgClosed.Classification
import SICs.FieldTheory.ComplexGalois

/-!
# Sign-switching `ℚ`-algebra automorphisms of `ℂ`

Extending a subfield automorphism to `ℂ`; a sign-switching automorphism exists.

Converting a ghost fiducial into a live one applies a single Galois automorphism `g : ℂ ≃ₐ[ℚ] ℂ`
entrywise. The arithmetic input of [AFK25, Conjecture 1.36, `conj:mrmvc`](2) gives modulus one
under every sign-switching automorphism, but does not assert that such an automorphism exists.
The construction needs one automorphism acting simultaneously on all overlaps of a fixed
candidate. This file supplies that existence for both the general and principal constructions:

`exists_switchesSqrt`: for every positive nonsquare `Δ : ℤ` there is a
`g : ℂ ≃ₐ[ℚ] ℂ` with `g (√Δ) = -√Δ`, i.e. `SwitchesSqrt g Δ`.

This is a theorem of field theory, not a conjectural input: nothing in this file is assumed.

## The extension step

The finite half uses the standard quadratic algebra `ℚ[ω]` with `ω² = Δ`. Since `Δ` is
nonsquare, this algebra is a field; its standard conjugation sends `ω` to `-ω`. Embedding it
in `ℂ` by `ω ↦ √Δ` identifies this conjugation with the nontrivial automorphism of `ℚ(√Δ)`.
The work is in extending that automorphism from the subfield to all of `ℂ`, which is
`exists_ringEquiv_extending` below.

The argument is the classical one. If `K` is any field equipped with an embedding into `ℂ` and
`B ⊆ ℂ` is a transcendence basis of `ℂ` over `K`, then `ℂ` is an algebraic closure of the
`K`-algebra `A = K[B]` generated by `B`, and `A` is a polynomial ring over `K` on `B`. A ring
automorphism `σ` of `K` therefore extends to `A` by acting on coefficients and fixing `B`, and any
isomorphism of the bases of two algebraic closures lifts to the closures themselves
(`IsAlgClosure.equivOfEquiv`). The lift is not canonical -- it involves a choice of transcendence
basis and a choice of lift -- which is why the statement is an existence statement.

`Mathlib.FieldTheory.IsAlgClosed.Classification` runs exactly this argument for the *identity* on
the base ring, in `IsAlgClosed.equivOfTranscendenceBasis`; the proof below is that construction
with the coefficient twist `σ` inserted, which is what makes the extension move `√Δ`.

## Main definitions and results

- `algEquivOfRingEquiv`: every ring automorphism of `ℂ` is a `ℚ`-algebra automorphism, since a ring
  homomorphism of fields of characteristic zero fixes the rationals.
- `exists_ringEquiv_extending`: every ring automorphism of a field embedded in `ℂ` extends to a
  ring automorphism of `ℂ`.
- `exists_algEquiv_extending`: the same statement for `ℚ`-algebra automorphisms of `ℂ`.
- `exists_switchesSqrt`: existence of a sign-switching automorphism for a positive nonsquare
  discriminant. The constructions use it at the field discriminant
  (`principalLiveUnitModulus_holds`).

## References

- [AFK25] Appleby, Flammia, Kopp, arXiv:2501.03970v2, Conjecture 1.36 and its footnote
-/

noncomputable section

namespace SIC

/-! ### Extending an automorphism of a subfield to `ℂ`

An automorphism of a subfield embedded in the algebraically closed field `ℂ` extends to a ring
automorphism of `ℂ`.  Characteristic zero then upgrades the extension to a `ℚ`-algebra
automorphism. -/

/-- Every ring automorphism of `ℂ` is a `ℚ`-algebra automorphism: a ring homomorphism between
fields of characteristic zero fixes every rational number. -/
def algEquivOfRingEquiv (g : ℂ ≃+* ℂ) : ComplexGaloisAutomorphism :=
  g.toRatAlgEquiv

/-- **Every ring automorphism of a field embedded in `ℂ` extends to `ℂ`.**

Concretely, if `K` is a field with an embedding `algebraMap K ℂ` and `σ` is a ring automorphism of
`K`, then some ring automorphism `g` of `ℂ` satisfies `g ∘ algebraMap K ℂ = algebraMap K ℂ ∘ σ`.

The proof takes a transcendence basis `B` of `ℂ` over `K`, extends `σ` to the polynomial algebra
`K[B]` by acting on coefficients, and lifts that extension along the two algebraic closures
`ℂ ⊇ K[B]` with `IsAlgClosure.equivOfEquiv`. Neither the basis nor the lift is canonical, so the
conclusion is an existence statement rather than a construction. -/
theorem exists_ringEquiv_extending (K : Type*) [Field K] [Algebra K ℂ] (σ : K ≃+* K) :
    ∃ g : ℂ ≃+* ℂ, ∀ k : K, g (algebraMap K ℂ k) = algebraMap K ℂ (σ k) := by
  have : FaithfulSMul K ℂ :=
    (faithfulSMul_iff_algebraMap_injective K ℂ).mpr (algebraMap K ℂ).injective
  obtain ⟨s, hs⟩ := exists_isTranscendenceBasis K ℂ
  have : IsAlgClosure (Algebra.adjoin K (Set.range ((↑) : s → ℂ))) ℂ :=
    IsAlgClosed.isAlgClosure_of_transcendence_basis _ hs
  -- The coefficientwise extension of `σ` to `K[B] ≃ MvPolynomial B K`.
  set e : Algebra.adjoin K (Set.range ((↑) : s → ℂ)) ≃+*
      Algebra.adjoin K (Set.range ((↑) : s → ℂ)) :=
    hs.1.aevalEquiv.symm.toRingEquiv.trans
      ((MvPolynomial.mapEquiv (↥s) σ).trans hs.1.aevalEquiv.toRingEquiv) with he
  have hbase : ∀ k : K,
      e (algebraMap K (Algebra.adjoin K (Set.range ((↑) : s → ℂ))) k) =
        algebraMap K (Algebra.adjoin K (Set.range ((↑) : s → ℂ))) (σ k) := by
    intro k
    rw [he]
    simp only [RingEquiv.coe_trans, Function.comp_apply, AlgEquiv.coe_ringEquiv,
      AlgEquiv.commutes, MvPolynomial.algebraMap_eq,
      MvPolynomial.mapEquiv_apply, MvPolynomial.map_C, RingEquiv.coe_toRingHom]
    rw [← MvPolynomial.algebraMap_eq, AlgEquiv.commutes]
  refine ⟨IsAlgClosure.equivOfEquiv ℂ ℂ e, fun k => ?_⟩
  rw [IsScalarTower.algebraMap_apply K (Algebra.adjoin K (Set.range ((↑) : s → ℂ))) ℂ k,
    IsAlgClosure.equivOfEquiv_algebraMap, hbase,
    ← IsScalarTower.algebraMap_apply K (Algebra.adjoin K (Set.range ((↑) : s → ℂ))) ℂ (σ k)]

/-- The `ℚ`-algebra form of `exists_ringEquiv_extending`: every ring automorphism of a field
embedded in `ℂ` extends to a `ℚ`-algebra automorphism of `ℂ`. -/
theorem exists_algEquiv_extending (K : Type*) [Field K] [Algebra K ℂ] (σ : K ≃+* K) :
    ∃ g : ComplexGaloisAutomorphism, ∀ k : K, g (algebraMap K ℂ k) = algebraMap K ℂ (σ k) := by
  obtain ⟨g, hg⟩ := exists_ringEquiv_extending K σ
  exact ⟨algEquivOfRingEquiv g, hg⟩

/-! ### The sign-switching automorphism

For a positive nonsquare integer `Δ`, the quadratic algebra `ℚ[ω]` with `ω² = Δ` is a field.
Its conjugation sends `ω` to `-ω`. The homomorphism sending `ω` to the positive real square
root embeds it in `ℂ`, and the extension theorem realizes conjugation as an ambient
`ℚ`-algebra automorphism of `ℂ`. -/

/-- **Existence of a sign-switching automorphism.**

For a positive nonsquare `Δ`, some `ℚ`-algebra automorphism of `ℂ` exchanges the two square roots
of `Δ`, that is, satisfies the Galois condition `SwitchesSqrt`.

Positivity is not used by the proof -- only that `Δ` is nonnegative, so that `√Δ` is a genuine
square root, and not a square, so that `ℚ(√Δ)` is a quadratic field -- but it is the hypothesis
under which the statement is consumed, `Δ` there being the discriminant of a real quadratic form.

This is a theorem of field theory, not a conjectural input; see the module docstring for the
extension argument. -/
theorem exists_switchesSqrt {Δ : ℤ} (hΔ : 0 < Δ) (hsq : ¬ IsSquare Δ) :
    ∃ g : ComplexGaloisAutomorphism, SwitchesSqrt g Δ := by
  let K := QuadraticAlgebra ℚ (Δ : ℚ) 0
  have : Fact (¬ IsSquare (Δ : ℚ)) := ⟨fun h ↦ hsq (Rat.isSquare_intCast_iff.mp h)⟩
  have hroot : (Real.sqrt (Δ : ℝ) : ℂ) * (Real.sqrt (Δ : ℝ) : ℂ) =
      (Δ : ℚ) • (1 : ℂ) + (0 : ℚ) • (Real.sqrt (Δ : ℝ) : ℂ) := by
    simp only [Algebra.smul_def, map_intCast, mul_one, ← sq]
    rw [← Complex.ofReal_pow, Real.sq_sqrt (by exact_mod_cast hΔ.le)]
    simp
  let f : K →ₐ[ℚ] ℂ := QuadraticAlgebra.lift ⟨(Real.sqrt (Δ : ℝ) : ℂ), hroot⟩
  let _ : Algebra K ℂ := f.toRingHom.toAlgebra
  have hmap : algebraMap K ℂ (QuadraticAlgebra.omega : K) =
      (Real.sqrt (Δ : ℝ) : ℂ) := by
    change f QuadraticAlgebra.omega = _
    change (QuadraticAlgebra.omega : K).re • (1 : ℂ) +
      (QuadraticAlgebra.omega : K).im • (Real.sqrt (Δ : ℝ) : ℂ) = _
    simp
  have hstar : starRingAut (QuadraticAlgebra.omega : K) =
      -(QuadraticAlgebra.omega : K) := by
    change star (QuadraticAlgebra.omega : K) = _
    ext <;> simp
  obtain ⟨g, hg⟩ := exists_algEquiv_extending K starRingAut
  refine ⟨g, ?_⟩
  have h := hg (QuadraticAlgebra.omega : K)
  rw [hmap, hstar, map_neg, hmap] at h
  exact h

end SIC

end
