/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import Mathlib.NumberTheory.Cyclotomic.Gal
import Mathlib.NumberTheory.NumberField.Discriminant.Different
import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.FieldTheory.LinearDisjoint

/-!
# Adjoining roots of unity to a Galois extension

The cyclotomic degree over a number field, the Galois structure of $L(\zeta_M)/K$, and the
base-change square $K \subset K(\zeta_p)$, $L \subset L(\zeta_p)$.

This follows Childress, *Class Field Theory* (2009), Chapter V, Lemma 2.7(i) and the proof of
Lemma 2.8, and Milne, *Class Field Theory*, version 4.03 (2020), Chapter VII, Lemma 6.1.

## The argument

A level prime to the discriminant of `L` makes the rational cyclotomic field linearly disjoint
from `L`; the degree over `L` is therefore $\varphi(M)$. The field $L(\zeta_M)$ is generated by
the images of `L` and the root, so restriction and the cyclotomic character determine its
automorphisms. For prime `p`, the degree of $K(\zeta_p)/K$ divides $p-1$; coprime degrees make
$L$ and $K(\zeta_p)$ linearly disjoint when $[L:K]=p$.
-/

noncomputable section

open IsDedekindDomain NumberField Polynomial
open scoped IntermediateField

namespace SIC

variable {K L Ω : Type*} [Field K] [Field L] [Field Ω] [Algebra K L] [Algebra L Ω]
  [Algebra K Ω] [IsScalarTower K L Ω]

/-- The images of `L` and a primitive `M`th root generate `Ω` over `K`. This is the
compositum description used in the irreducibility and Galois proofs. -/
theorem fieldRange_sup_adjoin_eq_top {M : ℕ} [NeZero M]
    [IsCyclotomicExtension {M} L Ω] {ζ : Ω} (hζ : IsPrimitiveRoot ζ M) :
    (IsScalarTower.toAlgHom K L Ω).fieldRange ⊔ K⟮ζ⟯ = ⊤ := by
  let F := (IsScalarTower.toAlgHom K L Ω).fieldRange
  have htop : L⟮ζ⟯ = ⊤ :=
    IntermediateField.adjoin_eq_top_of_algebra L {ζ}
      (IsCyclotomicExtension.adjoin_primitive_root_eq_top hζ)
  apply eq_top_iff.mpr
  intro x _
  have hx : x ∈ L⟮ζ⟯ := by rw [htop]; trivial
  refine IntermediateField.adjoin_induction L
    (p := fun x _ => x ∈ F ⊔ K⟮ζ⟯) ?_ ?_ ?_ ?_ ?_ hx
  · intro y hy
    have hy' : y = ζ := Set.mem_singleton_iff.mp hy
    subst y
    exact (le_sup_right : K⟮ζ⟯ ≤ F ⊔ K⟮ζ⟯)
      (IntermediateField.mem_adjoin_simple_self K ζ)
  · intro y
    exact (le_sup_left : F ≤ F ⊔ K⟮ζ⟯)
      (AlgHom.mem_fieldRange.mpr ⟨y, rfl⟩)
  · intro x y hx hy ihx ihy
    exact add_mem ihx ihy
  · intro x hx ihx
    exact inv_mem ihx
  · intro x y hx hy ihx ihy
    exact mul_mem ihx ihy

/-! ### Cyclotomic degree from discriminant coprimality -/

/-- The cyclotomic discriminant is coprime to the discriminant of `L` when its level is.
Used in `finrank_of_isCoprime_discr`. -/
private theorem coprime_cyclotomic_discr [NumberField L] {C : Type*} [Field C]
    [NumberField C] {M : ℕ} [NeZero M] [IsCyclotomicExtension {M} ℚ C]
    (h : IsCoprime (NumberField.discr L) (M : ℤ)) :
    IsCoprime (NumberField.discr C) (NumberField.discr L) := by
  have hc : (NumberField.discr L).natAbs.Coprime M := by
    simpa only [Int.natAbs_natCast] using (Int.isCoprime_iff_nat_coprime.mp h)
  rw [Int.isCoprime_iff_nat_coprime,
    IsCyclotomicExtension.Rat.natAbs_discr M C]
  exact (hc.symm.pow_left M.totient).coprime_div_left
    (Nat.prod_primeFactors_pow_totient_ediv_dvd (NeZero.pos M))

/-- Replacing a base field by its image in the top field preserves the relative degree.
Used in `finrank_of_isCoprime_discr`. -/
private theorem finrank_eq_finrank_fieldRange :
    Module.finrank L Ω =
      Module.finrank (IsScalarTower.toAlgHom K L Ω).fieldRange Ω := by
  apply Algebra.finrank_eq_of_equiv_equiv
    (IsScalarTower.toAlgHom K L Ω).equivFieldRange.toRingEquiv (RingEquiv.refl Ω)
  ext x
  rfl

/-- **Childress, Lemma 2.7(i)**: if `M` is prime to the discriminant of the number field `L`,
then $L\cap\mathbb Q(\zeta_M) = \mathbb Q$, so $[L(\zeta_M):L]=\varphi(M)$ and
$\operatorname{Gal}(L(\zeta_M)/L)\cong(\mathbb Z/M\mathbb Z)^\times$.
Childress, *Class Field Theory*, Chapter V, Lemma 2.7(i), for `F = L`. -/
theorem finrank_of_isCoprime_discr [NumberField L] {M : ℕ} [NeZero M]
    [IsCyclotomicExtension {M} L Ω]
    (h : IsCoprime (NumberField.discr L) (M : ℤ)) : Module.finrank L Ω = M.totient := by
  have : NumberField Ω := IsCyclotomicExtension.numberField {M} L Ω
  let ζ := IsCyclotomicExtension.zeta M L Ω
  have hζ : IsPrimitiveRoot ζ M := IsCyclotomicExtension.zeta_spec M L Ω
  let F : IntermediateField ℚ Ω := (IsScalarTower.toAlgHom ℚ L Ω).fieldRange
  let C : IntermediateField ℚ Ω := ℚ⟮ζ⟯
  have : IsCyclotomicExtension {M} ℚ C :=
    hζ.intermediateField_adjoin_isCyclotomicExtension ℚ
  have : IsGalois ℚ C := IsCyclotomicExtension.isGalois {M} ℚ C
  have hdiscr : NumberField.discr L = NumberField.discr F :=
    NumberField.discr_eq_discr_of_algEquiv L
      (IsScalarTower.toAlgHom ℚ L Ω).equivFieldRange
  have hcpr : IsCoprime (NumberField.discr C) (NumberField.discr F) := by
    rw [← hdiscr]
    exact coprime_cyclotomic_discr (C := C) h
  have hdisj : C.LinearDisjoint F :=
    NumberField.linearDisjoint_of_isGalois_isCoprime_discr Ω C F hcpr
  have hsup : C ⊔ F = ⊤ := by
    rw [sup_comm]
    exact fieldRange_sup_adjoin_eq_top (K := ℚ) (L := L) (Ω := Ω) hζ
  have hdegreeF : Module.finrank F Ω = M.totient := by
    rw [hdisj.finrank_right_eq_finrank hsup,
      IsCyclotomicExtension.Rat.finrank M C]
  exact (finrank_eq_finrank_fieldRange (K := ℚ) (L := L) (Ω := Ω)).trans hdegreeF

/-! ### The Galois group of `L(ζ_M)/K` -/

/-- The extension $L(\zeta_M)/K$ obtained from a finite Galois extension `L/K` by adjoining the
`M`th roots of unity is Galois. Childress, *Class Field Theory*, Chapter V, proof of Lemma 2.8. -/
theorem isGalois_of_isCyclotomicExtension [IsGalois K L]
    {M : ℕ} [NeZero M] [IsCyclotomicExtension {M} L Ω] : IsGalois K Ω := by
  have : IsGalois L Ω := IsCyclotomicExtension.isGalois {M} L Ω
  have : Algebra.IsIntegral K Ω := Algebra.IsIntegral.trans L
  have : Algebra.IsSeparable K Ω := Algebra.IsSeparable.trans K L Ω
  let ζ := IsCyclotomicExtension.zeta M L Ω
  have hζ : IsPrimitiveRoot ζ M := IsCyclotomicExtension.zeta_spec M L Ω
  let F : IntermediateField K Ω := (IsScalarTower.toAlgHom K L Ω).fieldRange
  let C : IntermediateField K Ω := K⟮ζ⟯
  have : IsGalois K F :=
    IsGalois.of_algEquiv (IsScalarTower.toAlgHom K L Ω).equivFieldRange
  have : IsCyclotomicExtension {M} K C :=
    hζ.intermediateField_adjoin_isCyclotomicExtension K
  have : IsGalois K C := IsCyclotomicExtension.isGalois {M} K C
  have htop : F ⊔ C = ⊤ := fieldRange_sup_adjoin_eq_top hζ
  have hnormal : Normal K Ω :=
    Normal.of_algEquiv ((IntermediateField.equivOfEq htop).trans IntermediateField.topEquiv)
  exact isGalois_iff.mpr ⟨inferInstance, hnormal⟩

/-- An automorphism of `L(ζ)` over `K` is determined by its restriction to `L` and its
action on `ζ`. Childress, *Class Field Theory*, Chapter V, proof of Lemma 2.8. -/
theorem IsPrimitiveRoot.algEquiv_ext [Normal K L] {M : ℕ} [NeZero M]
    [IsCyclotomicExtension {M} L Ω] {ζ : Ω} (hζ : IsPrimitiveRoot ζ M)
    {g₁ g₂ : Ω ≃ₐ[K] Ω} (hL : g₁.restrictNormal L = g₂.restrictNormal L)
    (hroot : g₁ ζ = g₂ ζ) : g₁ = g₂ := by
  apply AlgEquiv.ext
  intro x
  have htop : L⟮ζ⟯ = ⊤ :=
    IntermediateField.adjoin_eq_top_of_algebra L {ζ}
      (IsCyclotomicExtension.adjoin_primitive_root_eq_top hζ)
  have hx : x ∈ L⟮ζ⟯ := by rw [htop]; trivial
  refine IntermediateField.adjoin_induction L
    (p := fun x _ => g₁ x = g₂ x) ?_ ?_ ?_ ?_ ?_ hx
  · intro y hy
    have hy' : y = ζ := Set.mem_singleton_iff.mp hy
    subst y
    exact hroot
  · intro y
    calc
      g₁ (algebraMap L Ω y) = algebraMap L Ω (g₁.restrictNormal L y) := by
        rw [AlgEquiv.restrictNormal_commutes]
      _ = algebraMap L Ω (g₂.restrictNormal L y) := by rw [hL]
      _ = g₂ (algebraMap L Ω y) := by rw [AlgEquiv.restrictNormal_commutes]
  · intro x y hx hy ihx ihy
    simp [ihx, ihy]
  · intro x hx ihx
    simp [ihx]
  · intro x y hx hy ihx ihy
    simp [ihx, ihy]

/-- Restriction to `L` and the cyclotomic character determine an automorphism of `Ω`.
This is the injective half of `bijective_restrictNormal_prod_autToPow`, by
`IsPrimitiveRoot.algEquiv_ext`. -/
theorem injective_restrictNormal_prod_autToPow [Normal K L]
    {M : ℕ} [NeZero M] [IsCyclotomicExtension {M} L Ω]
    {ζ : Ω} (hζ : IsPrimitiveRoot ζ M) :
    Function.Injective (fun g : Ω ≃ₐ[K] Ω ↦ (g.restrictNormal L, hζ.autToPow K g)) := by
  intro g₁ g₂ h
  have hL : g₁.restrictNormal L = g₂.restrictNormal L := congrArg Prod.fst h
  have hpow : hζ.autToPow K g₁ = hζ.autToPow K g₂ := congrArg Prod.snd h
  apply IsPrimitiveRoot.algEquiv_ext hζ hL
  rw [← hζ.autToPow_spec K g₁, ← hζ.autToPow_spec K g₂, hpow]

/-- An automorphism of $L(\zeta_M)/K$ is determined by its restriction to `L` and its action on
$\zeta_M$, and when $[L(\zeta_M):L]=\varphi(M)$ every pair occurs:
$\operatorname{Gal}(L(\zeta_M)/K)\cong\operatorname{Gal}(L/K)\times(\mathbb Z/M\mathbb Z)^\times$.
Childress, *Class Field Theory*, Chapter V, proof of Lemma 2.8. -/
theorem bijective_restrictNormal_prod_autToPow [IsGalois K L] [FiniteDimensional K L]
    {M : ℕ} [NeZero M] [IsCyclotomicExtension {M} L Ω] {ζ : Ω} (hζ : IsPrimitiveRoot ζ M)
    (hdegree : Module.finrank L Ω = M.totient) :
    Function.Bijective fun g : Ω ≃ₐ[K] Ω ↦ (g.restrictNormal L, hζ.autToPow K g) := by
  classical
  have : FiniteDimensional L Ω := IsCyclotomicExtension.finite_of_singleton M L Ω
  have : FiniteDimensional K Ω := FiniteDimensional.trans K L Ω
  have : IsGalois K Ω :=
    isGalois_of_isCyclotomicExtension (K := K) (L := L) (Ω := Ω) (M := M)
  apply (Fintype.bijective_iff_injective_and_card _).mpr
  constructor
  · exact injective_restrictNormal_prod_autToPow hζ
  · calc
      Fintype.card (Ω ≃ₐ[K] Ω) = Module.finrank K Ω := by
        rw [← Nat.card_eq_fintype_card, IsGalois.card_aut_eq_finrank]
      _ = Module.finrank K L * Module.finrank L Ω :=
        (Module.finrank_mul_finrank K L Ω).symm
      _ = Module.finrank K L * M.totient := by
        rw [hdegree]
      _ = Fintype.card (L ≃ₐ[K] L) * Fintype.card (ZMod M)ˣ := by
        rw [← Nat.card_eq_fintype_card, IsGalois.card_aut_eq_finrank,
          ZMod.card_units_eq_totient]
      _ = Fintype.card ((L ≃ₐ[K] L) × (ZMod M)ˣ) :=
        (Fintype.card_prod _ _).symm

/-- The extension $L(\zeta_M)/K$ obtained from a finite abelian extension `L/K` is abelian: its
Galois group embeds in $\operatorname{Gal}(L/K)\times(\mathbb Z/M\mathbb Z)^\times$. -/
theorem isAbelianGalois_of_isCyclotomicExtension
    [IsAbelianGalois K L] {M : ℕ} [NeZero M] [IsCyclotomicExtension {M} L Ω] :
    IsAbelianGalois K Ω := by
  have : IsGalois L Ω := IsCyclotomicExtension.isGalois {M} L Ω
  have : Algebra.IsIntegral K Ω := Algebra.IsIntegral.trans L
  let ζ := IsCyclotomicExtension.zeta M L Ω
  have hζ : IsPrimitiveRoot ζ M := IsCyclotomicExtension.zeta_spec M L Ω
  let F : IntermediateField K Ω := (IsScalarTower.toAlgHom K L Ω).fieldRange
  let C : IntermediateField K Ω := K⟮ζ⟯
  have : IsAbelianGalois K F :=
    IsAbelianGalois.of_algHom (IsScalarTower.toAlgHom K L Ω).equivFieldRange.symm.toAlgHom
  have : IsCyclotomicExtension {M} K C :=
    hζ.intermediateField_adjoin_isCyclotomicExtension K
  have : IsAbelianGalois K C := IsCyclotomicExtension.isAbelianGalois {M} K C
  have htop : F ⊔ C = ⊤ := fieldRange_sup_adjoin_eq_top hζ
  have : IsAbelianGalois K ↥(F ⊔ C) :=
    IsAbelianGalois.sup (F := K) (E := Ω) F C
  exact IsAbelianGalois.of_algHom
    ((IntermediateField.equivOfEq htop).trans IntermediateField.topEquiv).symm.toAlgHom

end SIC

universe u v

namespace SIC.CyclotomicBaseChange

variable (p : ℕ) [Fact p.Prime] (K : Type u) (L : Type v) [Field K] [Field L]
  [CharZero K] [CharZero L] [Algebra K L] [FiniteDimensional K L]

/-- The field $K'=K(\zeta_p)$ inside $L'=L(\zeta_p)$ in Milne, *Class Field Theory*,
Chapter VII, Lemma 6.1. -/
def base : IntermediateField K (CyclotomicField p L) :=
  IntermediateField.adjoin K {IsCyclotomicExtension.zeta p L (CyclotomicField p L)}

/-- The upper right field of the cyclotomic square is finite over its lower left field. -/
local instance finiteDimensional_top : FiniteDimensional K (CyclotomicField p L) := by
  have : FiniteDimensional L (CyclotomicField p L) :=
    IsCyclotomicExtension.finite_of_singleton p L (CyclotomicField p L)
  exact FiniteDimensional.trans K L (CyclotomicField p L)

/-! ### The cyclotomic square

The chosen primitive root of $L'$ belongs to $K'$ by its definition. Cyclotomic Galois
automorphisms embed into $(\mathbb Z/p\mathbb Z)^\times$, giving $[K':K]\mid p-1$.
The embedded image of $L$ together with $K'$ generates $L'$. -/

/-- The chosen primitive root $\zeta_p$ viewed in $K'$. -/
def primitiveRoot : base p K L :=
  ⟨IsCyclotomicExtension.zeta p L (CyclotomicField p L),
    IntermediateField.subset_adjoin K _ (Set.mem_singleton _)⟩

omit [CharZero K] [FiniteDimensional K L] in
/-- The inclusion $K'\hookrightarrow L'$ sends its chosen root to the chosen root of $L'$. -/
@[simp] theorem algebraMap_primitiveRoot :
    algebraMap (base p K L) (CyclotomicField p L) (primitiveRoot p K L) =
      IsCyclotomicExtension.zeta p L (CyclotomicField p L) := rfl

omit [CharZero K] [FiniteDimensional K L] in
/-- The root $\zeta_p$ in $K'$ is primitive. -/
theorem primitiveRoot_spec : IsPrimitiveRoot (primitiveRoot p K L) p := by
  exact (IsCyclotomicExtension.zeta_spec p L (CyclotomicField p L)).of_map_of_injective
    (f := algebraMap (base p K L) (CyclotomicField p L))
    (algebraMap (base p K L) (CyclotomicField p L)).injective

omit [CharZero K] in
/-- The field $K'$ is the cyclotomic extension $K(\zeta_p)$. -/
instance isCyclotomicExtension : IsCyclotomicExtension {p} K (base p K L) :=
  IsPrimitiveRoot.intermediateField_adjoin_isCyclotomicExtension K
    (IsCyclotomicExtension.zeta_spec p L (CyclotomicField p L))

omit [CharZero K] in
/-- The cyclotomic extension $K'/K$ is Galois. -/
instance isGalois_base : IsGalois K (base p K L) :=
  IsCyclotomicExtension.isGalois {p} K (base p K L)

omit [CharZero K] in
/-- The cyclotomic degree satisfies $[K':K]\mid p-1$.
Milne, *Class Field Theory*, Chapter VII, proof of Lemma 6.1. -/
theorem finrank_base_dvd : Module.finrank K (base p K L) ∣ p - 1 := by
  have hζ := primitiveRoot_spec p K L
  have h := Subgroup.card_dvd_of_injective (hζ.autToPow K) (hζ.autToPow_injective K)
  rw [IsGalois.card_aut_eq_finrank, Nat.card_eq_fintype_card, ZMod.card_units] at h
  exact h

omit [CharZero K] in
/-- The cyclotomic degree $[K':K]$ is coprime to $p$.
Milne, *Class Field Theory*, Chapter VII, proof of Lemma 6.1. -/
theorem coprime_finrank_base : p.Coprime (Module.finrank K (base p K L)) := by
  apply Nat.Coprime.of_dvd_right (finrank_base_dvd p K L)
  exact (Nat.coprime_self_sub_right (Nat.Prime.one_lt (Fact.out : p.Prime)).le).2
    (Nat.coprime_one_right p)

/-- The embedded copy of $L$ in $L'$, used to apply Mathlib's compositum API. -/
private def original : IntermediateField K (CyclotomicField p L) :=
  (IsScalarTower.toAlgHom K L (CyclotomicField p L)).fieldRange

omit [CharZero K] [FiniteDimensional K L] in
/-- The two lower fields generate $L'$; used for its degree and Galois structure. -/
private theorem base_sup_original : base p K L ⊔ original p K L = ⊤ := by
  rw [sup_comm]
  exact SIC.fieldRange_sup_adjoin_eq_top
    (IsCyclotomicExtension.zeta_spec p L (CyclotomicField p L))

omit [CharZero K] in
/-- The degree of $L'$ over $K'$ equals $p$ when $[L:K]=p$.
Milne, *Class Field Theory*, Chapter VII, proof of Lemma 6.1. -/
theorem finrank_extension (hdegree : Module.finrank K L = p) :
    Module.finrank (base p K L) (CyclotomicField p L) = p := by
  have he : Module.finrank K (original p K L) = Module.finrank K L :=
    (IsScalarTower.toAlgHom K L (CyclotomicField p L)).equivFieldRange.toLinearEquiv.finrank_eq.symm
  have hcoprime : (Module.finrank K (base p K L)).Coprime
      (Module.finrank K (original p K L)) := by
    rw [he, hdegree]
    exact (coprime_finrank_base p K L).symm
  have hdisjoint := IntermediateField.LinearDisjoint.of_finrank_coprime hcoprime
  rw [hdisjoint.finrank_left_eq_finrank (base_sup_original p K L), he, hdegree]

variable [IsGalois K L]

/-- The base change $L'/K'$ of the Galois extension $L/K$ is Galois.
Milne, *Class Field Theory*, Chapter VII, proof of Lemma 6.1. -/
instance isGalois_extension : IsGalois (base p K L) (CyclotomicField p L) := by
  have : IsGalois K (original p K L) :=
    IsGalois.of_algEquiv (IsScalarTower.toAlgHom K L (CyclotomicField p L)).equivFieldRange
  exact IsGalois.sup_right (original p K L) (base p K L)
    (by rw [sup_comm, base_sup_original p K L])

end SIC.CyclotomicBaseChange
