/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.Principal.Dilogarithm.Group

/-!
# The Exact Sequence `0 → H → G_d → ℤ/(d - 3)ℤ → 0`

The character `⟨g; ·⟩` of `G_d` with kernel `H` and order dividing `d - 3`, the projection of a
sum over `G_d` onto `H` by averaging against its powers, and the order `|G_d| = N`.

This module follows the proof of [RW26, Radchenko, Wheeler (2026), Theorem 7, `thm:ghostsic`],
which uses the exact sequence `0 → H → G → ℤ/(M - 3)ℤ → 0` with `A ≅ ℤ/(M - 3)ℤ` generated by
`(ε - 1)/(M - 3)`, and its first two equalities of equation (40), `eq:sicmaintrick`: the sum
over `H` is `1/(M - 3)` of the sum over `G` against the `M - 3` characters `⟨w + jg; ·⟩`. The
order `|G| = N` of [RW26, Radchenko, Wheeler (2026), Section 1] at `γ = A_d` follows from the
general lattice count `card_fixedCharacteristics` and `det(A_d - I) = -N`. The group `G_d`, its
torsion `H`, the generator `g`, and the Gaussian and bicharacter are those of
`SICs.Principal.Dilogarithm.Group`.

## The argument

The exact sequence is carried by the character `⟨g; ·⟩` of `G_d`: it has order dividing `d - 3`,
because `(d - 3)g = N(1, 1) = 0` (`principalDilogBicharacter_generator_pow`), and
its kernel is exactly `H` (`principalDilogBicharacter_generator_eq_one_iff`). Both
are read off the closed form `thetaBicharacter_eq_exp`: with `(A_d - I)g = d(d - 1, 1)` modulo
`N`, `⟨g; x⟩ = e((d(d - 1)x₂ - d x₁)/N)`, which is `1` exactly when `d(d - 3)` divides the
symplectic pairing of `(d - 1, 1)` with `x`, and on `G_d` that is the condition `x ∈ H`.

Two consequences serve the proof of Theorem 7. Averaging a function on `G_d` against the
`d - 3` powers of `⟨g; ·⟩` projects it onto `H`, indexed by `(ℤ/dℤ)²` through
`principalDilogTorsionMod` (`sum_sum_mul_principalDilogBicharacter_pow`):
the geometric sum of a root of unity of order dividing `d - 3` is `d - 3` at `1` and `0`
otherwise. The group count `|G_d| = N = d²(d - 3)` (`card_principalDilogGroup`) specializes the
general count of fixed characteristics, using the determinant of `A_d - I`.
-/

noncomputable section

open scoped MatrixGroups

namespace SIC

/-! ### The character `⟨g; ·⟩` and the exact sequence `0 → H → G_d → ℤ/(d - 3)ℤ → 0`

The character `x ↦ ⟨g; x⟩` of `G_d` has order dividing `d - 3` and kernel `H`; this is the exact
sequence of [RW26, Radchenko, Wheeler (2026), proof of Theorem 7, `thm:ghostsic`]. -/

/-- The exponential formula for the generator pairing, used in the kernel calculation. -/
private theorem principalDilogBicharacter_generator_eq_exp (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    principalDilogBicharacter d (principalDilogGenerator d) x =
      Complex.exp (2 * (Real.pi : ℂ) * Complex.I *
        (((((d : ℤ) * ((d : ℤ) - 1) : ℤ) : ℚ) *
          zmodCharacteristic (principalDilogOrder d) x 1 -
          (d : ℚ) * zmodCharacteristic (principalDilogOrder d) x 0 : ℚ) : ℂ)) := by
  let r : Fin 2 → ℚ := fun _ => 1 / ((d : ℚ) - 3)
  let s := zmodCharacteristic (principalDilogOrder d) x
  let t := zmodCharacteristic (principalDilogOrder d) (principalDilogGenerator d)
  have hr : principalA d ∈ gammaSubgroup r := principalA_mem_gamma_generator d hd
  have hs : principalA d ∈ gammaSubgroup s :=
    (mem_principalDilogGroup_iff d hd x).mp hx
  have he : IsIntegralIndex (t - r) :=
    isIntegralIndex_principalDilogGenerator_sub d hd
  have hindex : r + (t - r) = t := by abel
  have hperiod := thetaBicharacter_add_of_isIntegralIndex_left (principalA d) hr hs he
  rw [hindex] at hperiod
  obtain ⟨hk₁, hk₂⟩ := principalA_generator_witnesses d hd
  have hk₁' : ((principalA d 0 0 : ℚ) - 1) * r 0 +
      (principalA d 0 1 : ℚ) * r 1 =
        ((d : ℤ) * ((d : ℤ) - 1) : ℤ) := by simpa [r] using hk₁
  have hk₂' : (principalA d 1 0 : ℚ) * r 0 +
      ((principalA d 1 1 : ℚ) - 1) * r 1 = (d : ℤ) := by
    simpa [r] using hk₂
  change thetaBicharacter t s _ = _
  rw [hperiod, thetaBicharacter_eq_exp (principalA d) hk₁' hk₂' hs]
  simp [s]

/-- The generator pairing is trivial exactly when its symplectic numerator is divisible by
`d(d - 3)`; used by `principalDilogBicharacter_generator_eq_one_iff`. -/
private theorem principalDilogBicharacter_generator_eq_one_iff_dvd (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    principalDilogBicharacter d (principalDilogGenerator d) x = 1 ↔
      (((d * (d - 3) : ℕ) : ℤ) ∣
        ((d : ℤ) - 1) * (x 1).val - (x 0).val) := by
  let C : ℕ := d * (d - 3)
  let a : ℤ := ((d : ℤ) - 1) * (x 1).val - (x 0).val
  let : NeZero C := ⟨(Nat.mul_pos (by omega : 0 < d) (by omega : 0 < d - 3)).ne'⟩
  have hdq : (d : ℚ) ≠ 0 := by exact_mod_cast (by omega : d ≠ 0)
  have hcq : (C : ℚ) ≠ 0 := by exact_mod_cast (NeZero.ne C)
  have hn : (principalDilogOrder d : ℚ) = (d : ℚ) * C := by
    simp only [C, principalDilogOrder, Nat.cast_mul, Nat.cast_pow]
    ring
  have hphase :
      (((d : ℤ) * ((d : ℤ) - 1) : ℤ) : ℚ) *
          zmodCharacteristic (principalDilogOrder d) x 1 -
        (d : ℚ) * zmodCharacteristic (principalDilogOrder d) x 0 =
      (a : ℚ) / C := by
    simp only [zmodCharacteristic, a, Int.cast_sub, Int.cast_mul, Int.cast_natCast]
    rw [hn]
    field_simp [hdq, hcq]
  rw [principalDilogBicharacter_generator_eq_exp d hd hx,
    exp_two_pi_I_ratCast_eq_one_iff, hphase]
  have hq : (∃ n : ℤ, (a : ℚ) / C = n) ↔ (a : ZMod C) = 0 := by
    simpa using (exists_div_sub_div_eq_intCast_iff C a 0)
  rw [hq, ZMod.intCast_zmod_eq_zero_iff_dvd]

/-- **`⟨g; x⟩^{d-3} = 1` on `G_d`**: `(d - 3)g = 0` and the bicharacter is additive
(`fixedBicharacter_add_left`, `principalDilogGenerator_nsmul`). -/
theorem principalDilogBicharacter_generator_pow (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    principalDilogBicharacter d (principalDilogGenerator d) x ^ (d - 3) = 1 := by
  have : NeZero (principalDilogOrder d) := principalDilogOrder_neZero d hd
  have hg := principalDilogGenerator_mem d hd
  rw [← fixedBicharacter_nsmul_left (principalA d) (principalDilogOrder d) hg hx,
    principalDilogGenerator_nsmul, fixedBicharacter_zero_left]

/-- The second row of `(A_d-I)x=0` after cancelling `d`, used in the generator kernel. -/
private theorem principalDilogGroup_row_two_dvd (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    (((d * (d - 3) : ℕ) : ℤ) ∣
      ((d : ℤ) - 2) * (x 0).val - (x 1).val) := by
  have : NeZero (principalDilogOrder d) := principalDilogOrder_neZero d hd
  have hrow' := ((mem_principalDilogGroup_iff_coords d hd x).mp hx).2
  have hz : (((d : ℤ) * (((d : ℤ) - 2) * (x 0).val - (x 1).val) : ℤ) :
      ZMod (principalDilogOrder d)) = 0 := by
    calc
      _ = (d : ZMod (principalDilogOrder d)) *
          ((d : ZMod (principalDilogOrder d)) - 2) * x 0 - d * x 1 := by
            push_cast
            rw [ZMod.natCast_zmod_val, ZMod.natCast_zmod_val]
            ring
      _ = 0 := hrow'
  have hdvd := (ZMod.intCast_zmod_eq_zero_iff_dvd _ _).mp hz
  have hn : (principalDilogOrder d : ℤ) =
      (d : ℤ) * ((d * (d - 3) : ℕ) : ℤ) := by
    simp only [principalDilogOrder, Nat.cast_mul, Nat.cast_pow]
    ring
  rw [hn] at hdvd
  exact (Int.mul_dvd_mul_iff_left (by exact_mod_cast (by omega : d ≠ 0))).mp hdvd

/-- On `G_d`, vanishing of the generator pairing forces both coordinates into the
`d(d - 3)` lattice. -/
private theorem principalDilogGroup_pairing_dvd_iff_coords (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    (((d * (d - 3) : ℕ) : ℤ) ∣
        ((d : ℤ) - 1) * (x 1).val - (x 0).val) ↔
      (((d * (d - 3) : ℕ) : ℤ) ∣ (x 0).val) ∧
        (((d * (d - 3) : ℕ) : ℤ) ∣ (x 1).val) := by
  let C : ℤ := (d * (d - 3) : ℕ)
  let X : ℤ := (x 0).val
  let Y : ℤ := (x 1).val
  have hrow : C ∣ ((d : ℤ) - 2) * X - Y := principalDilogGroup_row_two_dvd d hd hx
  have hC : C = (d : ℤ) * ((d : ℤ) - 3) := by
    simp only [C, Nat.cast_mul, Nat.cast_sub (by omega : 3 ≤ d)]
    ring
  have hcombo : ((d : ℤ) - 1) * (((d : ℤ) - 2) * X - Y) +
      (((d : ℤ) - 1) * Y - X) = C * X + X := by rw [hC]; ring
  constructor
  · intro hpair
    have hsum : C ∣ C * X + X := by
      rw [← hcombo]
      exact dvd_add (dvd_mul_of_dvd_right hrow _) hpair
    have hX : C ∣ X := by
      have h := dvd_sub hsum (dvd_mul_right C X)
      simpa [add_comm] using h
    have hY : C ∣ Y := by
      have h := dvd_sub (dvd_mul_of_dvd_left hX ((d : ℤ) - 2)) hrow
      simpa [mul_comm X ((d : ℤ) - 2)] using h
    exact ⟨hX, hY⟩
  · rintro ⟨hX, hY⟩
    exact dvd_sub (dvd_mul_of_dvd_right hY _) hX

/-- Coordinate description of the image of multiplication by `d(d - 3)` modulo `N`. -/
private theorem principalDilogTorsion_coordinate_image_iff_dvd (d : ℕ) (hd : 3 < d)
    (z : ZMod (principalDilogOrder d)) :
    (∃ p : ℤ, ((d * (d - 3) : ℕ) : ZMod (principalDilogOrder d)) *
      (p : ZMod (principalDilogOrder d)) = z) ↔
      (((d * (d - 3) : ℕ) : ℤ) ∣ (z.val : ℤ)) := by
  have : NeZero (principalDilogOrder d) := principalDilogOrder_neZero d hd
  let C : ℤ := (d * (d - 3) : ℕ)
  have hN : C ∣ (principalDilogOrder d : ℤ) := by
    refine ⟨d, ?_⟩
    simp only [C, principalDilogOrder, Nat.cast_mul, Nat.cast_pow]
    ring
  constructor
  · rintro ⟨p, hp⟩
    have heq : ((C * p : ℤ) : ZMod (principalDilogOrder d)) =
        (((z.val : ℕ) : ℤ) : ZMod (principalDilogOrder d)) := by
      simpa only [C, Int.cast_mul, Int.cast_natCast, ZMod.natCast_zmod_val] using hp
    have hmod := (ZMod.intCast_eq_intCast_iff _ _ _).mp heq
    have hdiff : (principalDilogOrder d : ℤ) ∣ (z.val : ℤ) - C * p := hmod.dvd
    have h := dvd_add (dvd_trans hN hdiff) (dvd_mul_right C p)
    simpa only [C, sub_add_cancel] using h
  · intro hz
    refine ⟨(z.val : ℤ) / C, ?_⟩
    calc
      ((d * (d - 3) : ℕ) : ZMod (principalDilogOrder d)) *
          (((z.val : ℤ) / C) : ZMod (principalDilogOrder d)) =
        ((C * ((z.val : ℤ) / C) : ℤ) : ZMod (principalDilogOrder d)) := by
          simp [C]
      _ = z := by rw [Int.mul_ediv_cancel' hz]; simp

/-- **The kernel of `⟨g; ·⟩` on `G_d` is `H`**, the exactness of
`0 → H → G → ℤ/(M - 3)ℤ → 0` in the proof of [RW26, Radchenko, Wheeler (2026), Theorem 7,
`thm:ghostsic`]: for `x ∈ G_d`, `⟨g; x⟩ = 1` exactly when `x = d(d - 3)p` for some integer
point `p`. By `thetaBicharacter_eq_exp` with `(A_d - I)((1, 1)/(d - 3)) = (d(d - 1), d)`,
`⟨g; x⟩ = e((d(d - 1)x₂ - d x₁)/N)`, which is `1` when `d(d - 3) ∣ (d - 1)x₂ - x₁`; on `G_d`
this forces `d(d - 3) ∣ x₁` and `d(d - 3) ∣ x₂`. -/
theorem principalDilogBicharacter_generator_eq_one_iff (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    principalDilogBicharacter d (principalDilogGenerator d) x = 1 ↔
      ∃ p : IntPhaseSpace, principalDilogTorsion d p = x := by
  rw [principalDilogBicharacter_generator_eq_one_iff_dvd d hd hx,
    principalDilogGroup_pairing_dvd_iff_coords d hd hx]
  constructor
  · rintro ⟨h₀, h₁⟩
    obtain ⟨p₀, hp₀⟩ :=
      (principalDilogTorsion_coordinate_image_iff_dvd d hd (x 0)).mpr h₀
    obtain ⟨p₁, hp₁⟩ :=
      (principalDilogTorsion_coordinate_image_iff_dvd d hd (x 1)).mpr h₁
    refine ⟨![p₀, p₁], ?_⟩
    funext i
    fin_cases i
    · simpa [principalDilogTorsion] using hp₀
    · simpa [principalDilogTorsion] using hp₁
  · rintro ⟨p, hp⟩
    constructor
    · apply (principalDilogTorsion_coordinate_image_iff_dvd d hd (x 0)).mp
      exact ⟨p 0, by simpa [principalDilogTorsion] using congrFun hp 0⟩
    · apply (principalDilogTorsion_coordinate_image_iff_dvd d hd (x 1)).mp
      exact ⟨p 1, by simpa [principalDilogTorsion] using congrFun hp 1⟩

open scoped Classical in
/-- The geometric character average is supported on the torsion image; used in the group sum. -/
private theorem principalDilogGenerator_geometric_sum (d : ℕ) (hd : 3 < d)
    {x : Fin 2 → ZMod (principalDilogOrder d)} (hx : x ∈ principalDilogGroup d) :
    ∑ j ∈ Finset.range (d - 3),
        principalDilogBicharacter d (principalDilogGenerator d) x ^ j =
      if ∃ p : IntPhaseSpace, principalDilogTorsion d p = x then (d - 3 : ℕ) else 0 := by
  let ζ := principalDilogBicharacter d (principalDilogGenerator d) x
  have hpow : ζ ^ (d - 3) = 1 := principalDilogBicharacter_generator_pow d hd hx
  by_cases hζ : ζ = 1
  · have hp := (principalDilogBicharacter_generator_eq_one_iff d hd hx).mp hζ
    simp [hp, ζ, hζ]
  · have hsum : (∑ j ∈ Finset.range (d - 3), ζ ^ j) = 0 := by
      have hgeom : (∑ j ∈ Finset.range (d - 3), ζ ^ j) * (ζ - 1) = 0 := by
        simpa [hpow] using geom_sum_mul ζ (d - 3)
      exact (mul_eq_zero.mp hgeom).resolve_right (sub_ne_zero.mpr hζ)
    have hn := (principalDilogBicharacter_generator_eq_one_iff d hd hx).not.mp hζ
    simpa [hn, ζ] using hsum

open scoped Classical in
/-- Reindexing the torsion support by residue classes; used in the group average. -/
private theorem sum_principalDilogTorsion_support (d : RankOneDimension)
    [NeZero (principalDilogOrder d)]
    (f : (Fin 2 → ZMod (principalDilogOrder d)) → ℂ) :
    ∑ x : principalDilogGroup d,
        (if ∃ p : IntPhaseSpace, principalDilogTorsion d p = x.val then f x else 0) =
      ∑ c : PhaseSpaceMod d, f (principalDilogTorsionMod d c) := by
  classical
  let e : PhaseSpaceMod d → principalDilogGroup d :=
    fun c => ⟨principalDilogTorsionMod d c, principalDilogTorsionMod_mem d c⟩
  have he : Function.Injective e := by
    intro c c' h
    exact principalDilogTorsionMod_injective d (congrArg Subtype.val h)
  symm
  apply Fintype.sum_of_injective e he
    (fun c => f (principalDilogTorsionMod d c))
    (fun x => if ∃ p : IntPhaseSpace, principalDilogTorsion d p = x.val then f x else 0)
  · intro x hx
    have hn : ¬∃ p : IntPhaseSpace, principalDilogTorsion d p = x.val := by
      rintro ⟨p, hp⟩
      apply hx
      refine ⟨intPhaseSpaceMod d p, ?_⟩
      apply Subtype.ext
      exact (principalDilogTorsionMod_intPhaseSpaceMod d p).trans hp
    simp [hn]
  · intro c
    have hp : ∃ p : IntPhaseSpace,
        principalDilogTorsion d p = (e c).val :=
      ⟨(canonicalPhaseSpaceTransversal d).repr c, rfl⟩
    simp [e, hp]

/-- **Averaging over the characters of `G_d/H`**, the passage from the sum over `H` to the sum
over `G_d` in equation (40), `eq:sicmaintrick`, of the proof of
[RW26, Radchenko, Wheeler (2026), Theorem 7, `thm:ghostsic`]: for every `f : G_d → ℂ`,
`∑_{j=0}^{d-4} ∑_{x ∈ G_d} f(x) ⟨g; x⟩^j = (d - 3) ∑_{u ∈ H} f(u)`, the sum over `H` being
indexed by `(ℤ/dℤ)²` through `principalDilogTorsionMod`. The
inner geometric sum is `d - 3` on `H`, where `⟨g; x⟩ = 1`
(`principalDilogBicharacter_generator_eq_one_iff`), and `0` off `H`, where
`⟨g; x⟩ ≠ 1` is a root of unity of order dividing `d - 3`
(`principalDilogBicharacter_generator_pow`). -/
theorem sum_sum_mul_principalDilogBicharacter_pow (d : RankOneDimension)
    [NeZero (principalDilogOrder d)]
    (f : (Fin 2 → ZMod (principalDilogOrder d)) → ℂ) :
    ∑ j ∈ Finset.range (d - 3), ∑ x : principalDilogGroup d,
        f x * principalDilogBicharacter d (principalDilogGenerator d) x ^ j =
      ((d : ℂ) - 3) * ∑ c : PhaseSpaceMod d, f (principalDilogTorsionMod d c) := by
  classical
  have hcast : ((d - 3 : ℕ) : ℂ) = (d : ℂ) - 3 := by
    simp only [Nat.cast_sub (by omega : 3 ≤ (d : ℕ))]
    norm_num
  calc
    _ = ∑ x : principalDilogGroup d,
          f x * ∑ j ∈ Finset.range (d - 3),
            principalDilogBicharacter d (principalDilogGenerator d) x ^ j := by
          rw [Finset.sum_comm]
          congr 1
          ext x
          rw [Finset.mul_sum]
    _ = ∑ x : principalDilogGroup d,
          if ∃ p : IntPhaseSpace, principalDilogTorsion d p = x.val then
            ((d : ℂ) - 3) * f x else 0 := by
          apply Fintype.sum_congr _ _
          intro x
          rw [principalDilogGenerator_geometric_sum d d.property x.property]
          split_ifs <;> simp [hcast, mul_comm]
    _ = ((d : ℂ) - 3) * ∑ x : principalDilogGroup d,
          if ∃ p : IntPhaseSpace, principalDilogTorsion d p = x.val then f x else 0 := by
          rw [Finset.mul_sum]
          apply Fintype.sum_congr _ _
          intro x
          split_ifs <;> simp
    _ = _ := by rw [sum_principalDilogTorsion_support d f]

/-- **`|G_d| = N`** for the group `G = ℤ²/Λ` of [RW26, Radchenko, Wheeler (2026), Section 1]
at `γ = A_d`, where `N = |det(A_d - I)| = d²(d - 3)`. Specializes
`card_fixedCharacteristics`. -/
theorem card_principalDilogGroup (d : ℕ) (hd : 3 < d) [NeZero (principalDilogOrder d)] :
    Fintype.card (principalDilogGroup d) = principalDilogOrder d := by
  exact card_fixedCharacteristics (principalA d) (principalDilogOrder d)
    (det_principalA_sub_one d hd)

end SIC

end
