/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.Principal.Cocycle.ModularValues
import SICs.Dilogarithm.Group

/-!
# The Finite Group of the Principal Quantum Dilogarithm

The group `G_d` of order `N = d²(d - 3)` on which the finite quantum dilogarithm of `A_d` lives,
its `d`-torsion `H ≅ (ℤ/dℤ)²`, the generator `g` of `G_d/H ≅ ℤ/(d - 3)ℤ`, and the Gaussian and
bicharacter on it.

This module follows [RW26, Radchenko, Wheeler (2026), Section 1 and Section 4.4] at
`γ = A_d = U_d³`, whose trace is `N + 2` with `N = d²(d - 3)`. Radchenko and Wheeler's group is
`G = ℤ²/Λ`, `Λ = Nℤ² + ker(γ - 1)`; in the project's characteristic coordinates it is the kernel
`principalDilogGroup d` of `A_d - I` on `(ℤ/Nℤ)²` (`fixedCharacteristics`), the residue vectors
`m` with `A_d ∈ Γ_{m/N}` (`mem_principalDilogGroup_iff`). Their `M`-torsion subgroup
`H = (1/M)ℤ[ε]/ℤ[ε] ≅ (ℤ/Mℤ)²` is the image of the integer phase space under
`principalDilogTorsion`, `p ↦ d(d - 3)p`, which sends the class of `p` to the characteristic
`p/d` (`isIntegralIndex_principalDilogTorsion_sub`); it lies in `G_d` because
`A_d ≡ I (mod d)`. The quotient `G/H ≅ ℤ/(M - 3)ℤ` is generated by `(ε - 1)/(M - 3)`, which is
the characteristic `(1, 1)/(d - 3)` of `principalDilogGenerator`, the residue vector `d²(1, 1)`.

## The argument

The Gaussian `⟨x⟩ = χ_{x/N}(A_d)` and the bicharacter `⟨x; y⟩ = ⟨x + y⟩/(⟨x⟩⟨y⟩)` are Kopp's theta
multiplier `thetaCharacter` and its quotient `thetaBicharacter`, evaluated at the lifted
characteristics; they play the roles of the Gaussian and bicharacter of
[RW26, Radchenko, Wheeler (2026), Section 1]. Since both are `ℤ²`-periodic on `Γ_r`-characteristics
and the lift is additive up to `ℤ²`, they are well defined on `G_d` and the bicharacter is
additive in each argument.

The explicit torsion Gaussian `⟨p/d⟩ = ω_d^{Q_d(p)}` and torsion bicharacter
`⟨r;p/d⟩ = ω_d^{⟨p,(A_d-I)r⟩}` are the principal closed forms of Section 4.4.

The exact sequence `0 → H → G → ℤ/(M - 3)ℤ → 0` of the proof of
[RW26, Radchenko, Wheeler (2026), Theorem 7, `thm:ghostsic`], carried by the character
`⟨g; ·⟩` of `G_d`, and its consequences (the projection onto `H` by averaging and the order
`|G_d| = N`) are in `SICs.Principal.Dilogarithm.ExactSequence`.
-/

noncomputable section

open scoped MatrixGroups

namespace SIC

/-! ### The order and the group

`N = d²(d - 3) = tr A_d - 2`; `G_d` is the kernel of `A_d - I` on `(ℤ/Nℤ)²`. -/

/-- `d² (d - 3) = 0` in `ℤ/Nℤ`, since `N = d² (d - 3)` (`ZMod.natCast_self`). -/
theorem natCast_sq_mul_natCast_sub_three_eq_zero (d : ℕ) (hd : 3 < d) :
    (d : ZMod (principalDilogOrder d)) ^ 2 *
      ((d : ZMod (principalDilogOrder d)) - 3) = 0 := by
  calc
    _ = ((d ^ 2 * (d - 3) : ℕ) : ZMod (principalDilogOrder d)) := by
      rw [Nat.cast_mul, Nat.cast_pow, Nat.cast_sub (by omega : 3 ≤ d)]
      norm_num
    _ = 0 := ZMod.natCast_self _

/-- `N > 0` for `d > 3`. -/
theorem principalDilogOrder_pos (d : ℕ) (hd : 3 < d) : 0 < principalDilogOrder d := by
  unfold principalDilogOrder
  exact Nat.mul_pos (pow_pos (by omega) _) (by omega)

/-- The `NeZero` instance for a bare `d` with `3 < d`, to be brought into scope with `haveI`. -/
theorem principalDilogOrder_neZero (d : ℕ) (hd : 3 < d) :
    NeZero (principalDilogOrder d) :=
  ⟨(principalDilogOrder_pos d hd).ne'⟩

/-- The real cast of the group order is $N=d^2(d-3)$. -/
theorem cast_principalDilogOrder_eq (d : ℕ) (hd : 3 < d) :
    (principalDilogOrder d : ℝ) = (d : ℝ) ^ 2 * ((d : ℝ) - 3) := by
  simp only [principalDilogOrder, Nat.cast_mul, Nat.cast_pow,
    Nat.cast_sub (by omega : 3 ≤ d)]
  norm_num

/-- The principal unit $\varepsilon=\rho_d^3$ satisfies $(\varepsilon-1)^2=N\varepsilon$.
This is the trace identity `principalJacobiFactor_add_inv` in the group order notation. -/
theorem principalRoot_pow_three_sub_one_sq (d : ℕ) (hd : 3 < d) :
    (principalRoot d ^ 3 - 1) ^ 2 =
      (principalDilogOrder d : ℝ) * principalRoot d ^ 3 := by
  have hε : principalRoot d ^ 3 ≠ 0 :=
    pow_ne_zero 3 (ne_of_gt (principalRoot_pos d hd))
  have hsum := principalJacobiFactor_add_inv d hd
  rw [principalJacobiFactor_eq_principalRoot_pow_three d hd] at hsum
  rw [cast_principalDilogOrder_eq d hd]
  have hm := congrArg (fun x : ℝ => x * principalRoot d ^ 3) hsum
  rw [add_mul, inv_mul_cancel₀ hε] at hm
  nlinarith

/-- `√N = d √(d - 3)`. -/
theorem sqrt_principalDilogOrder (d : ℕ) (hd : 3 < d) :
    Real.sqrt (principalDilogOrder d) = (d : ℝ) * Real.sqrt ((d : ℝ) - 3) := by
  rw [cast_principalDilogOrder_eq d hd,
    Real.sqrt_mul (sq_nonneg (d : ℝ)), Real.sqrt_sq (Nat.cast_nonneg d)]

/-- `√N = d √(d - 3)` in `ℂ` (`sqrt_principalDilogOrder`). -/
theorem ofReal_sqrt_principalDilogOrder (d : ℕ) (hd : 3 < d) :
    ((Real.sqrt (principalDilogOrder d) : ℝ) : ℂ) =
      (d : ℂ) * ((Real.sqrt ((d : ℝ) - 3) : ℝ) : ℂ) := by
  exact_mod_cast sqrt_principalDilogOrder d hd

/-- **The group `G_d`** of [RW26, Radchenko, Wheeler (2026), Section 1] at `γ = A_d`: the residue
vectors `x ∈ (ℤ/Nℤ)²` whose characteristic `x/N` is fixed by `A_d` modulo `ℤ²`. Specializes
`fixedCharacteristics`; see the module docstring for the dictionary with `ℤ²/Λ`. -/
abbrev principalDilogGroup (d : ℕ) : AddSubgroup (Fin 2 → ZMod (principalDilogOrder d)) :=
  fixedCharacteristics (principalA d) (principalDilogOrder d)

/-- Membership in `G_d` is `A_d ∈ Γ_{x/N}` (`mem_fixedCharacteristics_iff`). -/
theorem mem_principalDilogGroup_iff (d : ℕ) (hd : 3 < d)
    (x : Fin 2 → ZMod (principalDilogOrder d)) :
    x ∈ principalDilogGroup d ↔
      principalA d ∈ gammaSubgroup (zmodCharacteristic (principalDilogOrder d) x) := by
  have : NeZero (principalDilogOrder d) := principalDilogOrder_neZero d hd
  exact mem_fixedCharacteristics_iff (principalA d) (principalDilogOrder d) x

/-- Membership in `G_d` in coordinates: `(A_d-I)x=0` in `(ℤ/Nℤ)²`. -/
theorem mem_principalDilogGroup_iff_coords (d : ℕ) (_hd : 3 < d)
    (x : Fin 2 → ZMod (principalDilogOrder d)) :
    x ∈ principalDilogGroup d ↔
      d * (d ^ 2 - 3 * d + 1) * x 0 - d * (d - 2) * x 1 = 0 ∧
        d * (d - 2) * x 0 - d * x 1 = 0 := by
  rw [mem_fixedCharacteristics_iff_mulVec]
  let v := (((principalA d : Mat(2, ℤ)) - 1).map
    (Int.castRingHom (ZMod (principalDilogOrder d)))).mulVec x
  have h₀ : v 0 = d * (d ^ 2 - 3 * d + 1) * x 0 - d * (d - 2) * x 1 := by
    simp [v, coe_principalA, Matrix.mulVec, dotProduct, Fin.sum_univ_two]
    ring
  have h₁ : v 1 = d * (d - 2) * x 0 - d * x 1 := by
    simp [v, coe_principalA, Matrix.mulVec, dotProduct, Fin.sum_univ_two]
    ring
  rw [← h₀, ← h₁]
  constructor
  · intro h
    exact ⟨congrFun h 0, congrFun h 1⟩
  · rintro ⟨h₀', h₁'⟩
    funext i
    fin_cases i
    · exact h₀'
    · exact h₁'

/-! ### The `d`-torsion `H`

The integer phase space maps onto the `d`-torsion of `G_d` by `p ↦ d(d - 3)p`, the residue
vector of the characteristic `p/d = d(d - 3)p/N`. -/

/-- **The `d`-torsion embedding** `p ↦ d(d - 3)·p ∈ (ℤ/Nℤ)²`, whose lifted characteristic is
`p/d` up to `ℤ²`: the subgroup `H = (1/M)ℤ[ε]/ℤ[ε] ≅ (ℤ/Mℤ)²` of
[RW26, Radchenko, Wheeler (2026), Section 4.4], indexed by the integer phase space of the
Weyl--Heisenberg displacements. It depends on `p` only modulo `d`
(`principalDilogTorsion_eq_iff`). -/
def principalDilogTorsion (d : ℕ) (p : IntPhaseSpace) : Fin 2 → ZMod (principalDilogOrder d) :=
  fun i => ((d * (d - 3) : ℕ) : ZMod (principalDilogOrder d)) * (p i : ZMod (principalDilogOrder d))

/-- The torsion embedding is additive. -/
theorem principalDilogTorsion_add (d : ℕ) (p q : IntPhaseSpace) :
    principalDilogTorsion d (p + q) = principalDilogTorsion d p + principalDilogTorsion d q := by
  funext i
  simp [principalDilogTorsion, Pi.add_apply, mul_add]

/-- The torsion embedding commutes with negation. -/
theorem principalDilogTorsion_neg (d : ℕ) (p : IntPhaseSpace) :
    principalDilogTorsion d (-p) = -principalDilogTorsion d p := by
  funext i
  simp [principalDilogTorsion, Pi.neg_apply]

/-- The torsion embedding is subtractive. -/
theorem principalDilogTorsion_sub (d : ℕ) (p q : IntPhaseSpace) :
    principalDilogTorsion d (p - q) =
      principalDilogTorsion d p - principalDilogTorsion d q := by
  rw [sub_eq_add_neg, principalDilogTorsion_add, principalDilogTorsion_neg, sub_eq_add_neg]

/-- The torsion embedding sends the origin to `0`. -/
@[simp]
theorem principalDilogTorsion_zero (d : ℕ) : principalDilogTorsion d 0 = 0 := by
  funext i
  simp [principalDilogTorsion]

/-- Coordinate cancellation for `principalDilogTorsion_eq_iff`. -/
private theorem principalDilogTorsion_coordinate_eq_iff (d : ℕ) (hd : 3 < d) (p q : ℤ) :
    ((d * (d - 3) : ℕ) : ZMod (principalDilogOrder d)) *
        (p : ZMod (principalDilogOrder d)) =
      ((d * (d - 3) : ℕ) : ZMod (principalDilogOrder d)) *
        (q : ZMod (principalDilogOrder d)) ↔ (p : ZMod d) = (q : ZMod d) := by
  let C : ℤ := (d * (d - 3) : ℕ)
  suffices h : ((C * p : ℤ) : ZMod (principalDilogOrder d)) =
      ((C * q : ℤ) : ZMod (principalDilogOrder d)) ↔
        (p : ZMod d) = (q : ZMod d) by
    simpa only [C, Int.cast_natCast, Int.cast_mul] using h
  rw [ZMod.intCast_eq_intCast_iff, ZMod.intCast_eq_intCast_iff,
    Int.modEq_iff_dvd, Int.modEq_iff_dvd]
  have hc : C ≠ 0 := by
    dsimp [C]
    exact_mod_cast (Nat.mul_pos (by omega : 0 < d) (by omega : 0 < d - 3)).ne'
  have hn : (principalDilogOrder d : ℤ) =
      C * d := by
    dsimp [C]
    simp only [principalDilogOrder, Nat.cast_mul, Nat.cast_pow]
    ring
  rw [hn, ← mul_sub]
  exact Int.mul_dvd_mul_iff_left hc

/-- **The torsion embedding is injective modulo `d`**: `d(d - 3)p ≡ d(d - 3)q (mod N)` exactly
when `p ≡ q (mod d)`. -/
theorem principalDilogTorsion_eq_iff (d : ℕ) (hd : 3 < d) (p q : IntPhaseSpace) :
    principalDilogTorsion d p = principalDilogTorsion d q ↔
      intPhaseSpaceMod d p = intPhaseSpaceMod d q := by
  simp only [funext_iff, principalDilogTorsion, intPhaseSpaceMod,
    principalDilogTorsion_coordinate_eq_iff d hd]

/-- `d(d - 3)p = 0` in `G_d` exactly when `p ≡ 0 (mod d)`
(`principalDilogTorsion_eq_iff` at `q = 0`). -/
theorem principalDilogTorsion_eq_zero_iff (d : ℕ) (hd : 3 < d) (p : IntPhaseSpace) :
    principalDilogTorsion d p = 0 ↔ intPhaseSpaceMod d p = 0 := by
  have hzero : intPhaseSpaceMod d (0 : IntPhaseSpace) = 0 := by
    funext i
    simp [intPhaseSpaceMod]
  simpa only [principalDilogTorsion_zero, hzero] using
    principalDilogTorsion_eq_iff d hd p 0

/-- The lifted characteristic of `d(d - 3)p` is `p/d` up to `ℤ²`. -/
theorem isIntegralIndex_principalDilogTorsion_sub (d : ℕ) (hd : 3 < d)
    (p : IntPhaseSpace) :
    IsIntegralIndex
      (zmodCharacteristic (principalDilogOrder d) (principalDilogTorsion d p) -
        shiftRationalPoint d p) := by
  have : NeZero (principalDilogOrder d) := principalDilogOrder_neZero d hd
  have hp : principalDilogTorsion d p =
      fun i => (((d * (d - 3) : ℕ) : ℤ) * p i : ZMod (principalDilogOrder d)) := by
    funext i
    simp [principalDilogTorsion]
  have hden : (principalDilogOrder d : ℚ) = (d : ℚ) * (d - 3) * d := by
    simp only [principalDilogOrder, Nat.cast_mul, Nat.cast_pow,
      Nat.cast_sub (by omega : 3 ≤ d)]
    ring
  have hq : (fun i : Fin 2 =>
      ((((d * (d - 3) : ℕ) : ℤ) * p i : ℤ) : ℚ) / principalDilogOrder d) =
      shiftRationalPoint d p := by
    funext i
    simp only [shiftRationalPoint, Int.cast_mul, Int.cast_natCast,
      Nat.cast_mul, Nat.cast_sub (by omega : 3 ≤ d)]
    rw [hden]
    have hdq : (d : ℚ) ≠ 0 := by exact_mod_cast (by omega : d ≠ 0)
    have h3q : (d : ℚ) - 3 ≠ 0 := by exact_mod_cast (by omega : (d : ℤ) - 3 ≠ 0)
    have h3q' : -3 + (d : ℚ) ≠ 0 := by simpa [sub_eq_add_neg, add_comm] using h3q
    field_simp [hdq, h3q, h3q']
    push_cast
    ring
  rw [hp, ← hq]
  simpa using (isIntegralIndex_zmodCharacteristic_intCast_sub
    (principalDilogOrder d) (fun i => ((d * (d - 3) : ℕ) : ℤ) * p i))

/-- **`H ⊆ G_d`**: `A_d ≡ I (mod d)` (`principalA_mem_Gamma`), so `(A_d - I)(d(d - 3)p) ≡ 0
(mod N)`. -/
theorem principalDilogTorsion_mem (d : ℕ) (hd : 3 < d) (p : IntPhaseSpace) :
    principalDilogTorsion d p ∈ principalDilogGroup d := by
  have hshift : principalA d ∈ gammaSubgroup (shiftRationalPoint d p) :=
    mem_gammaSubgroup_of_mem_Gamma (principalA_mem_Gamma d)
      (exists_intCast_mul_shiftRationalPoint d p)
  exact (mem_principalDilogGroup_iff d hd _).mpr
    (mem_gammaSubgroup_of_isIntegralIndex_sub
      (isIntegralIndex_principalDilogTorsion_sub d hd p) hshift)

/-- **`H` indexed by `(ℤ/dℤ)²`**: `principalDilogTorsion` at the canonical representative of a
residue class, the map through which `principalDilogTorsion` factors
(`principalDilogTorsionMod_intPhaseSpaceMod`). It indexes the sums over `H` of the proof of
[RW26, Radchenko, Wheeler (2026), Theorem 7, `thm:ghostsic`]. -/
def principalDilogTorsionMod (d : ℕ) [NeZero d] (c : PhaseSpaceMod d) :
    Fin 2 → ZMod (principalDilogOrder d) :=
  principalDilogTorsion d ((canonicalPhaseSpaceTransversal d).repr c)

/-- `principalDilogTorsion` factors through the residue class (`principalDilogTorsion_eq_iff`). -/
theorem principalDilogTorsionMod_intPhaseSpaceMod (d : RankOneDimension)
    (p : IntPhaseSpace) :
    principalDilogTorsionMod d (intPhaseSpaceMod d p) = principalDilogTorsion d p := by
  apply (principalDilogTorsion_eq_iff d d.property _ _).mpr
  exact (canonicalPhaseSpaceTransversal d).residue_repr _

/-- The class `0` maps to `0`. -/
@[simp]
theorem principalDilogTorsionMod_zero (d : ℕ) [NeZero d] : principalDilogTorsionMod d 0 = 0 := by
  simp [principalDilogTorsionMod, canonicalPhaseSpaceTransversal_repr_zero]

/-- The indexing of `H` is injective (`principalDilogTorsion_eq_iff`). -/
theorem principalDilogTorsionMod_injective (d : RankOneDimension) :
    Function.Injective (principalDilogTorsionMod d) := by
  intro c c' h
  have h' := (principalDilogTorsion_eq_iff d d.property
    ((canonicalPhaseSpaceTransversal d).repr c)
    ((canonicalPhaseSpaceTransversal d).repr c')).mp h
  simpa only [(canonicalPhaseSpaceTransversal d).residue_repr] using h'

/-- `H ⊆ G_d` in the residue indexing (`principalDilogTorsion_mem`). -/
theorem principalDilogTorsionMod_mem (d : RankOneDimension) (c : PhaseSpaceMod d) :
    principalDilogTorsionMod d c ∈ principalDilogGroup d :=
  principalDilogTorsion_mem d d.property _

/-! ### The generator of `G_d/H`

The residue vector `d²(1, 1)`, with characteristic `(1, 1)/(d - 3)`, is
`(ε - 1)/(M - 3)` of [RW26, Radchenko, Wheeler (2026), proof of Theorem 7, `thm:ghostsic`]:
`⟨⟨(1, 1)/(d - 3), ρ_d⟩⟩ = (ρ_d - 1)/(d - 3)`. -/

/-- **The generator `g` of `G_d/H`**: the residue vector `d²(1, 1) ∈ (ℤ/Nℤ)²`, the
characteristic `(1, 1)/(d - 3)` whose fractional symplectic form at `ρ_d` is
`(ε - 1)/(M - 3)`, the generator of `A ≅ ℤ/(M - 3)ℤ` in the proof of
[RW26, Radchenko, Wheeler (2026), Theorem 7, `thm:ghostsic`]. -/
def principalDilogGenerator (d : ℕ) : Fin 2 → ZMod (principalDilogOrder d) :=
  fun _ => ((d ^ 2 : ℕ) : ZMod (principalDilogOrder d))

/-- The lifted characteristic of `g` is `(1, 1)/(d - 3)` up to `ℤ²`. -/
theorem isIntegralIndex_principalDilogGenerator_sub (d : ℕ) (hd : 3 < d) :
    IsIntegralIndex
      (zmodCharacteristic (principalDilogOrder d) (principalDilogGenerator d) -
        fun _ => 1 / ((d : ℚ) - 3)) := by
  have : NeZero (principalDilogOrder d) := principalDilogOrder_neZero d hd
  have hg : principalDilogGenerator d =
      fun _ : Fin 2 => ((d ^ 2 : ℕ) : ZMod (principalDilogOrder d)) := rfl
  have hq : (fun _ : Fin 2 => ((d ^ 2 : ℕ) : ℚ) / principalDilogOrder d) =
      fun _ => 1 / ((d : ℚ) - 3) := by
    funext i
    simp only [principalDilogOrder, Nat.cast_mul, Nat.cast_pow,
      Nat.cast_sub (by omega : 3 ≤ d)]
    have hdq : (d : ℚ) ≠ 0 := by exact_mod_cast (by omega : d ≠ 0)
    have h3q : (d : ℚ) - 3 ≠ 0 := by exact_mod_cast (by omega : (d : ℤ) - 3 ≠ 0)
    have h3q' : -3 + (d : ℚ) ≠ 0 := by simpa [sub_eq_add_neg, add_comm] using h3q
    field_simp [hdq, h3q, h3q']
    ring
  rw [hg, ← hq]
  convert (isIntegralIndex_zmodCharacteristic_intCast_sub
    (principalDilogOrder d) (fun _ : Fin 2 => (d ^ 2 : ℤ))) using 1
  funext i
  simp

/-- `(A_d - I)((1, 1)/(d - 3)) = (d(d - 1), d)`: the integral action of `A_d` on the rational
generator, used by `principalDilogGenerator_mem` and by the character kernel calculation of
`SICs.Principal.Dilogarithm.ExactSequence`. -/
theorem principalA_generator_witnesses (d : ℕ) (hd : 3 < d) :
    (((principalA d 0 0 : ℤ) : ℚ) - 1) * (1 / ((d : ℚ) - 3)) +
        ((principalA d 0 1 : ℤ) : ℚ) * (1 / ((d : ℚ) - 3)) =
        ((d : ℤ) * ((d : ℤ) - 1) : ℚ) ∧
      ((principalA d 1 0 : ℤ) : ℚ) * (1 / ((d : ℚ) - 3)) +
        (((principalA d 1 1 : ℤ) : ℚ) - 1) * (1 / ((d : ℚ) - 3)) =
        (d : ℚ) := by
  have h3 : (d : ℚ) - 3 ≠ 0 := by exact_mod_cast (by omega : (d : ℤ) - 3 ≠ 0)
  constructor
  · norm_num [coe_principalA, Matrix.cons_val_zero, Matrix.cons_val_one]
    field_simp [h3]
    ring
  · norm_num [coe_principalA, Matrix.cons_val_zero, Matrix.cons_val_one]
    field_simp [h3]
    ring

/-- `A_d ∈ Γ_{(1, 1)/(d - 3)}`: the rational generator belongs to the characteristic subgroup,
by `principalA_generator_witnesses`. -/
theorem principalA_mem_gamma_generator (d : ℕ) (hd : 3 < d) :
    principalA d ∈ gammaSubgroup (fun _ : Fin 2 => 1 / ((d : ℚ) - 3)) := by
  obtain ⟨h₁, h₂⟩ := principalA_generator_witnesses d hd
  intro i
  fin_cases i
  · exact ⟨(d : ℤ) * ((d : ℤ) - 1), by
      simpa [Fin.sum_univ_two] using h₁⟩
  · exact ⟨d, by
      simpa [Fin.sum_univ_two] using h₂⟩

/-- **`g ∈ G_d`**: `(A_d - I)(1, 1) = d(d - 3)(d - 1, 1)`, so `(A_d - I)(d²(1, 1)) ≡ 0 (mod N)`. -/
theorem principalDilogGenerator_mem (d : ℕ) (hd : 3 < d) :
    principalDilogGenerator d ∈ principalDilogGroup d := by
  exact (mem_principalDilogGroup_iff d hd _).mpr
    (mem_gammaSubgroup_of_isIntegralIndex_sub
      (isIntegralIndex_principalDilogGenerator_sub d hd)
      (principalA_mem_gamma_generator d hd))

/-- `(d - 3)·g = 0` in `(ℤ/Nℤ)²`, since `(d - 3)d² = N`. -/
theorem principalDilogGenerator_nsmul (d : ℕ) :
    (d - 3) • principalDilogGenerator d = 0 := by
  funext i
  simp only [Pi.smul_apply, principalDilogGenerator, Pi.zero_apply, nsmul_eq_mul]
  rw [← Nat.cast_mul, show (d - 3) * d ^ 2 = principalDilogOrder d by
    simp [principalDilogOrder, mul_comm]]
  exact ZMod.natCast_self _

/-! ### The Gaussian and the bicharacter on `G_d`

Kopp's theta multiplier at the lifted characteristic, and its quotient. Both descend to `G_d`
because they are `ℤ²`-periodic on `Γ_r`-characteristics. -/

/-- **The Gaussian `⟨x⟩`** of [RW26, Radchenko, Wheeler (2026), Section 1] on `G_d`: Kopp's theta
multiplier `χ_{x/N}(A_d)` (`thetaCharacter`) at the lifted characteristic. Radchenko and Wheeler
write it as `(-1)^{u₁+u₂+u₁u₂} e_{2N}(ω(uγ, u))`; that comparison is not formalized.
Specializes `fixedGaussian`. -/
abbrev principalDilogGaussian (d : ℕ) (x : Fin 2 → ZMod (principalDilogOrder d)) : ℂ :=
  fixedGaussian (principalA d) (principalDilogOrder d) x

/-- **The bicharacter `⟨x; y⟩ = ⟨x + y⟩/(⟨x⟩⟨y⟩)`** of [RW26, Radchenko, Wheeler (2026), Section 1]
on `G_d`: `thetaBicharacter` at the lifted characteristics. Specializes `fixedBicharacter`. -/
abbrev principalDilogBicharacter (d : ℕ) (x y : Fin 2 → ZMod (principalDilogOrder d)) : ℂ :=
  fixedBicharacter (principalA d) (principalDilogOrder d) x y

/-- **The metric group `G_d`**: `G_d` with the Gaussian `⟨x⟩` and `s = √N` of
[RW26, Radchenko, Wheeler (2026), Section 4.3, `prop:rqffinitedilog`] at `γ = A_d`. Specializes
`fixedMetricGroup`. -/
abbrev principalDilogMetricGroup (d : ℕ) (hd : 3 < d) [NeZero (principalDilogOrder d)] :
    MetricGroup (principalDilogGroup d) ℂ :=
  fixedMetricGroup (principalA d) (principalDilogOrder d) (det_principalA_sub_one d hd)

/-- **The Gaussian on the `d`-torsion**: `⟨d(d - 3)p⟩ = χ_{p/d}(A_d)`, the character at the
characteristic `p/d`, since the lift of `d(d - 3)p` is `p/d` up to `ℤ²`
(`isIntegralIndex_principalDilogTorsion_sub`,
`thetaCharacter_add_of_isIntegralIndex`); its closed form `ω_d^{Q_d(p)}` is
`thetaCharacter_shiftRationalPoint_principalA`. -/
theorem principalDilogGaussian_principalDilogTorsion (d : ℕ) (hd : 3 < d) (p : IntPhaseSpace) :
    principalDilogGaussian d (principalDilogTorsion d p) =
      thetaCharacter (shiftRationalPoint d p) (principalA d : Mat(2, ℤ)) := by
  let r := shiftRationalPoint d p
  let t := zmodCharacteristic (principalDilogOrder d) (principalDilogTorsion d p)
  have hr : principalA d ∈ gammaSubgroup r :=
    principalA_mem_gammaSubgroup_shiftRationalPoint d hd p
  have he : IsIntegralIndex (t - r) :=
    isIntegralIndex_principalDilogTorsion_sub d hd p
  have hindex : r + (t - r) = t := by abel
  change thetaCharacter t _ = thetaCharacter r _
  rw [← hindex, thetaCharacter_add_of_isIntegralIndex (principalA d) hr he]

/-! ### The Gaussian on `H`

`⟨p/d⟩ = χ_{p/d}(A_d) = ω_d^{Q_d(p)}`. -/

/-- The numerator in the principal Gaussian exponent differs from the principal form by an
even integer. This is the parity calculation used by
`thetaCharacter_shiftRationalPoint_principalA`. -/
private theorem principalGaussian_parity (d x y : ℤ) :
    Even (((d ^ 2 - 3 * d + 1) * x - (d - 2) * y) + ((d - 2) * x - y) +
      ((d ^ 2 - 3 * d + 1) * x - (d - 2) * y) * ((d - 2) * x - y) -
      (x ^ 2 + (1 - d) * x * y + y ^ 2)) := by
  rcases Int.even_or_odd d with ⟨a, ha⟩ | ⟨a, ha⟩ <;>
    rcases Int.even_or_odd x with ⟨b, hb⟩ | ⟨b, hb⟩ <;>
    rcases Int.even_or_odd y with ⟨c, hc⟩ | ⟨c, hc⟩ <;>
    rw [ha, hb, hc, even_iff_two_dvd] <;>
    ring_nf <;>
    omega

/-- The exponential in Kopp's formula at `p/d` is the principal form's root of unity. This
serves `thetaCharacter_shiftRationalPoint_principalA`. -/
private theorem principalGaussian_exp_eq (d : ℕ) [NeZero d] (p : IntPhaseSpace)
    (a b q : ℤ)
    (ha : a = ((d : ℤ) ^ 2 - 3 * d + 1) * p 0 - ((d : ℤ) - 2) * p 1)
    (hb : b = ((d : ℤ) - 2) * p 0 - p 1)
    (hq : q = (p 0) ^ 2 + (1 - (d : ℤ)) * p 0 * p 1 + (p 1) ^ 2) :
    Complex.exp (2 * (Real.pi : ℂ) * Complex.I *
      ((((a : ℚ) + b + a * b + a * ((p 1 : ℚ) / d) -
        b * ((p 0 : ℚ) / d)) / 2 : ℚ) : ℂ)) = standardRoot d ^ q := by
  have hdq : (d : ℚ) ≠ 0 := by exact_mod_cast (NeZero.ne d)
  have hpar : Even (a + b + a * b - q) := by
    rw [ha, hb, hq]
    exact principalGaussian_parity (d : ℤ) (p 0) (p 1)
  obtain ⟨n, hn⟩ := hpar
  have hfrac : a * p 1 - b * p 0 = (2 - (d : ℤ)) * q := by
    rw [ha, hb, hq]
    ring
  have hex : ((a : ℚ) + b + a * b + a * ((p 1 : ℚ) / d) -
      b * ((p 0 : ℚ) / d)) / 2 = (q : ℚ) / d + n := by
    have hnq : (a : ℚ) + b + a * b - q = (n : ℚ) + n := by
      exact_mod_cast hn
    have hfq : (a : ℚ) * p 1 - b * p 0 = (2 - (d : ℚ)) * q := by
      exact_mod_cast hfrac
    field_simp
    linear_combination (d : ℚ) * hnq + hfq
  rw [standardRoot, ← Complex.exp_int_mul]
  apply Complex.exp_eq_exp_iff_exists_int.mpr
  refine ⟨n, ?_⟩
  rw [hex]
  push_cast
  ring

/-- **The Gaussian on the `d`-torsion**, the first display of
[RW26, Radchenko, Wheeler (2026), Section 4.4]: `⟨p/d⟩ = χ_{p/d}(A_d) = ω_d^{Q_d(p)}` with
`Q_d(p) = p₁² + (1 - d)p₁p₂ + p₂²`, their `e_M(k² - kl + l²)` at `(k, l) = (p₂, -p₁)`. From
`thetaCharacter_eq_exp` with `(A_d - I)(p/d) = ((A_d - I)/d) p`. -/
theorem thetaCharacter_shiftRationalPoint_principalA (d : ℕ) [NeZero d]
    (p : IntPhaseSpace) :
    thetaCharacter (shiftRationalPoint d p) (principalA d : Mat(2, ℤ)) =
      standardRoot d ^ (principalOneSICForm d).eval (p 0) (p 1) := by
  let a : ℤ := ((d : ℤ) ^ 2 - 3 * d + 1) * p 0 - ((d : ℤ) - 2) * p 1
  let b : ℤ := ((d : ℤ) - 2) * p 0 - p 1
  let q : ℤ := (principalOneSICForm d).eval (p 0) (p 1)
  have hdq : (d : ℚ) ≠ 0 := by exact_mod_cast (NeZero.ne d)
  have ha : ((principalA d 0 0 : ℚ) - 1) * (shiftRationalPoint d p) 0 +
      (principalA d 0 1 : ℚ) * (shiftRationalPoint d p) 1 = (a : ℚ) := by
    simp only [shiftRationalPoint_eq_cons, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_fin_one]
    simp [coe_principalA, a]
    field_simp
    ring
  have hb : (principalA d 1 0 : ℚ) * (shiftRationalPoint d p) 0 +
      ((principalA d 1 1 : ℚ) - 1) * (shiftRationalPoint d p) 1 = (b : ℚ) := by
    simp only [shiftRationalPoint_eq_cons, Matrix.cons_val_zero, Matrix.cons_val_one,
      Matrix.cons_val_fin_one]
    simp [coe_principalA, b]
    field_simp
    ring
  have hq : q = (p 0) ^ 2 + (1 - (d : ℤ)) * p 0 * p 1 + (p 1) ^ 2 := by
    simp [q, principalOneSICForm, BinaryQF.eval]
  rw [thetaCharacter_eq_exp (principalA d) ha hb]
  simp only [shiftRationalPoint_eq_cons, Matrix.cons_val_zero, Matrix.cons_val_one,
    Matrix.cons_val_fin_one]
  exact principalGaussian_exp_eq d p a b q rfl rfl hq

/-- The principal character at `p/d` depends only on `p mod d`.
Specializes `thetaCharacter_div_natCast_congr`. -/
theorem thetaCharacter_shiftRationalPoint_principalA_congr (d : RankOneDimension)
    {p p' : IntPhaseSpace} (h : intPhaseSpaceMod d p' = intPhaseSpaceMod d p) :
    thetaCharacter (shiftRationalPoint d p') (principalA d : Mat(2, ℤ)) =
      thetaCharacter (shiftRationalPoint d p) (principalA d : Mat(2, ℤ)) := by
  have hp := principalA_mem_gammaSubgroup_shiftRationalPoint d d.property p
  have hcoords : ∀ i, (p' i : ZMod d) = (p i : ZMod d) := by
    intro i
    exact congrFun h i
  exact thetaCharacter_div_natCast_congr (principalA d) d hp hcoords

/-! ### The bicharacter on `G_d × H`

`⟨r; p/d⟩ = ω_d^{⟨p, (A_d - I)r⟩}`. -/

/-- The principal torsion bicharacter is `⟨r;p/d⟩ = ω_d^{⟨p,k⟩}` for
`(A_d-I)r=k` and `⟨p,k⟩=p₂k₁-p₁k₂` [RW26, Radchenko, Wheeler (2026), Section 4.4].
Specializes `thetaBicharacter_div_natCast`. -/
theorem thetaBicharacter_shiftRationalPoint_principalA (d : RankOneDimension)
    {r : Fin 2 → ℚ} {k : IntPhaseSpace}
    (hk : ∀ i, ratVecAction (principalA d : Mat(2, ℤ)) r i - r i = (k i : ℚ))
    (p : IntPhaseSpace) :
    thetaBicharacter r (shiftRationalPoint d p) (principalA d : Mat(2, ℤ)) =
      standardRoot d ^ intSymplecticForm p k := by
  have hp := principalA_mem_gammaSubgroup_shiftRationalPoint d d.property p
  have h := thetaBicharacter_div_natCast (principalA d) d hk p hp
  change thetaBicharacter r (shiftRationalPoint d p)
    (principalA d : Mat(2, ℤ)) = _ at h
  rw [h]
  rw [standardRoot, ← Complex.exp_int_mul]
  congr 1
  push_cast
  unfold intSymplecticForm
  push_cast
  ring

end SIC

end
