/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.ClassField.Density.Splitting

/-!
# Frobenius elements at primes of absolute degree one

In every finite Galois extension, Frobenius elements at primes of absolute degree one outside
any finite set generate the Galois group, so an integral element congruent to its `N𝔭`-th power
at almost all of them lies in the base field; in a finite abelian extension, every element of
order at most two is such a Frobenius element.

This module follows Milne, *Class Field Theory*, version 4.03 (2020), Chapter VI, the proof of
Corollary 3.8 with the primes restricted by Corollary 3.3, and the order-two case of
Exercise A-10 with its solution, adapted from cyclic to abelian extensions. It supplies prime
inputs for the reciprocity argument. Unlike
`closure_frobenius_outside_eq_top`, the generation theorem needs no solvability, and it uses
primes of absolute degree one only.

## The argument

If all but finitely many primes of absolute degree one split completely in $L$, the set of such
primes has density one and also, up to a finite set, density $1/[L:K]$
(`hasPrimeDensity_splitsCompletely`); so $[L:K]=1$.

For generation, let $H$ be the subgroup generated by the Frobenius elements at the primes of $L$
above primes of absolute degree one outside $S$. Conjugation permutes these elements, so $H$ is
normal and its fixed field $E$ is Galois over $K$. At a prime of absolute degree one outside $S$
and unramified in $L$, Frobenius lies in $H$, so its restriction to $E$ (Frobenius of $E/K$) is
trivial and the prime splits completely in $E$. Hence $E=K$ and $H$ is the whole group.

For $b$ with $b^2=1$ in an abelian extension, let $E$ be the fixed field of $\langle b\rangle$.
The unramified primes of absolute degree one splitting completely in $E$ have density
$|\langle b\rangle|/[L:K]$, and those splitting completely in $L$ have density $1/[L:K]$.
If $b\ne1$, the difference has density $1/[L:K]>0$ and is infinite. At such a prime,
Frobenius restricts trivially to $E$, so it lies in $\langle b\rangle=\{1,b\}$, and it is not
$1$ since the prime does not split in $L$; so it is $b$. If $b=1$, the completely split primes
themselves are infinite and have trivial Frobenius.

For the congruence criterion, the residue field at a prime $w$ of absolute degree one has $p$
elements, so the identity is a Frobenius element there and the prime below also has norm $p$.
If $z\in\mathcal O_L$ satisfies $z^{N\mathfrak p}\equiv z\pmod w$ at such primes outside a
finite set, the Frobenius element $\sigma_w$ gives $\sigma_wz\equiv z$. Each nonzero $gz-z$ lies
in finitely many primes; outside them $\sigma_wz=z$, and generation gives $gz=z$ for every $g$.
-/

namespace SIC

open NumberField IsDedekindDomain

variable {K : Type*} [Field K] [NumberField K] {L : Type*} [Field L] [NumberField L]
  [Algebra K L]

/-! ### Splitting at almost all primes of absolute degree one -/

/-- If all but finitely many primes of absolute degree one of $K$ split completely in a finite
Galois extension $L$, then $L=K$. Milne, *Class Field Theory*, Chapter VI, Theorem 3.4, as used
in the proof of Corollary 3.8. -/
private theorem finrank_eq_one_of_splitsCompletely [IsGalois K L]
    (h : {v : HeightOneSpectrum (𝓞 K) |
      (Ideal.absNorm v.asIdeal).Prime ∧ ¬ FinitePlace.SplitsCompletely L v}.Finite) :
    Module.finrank K L = 1 := by
  let D : Set (HeightOneSpectrum (𝓞 K)) :=
    {v | (Ideal.absNorm v.asIdeal).Prime}
  let T : Set (HeightOneSpectrum (𝓞 K)) :=
    {v | (Ideal.absNorm v.asIdeal).Prime ∧ ¬ FinitePlace.SplitsCompletely L v}
  have hTD : T ⊆ D := fun _ hv => hv.1
  have hsplit : D \ T = {v | (Ideal.absNorm v.asIdeal).Prime ∧
      FinitePlace.SplitsCompletely L v} := by
    ext v
    simp only [D, T, Set.mem_sdiff, Set.mem_ofPred_eq]
    tauto
  have hden : HasPrimeDensity (D \ T) 1 := by
    apply (hasPrimeDensity_degreeOne (K := K)).congr_finite
    · change T.Finite at h
      change (D \ (D \ T)).Finite
      rwa [Set.sdiff_sdiff_cancel_left hTD]
    · have he : (D \ T) \ D = ∅ := Set.sdiff_eq_empty.mpr Set.sdiff_subset
      rw [he]
      exact Set.finite_empty
  have hinv : (1 : ℝ) = (Module.finrank K L : ℝ)⁻¹ := by
    rw [hsplit] at hden
    exact hden.unique (hasPrimeDensity_splitsCompletely L)
  exact_mod_cast (inv_eq_one.mp hinv.symm)

/-! ### Generation and elements of order two -/

/-- Outside the excluded and ramified primes, a subgroup containing the degree-one Frobenius
elements has a fixed field in which every degree-one prime splits. This is the fixed-field step
in Milne, *Class Field Theory*, Chapter VI, proof of Corollary 3.8. -/
private theorem fixedField_splits_degreeOne_outside [IsGalois K L]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (H : Subgroup (L ≃ₐ[K] L)) [H.Normal]
    (hH : ∀ (g : L ≃ₐ[K] L) (Q : HeightOneSpectrum (𝓞 L)),
      FinitePlace.below (K := K) Q ∉ S →
      (Ideal.absNorm (FinitePlace.below (K := K) Q).asIdeal).Prime →
      IsFrobeniusAt K L g (FinitePlace.below (K := K) Q).asIdeal Q.asIdeal → g ∈ H)
    (v : HeightOneSpectrum (𝓞 K)) (hvS : v ∉ S)
    (hvprime : (Ideal.absNorm v.asIdeal).Prime)
    (hvram : v ∉ FinitePlace.ramifiedSet K L) :
    FinitePlace.SplitsCompletely (IntermediateField.fixedField H) v := by
  let E := IntermediateField.fixedField H
  have : IsGalois K E := IsGalois.of_fixedField_normal_subgroup H
  obtain ⟨q⟩ := (inferInstance : Nonempty (FinitePlace.PrimeAbove (L := L) v))
  let Q := FinitePlace.PrimeAbove.place v q
  have hbelow : FinitePlace.below (K := K) Q = v :=
    FinitePlace.below_eq_of_liesOver v Q
  obtain ⟨g, hg⟩ :=
    exists_isFrobeniusAt (K := K) (H := L) v.asIdeal Q.asIdeal v.ne_bot
  have hgH : g ∈ H := hH g Q (by simpa only [hbelow] using hvS)
    (by simpa only [hbelow] using hvprime) (by simpa only [hbelow] using hg)
  have hres : g.restrictNormal E = 1 :=
    (AlgEquiv.restrictNormal_eq_one_iff E g).mpr
      (fun x hx => (IntermediateField.mem_fixedField_iff H x).mp hx g hgH)
  exact (hg.restrictNormal_eq_one_iff_splitsCompletely E
    (FinitePlace.ramificationIdx_eq_one_of_notMem_ramifiedSet Q
      (by simpa only [hbelow] using hvram))).mp hres

/-- **Frobenius generation at primes of absolute degree one.** For a finite Galois extension
$L/K$ and a finite set $S$ of primes of $K$, the Frobenius elements at the primes of $L$ above
primes of absolute degree one outside $S$ generate $\operatorname{Gal}(L/K)$. Milne, *Class
Field Theory*, Chapter VI, proof of Corollary 3.8, with the primes restricted by
Corollary 3.3. -/
theorem closure_degreeOne_frobenius_eq_top [IsGalois K L]
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Subgroup.closure {g : L ≃ₐ[K] L | ∃ w : HeightOneSpectrum (𝓞 L),
      FinitePlace.below (K := K) w ∉ S ∧
        (Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal).Prime ∧
          IsFrobeniusAt K L g (FinitePlace.below (K := K) w).asIdeal w.asIdeal} = ⊤ := by
  classical
  let H : Subgroup (L ≃ₐ[K] L) := Subgroup.closure {g | ∃ w : HeightOneSpectrum (𝓞 L),
    (FinitePlace.below (K := K) w ∉ S ∧
      (Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal).Prime) ∧
        IsFrobeniusAt K L g (FinitePlace.below (K := K) w).asIdeal w.asIdeal}
  have : H.Normal := closure_isFrobeniusAt_normal
    (K := K) (H := L) (fun v => v ∉ S ∧ (Ideal.absNorm v.asIdeal).Prime)
  let E := IntermediateField.fixedField H
  have : IsGalois K E := IsGalois.of_fixedField_normal_subgroup H
  have hfinite : {v : HeightOneSpectrum (𝓞 K) |
      (Ideal.absNorm v.asIdeal).Prime ∧ ¬ FinitePlace.SplitsCompletely E v}.Finite := by
    apply ((S.finite_toSet).union (FinitePlace.ramifiedSet K L).finite_toSet).subset
    intro v ⟨hvprime, hvnonsplit⟩
    by_cases hvS : v ∈ S
    · exact Set.mem_union_left _ hvS
    by_cases hvram : v ∈ FinitePlace.ramifiedSet K L
    · exact Set.mem_union_right _ hvram
    exact (hvnonsplit (fixedField_splits_degreeOne_outside S H
      (fun g Q hS hp hg => Subgroup.subset_closure ⟨Q, ⟨hS, hp⟩, hg⟩)
      v hvS hvprime hvram)).elim
  have hdegree : Module.finrank K E = 1 :=
    finrank_eq_one_of_splitsCompletely hfinite
  have hE : E = ⊥ := IntermediateField.finrank_eq_one_iff.mp hdegree
  have htop : H = ⊤ := by
    rw [← IntermediateField.fixingSubgroup_fixedField H]
    change E.fixingSubgroup = ⊤
    rw [hE, IntermediateField.fixingSubgroup_bot]
  convert htop using 1
  congr 1
  ext g
  simp only [Set.mem_ofPred_eq]
  tauto

/-- An infinite set of base primes contains an unramified prime outside any finite set, with
a Frobenius element above it. This supplies witnesses in
`exists_degreeOne_isFrobeniusAt_of_sq_eq_one`. -/
private theorem exists_isFrobeniusAt_of_infinite_primes [IsGalois K L]
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    {T : Set (HeightOneSpectrum (𝓞 K))} (hT : T.Infinite) :
    ∃ Q : HeightOneSpectrum (𝓞 L), ∃ g : L ≃ₐ[K] L,
      FinitePlace.below (K := K) Q ∈ T ∧ FinitePlace.below (K := K) Q ∉ S ∧
      FinitePlace.below (K := K) Q ∉ FinitePlace.ramifiedSet K L ∧
        IsFrobeniusAt K L g (FinitePlace.below (K := K) Q).asIdeal Q.asIdeal := by
  classical
  obtain ⟨v, hv, hvout⟩ :=
    hT.exists_notMem_finset (S ∪ FinitePlace.ramifiedSet K L)
  obtain ⟨q⟩ := (inferInstance : Nonempty (FinitePlace.PrimeAbove (L := L) v))
  let Q := FinitePlace.PrimeAbove.place v q
  have hbelow : FinitePlace.below (K := K) Q = v :=
    FinitePlace.below_eq_of_liesOver v Q
  obtain ⟨g, hg⟩ :=
    exists_isFrobeniusAt (K := K) (H := L) v.asIdeal Q.asIdeal v.ne_bot
  refine ⟨Q, g, by simpa only [hbelow] using hv,
    by simpa only [hbelow] using (fun h => hvout (Finset.mem_union_left _ h)),
    by simpa only [hbelow] using (fun h => hvout (Finset.mem_union_right _ h)), ?_⟩
  simpa only [hbelow] using hg

/-- In a quadratic top step $L/E$, the degree-one primes splitting in $E$ but not in $L$
have density $1/[L:K]$. This is the density subtraction in Milne, *Class Field Theory*,
Chapter VI, Exercise A-10. -/
private theorem hasPrimeDensity_quadratic_split_difference [IsGalois K L]
    (E : IntermediateField K L) [IsGalois K E] (hcodegree : Module.finrank E L = 2) :
    HasPrimeDensity
      ({v : HeightOneSpectrum (𝓞 K) |
          (Ideal.absNorm v.asIdeal).Prime ∧ FinitePlace.SplitsCompletely E v} \
        {v : HeightOneSpectrum (𝓞 K) |
          (Ideal.absNorm v.asIdeal).Prime ∧ FinitePlace.SplitsCompletely L v})
      (Module.finrank K L : ℝ)⁻¹ := by
  have hBA : {v : HeightOneSpectrum (𝓞 K) |
      (Ideal.absNorm v.asIdeal).Prime ∧ FinitePlace.SplitsCompletely L v} ⊆
      {v | (Ideal.absNorm v.asIdeal).Prime ∧ FinitePlace.SplitsCompletely E v} := by
    rintro v ⟨hvprime, hvsplit⟩
    exact ⟨hvprime, FinitePlace.splitsCompletely_subextension E v hvsplit⟩
  have hden :=
    (hasPrimeDensity_splitsCompletely E).diff (hasPrimeDensity_splitsCompletely L) hBA
  have hdegree : (Module.finrank K L : ℝ) = 2 * (Module.finrank K E : ℝ) := by
    exact_mod_cast (by simpa only [hcodegree, mul_comm] using
      (Module.finrank_mul_finrank K E L).symm)
  have hEne : (Module.finrank K E : ℝ) ≠ 0 := by
    exact_mod_cast Module.finrank_pos.ne'
  have hdelta : (Module.finrank K E : ℝ)⁻¹ - (Module.finrank K L : ℝ)⁻¹ =
      (Module.finrank K L : ℝ)⁻¹ := by
    rw [hdegree]
    field_simp
    ring
  simpa only [hdelta] using hden

/-- If an unramified prime splits in the fixed field of an involution but not in $L$, its
Frobenius element is that involution. This is the final group step in Milne,
*Class Field Theory*, Chapter VI, Exercise A-10. -/
private theorem frobenius_eq_involution_of_fixedField_split [IsAbelianGalois K L]
    {b g : L ≃ₐ[K] L} (horder : orderOf b = 2)
    {v : HeightOneSpectrum (𝓞 K)} {Q : HeightOneSpectrum (𝓞 L)}
    (hg : IsFrobeniusAt K L g v.asIdeal Q.asIdeal)
    (hQram : Q.asIdeal.ramificationIdx (𝓞 K) = 1)
    (hEsplit : FinitePlace.SplitsCompletely
      (IntermediateField.fixedField (Subgroup.zpowers b)) v)
    (hLnot : ¬ FinitePlace.SplitsCompletely L v) : g = b := by
  let H : Subgroup (L ≃ₐ[K] L) := Subgroup.zpowers b
  have : H.Normal := Subgroup.normal_of_isMulCommutative H
  let E := IntermediateField.fixedField H
  have : IsGalois K E := IsGalois.of_fixedField_normal_subgroup H
  have hres : g.restrictNormal E = 1 :=
    (hg.restrictNormal_eq_one_iff_splitsCompletely E hQram).mpr hEsplit
  have hgfix : g ∈ E.fixingSubgroup :=
    (IntermediateField.mem_fixingSubgroup_iff E g).mpr
      ((AlgEquiv.restrictNormal_eq_one_iff E g).mp hres)
  have hgH : g ∈ H := by
    change g ∈ (IntermediateField.fixedField H).fixingSubgroup at hgfix
    rwa [IntermediateField.fixingSubgroup_fixedField H] at hgfix
  have hgne : g ≠ 1 := fun h =>
    hLnot ((hg.eq_one_iff_splitsCompletely hQram).mp h)
  obtain ⟨n, hn⟩ := Subgroup.mem_zpowers_iff.mp hgH
  rcases Int.emod_two_eq_zero_or_one n with hzero | hone
  · have hg1 : g = 1 := by
      rw [← hn, ← zpow_mod_orderOf b n]
      simp [horder, hzero]
    exact (hgne hg1).elim
  · calc
      g = b ^ n := hn.symm
      _ = b ^ (n % (orderOf b : ℤ)) := (zpow_mod_orderOf b n).symm
      _ = b := by simp [horder, hone]

/-- In a finite abelian extension $L/K$, every $b\in\operatorname{Gal}(L/K)$ with $b^2=1$ is the
Frobenius element at a prime of $L$ above a prime of absolute degree one outside any finite set
$S$. The order-two argument of Milne, *Class Field Theory*, Chapter VI, Exercise A-10 and its
solution, adapted from cyclic to abelian extensions. -/
theorem exists_degreeOne_isFrobeniusAt_of_sq_eq_one [IsAbelianGalois K L]
    (S : Finset (HeightOneSpectrum (𝓞 K))) {b : L ≃ₐ[K] L} (hb : b ^ 2 = 1) :
    ∃ w : HeightOneSpectrum (𝓞 L), FinitePlace.below (K := K) w ∉ S ∧
      (Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal).Prime ∧
        IsFrobeniusAt K L b (FinitePlace.below (K := K) w).asIdeal w.asIdeal := by
  classical
  have hLne : (Module.finrank K L : ℝ) ≠ 0 := by
    exact_mod_cast Module.finrank_pos.ne'
  by_cases hb1 : b = 1
  · subst b
    have hInfinite :=
      (hasPrimeDensity_splitsCompletely L).infinite (inv_ne_zero hLne)
    obtain ⟨Q, g, ⟨hvprime, hvsplit⟩, hvS, hvram, hg⟩ :=
      exists_isFrobeniusAt_of_infinite_primes (K := K) (L := L) S hInfinite
    have hQram : Q.asIdeal.ramificationIdx (𝓞 K) = 1 :=
      FinitePlace.ramificationIdx_eq_one_of_notMem_ramifiedSet Q hvram
    have hg1 : g = 1 := (hg.eq_one_iff_splitsCompletely hQram).mpr hvsplit
    exact ⟨Q, hvS, hvprime, hg1 ▸ hg⟩
  · let H : Subgroup (L ≃ₐ[K] L) := Subgroup.zpowers b
    have : H.Normal := Subgroup.normal_of_isMulCommutative H
    let E := IntermediateField.fixedField H
    have : IsGalois K E := IsGalois.of_fixedField_normal_subgroup H
    have horder : orderOf b = 2 := by
      have : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
      exact orderOf_eq_prime hb hb1
    have hcardH : Nat.card H = 2 := by
      simpa only [H, Nat.card_zpowers] using horder
    have hcodegree : Module.finrank E L = 2 := by
      rw [IntermediateField.finrank_fixedField_eq_card]
      exact hcardH
    have hInfinite :=
      (hasPrimeDensity_quadratic_split_difference E hcodegree).infinite
        (inv_ne_zero hLne)
    obtain ⟨Q, g, ⟨⟨hvprime, hvEsplit⟩, hvnotB⟩, hvS, hvram, hg⟩ :=
      exists_isFrobeniusAt_of_infinite_primes (K := K) (L := L) S hInfinite
    have hvLnot : ¬ FinitePlace.SplitsCompletely L (FinitePlace.below (K := K) Q) :=
      fun h => hvnotB ⟨hvprime, h⟩
    have hQram : Q.asIdeal.ramificationIdx (𝓞 K) = 1 :=
      FinitePlace.ramificationIdx_eq_one_of_notMem_ramifiedSet Q hvram
    have hgb := frobenius_eq_involution_of_fixedField_split horder hg hQram
      hvEsplit hvLnot
    exact ⟨Q, hvS, hvprime, hgb ▸ hg⟩

/-! ### Frobenius congruences at primes of absolute degree one

At a prime of absolute degree one the residue field is the prime field, so the identity is a
Frobenius element there. An integral element congruent to its `N𝔭`-th power at almost all
such primes is fixed by their Frobenius elements, which generate the Galois group. -/

/-- At a prime $w$ of $L$ of absolute degree one, the identity is a Frobenius element of $L/K$
over the prime below: $\mathcal O_L/w$ has $p=N(w)$ elements, so $x^p\equiv x\pmod w$, and the
prime below has norm $p$ (`FinitePlace.absNorm_below_eq_of_prime`). -/
theorem isFrobeniusAt_one_of_absNorm_prime (w : HeightOneSpectrum (𝓞 L))
    (hw : (Ideal.absNorm w.asIdeal).Prime) :
    IsFrobeniusAt K L 1 (FinitePlace.below (K := K) w).asIdeal w.asIdeal := by
  have : w.asIdeal.IsMaximal :=
    Ideal.isMaximal_of_isPrime_of_ne_bot w.asIdeal w.ne_bot
  let _ : Field ((𝓞 L) ⧸ w.asIdeal) := Ideal.Quotient.field w.asIdeal
  let _ : Fintype ((𝓞 L) ⧸ w.asIdeal) := Fintype.ofFinite _
  refine IsFrobeniusAt.intro w.isPrime (FinitePlace.liesOver_below w) ?_
  intro x
  change x - x ^ Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal ∈ w.asIdeal
  rw [FinitePlace.absNorm_below_eq_of_prime w hw, ← Ideal.Quotient.eq]
  simpa only [map_pow, Ideal.absNorm_apply, Submodule.cardQuot_apply,
    Nat.card_eq_fintype_card] using
    (FiniteField.pow_card (Ideal.Quotient.mk w.asIdeal x)).symm

/-- Primes dividing a nonzero difference between `z` and one of its Galois conjugates.
Used by `mem_range_of_pow_absNorm_sub_mem`. -/
private def badConjugatePrimes (z : 𝓞 L) : Set (HeightOneSpectrum (𝓞 L)) :=
  {w | ∃ g : L ≃ₐ[K] L, RingOfIntegers.mapRingEquiv g.toRingEquiv z ≠ z ∧
    RingOfIntegers.mapRingEquiv g.toRingEquiv z - z ∈ w.asIdeal}

/-- Only finitely many primes divide a nonzero difference between `K`-automorphism
conjugates of `z`.
This supplies the exceptional primes in `mem_range_of_pow_absNorm_sub_mem`. -/
private theorem finite_primes_of_conjugate_difference (z : 𝓞 L) :
    (badConjugatePrimes (K := K) z).Finite := by
  classical
  let D (g : L ≃ₐ[K] L) : Set (HeightOneSpectrum (𝓞 L)) :=
    {w | RingOfIntegers.mapRingEquiv g.toRingEquiv z ≠ z ∧
      RingOfIntegers.mapRingEquiv g.toRingEquiv z - z ∈ w.asIdeal}
  have hD (g : L ≃ₐ[K] L) : (D g).Finite := by
    by_cases hg : RingOfIntegers.mapRingEquiv g.toRingEquiv z = z
    · simp [D, hg]
    have hdiff : RingOfIntegers.mapRingEquiv g.toRingEquiv z - z ≠ 0 :=
      sub_ne_zero.mpr hg
    exact (finite_primes_containing hdiff).subset (fun _ hw => hw.2)
  apply (Set.finite_iUnion hD).subset
  rintro w ⟨g, hg⟩
  exact Set.mem_iUnion.mpr ⟨g, hg⟩

omit [NumberField L] in
/-- Outside the conjugate-difference primes, the power congruence makes a Frobenius element
fix `z`. This is the local step in `mem_range_of_pow_absNorm_sub_mem`. -/
private theorem frobenius_fixed_outside_bad (z : 𝓞 L) (g : L ≃ₐ[K] L)
    (w : HeightOneSpectrum (𝓞 L))
    (hw : w ∉ badConjugatePrimes (K := K) z)
    (hg : IsFrobeniusAt K L g (FinitePlace.below (K := K) w).asIdeal w.asIdeal)
    (hz : z ^ Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal - z ∈ w.asIdeal) :
    g (z : L) = (z : L) := by
  have hdiff : RingOfIntegers.mapRingEquiv g.toRingEquiv z - z ∈ w.asIdeal := by
    simpa only [sub_add_sub_cancel] using w.asIdeal.add_mem (hg.sub_mem z) hz
  have heq : RingOfIntegers.mapRingEquiv g.toRingEquiv z = z := by
    by_contra hne
    exact hw ⟨g, hne, hdiff⟩
  simpa only [RingOfIntegers.mapRingEquiv_apply, AlgEquiv.coe_ringEquiv] using congrArg
    (fun x : 𝓞 L => (x : L)) heq

/-- **An integral element congruent to its `N𝔭`-th power at almost all primes of absolute
degree one lies in the base.** Let $L/K$ be finite Galois and $z\in\mathcal O_L$ with
$z^{N\mathfrak p}\equiv z\pmod w$ at every prime $w$ of $L$ whose prime $\mathfrak p$ below has
prime absolute norm and lies outside a finite set $S$. Then $z\in K$. The Frobenius element
$\sigma$ at such a $w$ satisfies $\sigma z\equiv z^{N\mathfrak p}\equiv z$; excluding the
finitely many primes containing a nonzero $gz-z$, $g\in\operatorname{Gal}(L/K)$, it fixes $z$,
and these elements generate $\operatorname{Gal}(L/K)$ (`closure_degreeOne_frobenius_eq_top`).
This is the kernel argument in the proof of [RW26b, Radchenko, Wheeler (2026b), Section 8,
Proposition 4], with Frobenius generation in place of Chebotarev's theorem. -/
theorem mem_range_of_pow_absNorm_sub_mem [IsGalois K L]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (z : 𝓞 L)
    (hz : ∀ w : HeightOneSpectrum (𝓞 L), FinitePlace.below (K := K) w ∉ S →
      (Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal).Prime →
        z ^ Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal - z ∈ w.asIdeal) :
    (z : L) ∈ (algebraMap K L).range := by
  classical
  have hT := finite_primes_of_conjugate_difference (K := K) z
  let S' : Finset (HeightOneSpectrum (𝓞 K)) :=
    S ∪ (hT.image (FinitePlace.below (K := K))).toFinset
  let F : Set (L ≃ₐ[K] L) := {g | ∃ w : HeightOneSpectrum (𝓞 L),
    FinitePlace.below (K := K) w ∉ S' ∧
      (Ideal.absNorm (FinitePlace.below (K := K) w).asIdeal).Prime ∧
        IsFrobeniusAt K L g (FinitePlace.below (K := K) w).asIdeal w.asIdeal}
  have hfix (g : L ≃ₐ[K] L) (hgF : g ∈ F) : g (z : L) = (z : L) := by
    obtain ⟨w, hwS, hwprime, hg⟩ := hgF
    have hwS₀ : FinitePlace.below (K := K) w ∉ S :=
      fun h => hwS (Finset.mem_union_left _ h)
    apply frobenius_fixed_outside_bad z g w ?_ hg (hz w hwS₀ hwprime)
    intro hwT
    have hbelowT : FinitePlace.below (K := K) w ∈
        (hT.image (FinitePlace.below (K := K))).toFinset := by
      simpa only [Set.Finite.mem_toFinset] using
        Set.mem_image_of_mem (FinitePlace.below (K := K)) hwT
    exact hwS (Finset.mem_union_right S hbelowT)
  have hclosure : Subgroup.closure F ≤
      MulAction.stabilizer (L ≃ₐ[K] L) (z : L) := by
    apply (Subgroup.closure_le _).mpr
    intro g hg
    exact MulAction.mem_stabilizer_iff.mpr (hfix g hg)
  apply (IsGalois.mem_range_algebraMap_iff_fixed (z : L)).mpr
  intro g
  have hg : g ∈ Subgroup.closure F := by
    rw [closure_degreeOne_frobenius_eq_top S']
    trivial
  exact MulAction.mem_stabilizer_iff.mp (hclosure hg)

end SIC
