/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.ClassField.Reciprocity.GlobalArtinMap

/-!
# Complementary Kummer fields

When $\mu_n\subset K$, the Kummer field generated by the `n`th roots of the S-units that are
`n`th powers at a set of places has as norm group the idèles unrestricted at those places and
`n`th powers at the complementary places of `S` and infinity.

This module follows Childress, *Class Field Theory* (2009), Chapter VI, proof of Theorem 2.9:
for complementary subgroups $B_1$, $B_2$ of `freePowerSubgroup`, the fields
$L_1 = K(W_2^{1/n})$ and $L_2 = K(W_1^{1/n})$ with $W_i = K^\times\cap B_i$ are the class fields
of $K^\times B_1$ and $K^\times B_2$. It supplies the Kummer case of the complete splitting
theorem, `SICs.ClassField.Splitting.Kummer`. The two fields are constructed directly, without
the existence theorem.

## The argument

Let `S` contain the primes dividing `n` and represent the ideal classes, and let
$B_1 = $ `freePowerSubgroup n S I T` and $B_2 = $ `freePowerSubgroup n S Iᶜ Tᶜ`. Then
$B_1\cap B_2 = E$ is Milne's local-power subgroup and $B_1B_2$ is the group $J_{K,S}$ of idèles
integral outside `S` (`freePowerSubgroup_inf`, `freePowerSubgroup_sup`).

*The fields.* $M_i = K(W_j^{1/n})$, `j ≠ i`, is a Kummer extension of exponent dividing `n`
(`freePowerKummer_aut_pow`), unramified outside `S` because its radicands are S-units and `S`
contains the primes dividing `n` (`ramificationIdx_kummerExtension_eq_one`). Its radicands are local
`n`th powers at the places unrestricted in $B_i$, so these places split completely
(`FinitePlace.finrank_eq_one_of_local_roots`). Its degree is
$[W_j:W_j\cap K^{\times n}] = [W_j:O_S^{\times n}]$ (`kummerExtension_finrank`; a principal
element of `E` is an `n`th power of an S-unit, `powerSubgroup_comap_sUnits`).

*Containment.* By `map_freePowerSubgroup_le`, the classes of $B_i$ lie in $N_{M_i/K}C_{M_i}$:
`n`th powers of idèle classes are norms since $\operatorname{Gal}(M_i/K)$ has exponent dividing
`n`, unit idèles away from `S` are norms since $M_i/K$ is unramified there, and the local groups
at the split places are norms.

*Counting.* In $J_K$ with $P = K^\times$ and $G = J_{K,S}$: $P\,G = J_K$ by the choice of `S`,
$[G:E] = n^{2(|S|+r)}$ (`relIndex_powerSubgroup`, the product formula), and
$[G\cap P:E\cap P] = [O_S^\times:O_S^{\times n}] = n^{|S|+r}$
(`relIndex_powerSubgroup_principal`). The norm group of $M_i$ has index $[M_i:K]$
(`IdeleClassGroup.index_range_norm`), the principal index of $B_j$. So
`SIC.Subgroup.eq_sup_of_complementary` gives $N_{M_1/K}C_{M_1} = K^\times B_1$.
-/

noncomputable section

open IsDedekindDomain NumberField
open scoped SIC.FinitePlace NumberField.LiesOver SIC.InfinitePlace

namespace SIC.IdeleGroup

variable (K : Type*) [Field K] [NumberField K]

/-! ### The Kummer field of a free power subgroup -/

/-- The Kummer field $K(W^{1/n})$ of the principal elements $W = K^\times\cap B$ of
`B = freePowerSubgroup n S I T`: Childress's $L_1 = K(W_2^{1/n})$ and $L_2 = K(W_1^{1/n})$ in
*Class Field Theory*, Chapter VI, proof of Theorem 2.9. -/
def freePowerKummer (n : ℕ) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K))) :
    IntermediateField K (AlgebraicClosure K) :=
  kummerExtension K n
    ((freePowerSubgroup n S I T).comap (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K))

variable {K}

/-- The Kummer field of a free power subgroup is finite over `K` for $n>0$. -/
instance freePowerKummer_finiteDimensional (n : ℕ) [NeZero n]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (I : Set (InfinitePlace K))
    (T : Set (HeightOneSpectrum (𝓞 K))) : FiniteDimensional K (freePowerKummer K n S I T) :=
  kummerExtension_finiteDimensional (NeZero.pos n) (fg_comap_freePowerSubgroup n S I T)

/-- The Kummer field of a free power subgroup is a number field for $n>0$. -/
instance freePowerKummer_numberField (n : ℕ) [NeZero n]
    (S : Finset (HeightOneSpectrum (𝓞 K))) (I : Set (InfinitePlace K))
    (T : Set (HeightOneSpectrum (𝓞 K))) : NumberField (freePowerKummer K n S I T) :=
  NumberField.of_module_finite K _

/-- The Kummer field of a free power subgroup is abelian over `K` when $\mu_n\subset K$.
Specializes `kummerExtension_isAbelianGalois`. -/
theorem freePowerKummer_isAbelianGalois {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (S : Finset (HeightOneSpectrum (𝓞 K))) (I : Set (InfinitePlace K))
    (T : Set (HeightOneSpectrum (𝓞 K))) : IsAbelianGalois K (freePowerKummer K n S I T) :=
  kummerExtension_isAbelianGalois hζ (NeZero.pos n)

/-- Every automorphism of the Kummer field of a free power subgroup satisfies $\sigma^n = 1$.
Specializes `kummerExtension_aut_pow`. -/
theorem freePowerKummer_aut_pow {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (S : Finset (HeightOneSpectrum (𝓞 K))) (I : Set (InfinitePlace K))
    (T : Set (HeightOneSpectrum (𝓞 K))) (σ : Gal((freePowerKummer K n S I T)/K)) :
    σ ^ n = 1 :=
  kummerExtension_aut_pow hζ (NeZero.pos n) σ

/-- The degree of the Kummer field of `B = freePowerSubgroup n S I T` is the principal index
$[K^\times\cap B:K^\times\cap E]$ of the local-power subgroup `E`, i.e.
$[W:O_S^{\times n}]$. Childress, *Class Field Theory*, Chapter VI, proof of Theorem 2.9,
$[L_1:K] = [W_2:F_S^n]$. -/
theorem finrank_freePowerKummer {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (hclass : Function.Surjective (sIdealClass (K := K) (L := K) S))
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K))) :
    Module.finrank K (freePowerKummer K n S I T) =
      ((powerSubgroup n S ∅).comap (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)).relIndex
        ((freePowerSubgroup n S I T).comap (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)) := by
  classical
  let B : Subgroup Kˣ := (freePowerSubgroup n S I T).comap
    (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)
  let E : Subgroup Kˣ := (powerSubgroup n S ∅).comap
    (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)
  have hle : B ≤ sUnits (K := K) (L := K) S :=
    Subgroup.comap_mono (freePowerSubgroup_le_sSubgroup n S I T)
  have hpow : ((powMonoidHom n : Kˣ →* Kˣ).range).comap B.subtype =
      E.comap B.subtype := by
    ext x
    have hxS : (x.1 : Kˣ) ∈ sUnits (K := K) (L := K) S := hle x.2
    have hxE : (x.1 : Kˣ) ∈ E ↔
        (⟨x.1, hxS⟩ : sUnits (K := K) (L := K) S) ∈
          (powMonoidHom n : sUnits (K := K) (L := K) S →*
            sUnits (K := K) (L := K) S).range := by
      let a : sUnits (K := K) (L := K) (S ∪ ∅) := ⟨x.1, by simpa using hxS⟩
      have hm : a ∈ (powerSubgroup n S ∅).comap
          ((NumberField.IdeleGroup.unitEmbedding (𝓞 K) K).comp
            (sUnits (K := K) (L := K) (S ∪ ∅)).subtype) ↔
          a ∈ (powMonoidHom n : sUnits (K := K) (L := K) (S ∪ ∅) →*
            sUnits (K := K) (L := K) (S ∪ ∅)).range := by
        rw [powerSubgroup_comap_sUnits hζ (NeZero.pos n) S ∅
          (Finset.disjoint_empty_right S) hnS hclass
          (fun _ => ⟨1, Subsingleton.elim _ _⟩)]
      simpa [a, E] using hm
    change (x.1 : Kˣ) ∈ (powMonoidHom n : Kˣ →* Kˣ).range ↔ (x.1 : Kˣ) ∈ E
    exact (Iff.of_eq (congrArg
      (fun H : Subgroup (sUnits (K := K) (L := K) S) =>
        (⟨x.1, hxS⟩ : sUnits (K := K) (L := K) S) ∈ H)
      (sUnits_power_comap (K := K) (L := K) S (NeZero.ne n)))).trans hxE.symm
  rw [freePowerKummer, kummerExtension_finrank hζ (NeZero.pos n)
    (fg_comap_freePowerSubgroup n S I T)]
  change Nat.card (B ⧸ ((powMonoidHom n : Kˣ →* Kˣ).range).comap B.subtype) = E.relIndex B
  rw [hpow, Subgroup.relIndex, Subgroup.subgroupOf, Subgroup.index_eq_card]

/-- The Kummer field of a free power subgroup is unramified outside `S` when `S` contains the
primes dividing `n`. Childress, *Class Field Theory*, Chapter VI, proof of Theorem 2.9. -/
theorem ramificationIdx_freePowerKummer {n : ℕ} [NeZero n]
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K)))
    (w : HeightOneSpectrum (𝓞 (freePowerKummer K n S I T)))
    (hw : FinitePlace.below (K := K) w ∉ S) :
    w.asIdeal.ramificationIdx (𝓞 K) = 1 := by
  refine @ramificationIdx_kummerExtension_eq_one K _ _ n
    ((freePowerSubgroup n S I T).comap (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K))
    (fg_comap_freePowerSubgroup n S I T) (FinitePlace.below (K := K) w) ?_ ?_ w
    (FinitePlace.liesOver_below w)
  · intro b
    have hbS : (b.val : Kˣ) ∈ sUnits (K := K) (L := K) S :=
      (Subgroup.comap_mono (freePowerSubgroup_le_sSubgroup n S I T)) b.property
    exact sUnits_valuation_eq_one S ⟨b.val, hbS⟩ _ hw
  · exact fun hn => hw (hnS _ hn)

/-- The primes of `S` outside `T` split completely in the Kummer field of
`freePowerSubgroup n S I T`, its radicands being local `n`th powers there. Childress, *Class
Field Theory*, Chapter VI, proof of Theorem 2.9. -/
theorem finrank_adicCompletion_freePowerKummer {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K)))
    {v : HeightOneSpectrum (𝓞 K)} (hvS : v ∈ S) (hvT : v ∉ T)
    (w : HeightOneSpectrum (𝓞 (freePowerKummer K n S I T))) [w.asIdeal.LiesOver v.asIdeal] :
    Module.finrank (v.adicCompletion K) (w.adicCompletion (freePowerKummer K n S I T)) = 1 := by
  let B := (freePowerSubgroup n S I T).comap
    (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)
  let M := freePowerKummer K n S I T
  let : IsAbelianGalois K M :=
    freePowerKummer_isAbelianGalois hζ S I T
  have hgen : IntermediateField.adjoin K {x : M | ∃ b : B,
      x ^ n = algebraMap K M (b.val : K)} = ⊤ :=
    kummerExtension_adjoin_radicals_eq_top n B
  apply FinitePlace.finrank_eq_one_of_local_roots hζ (NeZero.pos n) B
    hgen v w
  intro b
  obtain ⟨y, hy⟩ := ((mem_freePowerSubgroup n S I T
    (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K b.val)).mp b.property).2.2 v hvS hvT
  exact ⟨y.val, by simpa only [Units.val_pow_eq_pow_val, finiteComponent_unitEmbedding,
    Units.coe_map, MonoidHom.coe_coe] using congrArg Units.val hy⟩

/-- The infinite places outside `I` split completely in the Kummer field of
`freePowerSubgroup n S I T`, its radicands being local `n`th powers there. Childress, *Class
Field Theory*, Chapter VI, proof of Theorem 2.9, at infinite places of `S`. -/
theorem finrank_completion_freePowerKummer {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K)))
    {v : InfinitePlace K} (hv : v ∉ I) (w : InfinitePlace (freePowerKummer K n S I T))
    [w.LiesOver v] :
    Module.finrank v.Completion w.Completion = 1 := by
  let B := (freePowerSubgroup n S I T).comap
    (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)
  let M := freePowerKummer K n S I T
  let : IsAbelianGalois K M :=
    freePowerKummer_isAbelianGalois hζ S I T
  have hgen : IntermediateField.adjoin K {x : M | ∃ b : B,
      x ^ n = algebraMap K M (b.val : K)} = ⊤ :=
    kummerExtension_adjoin_radicals_eq_top n B
  apply InfinitePlace.finrank_eq_one_of_local_roots hζ (NeZero.pos n) B
    hgen v w
  intro b
  obtain ⟨y, hy⟩ := ((mem_freePowerSubgroup n S I T
    (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K b.val)).mp b.property).2.1 v hv
  exact ⟨y.val, by simpa only [Units.val_pow_eq_pow_val, infiniteComponent_unitEmbedding,
    Units.coe_map, MonoidHom.coe_coe] using congrArg Units.val hy⟩

/-! ### The norm group

The classes of each complementary subgroup are norms from the Kummer field of the other, and the
two degrees are the two principal indices; the complementary counting identifies the norm
groups. -/

/-- The classes of a free power subgroup are norms from the Kummer field generated by the
complementary principal radicands. Used by `range_norm_freePowerKummer`. -/
private theorem map_freePowerSubgroup_le_range_norm {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K))) :
    (freePowerSubgroup n S I T).map
      (QuotientGroup.mk' (NumberField.IdeleGroup.principalSubgroup (𝓞 K) K)) ≤
        (IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S Iᶜ Tᶜ)).range := by
  classical
  let M := freePowerKummer K n S Iᶜ Tᶜ
  let _ : IsAbelianGalois K M := freePowerKummer_isAbelianGalois hζ S Iᶜ Tᶜ
  apply map_freePowerSubgroup_le S I T
  · intro x
    exact IdeleClassGroup.pow_mem_range_norm
      (freePowerKummer_aut_pow hζ S Iᶜ Tᶜ) x
  · exact map_awayUnitSubgroup_le_range_norm S
      ((FinitePlace.ramifiedSet_subset_iff S).mpr
        (fun w hw => ramificationIdx_freePowerKummer S hnS Iᶜ Tᶜ w hw))
  · intro v hv
    let w : InfinitePlace.PlaceAbove (L := M) v := Classical.choice inferInstance
    apply IdeleClassGroup.range_ofCompletion_le_range_norm v w.val
    exact finrank_completion_freePowerKummer hζ S Iᶜ Tᶜ (by simpa using hv) w.val
  · intro v hvS hvT
    let w : FinitePlace.PrimeAbove (L := M) v := Classical.choice inferInstance
    apply IdeleClassGroup.range_ofAdicCompletion_le_range_norm v
      (FinitePlace.PrimeAbove.place v w)
    exact finrank_adicCompletion_freePowerKummer hζ S Iᶜ Tᶜ
      hvS (by simpa using hvT) (FinitePlace.PrimeAbove.place v w)

/-- Complementary unrestricted places give intersection $E$ and join $J_{K,S}$.
Used by `range_norm_freePowerKummer`. -/
private theorem freePowerSubgroup_complementary (n : ℕ)
    (S : Finset (HeightOneSpectrum (𝓞 K))) (I : Set (InfinitePlace K))
    (T : Set (HeightOneSpectrum (𝓞 K))) :
    freePowerSubgroup n S I T ⊓ freePowerSubgroup n S Iᶜ Tᶜ = powerSubgroup n S ∅ ∧
      freePowerSubgroup n S I T ⊔ freePowerSubgroup n S Iᶜ Tᶜ =
        sSubgroup (K := K) (L := K) S := by
  constructor
  · rw [freePowerSubgroup_inf, Set.inter_compl_self, Set.inter_compl_self,
      freePowerSubgroup_empty]
  · rw [freePowerSubgroup_sup, Set.union_compl_self, Set.union_compl_self,
      freePowerSubgroup_univ]

/-- The local power index is the square of the principal index, the two numerical inputs to
the complementary count in `range_norm_freePowerKummer`. -/
private theorem freePowerSubgroup_complementary_indices {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (hclass : Function.Surjective (sIdealClass (K := K) (L := K) S)) :
    (powerSubgroup n S ∅).relIndex (sSubgroup (K := K) (L := K) S) =
        (n ^ (S.card + Nat.card (InfinitePlace K))) ^ 2 ∧
      ((powerSubgroup n S ∅) ⊓ NumberField.IdeleGroup.principalSubgroup (𝓞 K) K).relIndex
        ((sSubgroup (K := K) (L := K) S) ⊓
          NumberField.IdeleGroup.principalSubgroup (𝓞 K) K) =
        n ^ (S.card + Nat.card (InfinitePlace K)) := by
  classical
  constructor
  · have h := relIndex_powerSubgroup hζ (NeZero.pos n) S ∅ hnS
    simp only [Finset.union_empty] at h
    rw [h, ← pow_mul]
    congr 1
    omega
  · change (powerSubgroup n S ∅ ⊓
        (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K).range).relIndex
      (sSubgroup (K := K) (L := K) S ⊓
        (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K).range) = _
    rw [SIC.Subgroup.relIndex_inf_range]
    simpa [sUnits] using relIndex_powerSubgroup_principal hζ (NeZero.pos n)
      S ∅ (Finset.disjoint_empty_right S) hnS hclass
          (fun _ => ⟨1, Subsingleton.elim _ _⟩)

/-- The principal idèles and a free power subgroup lie in the pullback of the norm group of
the complementary Kummer field. Used by `range_norm_freePowerKummer`. -/
private theorem sup_freePowerSubgroup_le_norm_comap {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K))) :
    NumberField.IdeleGroup.principalSubgroup (𝓞 K) K ⊔ freePowerSubgroup n S I T ≤
      ((IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S Iᶜ Tᶜ)).range).comap
        (QuotientGroup.mk' (NumberField.IdeleGroup.principalSubgroup (𝓞 K) K)) := by
  let P := NumberField.IdeleGroup.principalSubgroup (𝓞 K) K
  let q := QuotientGroup.mk' P
  apply sup_le
  · intro x hx
    change q x ∈ (IdeleClassGroup.norm (K := K)
      (L := freePowerKummer K n S Iᶜ Tᶜ)).range
    have hqx : q x = 1 := by
      have hm : q x ∈ P.map q := ⟨x, hx, rfl⟩
      simpa only [q, QuotientGroup.map_mk'_self, Subgroup.mem_bot] using hm
    rw [hqx]
    exact Subgroup.one_mem _
  · intro x hx
    exact map_freePowerSubgroup_le_range_norm hζ S hnS I T ⟨x, hx, rfl⟩

/-- The norm index of `freePowerKummer` is the principal index of its radicands.
Used by `range_norm_freePowerKummer`. -/
private theorem index_comap_norm_freePowerKummer {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (hclass : Function.Surjective (sIdealClass (K := K) (L := K) S))
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K))) :
    (((IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S I T)).range).comap
      (QuotientGroup.mk' (NumberField.IdeleGroup.principalSubgroup (𝓞 K) K))).index =
        ((powerSubgroup n S ∅) ⊓ NumberField.IdeleGroup.principalSubgroup (𝓞 K) K).relIndex
          ((freePowerSubgroup n S I T) ⊓
            NumberField.IdeleGroup.principalSubgroup (𝓞 K) K) := by
  let _ : IsAbelianGalois K (freePowerKummer K n S I T) :=
    freePowerKummer_isAbelianGalois hζ S I T
  calc
    _ = (IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S I T)).range.index :=
      Subgroup.index_comap_of_surjective _ QuotientGroup.mk_surjective
    _ = Module.finrank K (freePowerKummer K n S I T) := IdeleClassGroup.index_range_norm
    _ = _ := by
      rw [finrank_freePowerKummer hζ S hnS hclass I T]
      exact (SIC.Subgroup.relIndex_inf_range (freePowerSubgroup n S I T)
        (powerSubgroup n S ∅) (NumberField.IdeleGroup.unitEmbedding (𝓞 K) K)).symm

/-- **The norm group of a complementary Kummer field**: when $\mu_n\subset K$ and `S` contains
the primes dividing `n` and represents the ideal classes, the Kummer field of
`freePowerSubgroup n S Iᶜ Tᶜ` has norm group the classes of `freePowerSubgroup n S I T`.
Childress, *Class Field Theory*, Chapter VI, proof of Theorem 2.9: $L_1$ is the class field of
$K^\times B_1$. -/
theorem range_norm_freePowerKummer {n : ℕ} [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
    (S : Finset (HeightOneSpectrum (𝓞 K)))
    (hnS : ∀ v : HeightOneSpectrum (𝓞 K), (n : 𝓞 K) ∈ v.asIdeal → v ∈ S)
    (hclass : Function.Surjective (sIdealClass (K := K) (L := K) S))
    (I : Set (InfinitePlace K)) (T : Set (HeightOneSpectrum (𝓞 K))) :
    (IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S Iᶜ Tᶜ)).range =
      (freePowerSubgroup n S I T).map
        (QuotientGroup.mk' (NumberField.IdeleGroup.principalSubgroup (𝓞 K) K)) := by
  classical
  let P := NumberField.IdeleGroup.principalSubgroup (𝓞 K) K
  let q := QuotientGroup.mk' P
  let G := sSubgroup (K := K) (L := K) S
  let E := powerSubgroup n S ∅
  let B₁ := freePowerSubgroup n S I T
  let B₂ := freePowerSubgroup n S Iᶜ Tᶜ
  let H₁ := (IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S Iᶜ Tᶜ)).range
  let H₂ := (IdeleClassGroup.norm (K := K) (L := freePowerKummer K n S I T)).range
  let N₁ := H₁.comap q
  let N₂ := H₂.comap q
  let s := n ^ (S.card + Nat.card (InfinitePlace K))
  obtain ⟨hinf, hsup⟩ := freePowerSubgroup_complementary n S I T
  obtain ⟨hG, hP⟩ := freePowerSubgroup_complementary_indices hζ S hnS hclass
  have htop : P ⊔ G = ⊤ := by
    rw [sup_comm]
    exact sSubgroup_sup_principal S hclass
  have h₁ : P ⊔ B₁ ≤ N₁ := sup_freePowerSubgroup_le_norm_comap hζ S hnS I T
  have h₂ : P ⊔ B₂ ≤ N₂ := by
    have h := sup_freePowerSubgroup_le_norm_comap hζ S hnS Iᶜ Tᶜ
    rw [compl_compl I, compl_compl T] at h
    exact h
  have hN₁ : N₁.index = (E ⊓ P).relIndex (B₂ ⊓ P) :=
    index_comap_norm_freePowerKummer hζ S hnS hclass Iᶜ Tᶜ
  have hN₂ : N₂.index = (E ⊓ P).relIndex (B₁ ⊓ P) :=
    index_comap_norm_freePowerKummer hζ S hnS hclass I T
  have hN := SIC.Subgroup.eq_sup_of_complementary hinf hsup htop
    (pow_ne_zero _ (NeZero.ne n)) hG hP h₁ h₂ hN₁ hN₂
  have hm := congrArg (fun A : Subgroup (NumberField.IdeleGroup (𝓞 K) K) => A.map q) hN
  change (H₁.comap q).map q = (P ⊔ B₁).map q at hm
  rw [Subgroup.map_comap_eq, QuotientGroup.range_mk' P, top_inf_eq,
    Subgroup.map_sup, QuotientGroup.map_mk'_self P, bot_sup_eq] at hm
  exact hm

end SIC.IdeleGroup
