/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.Dilogarithm.Frobenius.CyclicSummand
import SICs.Dilogarithm.Frobenius.SplitLines
import SICs.Dilogarithm.Frobenius.SplitTranslation

/-!
# Translation invariance of a pseudolattice dilogarithm along a split line

For an odd prime `p`, a valuation with `v(p) < 1`, a period `η` of `I` with `η ≡ 1` on `I/pI`,
and a split pair of lines `J₀, J₁` of `I` at `p`, the reduction of `E_{I,η}` modulo `𝔪` is
invariant under translation by one of the lines `J_i/I`, the same for every argument.

This module completes [RW26b, Radchenko, Wheeler (2026b), Section 7, Theorem 7] for a
pseudolattice: it supplies the lattice part of the proof and applies the metric-group part
(`FiniteQuantumDilog.translation_invariant_of_summands`). The source assumes `I` locally maximal
at an odd split prime `p` and `η ≡ 1 (mod p𝒪_K)`; here these are replaced by what the proof
uses, a split pair of lines (`IsSplitLinePair`, which `J = (𝔭⁻¹I, 𝔮⁻¹I)` is under the source's
hypotheses) and `(η - 1)/p` in the multiplier ring of `I`.

## The argument

*The exponent `s`.* `η ≠ 1`, so there is a largest `s ≥ 1` with `TI ⊆ I` for `T = (η - 1)/p^s`;
then `T/p` does not preserve `I`. The source writes `η - 1 = p^sB` with both residues of `B` at
`𝔭`, `𝔮` nonzero; maximality of `s` on the lattice plays that role.

*The scalars of `T`.* `T` acts on the lines by integers `t₀`, `t₁`
(`IsSplitLinePair.exists_scalar`) with `t₀ + t₁ ≡ Tr T` (`exists_trace_norm_eq`). From
`N(η) = N(1 + p^sT) = 1 + p^s Tr T + p^{2s}N(T) = 1`, `Tr T = -p^sN(T) ≡ 0`, so `t₀ ≡ -t₁`. If
both vanished modulo `p`, `T` would kill `p⁻¹I/I` (`mul_mem_of_dvd`), against maximality. So
`t₀ ≡ -t₁` are units, distinct as `p` is odd: the source's statement that the residues of `B` are
opposite, nonzero, and distinct.

*The `p`-primary part.* `T` is injective on `p⁻¹I/I` (`mem_of_mul_mem`), so
`G_{I,η}[p^∞] = p^{-s}I/I ≅ (ℤ/p^s)²` (`IsPeriod.exists_primaryEmbedding`), with `p`-torsion
`J₀/I ⊕ J₁/I` spanned by the residues `a`, `b` of `w_i ∈ J_i \ I`, independent by
`IsSplitLinePair.dvd_of_add_mem`.

*The summands.* A cyclic summand of order `p^s` is `⟨z⟩` with `p^sz ∈ I`; if its `p`-torsion
`⟨p^{s-1}z⟩` is neither `⟨a⟩` nor `⟨b⟩`, then `p^{s-1}z` lies in neither line, so it is not an
eigenvector of `T` modulo `I` (`mem_or_mem_of_mul_sub_mem`, the scalars being distinct), and
`pseudolatticeDilog_prod_summand_congr` gives the invariance of the summand products.
`translation_invariant_of_summands`, with unit values from `pseudolatticeDilog_valuation_eq_one`,
then gives invariance along `a` or along `b`, hence along the whole line, which is generated by
it (`IsSplitLinePair.exists_int_sub_mem`).
-/

noncomputable section

open scoped MatrixGroups NNReal

namespace SIC

variable {K : Type*} [Field K] [NumberField K] [NumberField.IsTotallyReal K]
variable {F : RealQuadraticFieldData K} {B : PseudolatticeBasis F}

/-! ### The lattice exponent and its split-line scalars

The maximal multiplier exponent and the opposite nonzero scalars of its quotient. -/

/-- The quadratic norm identity `N(1+aT)=1+a Tr(T)+a²N(T)`, used in
`scalar_sum_dvd`. -/
private theorem norm_one_add_quadratic (F : RealQuadraticFieldData K) (a : ℚ) (T : K) :
    Algebra.norm ℚ (1 + (a : K) * T) =
      1 + a * Algebra.trace ℚ K T + a ^ 2 * Algebra.norm ℚ T := by
  have hreal : (((Algebra.norm ℚ (1 + (a : K) * T) : ℚ) : ℝ)) =
      1 + (a : ℝ) * (((Algebra.trace ℚ K) T : ℚ) : ℝ) +
        (a : ℝ) ^ 2 * (((Algebra.norm ℚ T : ℚ) : ℝ)) := by
    rw [← F.mul_realEmbeddingAt_otherPlace_eq_norm,
      ← F.add_realEmbeddingAt_otherPlace_eq_trace,
      ← F.mul_realEmbeddingAt_otherPlace_eq_norm]
    simp only [map_add, map_one, map_mul, map_ratCast]
    ring
  exact_mod_cast hreal

/-- The scalars of `T=(η-1)/p^s` on the two split lines sum to zero modulo `p`.
Used by `pseudolatticeDilog_split_translation`; this is the trace step of [RW26b, Radchenko,
Wheeler (2026b), Section 7, proof of Theorem 7]. -/
private theorem scalar_sum_dvd {η T : K} (h : B.IsPeriod η) {p s : ℕ}
    [Fact p.Prime] (hs : 1 ≤ s) (hT : η - 1 = (p : K) ^ s * T)
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J)
    (hTI : ∀ x ∈ B.submodule, T * x ∈ B.submodule)
    {t : Fin 2 → ℤ} (ht : ∀ i, ∀ y ∈ J i, T * y - t i * y ∈ B.submodule) :
    (p : ℤ) ∣ t 0 + t 1 := by
  have hfg : B.submodule.FG := by
    unfold PseudolatticeBasis.submodule
    exact Submodule.fg_span ((Set.finite_singleton B.scale).insert (B.scale * B.tau))
  obtain ⟨u, w, htr, hnorm⟩ := hJ.exists_trace_norm_eq F.finrank_eq_two hfg hTI ht
  have hηeq : η = 1 + (p : K) ^ s * T := by linear_combination hT
  have hq0 : (p : ℚ) ^ s ≠ 0 := by
    have hp0 : (p : ℚ) ≠ 0 := by exact_mod_cast (Fact.out : p.Prime).ne_zero
    exact pow_ne_zero _ hp0
  have hqn : (((p : ℚ) ^ s : ℚ) : K) = (p : K) ^ s := by norm_cast
  have hnormη := norm_one_add_quadratic F ((p : ℚ) ^ s) T
  rw [hqn, ← hηeq, h.norm_one, htr, hnorm] at hnormη
  have hqeq : (p : ℚ) ^ s *
      ((((t 0 + t 1 + p * u : ℤ) : ℚ)) +
        (p : ℚ) ^ s * (((t 0 * t 1 + p * w : ℤ) : ℚ))) = 0 := by
    nlinarith [hnormη]
  have htrace : (((t 0 + t 1 + p * u : ℤ) : ℚ)) =
      - (p : ℚ) ^ s * (((t 0 * t 1 + p * w : ℤ) : ℚ)) := by
    have hz := (mul_eq_zero.mp hqeq).resolve_left hq0
    linear_combination hz
  have htraceInt : t 0 + t 1 + p * u =
      -(p : ℤ) ^ s * (t 0 * t 1 + p * w) := by
    exact_mod_cast htrace
  have hpow : (p : ℤ) ∣ (p : ℤ) ^ s := dvd_pow_self _ (by omega)
  have hleft : (p : ℤ) ∣ t 0 + t 1 + p * u := by
    rw [htraceInt]
    simpa only [neg_mul] using (dvd_neg.mpr (dvd_mul_of_dvd_left hpow
      (t 0 * t 1 + p * w)))
  have hright : (p : ℤ) ∣ (p : ℤ) * u := dvd_mul_right _ _
  convert dvd_sub hleft hright using 1; ring

/-- Only finitely many quotients `(η-1)/p^n` preserve `I`, as used by
`exists_max_power`. The integral norms of these multipliers are bounded away from zero. -/
private theorem exists_non_multiplier_power {η : K} (h : B.IsPeriod η)
    {p : ℕ} [Fact p.Prime]
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J) :
    ∃ n : ℕ, ¬ ∀ x ∈ B.submodule,
      ((η - 1) / (p : K) ^ n) * x ∈ B.submodule := by
  have hp0 : (p : K) ≠ 0 := by exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hne : η - 1 ≠ 0 := by
    intro he
    have he' : η = 1 := sub_eq_zero.mp he
    have hh := h.one_lt
    simp [he'] at hh
  have hq : Algebra.norm ℚ (η - 1) ≠ 0 := Algebra.norm_ne_zero_iff.mpr hne
  have hp1 : (1 : ℚ) < p := by exact_mod_cast (Fact.out : p.Prime).one_lt
  obtain ⟨N, hN⟩ := pow_unbounded_of_one_lt (|Algebra.norm ℚ (η - 1)|)
    (show (1 : ℚ) < (p : ℚ) ^ 2 by nlinarith)
  refine ⟨N, ?_⟩
  intro hPN
  let T : K := (η - 1) / (p : K) ^ N
  obtain ⟨t, ht⟩ := hJ.exists_scalar (a := T) hPN
  have hfg : B.submodule.FG := by
    unfold PseudolatticeBasis.submodule
    exact Submodule.fg_span ((Set.finite_singleton B.scale).insert (B.scale * B.tau))
  obtain ⟨_, w, _, hnorm⟩ := hJ.exists_trace_norm_eq F.finrank_eq_two hfg hPN ht
  have hA : η - 1 = (p : K) ^ N * T := by
    dsimp [T]
    field_simp
  have hnormA : Algebra.norm ℚ (η - 1) =
      (p : ℚ) ^ (2 * N) * ((t 0 * t 1 + p * w : ℤ) : ℚ) := by
    calc
      _ = Algebra.norm ℚ ((p : K) ^ N * T) := by rw [← hA]
      _ = Algebra.norm ℚ ((p : K) ^ N) * Algebra.norm ℚ T := by rw [map_mul]
      _ = ((p : ℚ) ^ 2) ^ N * ((t 0 * t 1 + p * w : ℤ) : ℚ) := by
        rw [map_pow, Algebra.norm_natCast ℚ, F.finrank_eq_two, hnorm]
      _ = _ := by rw [← pow_mul]
  have hk : (t 0 * t 1 + p * w : ℤ) ≠ 0 := by
    intro hk
    have hzero : Algebra.norm ℚ (η - 1) = 0 := by simpa [hk] using hnormA
    exact hq hzero
  have hkle : (1 : ℚ) ≤ |((t 0 * t 1 + p * w : ℤ) : ℚ)| := by
    exact_mod_cast (Int.one_le_abs hk)
  have hlarge : (p : ℚ) ^ (2 * N) ≤ |Algebra.norm ℚ (η - 1)| := by
    rw [hnormA, abs_mul, abs_of_nonneg (pow_nonneg (by positivity) _)]
    exact le_mul_of_one_le_right (pow_nonneg (by positivity) _) hkle
  rw [← pow_mul] at hN
  exact (not_lt_of_ge hlarge) hN

/-- There is a largest `s ≥ 1` for which `(η-1)/p^s` preserves the pseudolattice.
Used by `pseudolatticeDilog_split_translation` as in [RW26b, Radchenko, Wheeler (2026b),
Section 7, proof of Theorem 7]. -/
private theorem exists_max_power {η : K} (h : B.IsPeriod η) {p : ℕ} [Fact p.Prime]
    (hη : ∀ x ∈ B.submodule, (η - 1) / p * x ∈ B.submodule)
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J) :
    ∃ (s : ℕ) (T : K), 1 ≤ s ∧ η - 1 = (p : K) ^ s * T ∧
      (∀ x ∈ B.submodule, T * x ∈ B.submodule) ∧
      ∃ x ∈ B.submodule, T / p * x ∉ B.submodule := by
  let P : ℕ → Prop := fun n => ∀ x ∈ B.submodule, ((η - 1) / (p : K) ^ n) * x ∈ B.submodule
  have hp0 : (p : K) ≠ 0 := by exact_mod_cast (Fact.out : p.Prime).ne_zero
  have hP0 : P 0 := by
    intro x hx
    simpa only [P, pow_zero, div_one, sub_mul, one_mul] using B.submodule.sub_mem (h.mul_mem hx) hx
  have hP1 : P 1 := by simpa only [P, pow_one] using hη
  have hbad : ∃ n, ¬ P n := exists_non_multiplier_power h hJ
  classical
  let n := Nat.find hbad
  have hn : ¬ P n := Nat.find_spec hbad
  have hPn : 1 < n := by
    by_contra hn'
    have heq : n = 0 ∨ n = 1 := by omega
    rcases heq with h0 | h1
    · exact hn (h0 ▸ hP0)
    · exact hn (h1 ▸ hP1)
  have hPs : P (n - 1) := by
    by_contra hs
    exact Nat.find_min hbad (show n - 1 < n by omega) hs
  let s := n - 1
  let T : K := (η - 1) / (p : K) ^ s
  refine ⟨s, T, by dsimp [s]; omega, ?_, hPs, ?_⟩
  · dsimp [T]
    field_simp
  · have hnext : ¬P (s + 1) := by simpa [s, Nat.sub_add_cancel (by omega : 1 ≤ n)] using hn
    simp only [P, not_forall] at hnext
    obtain ⟨x, hx, hnot⟩ := hnext
    refine ⟨x, hx, ?_⟩
    have hdiv : T / p = (η - 1) / (p : K) ^ (s + 1) := by
      dsimp [T]
      rw [pow_succ]
      ring
    rwa [hdiv]
/-- The split-line scalars of `T` are nonzero and distinct modulo an odd `p` when
`T/p` fails to preserve the lattice. Used by `pseudolatticeDilog_split_translation`. -/
private theorem scalar_nonzero_distinct {p : ℕ} [Fact p.Prime] (hp : p ≠ 2)
    {T : K} {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J)
    {t : Fin 2 → ℤ} (ht : ∀ i, ∀ y ∈ J i, T * y - t i * y ∈ B.submodule)
    (hsum : (p : ℤ) ∣ t 0 + t 1)
    (hmax : ∃ x ∈ B.submodule, T / p * x ∉ B.submodule) :
    ¬ (p : ℤ) ∣ t 0 ∧ ¬ (p : ℤ) ∣ t 1 ∧ ¬ (p : ℤ) ∣ t 0 - t 1 := by
  have hboth (h0 : (p : ℤ) ∣ t 0) (h1 : (p : ℤ) ∣ t 1) : False := by
    obtain ⟨x, hx, hnot⟩ := hmax
    have hp0 : (p : K) ≠ 0 := by exact_mod_cast (Fact.out : p.Prime).ne_zero
    have hpx : (p : K) * (x / p) ∈ B.submodule := by
      have heq : (p : K) * (x / p) = x := by field_simp
      rwa [heq]
    have htx := hJ.mul_mem_of_dvd ht h0 h1 hpx
    apply hnot
    convert htx using 1; ring
  have h0 : ¬ (p : ℤ) ∣ t 0 := by
    intro h0
    have h1 : (p : ℤ) ∣ t 1 := by
      have hh := dvd_sub hsum h0
      convert hh using 1; ring
    exact hboth h0 h1
  have h1 : ¬ (p : ℤ) ∣ t 1 := by
    intro h1
    have h0' : (p : ℤ) ∣ t 0 := by
      have hh := dvd_sub hsum h1
      convert hh using 1; ring
    exact hboth h0' h1
  refine ⟨h0, h1, ?_⟩
  intro hd
  have h2t : (p : ℤ) ∣ 2 * t 0 := by
    have hh := dvd_add hsum hd
    convert hh using 1; ring
  rcases Int.Prime.dvd_mul (Fact.out : p.Prime) h2t with h2 | ht0
  · have hp2 : p ∣ 2 := by simpa using h2
    exact hp ((Nat.prime_dvd_prime_iff_eq (Fact.out : p.Prime) Nat.prime_two).mp hp2)
  · exact h0 ((Int.natCast_dvd).mpr ht0)

/-! ### Residues and translation along a split line

The residue homomorphism carries lattice congruences to the finite dilogarithm group; a
translation congruence for a generator extends to its whole cyclic line. -/

/-- A split-line element belongs to `(η-1)⁻¹I` when `(η-1)/p` preserves `I`.
Used by `pseudolatticeDilog_split_translation`. -/
private theorem splitLine_mem_torsion {η : K} {p : ℕ}
    [Fact p.Prime] (hη : ∀ x ∈ B.submodule, (η - 1) / p * x ∈ B.submodule)
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J)
    {i : Fin 2} {y : K} (hy : y ∈ J i) : (η - 1) * y ∈ B.submodule := by
  have hpy := hJ.prime_mul_mem i hy
  have hmem := hη _ hpy
  have hp0 : (p : K) ≠ 0 := by exact_mod_cast (Fact.out : p.Prime).ne_zero
  convert hmem using 1
  field_simp

/-- The residue map transports a translated finite quantum dilogarithm value to its
pseudolattice lift. Used by `pseudolatticeDilog_split_translation`. -/
private theorem finiteQuantumDilog_lift_shift {η : K} (h : B.IsPeriod η)
    [NeZero (finiteDilogOrder h.matrix)] (X U Z : B.torsionLattice η) (m : ℕ) :
    h.finiteQuantumDilog (h.residueHom X + h.residueHom U + m • h.residueHom Z) =
      pseudolatticeDilog h ((X : K) + (U : K) + (m : K) * (Z : K)) := by
  calc
    _ = h.finiteQuantumDilog (h.residueHom (X + U + m • Z)) := by
      rw [map_add, map_add, map_nsmul]
    _ = pseudolatticeDilog h (X + U + m • Z : B.torsionLattice η) :=
      h.finiteQuantumDilog_residueHom _
    _ = _ := by congr 1; simp [nsmul_eq_mul]

/-- Every integer multiple of an element killed by `p` is a natural multiple. Used by
`pseudolatticeDilog_split_translation` to identify excluded summand lines. -/
private theorem zsmul_eq_nsmul_of_torsion {G : Type*} [AddCommGroup G]
    {p : ℕ} (hp : 0 < p) {a : G} (ha : p • a = 0) (m : ℤ) :
    ∃ n : ℕ, m • a = n • a := by
  refine ⟨(m % p).toNat, ?_⟩
  have hp0 : (p : ℤ) ≠ 0 := by exact_mod_cast hp.ne'
  have hm0 : 0 ≤ m % p := Int.emod_nonneg _ hp0
  have hmcast : (((m % p).toNat : ℕ) : ℤ) = m % p := Int.toNat_of_nonneg hm0
  have hdecomp : m = m % p + (p : ℤ) * (m / p) := (Int.emod_add_mul_ediv m p).symm
  calc
    m • a = (m % p) • a + ((p : ℤ) * (m / p)) • a := by rw [← add_zsmul, ← hdecomp]
    _ = (m % p) • a := by
      rw [mul_comm (p : ℤ), mul_zsmul]
      simp [ha]
    _ = (m % p).toNat • a := by
      simpa only [natCast_zsmul] using congrArg (fun z : ℤ => z • a) hmcast.symm

/-- A valuation congruence under translation by `a` extends to natural multiples of
`a`. Used by `valuation_translation_zsmul`. -/
private theorem valuation_translation_nsmul {G : Type*} [AddCommGroup G]
    (v : Valuation ℂ ℝ≥0) (E : G → ℂ) {a : G}
    (ha : ∀ g, v (E (g + a) - E g) < 1) (g : G) (n : ℕ) :
    v (E (g + n • a) - E g) < 1 := by
  induction n with
  | zero => simp
  | succ n ih =>
      have hstep := ha (g + n • a)
      have heq : E (g + (n + 1) • a) - E g =
          (E ((g + n • a) + a) - E (g + n • a)) +
            (E (g + n • a) - E g) := by
        rw [succ_nsmul]
        abel_nf
      rw [heq]
      exact v.map_add_lt hstep ih

/-- A valuation congruence under translation by `a` extends to all integer multiples
of `a`. Used by `splitLine_translation_of_generator`. -/
private theorem valuation_translation_zsmul {G : Type*} [AddCommGroup G]
    (v : Valuation ℂ ℝ≥0) (E : G → ℂ) {a : G}
    (ha : ∀ g, v (E (g + a) - E g) < 1) (g : G) (m : ℤ) :
    v (E (g + m • a) - E g) < 1 := by
  cases m with
  | ofNat n => simpa only [Int.ofNat_eq_natCast, natCast_zsmul] using
        valuation_translation_nsmul v E ha g n
  | negSucc n =>
      have hb : ∀ t, v (E (t + (-a)) - E t) < 1 := by
        intro t
        have hh := ha (t - a)
        have heq : E (t + -a) - E t = -(E ((t - a) + a) - E (t - a)) := by
          abel_nf
        rw [heq, v.map_neg]
        exact hh
      simpa only [negSucc_zsmul, neg_nsmul] using
        valuation_translation_nsmul v E hb g (n + 1)

/-- Congruence under a generator of `J_i/I` extends to every element of the split
line `J_i/I`. Used by `pseudolatticeDilog_split_translation`. -/
private theorem splitLine_translation_of_generator (v : Valuation ℂ ℝ≥0)
    {η : K} (h : B.IsPeriod η) [NeZero (finiteDilogOrder h.matrix)]
    {p : ℕ} [Fact p.Prime]
    (hη : ∀ x ∈ B.submodule, (η - 1) / p * x ∈ B.submodule)
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J)
    {i : Fin 2} {w : K} (hw : w ∈ J i) (hwI : w ∉ B.submodule)
    (ha : ∀ g : finiteDilogGroup h.matrix,
      v (h.finiteQuantumDilog (g + h.residueHom
        (⟨w, splitLine_mem_torsion hη hJ hw⟩ : B.torsionLattice η)) -
        h.finiteQuantumDilog g) < 1) :
    ∀ x : K, (η - 1) * x ∈ B.submodule → ∀ y ∈ J i,
      v (pseudolatticeDilog h (x + y) - pseudolatticeDilog h x) < 1 := by
  let W : B.torsionLattice η := ⟨w, splitLine_mem_torsion hη hJ hw⟩
  intro x hx y hy
  let X : B.torsionLattice η := ⟨x, hx⟩
  let Y : B.torsionLattice η := ⟨y, splitLine_mem_torsion hη hJ hy⟩
  obtain ⟨m, hm⟩ := hJ.exists_int_sub_mem hw hwI hy
  have hyEq : h.residueHom Y = m • h.residueHom W := by
    have hmem : ((Y - m • W : B.torsionLattice η) : K) ∈ B.submodule := by
      simpa [Y, W, zsmul_eq_mul] using hm
    have hzero := (h.residueHom_eq_zero_iff _).mpr hmem
    have hzero' : h.residueHom Y - m • h.residueHom W = 0 := by
      simpa only [map_sub, map_zsmul] using hzero
    exact sub_eq_zero.mp hzero'
  have hval := valuation_translation_zsmul v h.finiteQuantumDilog (by simpa [W] using ha)
    (h.residueHom X) m
  rw [← hyEq, ← map_add] at hval
  rw [h.finiteQuantumDilog_residueHom X, h.finiteQuantumDilog_residueHom (X + Y)] at hval
  simpa [X, Y] using hval

/-! ### Cyclic summands away from the split lines

The two line generators are independent. A summand whose `p`-torsion avoids them has no
eigenvector for `T`, so its product congruence follows from the cyclic summand theorem. -/

/-- Generators of the two split lines give independent `p`-torsion residues, as used by
`pseudolatticeDilog_split_translation`. -/
private theorem splitLine_generators_independent {η : K} (h : B.IsPeriod η)
    {p : ℕ} [Fact p.Prime] {J : Fin 2 → Submodule ℤ K}
    (hJ : IsSplitLinePair p B.submodule J) (W : Fin 2 → B.torsionLattice η)
    (hW : ∀ i, (W i : K) ∈ J i) (hWI : ∀ i, (W i : K) ∉ B.submodule) :
    ∀ i j : ZMod p,
      i.val • h.residueHom (W 0) + j.val • h.residueHom (W 1) = 0 →
        i = 0 ∧ j = 0 := by
  intro i j hij
  let X : B.torsionLattice η := i.val • W 0 + j.val • W 1
  have hzero : h.residueHom X = 0 := by
    simpa only [X, map_add, map_nsmul] using hij
  have hmem : ((i.val : K) * (W 0 : K) + (j.val : K) * (W 1 : K)) ∈
      B.submodule := by
    have hh := (h.residueHom_eq_zero_iff X).mp hzero
    simpa [X, nsmul_eq_mul] using hh
  let m : Fin 2 → ℤ := fun k => if k = 0 then i.val else j.val
  have hd := hJ.dvd_of_add_mem hW hWI (m := m) (by simpa [m] using hmem)
  have hdi : p ∣ i.val := (Int.natCast_dvd_natCast).mp (by simpa [m] using hd 0)
  have hdj : p ∣ j.val := (Int.natCast_dvd_natCast).mp (by simpa [m] using hd 1)
  constructor
  · have hi0 : (i.val : ZMod p) = 0 := (ZMod.natCast_eq_zero_iff i.val p).mpr hdi
    simpa only [ZMod.natCast_zmod_val] using hi0
  · have hj0 : (j.val : ZMod p) = 0 := (ZMod.natCast_eq_zero_iff j.val p).mpr hdj
    simpa only [ZMod.natCast_zmod_val] using hj0

/-- If the `p`-torsion of a cyclic summand avoids both split lines, it cannot be an
eigenvector of the multiplier `T`. Used by `splitLine_summand_congr`, following
[RW26b, Radchenko, Wheeler (2026b), Section 7, proof of Theorem 7]. -/
private theorem splitLine_nonEigen_of_avoids {η : K} (h : B.IsPeriod η)
    {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s) {T : K}
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J)
    {t : Fin 2 → ℤ} (ht : ∀ i, ∀ y ∈ J i, T * y - t i * y ∈ B.submodule)
    (htdiff : ¬ (p : ℤ) ∣ t 0 - t 1) (W : Fin 2 → B.torsionLattice η)
    (hW : ∀ i, (W i : K) ∈ J i) (hWI : ∀ i, (W i : K) ∉ B.submodule)
    (hat : ∀ i, p • h.residueHom (W i) = 0) (Z : B.torsionLattice η)
    (hzK : (p : K) ^ s * (Z : K) ∈ B.submodule)
    (havoid : ∀ (i : Fin 2) (n : ℕ),
      p ^ (s - 1) • h.residueHom Z ≠ n • h.residueHom (W i)) :
    ∀ c : ℤ,
      T * ((p : K) ^ (s - 1) * (Z : K)) -
        c * ((p : K) ^ (s - 1) * (Z : K)) ∉ B.submodule := by
  let y : K := (p : K) ^ (s - 1) * (Z : K)
  have hpy : (p : K) * y ∈ B.submodule := by
    have hpow : (p : K) * (p : K) ^ (s - 1) = (p : K) ^ s := by
      calc
        _ = (p : K) ^ (s - 1 + 1) := by rw [pow_succ]; ring
        _ = _ := by rw [Nat.sub_add_cancel hs]
    change (p : K) * ((p : K) ^ (s - 1) * (Z : K)) ∈ B.submodule
    rw [← mul_assoc, hpow]
    exact hzK
  intro c hc
  have hlinecontra (i : Fin 2) (hy : y ∈ J i) : False := by
    obtain ⟨m, hm⟩ := hJ.exists_int_sub_mem (hW i) (hWI i) hy
    have hmem : ((p ^ (s - 1) • Z - m • W i : B.torsionLattice η) : K) ∈
        B.submodule := by
      simpa [y, nsmul_eq_mul, zsmul_eq_mul] using hm
    have hzero := (h.residueHom_eq_zero_iff _).mpr hmem
    have hEq : p ^ (s - 1) • h.residueHom Z = m • h.residueHom (W i) := by
      have hEq0 : p ^ (s - 1) • h.residueHom Z - m • h.residueHom (W i) = 0 := by
        simpa only [map_sub, map_nsmul, map_zsmul] using hzero
      exact sub_eq_zero.mp hEq0
    obtain ⟨n, hmn⟩ := zsmul_eq_nsmul_of_torsion (Fact.out : p.Prime).pos (hat i) m
    exact havoid i n (hEq.trans hmn)
  rcases hJ.mem_or_mem_of_mul_sub_mem ht htdiff hpy hc with h0 | h1
  · exact hlinecontra 0 h0
  · exact hlinecontra 1 h1

/-- The cyclic summand congruence on the pseudolattice supplies the summand hypothesis of
`FiniteQuantumDilog.translation_invariant_of_summands`. -/
private theorem splitLine_summand_congr (v : Valuation ℂ ℝ≥0) {p : ℕ}
    [Fact p.Prime] (hvp : v (p : ℂ) < 1) {η : K} (h : B.IsPeriod η)
    [NeZero (finiteDilogOrder h.matrix)] {s : ℕ} {T : K} (hs : 1 ≤ s)
    (hT : η - 1 = (p : K) ^ s * T) (hTI : ∀ x ∈ B.submodule, T * x ∈ B.submodule)
    {J : Fin 2 → Submodule ℤ K} (hJ : IsSplitLinePair p B.submodule J)
    {t : Fin 2 → ℤ} (ht : ∀ i, ∀ y ∈ J i, T * y - t i * y ∈ B.submodule)
    (htdiff : ¬ (p : ℤ) ∣ t 0 - t 1) (W : Fin 2 → B.torsionLattice η)
    (hW : ∀ i, (W i : K) ∈ J i) (hWI : ∀ i, (W i : K) ∉ B.submodule)
    (hat : ∀ i, p • h.residueHom (W i) = 0) : ∀ z : finiteDilogGroup h.matrix,
      addOrderOf z = p ^ s →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • h.residueHom (W 0)) →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • h.residueHom (W 1)) →
      ∀ x u : finiteDilogGroup h.matrix, p • u = 0 →
      v (∏ m ∈ Finset.range (p ^ s), h.finiteQuantumDilog (x + u + m • z) -
        ∏ m ∈ Finset.range (p ^ s), h.finiteQuantumDilog (x + m • z)) < 1 := by
  intro z hz hza hzb x u hu
  obtain ⟨Z, hZ⟩ := h.residueHom_surjective z
  obtain ⟨X, hX⟩ := h.residueHom_surjective x
  obtain ⟨U, hU⟩ := h.residueHom_surjective u
  have hzK : (p : K) ^ s * (Z : K) ∈ B.submodule := by
    have hh := (h.residueHom_nsmul_eq_zero_iff Z (p ^ s)).mp (by
      rw [hZ, ← hz]
      exact addOrderOf_nsmul_eq_zero z)
    simpa only [Nat.cast_pow] using hh
  have huK : (p : K) * (U : K) ∈ B.submodule := by
    apply (h.residueHom_nsmul_eq_zero_iff U p).mp
    simpa only [hU] using hu
  have havoidZ (i : Fin 2) (n : ℕ) :
      p ^ (s - 1) • h.residueHom Z ≠ n • h.residueHom (W i) := by
    rw [hZ]
    fin_cases i
    · exact hza n
    · exact hzb n
  have hzT := splitLine_nonEigen_of_avoids h hs hJ ht htdiff W hW hWI hat Z hzK havoidZ
  have hprod := pseudolatticeDilog_prod_summand_congr v hvp h hT hTI hzK hzT X.2 huK
  have hleft :
      (∏ m ∈ Finset.range (p ^ s), h.finiteQuantumDilog (x + u + m • z)) =
        ∏ m ∈ Finset.range (p ^ s),
          pseudolatticeDilog h ((X : K) + (U : K) + (m : K) * (Z : K)) := by
    apply Finset.prod_congr rfl
    intro m hm
    rw [← hX, ← hU, ← hZ]
    exact finiteQuantumDilog_lift_shift h X U Z m
  have hright :
      (∏ m ∈ Finset.range (p ^ s), h.finiteQuantumDilog (x + m • z)) =
        ∏ m ∈ Finset.range (p ^ s),
          pseudolatticeDilog h ((X : K) + (m : K) * (Z : K)) := by
    apply Finset.prod_congr rfl
    intro m hm
    simpa [← hX, ← hZ] using
      (finiteQuantumDilog_lift_shift h X (0 : B.torsionLattice η) Z m)
  rwa [hleft, hright]

/-! ### Theorem 7 for a pseudolattice

The lattice part of the proof, feeding `FiniteQuantumDilog.translation_invariant_of_summands`. -/

/-- **[RW26b, Radchenko, Wheeler (2026b), Section 7, Theorem 7] (translation invariance at split
primes)**: let `p` be an odd prime, `v` a valuation of `ℂ` with `v(p) < 1`, `η` a period of `I`
with `(η - 1)/p` in the multiplier ring of `I`, and `J₀, J₁` a split pair of lines of `I` at `p`.
Then for one `i`, independent of `x`,

$$E_{I,\eta}(x+a)\equiv E_{I,\eta}(x)\pmod{\mathfrak m}\qquad(x\in G_{I,\eta},\ a\in J_i/I).$$

The source's hypotheses, `I` locally maximal at the odd split prime `p` and
`η ≡ 1 (mod p𝒪_K)`, give these with `J = (𝔭⁻¹I, 𝔮⁻¹I)`. -/
@[source "RW26b, Theorem 7, p. 12"]
theorem pseudolatticeDilog_split_translation (v : Valuation ℂ ℝ≥0) {p : ℕ} [Fact p.Prime]
    (hp : p ≠ 2) (hvp : v (p : ℂ) < 1) {η : K} (h : B.IsPeriod η)
    (hη : ∀ x ∈ B.submodule, (η - 1) / p * x ∈ B.submodule) {J : Fin 2 → Submodule ℤ K}
    (hJ : IsSplitLinePair p B.submodule J) :
    ∃ i, ∀ x : K, (η - 1) * x ∈ B.submodule → ∀ y ∈ J i,
      v (pseudolatticeDilog h (x + y) - pseudolatticeDilog h x) < 1 := by
  have : NeZero (finiteDilogOrder h.matrix) := finiteDilogOrder_neZero h.isAttractiveFixedPoint
  obtain ⟨s, T, hs, hT, hTI, hmax⟩ := exists_max_power h hη hJ
  obtain ⟨t, ht⟩ := hJ.exists_scalar hTI
  have hsum := scalar_sum_dvd h hs hT hJ hTI ht
  obtain ⟨ht0, ht1, htdiff⟩ := scalar_nonzero_distinct hp hJ ht hsum hmax
  have hTp : ∀ y : K, T * y ∈ B.submodule → (p : K) * y ∈ B.submodule →
      y ∈ B.submodule := by
    intro y hy hpy
    exact hJ.mem_of_mul_mem ht ht0 ht1 hpy hy
  obtain ⟨e, he, hH⟩ := h.exists_primaryEmbedding hT hTI hTp
  choose w hw hwI using fun i => hJ.exists_mem_notMem i
  let W (i : Fin 2) : B.torsionLattice η :=
    ⟨w i, splitLine_mem_torsion hη hJ (hw i)⟩
  let a (i : Fin 2) : finiteDilogGroup h.matrix := h.residueHom (W i)
  have hat (i : Fin 2) : p • a i = 0 := by
    change p • h.residueHom (W i) = 0
    exact (h.residueHom_nsmul_eq_zero_iff (W i) p).mpr (hJ.prime_mul_mem i (hw i))
  have hW (i : Fin 2) : (W i : K) ∈ J i := hw i
  have hWI (i : Fin 2) : (W i : K) ∉ B.submodule := hwI i
  have hab := splitLine_generators_independent h hJ W hW hWI
  have hL := splitLine_summand_congr v hvp h hs hT hTI hJ ht htdiff W hW hWI hat
  have hunit : ∀ g : finiteDilogGroup h.matrix, v (h.finiteQuantumDilog g) = 1 := by
    intro g
    obtain ⟨X, rfl⟩ := h.residueHom_surjective g
    rw [h.finiteQuantumDilog_residueHom X]
    exact pseudolatticeDilog_valuation_eq_one v hvp h X.2
  rcases h.finiteQuantumDilog.translation_invariant_of_summands v hvp hunit hs e he hH
    (hat 0) (hat 1) hab hL with ha | hb
  · refine ⟨0, ?_⟩
    exact splitLine_translation_of_generator v h hη hJ (hw 0) (hwI 0)
      (by simpa [a, W] using ha)
  · refine ⟨1, ?_⟩
    exact splitLine_translation_of_generator v h hη hJ (hw 1) (hwI 1)
      (by simpa [a, W] using hb)


end SIC

end
