/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import Mathlib.Analysis.Fourier.FiniteAbelian.PontryaginDuality
import Mathlib.Algebra.CharP.Lemmas
import Mathlib.Analysis.SpecialFunctions.Complex.CircleAddChar
import Mathlib.Tactic
import SICs.Analysis.CharacterSums
import SICs.Source

/-!
# Separation of variables from products over cyclic summands

A function `g : (ℤ/p^s)² → k^×` into a field of characteristic `p` whose products over the cyclic
summands `L` of order `p^s`, other than those with `L[p] = ⟨a⟩` or `⟨b⟩`, are invariant under the
`p`-torsion satisfies `g(x + a + b)g(x) = g(x + a)g(x + b)`; so on each coset of the `p`-torsion it
is a product of a function of the `a`-coordinate and a function of the `b`-coordinate.

This module follows [RW26b, Radchenko, Wheeler (2026b), Section 7, Lemma 6]. A cyclic summand of
order `p^s` of `H = (ℤ/p^s)²` is generated by an element `z` of order `p^s`, and
`L[p] = ⟨p^{s-1}z⟩`; the hypothesis is stated for these generators, with the product over
`L = {mz : 0 ≤ m < p^s}`.

## The argument

In the group ring `ℤ[H]`, with `[L] = ∑_{ℓ ∈ L} [ℓ]` and `L` running over the summands of the
statement, `([a] - [0])([b] - [0]) ∑_L [L] = p^s ([a] - [0])([b] - [0])`. Indeed a complex
character `χ` of `H` annihilates both sides unless `χ(a) ≠ 1` and `χ(b) ≠ 1`; such a `χ` is
nontrivial on `H[p]`, so it has order `p^s` and its kernel is one of the summands
`L` (a cyclic summand of order `p^s` whose `p`-torsion is neither `⟨a⟩` nor `⟨b⟩`); then
`χ([L]) = p^s` for `L = ker χ` and `0` for the other summands. Characters separate the elements
of `ℂ[H]`. Evaluating the identity multiplicatively on `g` at `x`, the left side is the
second difference `([a] - [0])([b] - [0])` of the invariant products, which is `1`, so
`D(x)^{p^s} = 1` for `D(x) = g(x + a + b)g(x)/(g(x + a)g(x + b))`. In characteristic `p`,
`D^{p^s} - 1 = (D - 1)^{p^s}`, so `D(x) = 1`.
-/

namespace SIC

/-! ### Lemma 6

The line incidence weight is summed once per distinct finite cyclic line. Its Fourier transform
is evaluated by the character-kernel description, and the resulting identity is then applied
to the products of `g` along the lines. -/

/-- The group $(\mathbb Z/p^s)^2$ used throughout Lemma 6. -/
private abbrev H (p s : ℕ) := Fin 2 → ZMod (p ^ s)

/-- Nonunits of `ZMod (p^s)` are divisible by `p`, used in the character classification. -/
private theorem nonunit_eq_p_mul {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {c : ZMod (p ^ s)} (hc : ¬IsUnit c) :
    ∃ d : ZMod (p ^ s), c = (p : ZMod (p ^ s)) * d := by
  have hpdiv : p ∣ c.val := by
    by_contra hn
    apply hc
    rw [← ZMod.natCast_zmod_val c]
    exact (ZMod.isUnit_natCast_iff_not_dvd_pow Fact.out hs).mpr hn
  obtain ⟨d, hd⟩ := hpdiv
  refine ⟨d, ?_⟩
  rw [← ZMod.natCast_zmod_val c, hd]
  push_cast
  ring

/-- A character nontrivial on `p`-torsion has a unit coordinate coefficient. -/
private theorem coord_unit_of_nontrivial_torsion {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    (c a : H p s) (ha : p • a = 0) (hχa : residueCoordinateChar (p ^ s) c a ≠ 1) :
    IsUnit (c 0) ∨ IsUnit (c 1) := by
  classical
  by_contra h
  push Not at h
  obtain ⟨d₀, hd₀⟩ := nonunit_eq_p_mul hs h.1
  obtain ⟨d₁, hd₁⟩ := nonunit_eq_p_mul hs h.2
  have ha₀ : (p : ZMod (p ^ s)) * a 0 = 0 := by
    simpa only [Pi.smul_apply, Pi.zero_apply, nsmul_eq_mul] using congrFun ha 0
  have ha₁ : (p : ZMod (p ^ s)) * a 1 = 0 := by
    simpa only [Pi.smul_apply, Pi.zero_apply, nsmul_eq_mul] using congrFun ha 1
  have hc : c 0 * a 0 + c 1 * a 1 = 0 := by
    rw [hd₀, hd₁]
    calc
      (p : ZMod (p ^ s)) * d₀ * a 0 + (p : ZMod (p ^ s)) * d₁ * a 1 =
          d₀ * ((p : ZMod (p ^ s)) * a 0) + d₁ * ((p : ZMod (p ^ s)) * a 1) := by ring
      _ = 0 := by rw [ha₀, ha₁]; ring
  apply hχa
  change ZMod.stdAddChar (c 0 * a 0 + c 1 * a 1) = 1
  rw [hc, AddChar.map_zero_eq_one]

/-- The finite cyclic line generated by `z`, used in `mul_eq_mul_of_prod_summand_invariant`. -/
private def cyclicLine (p s : ℕ) (z : H p s) : Finset (H p s) :=
  (Finset.range (p ^ s)).image (fun m => m • z)

/-- The graph generator for a character with unit first coefficient. -/
private def fstKernelGenerator {p s : ℕ} (c : H p s) : H p s :=
  ![-(c 0)⁻¹ * c 1, 1]

/-- The graph generator has order `p^s`. -/
private theorem fstKernelGenerator_order {p s : ℕ} (c : H p s) :
    addOrderOf (fstKernelGenerator c) = p ^ s := by
  have hqz : (p ^ s) • fstKernelGenerator c = 0 := by
    funext i
    simp only [Pi.smul_apply, Pi.zero_apply, nsmul_eq_mul]
    rw [ZMod.natCast_self, zero_mul]
  apply Nat.dvd_antisymm
  · exact addOrderOf_dvd_iff_nsmul_eq_zero.mpr hqz
  · have h := addOrderOf_apply_dvd_addOrderOf (x := fstKernelGenerator c) 1
    simpa [fstKernelGenerator, ZMod.addOrderOf_one] using h

/-- The graph generator lies in the character kernel. -/
private theorem fstKernelGenerator_dot_zero {p s : ℕ} (c : H p s)
    (hc : IsUnit (c 0)) :
    c 0 * (fstKernelGenerator c) 0 + c 1 * (fstKernelGenerator c) 1 = 0 := by
  have hc0 : c 0 * (c 0)⁻¹ = 1 := ZMod.mul_inv_of_unit _ hc
  simp only [fstKernelGenerator, Matrix.cons_val_zero, Matrix.cons_val_one, mul_one]
  calc
    c 0 * (-(c 0)⁻¹ * c 1) + c 1 = -(c 0 * (c 0)⁻¹) * c 1 + c 1 := by ring
    _ = 0 := by rw [hc0]; ring

/-- Solving the character equation when the first coefficient is a unit. -/
private theorem fst_eq_of_dot_zero {p s : ℕ} (c v : H p s)
    (hc : IsUnit (c 0)) (hzero : c 0 * v 0 + c 1 * v 1 = 0) :
    v 0 = (-(c 0)⁻¹ * c 1) * v 1 := by
  have hc0 : c 0 * (c 0)⁻¹ = 1 := ZMod.mul_inv_of_unit _ hc
  have hca : c 0 * v 0 = -(c 1 * v 1) := eq_neg_of_add_eq_zero_left hzero
  calc
    v 0 = ((c 0)⁻¹ * c 0) * v 0 := by rw [mul_comm (c 0)⁻¹ (c 0), hc0, one_mul]
    _ = (c 0)⁻¹ * (c 0 * v 0) := by ring
    _ = (-(c 0)⁻¹ * c 1) * v 1 := by rw [hca]; ring

/-- Membership in the graph line is equivalent to vanishing of its character. -/
private theorem mem_fstKernelGenerator_iff {p s : ℕ} [Fact p.Prime]
    (c : H p s) (hc : IsUnit (c 0)) (v : H p s) :
    v ∈ cyclicLine p s (fstKernelGenerator c) ↔ residueCoordinateChar (p ^ s) c v = 1 := by
  classical
  let z := fstKernelGenerator c
  have hz := fstKernelGenerator_dot_zero c hc
  constructor
  · intro hv
    obtain ⟨m, hm, hmv⟩ := Finset.mem_image.mp hv
    have hzchar : residueCoordinateChar (p ^ s) c z = 1 := by
      change ZMod.stdAddChar (c 0 * z 0 + c 1 * z 1) = 1
      rw [hz, AddChar.map_zero_eq_one]
    rw [← hmv, (residueCoordinateChar (p ^ s) c).map_nsmul_eq_pow, hzchar, one_pow]
  · intro hv
    have hdot : c 0 * v 0 + c 1 * v 1 = 0 := by
      apply ZMod.injective_stdAddChar
      change ZMod.stdAddChar (c 0 * v 0 + c 1 * v 1) = 1 at hv
      simpa only [AddChar.map_zero_eq_one] using hv
    have hv0 := fst_eq_of_dot_zero c v hc hdot
    apply Finset.mem_image.mpr
    refine ⟨(v 1).val, Finset.mem_range.mpr (ZMod.val_lt _), ?_⟩
    funext i
    fin_cases i
    · change (v 1).val • z 0 = v 0
      calc
        (v 1).val • z 0 = (v 1) * (-(c 0)⁻¹ * c 1) := by
          simp [z, fstKernelGenerator, nsmul_eq_mul]
        _ = v 0 := by rw [mul_comm]; exact hv0.symm
    · simp [fstKernelGenerator, Pi.smul_apply, nsmul_eq_mul]

/-- A unit first coordinate makes the character kernel a single cyclic line. -/
private theorem kernel_line_of_unit_fst {p s : ℕ} [Fact p.Prime]
    (c : H p s) (hc : IsUnit (c 0)) :
    ∃ z : H p s, addOrderOf z = p ^ s ∧
      ∀ v : H p s, v ∈ cyclicLine p s z ↔ residueCoordinateChar (p ^ s) c v = 1 :=
  ⟨fstKernelGenerator c, fstKernelGenerator_order c, mem_fstKernelGenerator_iff c hc⟩

/-- Swapping the two coordinates identifies the symmetric character-kernel cases. -/
private def swapCoords {p s : ℕ} : H p s ≃+ H p s where
  toFun v := ![v 1, v 0]
  invFun v := ![v 1, v 0]
  left_inv v := by funext i; fin_cases i <;> simp
  right_inv v := by funext i; fin_cases i <;> simp
  map_add' v w := by funext i; fin_cases i <;> simp

/-- The coordinate pairing is unchanged by swapping both its arguments. -/
private theorem residueChar_swap {p s : ℕ} [NeZero (p ^ s)]
    (c v : H p s) :
    residueCoordinateChar (p ^ s) (swapCoords c) (swapCoords v) =
      residueCoordinateChar (p ^ s) c v := by
  change ZMod.stdAddChar ((swapCoords c) 0 * (swapCoords v) 0 +
    (swapCoords c) 1 * (swapCoords v) 1) =
    ZMod.stdAddChar (c 0 * v 0 + c 1 * v 1)
  change ZMod.stdAddChar (c 1 * v 1 + c 0 * v 0) =
    ZMod.stdAddChar (c 0 * v 0 + c 1 * v 1)
  rw [add_comm]

/-- Swapping both coordinates twice is the identity. -/
private theorem swapCoords_swap {p s : ℕ} (v : H p s) : swapCoords (swapCoords v) = v :=
  swapCoords.left_inv v

/-- Swapping coordinates commutes with natural scalar multiplication. -/
private theorem swapCoords_nsmul {p s : ℕ} (n : ℕ) (v : H p s) :
    swapCoords (n • v) = n • swapCoords v := by
  funext i
  fin_cases i <;> simp [swapCoords, Pi.smul_apply]

/-- Swapping coordinates carries a cyclic line to the line of the swapped generator. -/
private theorem mem_cyclicLine_swap {p s : ℕ} (z v : H p s) :
    v ∈ cyclicLine p s z ↔ swapCoords v ∈ cyclicLine p s (swapCoords z) := by
  classical
  constructor
  · intro hv
    obtain ⟨m, hm, hmv⟩ := Finset.mem_image.mp hv
    apply Finset.mem_image.mpr
    refine ⟨m, hm, ?_⟩
    rw [← hmv]
    exact (swapCoords_nsmul m z).symm
  · intro hv
    obtain ⟨m, hm, hmv⟩ := Finset.mem_image.mp hv
    apply Finset.mem_image.mpr
    refine ⟨m, hm, ?_⟩
    apply swapCoords.injective
    rw [swapCoords_nsmul]
    exact hmv

/-- A unit second coordinate makes the character kernel a single cyclic line. -/
private theorem kernel_line_of_unit_snd {p s : ℕ} [Fact p.Prime]
    (c : H p s) (hc : IsUnit (c 1)) :
    ∃ z : H p s, addOrderOf z = p ^ s ∧
      ∀ v : H p s, v ∈ cyclicLine p s z ↔ residueCoordinateChar (p ^ s) c v = 1 := by
  have hc' : IsUnit ((swapCoords c) 0) := by simpa [swapCoords] using hc
  obtain ⟨z, hz, hker⟩ := kernel_line_of_unit_fst (swapCoords c) hc'
  refine ⟨swapCoords z, ?_, ?_⟩
  · simpa only [swapCoords.addOrderOf_eq] using hz
  · intro v
    have hswap := hker (swapCoords v)
    rw [residueChar_swap c v] at hswap
    simpa only [swapCoords_swap] using
      (mem_cyclicLine_swap (swapCoords z) v).trans
        (by simpa only [swapCoords_swap] using hswap)

/-- Every character nontrivial on `a` has a cyclic kernel of order `p^s`. -/
private theorem exists_char_kernel_line {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    (a : H p s) (ha : p • a = 0) (χ : AddChar (H p s) ℂ) (hχa : χ a ≠ 1) :
    ∃ z : H p s, addOrderOf z = p ^ s ∧
      ∀ v : H p s, v ∈ cyclicLine p s z ↔ χ v = 1 := by
  obtain ⟨c, rfl⟩ := exists_residueCoordinateChar (p ^ s) χ
  rcases coord_unit_of_nontrivial_torsion hs c a ha hχa with hc | hc
  · exact kernel_line_of_unit_fst c hc
  · exact kernel_line_of_unit_snd c hc

/-- A character of order `p` is injective on its generated `p`-torsion line. -/
private theorem nsmul_eq_zero_of_char_eq_one {p : ℕ} [Fact p.Prime]
    {G : Type*} [AddCommGroup G] {a : G} (ha : p • a = 0)
    (χ : AddChar G ℂ) (hχa : χ a ≠ 1) {n : ℕ} (hn : χ (n • a) = 1) :
    n • a = 0 := by
  have hχpow : χ a ^ p = 1 := by
    rw [← χ.map_nsmul_eq_pow, ha, AddChar.map_zero_eq_one]
  have hporder : orderOf (χ a) = p := orderOf_eq_prime hχpow hχa
  have hpn : p ∣ n := by
    rw [← hporder, orderOf_dvd_iff_pow_eq_one]
    simpa only [χ.map_nsmul_eq_pow] using hn
  obtain ⟨m, rfl⟩ := hpn
  rw [mul_comm p m, mul_smul, ha, smul_zero]

/-- The `p`-torsion of a full-order generator is nonzero. -/
private theorem generator_torsion_ne_zero {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {z : H p s} (hz : addOrderOf z = p ^ s) : p ^ (s - 1) • z ≠ 0 := by
  obtain ⟨t, rfl⟩ := Nat.exists_eq_succ_of_ne_zero (by omega : s ≠ 0)
  intro h
  have hdvd : p ^ (t + 1) ∣ p ^ t := by
    rw [← hz]
    simpa using (addOrderOf_dvd_iff_nsmul_eq_zero.mpr h)
  have hlt : p ^ t < p ^ (t + 1) :=
    pow_lt_pow_right₀ (Fact.out : p.Prime).one_lt (by omega)
  have hle : p ^ (t + 1) ≤ p ^ t := Nat.le_of_dvd (pow_pos (Fact.out : p.Prime).pos _) hdvd
  omega

/-- The kernel line is distinct from the two excluded `p`-torsion directions. -/
private theorem char_kernel_line_good {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {a b z : H p s} (ha : p • a = 0) (hb : p • b = 0)
    (χ : AddChar (H p s) ℂ) (hχa : χ a ≠ 1) (hχb : χ b ≠ 1)
    (hz : addOrderOf z = p ^ s) (hker : ∀ v, v ∈ cyclicLine p s z ↔ χ v = 1) :
    (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) ∧
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) := by
  have htmem : p ^ (s - 1) • z ∈ cyclicLine p s z := by
    apply Finset.mem_image.mpr
    refine ⟨p ^ (s - 1), Finset.mem_range.mpr ?_, rfl⟩
    exact pow_lt_pow_right₀ (Fact.out : p.Prime).one_lt (Nat.sub_lt hs (by omega))
  have htchar := (hker _).mp htmem
  constructor
  · intro n hn
    have hna : χ (n • a) = 1 := by rw [← hn]; exact htchar
    have hn0 := nsmul_eq_zero_of_char_eq_one ha χ hχa hna
    exact generator_torsion_ne_zero hs (by rw [hz]) (hn.trans hn0)
  · intro n hn
    have hnb : χ (n • b) = 1 := by rw [← hn]; exact htchar
    have hn0 := nsmul_eq_zero_of_char_eq_one hb χ hχb hnb
    exact generator_torsion_ne_zero hs (by rw [hz]) (hn.trans hn0)

/-- Distinct exponents below the order of `z` give distinct points of its cyclic line. -/
private theorem cyclicLine_injective {p s : ℕ} {z : H p s}
    (hz : addOrderOf z = p ^ s) :
    Set.InjOn (fun m : ℕ => m • z) (Finset.range (p ^ s) : Set ℕ) := by
  intro m hm n hn hmn
  have hm' : m < p ^ s := Finset.mem_range.mp hm
  have hn' : n < p ^ s := Finset.mem_range.mp hn
  have hmod := (nsmul_inj_mod.mp hmn)
  rw [hz, Nat.mod_eq_of_lt hm', Nat.mod_eq_of_lt hn'] at hmod
  exact hmod

/-- The cyclic line has precisely `p^s` elements. -/
private theorem cyclicLine_card {p s : ℕ} {z : H p s}
    (hz : addOrderOf z = p ^ s) : (cyclicLine p s z).card = p ^ s := by
  classical
  rw [cyclicLine, Finset.card_image_iff.mpr (cyclicLine_injective hz)]
  simp

/-- Sum of a character over one cyclic line. -/
private theorem char_sum_cyclicLine {p s : ℕ} {z : H p s}
    (hz : addOrderOf z = p ^ s) (χ : AddChar (H p s) ℂ) :
    ∑ v ∈ cyclicLine p s z, χ v = if χ z = 1 then (p ^ s : ℂ) else 0 := by
  classical
  have hinj := cyclicLine_injective hz
  rw [cyclicLine, Finset.sum_image hinj]
  simp_rw [χ.map_nsmul_eq_pow]
  split_ifs with hχ
  · simp [hχ]
  · have hpow : χ z ^ (p ^ s) = 1 := by
      have hqz : p ^ s • z = 0 := by simpa only [hz] using addOrderOf_nsmul_eq_zero z
      calc
        χ z ^ (p ^ s) = χ (p ^ s • z) := (χ.map_nsmul_eq_pow _ _).symm
        _ = 1 := by rw [hqz, AddChar.map_zero_eq_one]
    rw [geom_sum_eq hχ (p ^ s), hpow, sub_self, zero_div]

/-- Each admissible cyclic summand occurs once in the group-ring sum. -/
private noncomputable def goodLines {p s : ℕ} [Fact p.Prime]
    (a b : H p s) : Finset (Finset (H p s)) := by
  classical
  exact Finset.univ.filter fun L => ∃ z : H p s,
    addOrderOf z = p ^ s ∧ L = cyclicLine p s z ∧
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) ∧
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b)

/-- The kernel of a character nontrivial on both `a` and `b` belongs to `goodLines`. -/
private theorem char_kernel_good {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {a b : H p s} (ha : p • a = 0) (hb : p • b = 0)
    (χ : AddChar (H p s) ℂ) (hχa : χ a ≠ 1) (hχb : χ b ≠ 1) :
    ∃ K ∈ goodLines a b, ∀ v : H p s, v ∈ K ↔ χ v = 1 := by
  obtain ⟨z, hz, hker⟩ := exists_char_kernel_line hs a ha χ hχa
  obtain ⟨hgooda, hgoodb⟩ := char_kernel_line_good hs ha hb χ hχa hχb hz hker
  refine ⟨cyclicLine p s z, ?_, hker⟩
  simp only [goodLines, Finset.mem_filter, Finset.mem_univ, true_and]
  exact ⟨z, hz, rfl, hgooda, hgoodb⟩

/-- A full-order line on which `χ` is trivial equals the kernel line. -/
private theorem cyclicLine_eq_char_kernel {p s : ℕ} {z : H p s}
    (hz : addOrderOf z = p ^ s) (χ : AddChar (H p s) ℂ)
    {K : Finset (H p s)} (hK : ∀ v, v ∈ K ↔ χ v = 1)
    (hcard : K.card = p ^ s) (hχz : χ z = 1) : cyclicLine p s z = K := by
  classical
  apply Finset.eq_of_subset_of_card_le
  · intro v hv
    obtain ⟨m, hm, rfl⟩ := Finset.mem_image.mp hv
    apply (hK _).mpr
    rw [χ.map_nsmul_eq_pow, hχz, one_pow]
  · rw [cyclicLine_card hz, hcard]

/-- Exactly the kernel line contributes to the sum of character values. -/
private theorem sum_goodLine_char {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {a b : H p s} (ha : p • a = 0) (hb : p • b = 0)
    (χ : AddChar (H p s) ℂ) (hχa : χ a ≠ 1) (hχb : χ b ≠ 1) :
    ∑ L ∈ goodLines a b, ∑ v ∈ L, χ v = (p ^ s : ℂ) := by
  classical
  obtain ⟨K, hKgood, hK⟩ := char_kernel_good hs ha hb χ hχa hχb
  have hKcard : K.card = p ^ s := by
    obtain ⟨z, hz, rfl, _, _⟩ : ∃ z : H p s, addOrderOf z = p ^ s ∧
        K = cyclicLine p s z ∧ (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) ∧
        (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) := by
      simpa only [goodLines, Finset.mem_filter, Finset.mem_univ, true_and] using hKgood
    exact cyclicLine_card hz
  rw [Finset.sum_eq_single_of_mem K hKgood]
  · have hsum : (∑ v ∈ K, χ v) = ∑ v ∈ K, (1 : ℂ) := by
      apply Finset.sum_congr rfl
      intro v hv
      exact (hK v).mp hv
    rw [hsum]
    simp [hKcard]
  · intro L hL hLK
    obtain ⟨z, hz, rfl, _, _⟩ : ∃ z : H p s, addOrderOf z = p ^ s ∧
        L = cyclicLine p s z ∧ (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) ∧
        (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) := by
      simpa only [goodLines, Finset.mem_filter, Finset.mem_univ, true_and] using hL
    have hχz : χ z ≠ 1 := by
      intro hχz
      exact hLK (cyclicLine_eq_char_kernel hz χ hK hKcard hχz)
    rw [char_sum_cyclicLine hz χ]
    simp [hχz]

/-- Number of admissible cyclic summands containing a point of `H`. -/
private noncomputable def lineWeight {p s : ℕ} [Fact p.Prime]
    (a b : H p s) (v : H p s) : ℕ :=
  ∑ L ∈ goodLines a b, if v ∈ L then 1 else 0

/-- Fourier transform of the incidence weight is the sum of character sums over the lines. -/
private theorem char_sum_lineWeight {p s : ℕ} [Fact p.Prime]
    (a b : H p s) (χ : AddChar (H p s) ℂ) :
    ∑ v : H p s, (lineWeight a b v : ℂ) * χ v =
      ∑ L ∈ goodLines a b, ∑ v ∈ L, χ v := by
  classical
  simp only [lineWeight, Nat.cast_sum, Nat.cast_ite, Nat.cast_one, Nat.cast_zero,
    Finset.sum_mul]
  rw [Finset.sum_comm]
  apply Finset.sum_congr rfl
  intro L hL
  simp

/-- Fourier transform of a point mass. -/
private theorem char_sum_pointMass {G : Type*} [AddCommGroup G] [Fintype G]
    [DecidableEq G]
    (u : G) (χ : AddChar G ℂ) :
    ∑ v : G, (if v = u then (1 : ℂ) else 0) * χ v = χ u := by
  classical
  simp

/-- Fourier transform of two point masses with a common coefficient. -/
private theorem char_sum_two_pointMass {G : Type*} [AddCommGroup G] [Fintype G]
    [DecidableEq G] (u v : G) (q : ℂ) (χ : AddChar G ℂ) :
    ∑ x : G, q * ((if x = u then 1 else 0) + (if x = v then 1 else 0)) * χ x =
      q * (χ u + χ v) := by
  calc
    _ = q * (∑ x : G, ((if x = u then (1 : ℂ) else 0) * χ x +
        (if x = v then (1 : ℂ) else 0) * χ x)) := by
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro x hx
      ring
    _ = q * ((∑ x : G, (if x = u then (1 : ℂ) else 0) * χ x) +
        ∑ x : G, (if x = v then (1 : ℂ) else 0) * χ x) := by
      rw [Finset.sum_add_distrib]
    _ = q * (χ u + χ v) := by rw [char_sum_pointMass, char_sum_pointMass]

/-- The incidence-weight identity in the integral group ring, first checked over `ℂ`. -/
private theorem lineWeight_identity_complex {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {a b : H p s} (ha : p • a = 0) (hb : p • b = 0)
    (y : H p s) :
    (lineWeight a b (y - a - b) : ℂ) + (lineWeight a b y : ℂ) +
        (p ^ s : ℂ) * ((if y = a then (1 : ℂ) else 0) +
          (if y = b then (1 : ℂ) else 0)) =
      (lineWeight a b (y - a) : ℂ) + (lineWeight a b (y - b) : ℂ) +
        (p ^ s : ℂ) * ((if y = a + b then (1 : ℂ) else 0) +
          (if y = 0 then (1 : ℂ) else 0)) := by
  classical
  let w : H p s → ℂ := fun v => (lineWeight a b v : ℂ)
  let d : H p s → ℂ := fun v =>
    w (v - a - b) + w v + (p ^ s : ℂ) *
      ((if v = a then 1 else 0) + (if v = b then 1 else 0)) -
      (w (v - a) + w (v - b) + (p ^ s : ℂ) *
        ((if v = a + b then 1 else 0) + (if v = 0 then 1 else 0)))
  have hχ (χ : AddChar (H p s) ℂ) : ∑ v, d v * χ v = 0 := by
    have hshift_ab :
        (∑ v, w (v - a - b) * χ v) = χ (a + b) * ∑ v, w v * χ v := by
      simpa only [sub_add_eq_sub_sub] using charSum_translate w (a + b) χ
    have hshift_a := charSum_translate w a χ
    have hshift_b := charSum_translate w b χ
    have hpoints_ab := char_sum_two_pointMass a b (p ^ s : ℂ) χ
    have hpoints_ab0 := char_sum_two_pointMass (a + b) (0 : H p s) (p ^ s : ℂ) χ
    have hweight : (∑ v, w v * χ v) =
        ∑ L ∈ goodLines a b, ∑ v ∈ L, χ v := char_sum_lineWeight a b χ
    have htransform : (∑ v, d v * χ v) =
        (χ a - 1) * (χ b - 1) * ((∑ v, w v * χ v) - (p ^ s : ℂ)) := by
      simp only [d]
      simp_rw [sub_mul, add_mul]
      simp only [Finset.sum_sub_distrib, Finset.sum_add_distrib]
      rw [hshift_ab, hshift_a, hshift_b, hpoints_ab, hpoints_ab0]
      rw [χ.map_add_eq_mul, χ.map_zero_eq_one]
      ring
    rw [htransform]
    by_cases hχa : χ a = 1
    · simp [hχa]
    by_cases hχb : χ b = 1
    · simp [hχb]
    rw [hweight, sum_goodLine_char hs ha hb χ hχa hχb, sub_self, mul_zero]
  have hd : d = 0 := by
    apply eq_zero_of_forall_charCoeff_eq_zero
    intro χ
    simpa only [charCoeff, AddChar.neg_apply] using hχ (-χ)
  have hdy := congrFun hd y
  exact sub_eq_zero.mp hdy

/-- The incidence-weight identity in `ℕ`, with the four point masses kept positive. -/
private theorem lineWeight_identity {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {a b : H p s} (ha : p • a = 0) (hb : p • b = 0) (y : H p s) :
    lineWeight a b (y - a - b) + lineWeight a b y +
        p ^ s * ((if y = a then 1 else 0) + (if y = b then 1 else 0)) =
      lineWeight a b (y - a) + lineWeight a b (y - b) +
        p ^ s * ((if y = a + b then 1 else 0) + (if y = 0 then 1 else 0)) := by
  exact_mod_cast lineWeight_identity_complex hs ha hb y

/-- Evaluation of the incidence weight as a product over admissible lines. -/
private theorem prod_pow_lineWeight {p s : ℕ} [Fact p.Prime]
    {k : Type*} [CommMonoid k] (a b : H p s) (g : H p s → k) (x : H p s) :
    ∏ v : H p s, g (x + v) ^ lineWeight a b v =
      ∏ L ∈ goodLines a b, ∏ v ∈ L, g (x + v) := by
  classical
  calc
    _ = ∏ v : H p s, ∏ L ∈ goodLines a b,
        g (x + v) ^ (if v ∈ L then 1 else 0) := by
      apply Finset.prod_congr rfl
      intro v hv
      exact (Finset.prod_pow_eq_pow_sum (goodLines a b)
        (fun L => if v ∈ L then 1 else 0) (g (x + v))).symm
    _ = ∏ L ∈ goodLines a b, ∏ v : H p s,
        g (x + v) ^ (if v ∈ L then 1 else 0) := Finset.prod_comm
    _ = ∏ L ∈ goodLines a b, ∏ v ∈ L, g (x + v) := by
      apply Finset.prod_congr rfl
      intro L hL
      simp

/-- Product over a full-order cyclic line equals the generator-indexed product. -/
private theorem prod_cyclicLine {p s : ℕ} {z : H p s}
    (hz : addOrderOf z = p ^ s) {k : Type*} [CommMonoid k]
    (g : H p s → k) (x : H p s) :
    ∏ v ∈ cyclicLine p s z, g (x + v) =
      ∏ m ∈ Finset.range (p ^ s), g (x + m • z) := by
  classical
  rw [cyclicLine, Finset.prod_image (cyclicLine_injective hz)]

/-- Invariance of an admissible line product under `p`-torsion. -/
private theorem goodLine_prod_invariant {p s : ℕ} [Fact p.Prime]
    {k : Type*} [CommMonoid k] {a b : H p s} (g : H p s → k)
    (hL : ∀ z : H p s, addOrderOf z = p ^ s →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) →
        ∀ x u : H p s, p • u = 0 →
          ∏ m ∈ Finset.range (p ^ s), g (x + u + m • z) =
            ∏ m ∈ Finset.range (p ^ s), g (x + m • z))
    {L : Finset (H p s)} (hgood : L ∈ goodLines a b)
    (x u : H p s) (hu : p • u = 0) :
    (∏ v ∈ L, g (x + u + v)) = ∏ v ∈ L, g (x + v) := by
  classical
  obtain ⟨z, hz, rfl, hza, hzb⟩ : ∃ z : H p s, addOrderOf z = p ^ s ∧
      L = cyclicLine p s z ∧ (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) ∧
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) := by
    simpa only [goodLines, Finset.mem_filter, Finset.mem_univ, true_and] using hgood
  rw [prod_cyclicLine hz, prod_cyclicLine hz]
  exact hL z hz hza hzb x u hu

/-- The product over all admissible lines is invariant under `p`-torsion. -/
private theorem goodLines_prod_invariant {p s : ℕ} [Fact p.Prime]
    {k : Type*} [CommMonoid k] {a b : H p s} (g : H p s → k)
    (hL : ∀ z : H p s, addOrderOf z = p ^ s →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) →
        ∀ x u : H p s, p • u = 0 →
          ∏ m ∈ Finset.range (p ^ s), g (x + u + m • z) =
            ∏ m ∈ Finset.range (p ^ s), g (x + m • z))
    (x u : H p s) (hu : p • u = 0) :
    (∏ L ∈ goodLines a b, ∏ v ∈ L, g (x + u + v)) =
      ∏ L ∈ goodLines a b, ∏ v ∈ L, g (x + v) := by
  classical
  apply Finset.prod_congr rfl
  intro L hgood
  exact goodLine_prod_invariant g hL hgood x u hu

/-- Reindexing a weighted product by a translation. -/
private theorem prod_translate_weight {G : Type*} [AddCommGroup G] [Fintype G]
    {k : Type*} [CommMonoid k] (g : G → k) (w : G → ℕ) (x u : G) :
    (∏ v : G, g (x + v) ^ w (v - u)) =
      ∏ v : G, g (x + u + v) ^ w v := by
  classical
  symm
  apply Fintype.prod_equiv (Equiv.addRight u)
  intro v
  simp [add_comm, add_left_comm]

/-- A point mass in an exponent evaluates at its support. -/
private theorem prod_pointMass {G : Type*} [AddCommGroup G] [Fintype G]
    [DecidableEq G] {k : Type*} [CommMonoid k] (g : G → k) (x u : G) (q : ℕ) :
    (∏ v : G, g (x + v) ^ (if v = u then q else 0)) = g (x + u) ^ q := by
  simp

/-- Two point masses in an exponent evaluate as a product. -/
private theorem prod_two_pointMass {G : Type*} [AddCommGroup G] [Fintype G]
    [DecidableEq G] {k : Type*} [CommMonoid k] (g : G → k) (x u v : G) (q : ℕ) :
    (∏ y : G, g (x + y) ^ (q * ((if y = u then 1 else 0) +
      (if y = v then 1 else 0)))) = (g (x + u) * g (x + v)) ^ q := by
  simp_rw [mul_add, pow_add]
  rw [Finset.prod_mul_distrib]
  have hu : (∏ y : G, g (x + y) ^ (q * if y = u then 1 else 0)) =
      g (x + u) ^ q := by
    convert prod_pointMass g x u q using 1
    apply Finset.prod_congr rfl
    intro y hy
    split_ifs <;> simp
  have hv : (∏ y : G, g (x + y) ^ (q * if y = v then 1 else 0)) =
      g (x + v) ^ q := by
    convert prod_pointMass g x v q using 1
    apply Finset.prod_congr rfl
    intro y hy
    split_ifs <;> simp
  rw [hu, hv, mul_pow]

/-- Multiplicative evaluation of the group-ring identity. -/
private theorem mixed_product_pow_eq {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {k : Type*} [Field k] {a b : H p s} (ha : p • a = 0) (hb : p • b = 0)
    (g : H p s → k) (hg : ∀ x, g x ≠ 0)
    (hL : ∀ z : H p s, addOrderOf z = p ^ s →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) →
        ∀ x u : H p s, p • u = 0 →
          ∏ m ∈ Finset.range (p ^ s), g (x + u + m • z) =
            ∏ m ∈ Finset.range (p ^ s), g (x + m • z))
    (x : H p s) :
    (g (x + a + b) * g x) ^ (p ^ s) =
      (g (x + a) * g (x + b)) ^ (p ^ s) := by
  classical
  let P : k := ∏ L ∈ goodLines a b, ∏ v ∈ L, g (x + v)
  have hP : P ≠ 0 := by
    dsimp [P]
    apply Finset.prod_ne_zero_iff.mpr
    intro L hLgood
    apply Finset.prod_ne_zero_iff.mpr
    intro v hv
    exact hg (x + v)
  have hshift (u : H p s) (hu : p • u = 0) :
      (∏ v : H p s, g (x + v) ^ lineWeight a b (v - u)) = P := by
    calc
      _ = ∏ v : H p s, g (x + u + v) ^ lineWeight a b v :=
        prod_translate_weight g (lineWeight a b) x u
      _ = ∏ L ∈ goodLines a b, ∏ v ∈ L, g (x + u + v) := by
        simpa only [add_assoc] using prod_pow_lineWeight a b g (x + u)
      _ = P := goodLines_prod_invariant g hL x u hu
  have hzero : (∏ v : H p s, g (x + v) ^ lineWeight a b v) = P :=
    prod_pow_lineWeight a b g x
  have hab : p • (a + b) = 0 := by rw [smul_add, ha, hb, zero_add]
  have hshiftab :
      (∏ v : H p s, g (x + v) ^ lineWeight a b (v - a - b)) = P := by
    simpa only [sub_add_eq_sub_sub] using hshift (a + b) hab
  have hcoeff :
      (∏ v : H p s, g (x + v) ^
        (lineWeight a b (v - a - b) + lineWeight a b v +
          p ^ s * ((if v = a then 1 else 0) + (if v = b then 1 else 0)))) =
      (∏ v : H p s, g (x + v) ^
        (lineWeight a b (v - a) + lineWeight a b (v - b) +
          p ^ s * ((if v = a + b then 1 else 0) + (if v = 0 then 1 else 0)))) := by
    apply Finset.prod_congr rfl
    intro v hv
    rw [lineWeight_identity hs ha hb v]
  simp only [pow_add, Finset.prod_mul_distrib] at hcoeff
  rw [hshiftab, hzero, hshift a ha, hshift b hb,
    prod_two_pointMass g x a b (p ^ s),
    prod_two_pointMass g x (a + b) 0 (p ^ s)] at hcoeff
  have hpow : (g (x + a) * g (x + b)) ^ (p ^ s) =
      (g (x + a + b) * g x) ^ (p ^ s) := by
    apply mul_left_cancel₀ (mul_ne_zero hP hP)
    simpa only [mul_assoc, P, add_assoc, add_zero] using hcoeff
  exact hpow.symm

/-- **[RW26b, Radchenko, Wheeler (2026b), Section 7, Lemma 6]**: on `H = (ℤ/p^s)²` with
`a, b ∈ H[p]`, if `g : H → k^×` (`k` of characteristic `p`) has products over every cyclic summand
`L = ⟨z⟩` of order `p^s` with `L[p] ∉ {⟨a⟩, ⟨b⟩}` invariant under `H[p]`, then
`g(x + a + b)g(x) = g(x + a)g(x + b)`. The source assumes that `a, b` is a basis of `H[p]`; the
proof does not use it, since a character with `χ(a) ≠ 1 ≠ χ(b)` has a good kernel in any case. -/
@[source "RW26b, Lemma 6, p. 11"]
theorem mul_eq_mul_of_prod_summand_invariant {p s : ℕ} [Fact p.Prime] (hs : 1 ≤ s)
    {k : Type*} [Field k] [CharP k p] {a b : Fin 2 → ZMod (p ^ s)} (ha : p • a = 0)
    (hb : p • b = 0) (g : (Fin 2 → ZMod (p ^ s)) → k) (hg : ∀ x, g x ≠ 0)
    (hL : ∀ z : Fin 2 → ZMod (p ^ s), addOrderOf z = p ^ s →
      (∀ n : ℕ, p ^ (s - 1) • z ≠ n • a) → (∀ n : ℕ, p ^ (s - 1) • z ≠ n • b) →
        ∀ x u : Fin 2 → ZMod (p ^ s), p • u = 0 →
          ∏ m ∈ Finset.range (p ^ s), g (x + u + m • z) =
            ∏ m ∈ Finset.range (p ^ s), g (x + m • z))
    (x : Fin 2 → ZMod (p ^ s)) : g (x + a + b) * g x = g (x + a) * g (x + b) := by
  have hpow := mixed_product_pow_eq hs ha hb g hg hL x
  have hzero : (g (x + a + b) * g x - g (x + a) * g (x + b)) ^ p ^ s = 0 := by
    rw [sub_pow_char_pow, hpow, sub_self]
  exact sub_eq_zero.mp (eq_zero_of_pow_eq_zero hzero)

end SIC
