/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.ClassField.RayClassField.Narrow
import SICs.ClassField.Frobenius.DegreeOne
import SICs.ClassField.Reciprocity.RealPlace

/-!
# Sign classes: primes of absolute degree one and Artin symbols

For a nonzero modulus `m` of a real quadratic field and any signs at the two real places, there
are primes of absolute degree one outside every finite set generated by some
$\alpha\equiv1\pmod{\mathfrak m}$ with those signs; a sign class supported at one real place has
Artin symbol trivial or complex conjugation above that place.

This module gives the order-two sign-class conclusion of Milne, *Class Field Theory*, version
4.03 (2020), Chapter VI, Theorem 4.8. That theorem states its density formula subject to an
$L$-function nonvanishing condition; the proof here instead adapts the splitting argument of
Chapter VI, Exercise A-10 and its solution from cyclic to abelian extensions. It also uses the
weak real-place law of [83, Neukirch (1999), Chapter VI, Proposition 5.6]. It supplies the prime
inputs and real-place Artin symbols of the sign actions in [RW26b, Radchenko, Wheeler (2026b),
Propositions 5 and 7]; the trivial signs give the identity class.

## The argument

Let `H` be the narrow ray class field of modulus `m` (`exists_narrowRayClassField`) and
$b=\operatorname{Art}_{H/K}(\varepsilon)$ for the sign idèle class $\varepsilon$. Since
$\varepsilon^2$ lies in the norm group (`signIdeleClass_sq_mem`, `ker_globalArtin`), $b^2=1$,
so $b$ is Frobenius at a prime of `H` above a prime $\mathfrak p$ of `K` of absolute degree one
outside the given set, the support of `m`, and the ramified primes
(`exists_degreeOne_isFrobeniusAt_of_sq_eq_one`). By
`isFrobeniusAt_globalArtin_signIdeleClass_iff`, $\mathfrak p$ has a signed ray generator with
signs $\varepsilon$.

*Artin symbols at a real place.* A sign idèle class supported at one real place `w` is the
class of $\varepsilon_w\in\{\pm1\}\subset K_w^\times$, so its Artin symbol is trivial or complex
conjugation at every embedding above `w` (`globalArtin_ofCompletion_eq_one_or_isConj`).
-/

noncomputable section

namespace SIC

open IsDedekindDomain NumberField

universe u

variable {K : Type u} [Field K] [NumberField K] [NumberField.IsTotallyReal K]

/-- **Primes of absolute degree one in the sign classes.** For a nonzero modulus `m` of a real
quadratic field, signs $\varepsilon$ at its infinite places, and a finite set `S` of primes, some
prime $\mathfrak p\notin S$ of absolute degree one has a generator $\alpha\equiv1\pmod{\mathfrak m}$
with sign $\varepsilon_w$ at every real place `w`. The order-two sign-class case of Milne,
*Class Field Theory*, Chapter VI, Theorem 4.8, proved by adapting the argument of Chapter VI,
Exercise A-10 and its solution to an abelian extension. -/
theorem exists_degreeOne_hasSignedRayGenerator (F : RealQuadraticFieldData K)
    {m : Ideal (𝓞 K)} (hm : m ≠ ⊥) (ε : InfinitePlace K → ℤˣ)
    (S : Finset (HeightOneSpectrum (𝓞 K))) :
    ∃ v : HeightOneSpectrum (𝓞 K), v ∉ S ∧ (Ideal.absNorm v.asIdeal).Prime ∧
      HasSignedRayGenerator m ε v.asIdeal := by
  classical
  obtain ⟨H, hNF, hAb, hU⟩ := exists_narrowRayClassField F hm
  have : NumberField H := hNF
  have : IsAbelianGalois K H := hAb
  have hb : (globalArtin H (signIdeleClass ε)) ^ 2 = 1 := by
    rw [← map_pow]
    apply (MonoidHom.mem_ker (f := globalArtin H)).mp
    rw [ker_globalArtin (K := K) (L := H), hU]
    exact signIdeleClass_sq_mem ε m
  obtain ⟨w, hwS, hwprime, hwFrob⟩ :=
    exists_degreeOne_isFrobeniusAt_of_sq_eq_one
      (K := K) (L := H) (S ∪ FinitePlace.modulusSupport m) hb
  let v := FinitePlace.below (K := K) w
  have hvS : v ∉ S := fun hv => hwS (Finset.mem_union_left _ hv)
  have hvSupport : v ∉ FinitePlace.modulusSupport m :=
    fun hv => hwS (Finset.mem_union_right _ hv)
  have hvCoprime : IsCoprime v.asIdeal m :=
    (FinitePlace.isCoprime_iff_modulusExponent_eq_zero hm v).mpr
      (not_ne_iff.mp ((FinitePlace.mem_modulusSupport).not.mp hvSupport))
  have : w.asIdeal.LiesOver v.asIdeal := FinitePlace.liesOver_below w
  exact ⟨v, hvS, hwprime,
    (isFrobeniusAt_globalArtin_signIdeleClass_iff hU ε hvCoprime w).mp hwFrob⟩

omit [NumberField.IsTotallyReal K] in
/-- **The Artin symbol of a sign class at one real place**: if the signs $\varepsilon$ are $+1$
away from the real place `w`, then in every finite abelian extension `H/K` the Artin symbol of
the sign idèle class is trivial or complex conjugation at every embedding $\rho:H\to\mathbb C$
above `w`. [83, Neukirch (1999), Chapter VI, Proposition 5.6], weak form. -/
theorem globalArtin_signIdeleClass_eq_one_or_isConj {H : Type*} [Field H] [NumberField H]
    [Algebra K H] [IsAbelianGalois K H] {ε : InfinitePlace K → ℤˣ} {w : InfinitePlace K}
    (hε : ∀ w' : InfinitePlace K, w' ≠ w → ε w' = 1) (ρ : H →+* ℂ)
    [(InfinitePlace.mk ρ).LiesOver w] :
    globalArtin H (signIdeleClass ε) = 1 ∨
      ComplexEmbedding.IsConj ρ (globalArtin H (signIdeleClass ε)) := by
  classical
  let x := Units.map (Int.castRingHom w.Completion : ℤ →* w.Completion) (ε w)
  have hsign : signIdele ε = NumberField.IdeleGroup.ofCompletion (𝓞 K) K w x := by
    rw [signIdele, Finset.prod_eq_single w]
    · intro w' _ hw'
      rw [hε w' hw']
      simp
    · simp
  have hclass : signIdeleClass ε = NumberField.IdeleClassGroup.ofCompletion (𝓞 K) K w x := by
    rw [signIdeleClass, hsign, NumberField.IdeleClassGroup.ofCompletion_apply]
  rw [hclass]
  exact globalArtin_ofCompletion_eq_one_or_isConj w ρ x

end SIC

end
