/-
Copyright (c) 2026 Maris Ozols. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Maris Ozols
-/
import SICs.Admissible.Triples
import SICs.Quadratic.FormStabilizers

/-!
# Associated Stabilizers

Associated level/Zauner stabilizer pairs, the closed form of `A_t`, the power identities of
`L_{z,t}`, and `Tr A_t + 2 = (d - 2r)²(d_j + 1)`.

This file formalizes the level and Zauner generators among the associated stabilizers of
[AFK25, Definition 1.28, `dfn:AssociatedStabilizers`] for arbitrary admissible tuples.  It records
the doubled integral formula for the Zauner generator, the power relation defining the level
generator, its orientation, and the cyclic generation of the level stability group, and proves
that these conditions determine the pair. Their existence, [AFK25, Theorem 4.50, `tm:symgp`], is
proved in `SICs.Admissible.StabilizerExistence`.

The matrix identities used by the explicit shift are [AFK26, Appleby, Flammia, Kopp (2026),
Lemmas 4.2--4.3]: the factorization of `A_t-I` and the rank-grid formula for `L_{z,t}^m`.

## Mathematical argument

The doubled formula determines the Zauner generator because integral matrices have no
two-torsion.  The level generator is then its prescribed odd power, so the associated pair is
unique.

Existence is the content of [AFK25, Theorem 4.50, `tm:symgp`]: the source represents the
norm-one units `ε^j` and `ε^{j(2m+1)}` of the order of conductor `f` as integral matrices, shows
that the level stability group `S_d(Q) = S(Q) ∩ Γ(d)` is generated by the latter, and reads off
the formula for the Zauner generator. That construction is carried out in
`SICs.Admissible.StabilizerExistence`, which proves
`AdmissibleTuple.exists_isAssociatedStabilizerPair`.

This module deliberately contains no shifts or analytic cocycle values.  Downstream shift modules
can therefore import the associated-stabilizer relation before defining `IsShift`.

## References

- [AFK25] Appleby, Flammia, Kopp, arXiv:2501.03970v2, Definition 1.28 and Theorem 4.50
-/

noncomputable section

open scoped MatrixGroups

namespace SIC

namespace AdmissibleTuple

/-! #### Associated stabilizers [AFK25, Definition 1.28, `dfn:AssociatedStabilizers`]

The general bundle records the level generator `A_t`, the Zauner generator `L_{z,t}`, their power
relation, and the required orientation. -/

/-- The `A_t` and `L_{z,t}` components of the associated stabilizers in [AFK25, Definition 1.28,
`dfn:AssociatedStabilizers`]. The doubled formula records
`L_{z,t} = ((d_j - 1)/2) I + (f_j/f) SQ` integrally. The power relation
`A_t = L_{z,t}^{2m+1}` is the consequence proved in [AFK25, Theorem 4.50, `tm:symgp`]. The last two
fields say that `A_t` is the generator of
`S_d(Q) = S(Q) ∩ Γ(d)` oriented by `sgn(A_t) = sgn(Q)`.

The source definition also introduces `L_t`, the oriented positive-trace generator of the full
stability group, and the determinant-one generator `L_{+,t}`. They are not inputs to the shift
predicate and are not formalized.
Membership `A_t ∈ S_d(Q)` follows from the generator field and is exposed by
`A_mem_stabilityGroupLevel`; in turn it supplies `A_t ∈ Γ_r` at every cocycle summand through
`A_mem_gammaSubgroup`. -/
@[source "AFK25, Definition 1.28, p. 15, dfn:AssociatedStabilizers (A_t, L_{z,t})"
  (symbol := "A_t, L_{z,t}")]
structure IsAssociatedStabilizerPair (t : AdmissibleTuple)
    (A_t Lz : SL(2, ℤ)) : Prop where
  /-- The doubled form of the defining formula [AFK25, equation (1.41)]. -/
  twice_Lz_eq :
    (2 : ℤ) • (Lz : Mat(2, ℤ)) =
      ((t.triple.towerDimension : ℤ) - 1) • (1 : Mat(2, ℤ)) +
        ((t.towerConductorRatio : ℤ)) • t.Q.twiceSQ
  /-- The level generator is the `(2m+1)`-st power of the Zauner generator, by
  [AFK25, Theorem 4.50, `tm:symgp`]. -/
  A_eq_Lz_pow : A_t = Lz ^ (2 * (t.triple.m : ℕ) + 1)
  /-- The level generator has the source's prescribed orientation, `sgn(A_t) = sgn(Q)`. -/
  A_sign : BinaryQF.signMatrix (A_t : Mat(2, ℤ)) = t.Q.sign
  /-- The level stability group is generated by `A_t`: `S_d(Q) = ⟨A_t⟩`. -/
  A_generates : t.Q.stabilityGroupLevel t.d = Subgroup.zpowers A_t

/-- The associated level generator belongs to `S_d(Q)`, derived from `A_generates`. -/
lemma IsAssociatedStabilizerPair.A_mem_stabilityGroupLevel {t : AdmissibleTuple}
    {A_t Lz : SL(2, ℤ)} (h : t.IsAssociatedStabilizerPair A_t Lz) :
    A_t ∈ t.Q.stabilityGroupLevel t.d := by
  rw [h.A_generates]
  exact Subgroup.mem_zpowers A_t

/-- **The associated stabilizers are unique.** The doubled formula determines `L_{z,t}` because
integral matrices are torsion-free under doubling, and `A_t` is then determined as a power of
it. -/
theorem IsAssociatedStabilizerPair.unique {t : AdmissibleTuple}
    {A_t Lz A_t' Lz' : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz)
    (h' : t.IsAssociatedStabilizerPair A_t' Lz') :
    A_t = A_t' ∧ Lz = Lz' := by
  have hcoe : (Lz : Mat(2, ℤ)) = (Lz' : Mat(2, ℤ)) :=
    smul_right_injective _ two_ne_zero (h.twice_Lz_eq.trans h'.twice_Lz_eq.symm)
  have hLz : Lz = Lz' := Subtype.ext hcoe
  exact ⟨by rw [h.A_eq_Lz_pow, h'.A_eq_Lz_pow, hLz], hLz⟩

/-! #### The closed form of the level generator

`IsAssociatedStabilizerPair` pins `A_t` down only relationally, through
`2L_{z,t} = (d_j - 1) I + (f_j/f) 2SQ` and `A_t = L_{z,t}^{2m+1}`.  A closed form for `A_t` itself
follows from those two facts alone.  Taking traces in the doubled formula kills `2SQ` and leaves
`Tr L_{z,t} = d_j - 1`; in two dimensions Cayley--Hamilton then makes every power of `L_{z,t}` an
integer combination of `L_{z,t}` and `I`, with coefficients the values of the recursion
`r_{n+2} = (d_j - 1) r_{n+1} - r_n`.  That recursion is the rank grid of
`SICs.Quadratic.DimensionGrids`, so

`A_t = L_{z,t}^{2m+1} = r_{j,2m+1} L_{z,t} - r_{j,2m} I`,

and doubling turns this into an identity in `I` and `2SQ`.  The index-doubling identities evaluate
the two coefficients as `d²(d_j - 3)` and `d (r_{j,m+1} - r_{j,m})`, which is `A_t - I = dH`.

Only the `2SQ` coefficient enters the symplectic pairing `⟨A_t p, p⟩`, because `I` pairs to zero;
the `I` coefficient is the part that exhibits the level congruence `A_t ≡ I (mod d)`.
-/

/-- The Zauner generator has trace `d_j - 1`.  Taking traces in the doubled defining formula kills
`2SQ`, whose diagonal entries are `-b` and `b`. -/
lemma IsAssociatedStabilizerPair.trace_Lz {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    Matrix.trace (Lz : Mat(2, ℤ)) = (t.triple.towerDimension : ℤ) - 1 :=
  BinaryQF.trace_eq_of_twice_eq h.twice_Lz_eq

/-- The rank-grid recurrence with the trace of `Lz`, used by `pow_succ_eq` and
`pow_mul_sub_one`. -/
private lemma IsAssociatedStabilizerPair.rankGridInt_rec {t : AdmissibleTuple}
    {A_t Lz : SL(2, ℤ)} (h : t.IsAssociatedStabilizerPair A_t Lz) (n : ℕ) :
    t.triple.tower.rankGridInt t.triple.j (n + 2) =
      Matrix.trace (Lz : Mat(2, ℤ)) *
        t.triple.tower.rankGridInt t.triple.j (n + 1) -
          t.triple.tower.rankGridInt t.triple.j n := by
  rw [h.trace_Lz]
  change t.triple.tower.rankGridInt t.triple.j (n + 2) =
    ((t.triple.tower.canonicalDimension t.triple.j : ℤ) - 1) *
      t.triple.tower.rankGridInt t.triple.j (n + 1) -
        t.triple.tower.rankGridInt t.triple.j n
  rw [t.triple.tower.canonicalDimension_coe_int t.triple.j]
  exact t.triple.tower.rankGridInt_add_two t.triple.j n

/-- The rank-grid power expansion of `Lz` used by `twice_A_sub_one_eq`, `A_sub_one_eq`, and
`Lz_pow_m_eq`. -/
private lemma IsAssociatedStabilizerPair.pow_succ_eq {t : AdmissibleTuple}
    {A_t Lz : SL(2, ℤ)} (h : t.IsAssociatedStabilizerPair A_t Lz) (n : ℕ) :
    (Lz : Mat(2, ℤ)) ^ (n + 1) =
      t.triple.tower.rankGridInt t.triple.j (n + 1) • (Lz : Mat(2, ℤ)) -
        t.triple.tower.rankGridInt t.triple.j n • 1 := by
  exact SL2Z.pow_succ_eq_smul_sub_smul Lz
    (t.triple.tower.rankGridInt_zero t.triple.j)
    (t.triple.tower.rankGridInt_one t.triple.j)
    h.rankGridInt_rec n

/-- **The closed form of the associated level generator.**  This is [AFK25, equation (5.26),
`eq:amidjmh`], from the proof of [AFK25, Lemma 5.5, `lem:drafjfqp`], in doubled form:

`2(A_t - I) = d²(d_j - 3) I + d (r_{j,m+1} - r_{j,m}) (f_j/f) 2SQ`,

which is `A_t - I = dH` with `H = d((d_j-3)/2) I + (r_{j,m+1} - r_{j,m}) S Q̄` and `Q̄ = (f_j/f) Q`.
Doubling clears the halves, exactly as `twice_Lz_eq` does for `L_{z,t}`.

The source reads these coefficients off the canonical representation of `ε^{j(2m+1)}` supplied by
[AFK25, Theorem 4.50, `tm:symgp`], and evaluates the scalar one by hyperbolic identities.  That
representation is constructed in `SICs.Admissible.StabilizerExistence`; the proof here uses only
the relational data of `IsAssociatedStabilizerPair`: it expands `A_t = L_{z,t}^{2m+1}` by
`SIC.SL2Z.pow_succ_eq_smul_sub_smul` and evaluates the resulting rank-grid coefficients with
`RealQuadraticUnitData.rankGridInt_scalar_part` and
`RealQuadraticUnitData.rankGridInt_two_mul_add_one_eq_mul_dimensionGrid`. The two expressions have
the same `SQ` coefficient because `f_{j(2m+1)}/f = r_{j,2m+1} f_j/f`. -/
theorem IsAssociatedStabilizerPair.twice_A_sub_one_eq {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    (2 : ℤ) • ((A_t : Mat(2, ℤ)) - 1) =
      ((t.d : ℤ) ^ 2 * ((t.triple.towerDimension : ℤ) - 3)) •
          (1 : Mat(2, ℤ)) +
        ((t.d : ℤ) *
            (t.triple.tower.rankGridInt t.triple.j ((t.triple.m : ℕ) + 1) -
              t.triple.tower.rankGridInt t.triple.j (t.triple.m : ℕ)) *
            (t.towerConductorRatio : ℤ)) • t.Q.twiceSQ := by
  have hcd : (t.triple.towerDimension : ℤ) =
      t.triple.tower.dimensionInt (t.triple.j : ℕ) :=
    t.triple.tower.canonicalDimension_coe_int t.triple.j
  have hd : (t.d : ℤ) = (t.triple.tower.dimensionGrid t.triple.j t.triple.m : ℤ) := by
    rw [t.d_eq_dimension]; rfl
  -- `A_t` as an integer combination of `L_{z,t}` and `I`.
  have hA : (A_t : Mat(2, ℤ)) =
      t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ) + 1) •
          (Lz : Mat(2, ℤ)) -
        t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ)) • 1 := by
    rw [h.A_eq_Lz_pow, Matrix.SpecialLinearGroup.coe_pow]
    exact h.pow_succ_eq (2 * (t.triple.m : ℕ))
  -- The two scalar coefficients, in rank-grid form.
  have hscalar : (t.d : ℤ) ^ 2 * ((t.triple.towerDimension : ℤ) - 3) =
      ((t.triple.towerDimension : ℤ) - 1) *
          t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ) + 1) -
        2 * t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ)) - 2 := by
    rw [hd, hcd]
    exact (t.triple.tower.rankGridInt_scalar_part t.triple.j t.triple.m).symm
  have hvec : (t.d : ℤ) *
      (t.triple.tower.rankGridInt t.triple.j ((t.triple.m : ℕ) + 1) -
        t.triple.tower.rankGridInt t.triple.j (t.triple.m : ℕ)) =
      t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ) + 1) := by
    rw [hd, t.triple.tower.rankGridInt_two_mul_add_one_eq_mul_dimensionGrid t.triple.j t.triple.m]
    ring
  rw [hscalar, hvec, hA]
  have hkey : (2 : ℤ) •
      (t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ) + 1) •
          (Lz : Mat(2, ℤ)) -
        t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ)) • 1 - 1) =
      t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ) + 1) •
          ((2 : ℤ) • (Lz : Mat(2, ℤ))) -
        (2 * t.triple.tower.rankGridInt t.triple.j (2 * (t.triple.m : ℕ)) + 2) •
          (1 : Mat(2, ℤ)) := by
    module
  rw [hkey, h.twice_Lz_eq]
  module

/-- The trace of the associated level generator, `Tr A_t = d²(d_j - 3) + 2`: the trace of the
closed form `twice_A_sub_one_eq`, in which `2SQ` is traceless. -/
lemma IsAssociatedStabilizerPair.trace_A {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    Matrix.trace (A_t : Mat(2, ℤ)) =
      (t.d : ℤ) ^ 2 * ((t.triple.towerDimension : ℤ) - 3) + 2 := by
  have h00 := congrFun (congrFun h.twice_A_sub_one_eq 0) 0
  have h11 := congrFun (congrFun h.twice_A_sub_one_eq 1) 1
  simp only [Matrix.smul_apply, Matrix.sub_apply, Matrix.add_apply, smul_eq_mul] at h00 h11
  simp [BinaryQF.twiceSQ] at h00 h11
  simp only [Matrix.trace_fin_two]
  linarith

/-- **The trace shift of the level generator is a square times `d_j + 1`**:
`Tr A_t + 2 = (d - 2r)²(d_j + 1)`. This is the square of [AFK25, equation (5.70),
`eq:nu01overnu0val2`], `√(Tr A_t + 2) = (d - 2r_{j,m})√(d_j + 1)`, in the proof of
[AFK25, Lemma 5.9, `lem:nu01overnu0val`]. The source reads it off `Tr A_t = d_{j(2m+1)} - 1` and
the grid identities of [AFK25, Lemma 4.23, `lem:dimgridtechres`]; here it is `trace_A` combined
with the pair equation `(d_j + 1) r (d - r) = d² - 1`. -/
lemma IsAssociatedStabilizerPair.trace_A_add_two {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    Matrix.trace (A_t : Mat(2, ℤ)) + 2 =
      ((t.d : ℤ) - 2 * t.r) ^ 2 * ((t.triple.towerDimension : ℤ) + 1) := by
  have heq := t.pair.equation_int
  rw [t.pair_n_eq] at heq
  push_cast at heq
  rw [h.trace_A]
  linear_combination 4 * heq

/-! #### The stabilizer algebra of [AFK26, Appleby, Flammia, Kopp (2026), Section 4]

With `L = L_{z,t}`, `γ = A_t = L^{2m+1}`, `d = d_{j,m}` and `r_{j,n}` the rank grid, the
characteristic polynomial `L² - (d_j - 1)L + I = 0` gives
`L^n = r_{j,n} L - r_{j,n-1} I` (Lemma 4.3). The source proves Lemma 4.2,
`L^{2m+1} - I = d L^m (L - I)`, by summing `L^{-m}, …, L^m`. Here the index-doubling
identities and the Cassini relation for `r_{j,n}` identify the coefficients on both sides.
The factorization identifies the torsion of the finite quantum dilogarithm group of `A_t`;
the power formula computes its bicharacter phase in the proof of
[AFK26, Appleby, Flammia, Kopp (2026), Theorem 1.2, `thm:tci`]. -/

/-- The inverse of the associated Zauner generator is `L⁻¹ = (d_j-1)I-L`, from
`SL2Z.inv_eq_trace_smul_sub` and `trace_Lz`. -/
theorem IsAssociatedStabilizerPair.Lz_inv_eq {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    ((Lz⁻¹ : SL(2, ℤ)) : Mat(2, ℤ)) =
      ((t.triple.towerDimension : ℤ) - 1) • (1 : Mat(2, ℤ)) - (Lz : Mat(2, ℤ)) := by
  rw [← h.trace_Lz]
  exact SL2Z.inv_eq_trace_smul_sub Lz

/-- The product `L^{k+1}(L-I)` in the rank-grid basis, used by `A_sub_one_eq`. -/
private lemma IsAssociatedStabilizerPair.pow_mul_sub_one {t : AdmissibleTuple}
    {A_t Lz : SL(2, ℤ)} (h : t.IsAssociatedStabilizerPair A_t Lz) (k : ℕ) :
    (Lz : Mat(2, ℤ)) ^ (k + 1) * ((Lz : Mat(2, ℤ)) - 1) =
      (t.triple.tower.rankGridInt t.triple.j (k + 2) -
        t.triple.tower.rankGridInt t.triple.j (k + 1)) • (Lz : Mat(2, ℤ)) -
      (t.triple.tower.rankGridInt t.triple.j (k + 1) -
        t.triple.tower.rankGridInt t.triple.j k) • 1 := by
  let r : ℕ → ℤ := t.triple.tower.rankGridInt t.triple.j
  let M : Mat(2, ℤ) := Lz
  change M ^ (k + 1) * (M - 1) =
    (r (k + 2) - r (k + 1)) • M - (r (k + 1) - r k) • 1
  have hrec : r (k + 2) = Matrix.trace M * r (k + 1) - r k :=
    h.rankGridInt_rec k
  rw [show M ^ (k + 1) = r (k + 1) • M - r k • 1 from h.pow_succ_eq k]
  have hsq : M ^ 2 = Matrix.trace M • M - 1 := SL2Z.sq_eq_trace_smul_sub_one Lz
  calc
    (r (k + 1) • M - r k • 1) * (M - 1) =
        r (k + 1) • M ^ 2 - (r (k + 1) + r k) • M + r k • 1 := by
          rw [sub_mul, mul_sub, mul_sub]
          simp only [smul_mul_assoc, Matrix.one_mul, Matrix.mul_one, ← pow_two, one_pow]
          module
    _ = (r (k + 2) - r (k + 1)) • M - (r (k + 1) - r k) • 1 := by
      rw [hsq, hrec]
      module

/-- **[AFK26, Appleby, Flammia, Kopp (2026), Lemma 4.2, `lem:Lpower`]**:
`A_t - I = L^{2m+1} - I = d_{j,m} L^m (L - I)` for `L = L_{z,t}`. -/
@[source "AFK26, Lemma 4.2, p. 7, lem:Lpower"]
theorem IsAssociatedStabilizerPair.A_sub_one_eq {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    (A_t : Mat(2, ℤ)) - 1 =
      (t.d : ℤ) • ((Lz : Mat(2, ℤ)) ^ (t.triple.m : ℕ) * ((Lz : Mat(2, ℤ)) - 1)) := by
  let T := t.triple.tower
  let j := t.triple.j
  let m : ℕ := t.triple.m
  let r : ℕ → ℤ := T.rankGridInt j
  let M : Mat(2, ℤ) := Lz
  let d : ℤ := t.d
  obtain ⟨k, hk⟩ : ∃ k : ℕ, m = k + 1 :=
    ⟨m - 1, by dsimp [m]; have := t.triple.m.pos; omega⟩
  have hcoef1 : r (2 * m + 1) = d * (r (m + 1) - r m) := by
    dsimp [r]
    rw [show d = (T.dimensionGrid j t.triple.m : ℤ) by
      dsimp [d, T, j]; rw [t.d_eq_dimension]; rfl,
      T.rankGridInt_two_mul_add_one_eq_mul_dimensionGrid j t.triple.m]
    ring
  have hcoef2 : r (2 * m) + 1 = d * (r m - r (m - 1)) := by
    simpa only [r, d, m, T, j, t.d_eq_dimension, AdmissibleTriple.dimension] using
      T.rankGridInt_even_add_one_eq j t.triple.m
  have hA : (A_t : Mat(2, ℤ)) = r (2 * m + 1) • M - r (2 * m) • 1 := by
    rw [h.A_eq_Lz_pow, Matrix.SpecialLinearGroup.coe_pow]
    exact h.pow_succ_eq (2 * m)
  change (A_t : Mat(2, ℤ)) - 1 = d • (M ^ m * (M - 1))
  rw [hA, hk]
  rw [h.pow_mul_sub_one k]
  have hcoef2' : r (2 * (k + 1)) = d * (r (k + 1) - r k) - 1 := by
    rw [hk] at hcoef2
    simp only [Nat.add_sub_cancel] at hcoef2
    omega
  rw [hk] at hcoef1
  rw [hcoef1, hcoef2']
  module

/-- **[AFK26, Appleby, Flammia, Kopp (2026), Lemma 4.3, `lem:Ltom`]**:
`L^m = r_{j,m} L - r_{j,m-1} I` for `L = L_{z,t}`. -/
@[source "AFK26, Lemma 4.3, p. 7, lem:Ltom"]
theorem IsAssociatedStabilizerPair.Lz_pow_m_eq {t : AdmissibleTuple} {A_t Lz : SL(2, ℤ)}
    (h : t.IsAssociatedStabilizerPair A_t Lz) :
    (Lz : Mat(2, ℤ)) ^ (t.triple.m : ℕ) =
      t.triple.tower.rankGridInt t.triple.j (t.triple.m : ℕ) • (Lz : Mat(2, ℤ)) -
        t.triple.tower.rankGridInt t.triple.j ((t.triple.m : ℕ) - 1) • (1 : Mat(2, ℤ)) := by
  obtain ⟨k, hk⟩ : ∃ k : ℕ, (t.triple.m : ℕ) = k + 1 :=
    ⟨(t.triple.m : ℕ) - 1, by have := t.triple.m.pos; omega⟩
  rw [hk]
  simpa [hk] using h.pow_succ_eq k

/-- The `m+1` companion to [AFK26, Appleby, Flammia, Kopp (2026), Lemma 4.3,
`lem:Ltom`]: `L^{m+1} = (d-r)L-rI`. -/
theorem IsAssociatedStabilizerPair.Lz_pow_m_succ_eq {t : AdmissibleTuple}
    {A_t Lz : SL(2, ℤ)} (h : t.IsAssociatedStabilizerPair A_t Lz) :
    (Lz : Mat(2, ℤ)) ^ ((t.triple.m : ℕ) + 1) =
      ((t.d : ℤ) - (t.r : ℤ)) • (Lz : Mat(2, ℤ)) -
        (t.r : ℤ) • (1 : Mat(2, ℤ)) := by
  have hsq := SL2Z.sq_eq_trace_smul_sub_one Lz
  rw [h.trace_Lz] at hsq
  calc
    _ = ((Lz : Mat(2, ℤ)) ^ (t.triple.m : ℕ)) * (Lz : Mat(2, ℤ)) := by
      rw [pow_succ]
    _ = _ := by
      rw [h.Lz_pow_m_eq, sub_mul]
      simp only [smul_mul_assoc, Matrix.one_mul, ← pow_two]
      rw [hsq]
      have hprev := t.triple.tower.rankGridInt_prev_eq t.triple.j t.triple.m
      rw [← t.triple.tower.canonicalDimension_coe_int t.triple.j] at hprev
      have hprev' : t.triple.tower.rankGridInt t.triple.j ((t.triple.m : ℕ) - 1) =
          (t.triple.towerDimension : ℤ) *
            t.triple.tower.rankGridInt t.triple.j (t.triple.m : ℕ) - (t.d : ℤ) := by
        rw [t.d_eq_dimension]
        exact hprev
      have hr : t.triple.tower.rankGridInt t.triple.j (t.triple.m : ℕ) =
          (t.r : ℤ) := by
        rw [t.r_eq_rank]
        exact (t.triple.tower.rankGrid_coe_int t.triple.j t.triple.m).symm
      rw [hprev', hr]
      module

end AdmissibleTuple

end SIC

end
